### ISSUE TITLE
docShredder adding extra indentation

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular.io#1000]
If you have a docregion like:

```
// #docregion foo
function foo() {
  var a = 10;
}
// #enddocregion foo
```

You get something like:

```
` ` `
function foo() {
  var a = 10;
}
` ` `
```

But if you have another docregion inside and you "extract" the one outside, like:

```
// #docregion foo
function foo() {
  // #docregion var
  var a = 10;
  // #enddocregion var
}
// #enddocregion foo
```

You get:

```
` ` `
  function foo() {
    var a = 10;
  }
` ` `
```

The inner one doesn't get extra indentation.

You can see it in our project for example in `public/docs/_fragments/toh-4/ts/app/app.component.1-ng-on-init.ts.md`.

There is also one more case and I debugged it and ended being that.

I am not sure if this docShredder has a repo or if it is internal, so I am reporting it here.

**Comment by wardbell** [comment]
Old. Raise again if it's still relevant
