### ISSUE TITLE
Update routing and navigation documentation with correct base href implementation

### ISSUE THREAD

**Issue by user414** [angular/angular.io#1035]
As described here

https://github.com/angular/angular/issues/4735#issuecomment-204362103

**Comment by Foxandxss** [comment]
Is this still relevant?

/cc @brandonroberts

**Comment by user414** [comment]
@Foxandxss I noticed it was changed from the original issue that used / as root reference but we didn't update our code yet to try the new "." root instead. So I'm assuming it is fixed but not sure yet until we try it. Would you rather I close this and reopen if it's still an issue after we migrate to new suggestion?

**Comment by Foxandxss** [comment]
Let see what Brandon has to say.

**Comment by brandonroberts** [comment]
Stick the with `/` as your base href. Using the `.` was more meant for plunkers because of the way it sets the base URL for the previews and something like Electron for desktop apps with no server.

**Comment by user414** [comment]
@brandonroberts  The "/" is the one that causes the problem, as described in original post above. It's a fairly lengthy post but describe the issue, have a quick look at it.

**Comment by brandonroberts** [comment]
@user414 I don't think this issue is still relevant is it related to the deprecated router. If the issue still issues with the V3 router, then close the previous issue and open a new one.

**Comment by user414** [comment]
@brandonroberts Ok it's possible it was only with the deprecated router. Will close for now, once we have migrated to the new router if it's still an issue will open a new one. Thanks.
