### ISSUE TITLE
Missing arrow in ToH Introduction's navigation overview diagram

### ISSUE THREAD

**Issue by RichardOtvos** [angular/angular.io#1041]
In the Introduction chapter of the ToH, around the middle, there is a diagram of where each navigation option takes you to. There is a **missing arrow from the Dashboard to the details view.** (eg.: you will be taken to the "Magenta" details page, if you click on the rectangle with Magenta on the Dashboard)

The image itself is  [here](https://github.com/angular/angular.io/blob/master/public%2Fresources%2Fimages%2Fdevguide%2Ftoh%2Fnav-diagram.png). I would submit a fixed version, but I couldn't find the original files in the repo (I guess you have some some layered image-file for the arrows). 

Could you fix this, or commit the files, so I can do it? 

Thanks!

**Comment by wardbell** [comment]
Thanks. Fixed in PR #1045
