### ISSUE TITLE
Angular Material updates

### ISSUE THREAD

**Issue by alexwolfe** [angular/angular.io#105]
Update dropdowns and layout to now use Angular Material.

**Comment by Foxandxss** [comment]
Is this fixed @alexwolfe ?

**Comment by lazaridis-com** [comment]
@gkalpak, @wardbell , any idea who could verify if this was fixed? - This issue here is in the "Club of the Ancients".

**Comment by gkalpak** [comment]
I am not even sure what this issue is about :grin:

**Comment by lazaridis-com** [comment]
@gkalpak , ok, I describe the action: someone should verify if the angular.io website uses angular-material for dropdowns, layout etc. - if yes, then this ancient issue can be closed.

**Comment by Foxandxss** [comment]
I am closing it anyway, since we are migrating to a new site.
