### ISSUE TITLE
Add possible info for how to achieve module-relative paths when selecting templateUrl ?

### ISSUE THREAD

**Issue by MarkPieszak** [angular/angular.io#1052]
> We specify the path all the way back to the application root. Angular doesn't support module-relative paths.

Maybe we should mention that modular bundlers like webpack can handle *module-relative paths*?

Stating perhaps: 

> We specify the path all the way back to the application root. Angular by default doesn't support module-relative paths, but bundlers such as Webpack (https://webpack.github.io/) & SystemJS can allow you to do this.

I'm not positive if System can, but I'm guessing it can?

Just thought it might help since it's always great to be able to use relative paths for this!

What do you guys think?

**Comment by Foxandxss** [comment]
Personally I think it is good as is because that message is scoped to the concrete tutorial and its tools. 

It is an easy going tutorial to teach the basic of Angular 2 and I personally think that we should try to maintain the reader within the tutorial context. The user should be focused on learning Angular 2 at this point.

Webpack will be properly covered in its own page here in the docs.

Cheers.

**Comment by MarkPieszak** [comment]
Good point, maybe you're right. Later "sections" could talk about modular bundling as it is out of the scope of Angular itself, but more of just an important part of the build process.

Thanks Fox. I'll close out, should of figured more was to come :)

Is there a roadmap somewhere of potential upcoming sections (for the tutorial / etc)? I'd love to add/help in some missing areas.

**Comment by Foxandxss** [comment]
Tooling and stuff will be covered outside the tutorial context. To be honest I don't know if the tutorial will have some of that in the future.

Feel free to open issues like this if you feel that something is not right.

**Comment by MarkPieszak** [comment]
Very true. I'll try to put some ideas together for a "side tutorial" that goes through general concepts. Modular bundlers / task runners / etc. might be useful to those new to these things that used Angular1 but did it all manually!
