### ISSUE TITLE
Changes in to url not reflected in page and throws errors

### ISSUE THREAD

**Issue by TroyWilsonAus** [angular/angular.io#1055]
Hi,

When using HashLocationStrategy, if the user manipulates the url (we have seen on ipads, when navigating from emailed links to our app, safari reusing the same page, and changing the url), the page doesn't load correctly.
When running with the console open we get a bunch of errors.
`angular2.dev.js:23877 Error: Uncaught (in promise): ObjectUnsubscribedError
    at resolvePromise (angular2-polyfills.js:543)
    at angular2-polyfills.js:579
    at ZoneDelegate.invokeTask (angular2-polyfills.js:365)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (angular2.dev.js:2103)
    at ZoneDelegate.invokeTask (angular2-polyfills.js:364)
    at Zone.runTask (angular2-polyfills.js:263)
    at drainMicroTaskQueue (angular2-polyfills.js:482)
    at ZoneTask.invoke (angular2-polyfills.js:434)`

I have created a plunker that replicates this problem.
[Plunker based off heros demo](http://plnkr.co/edit/vHqD9N0A7dF6WRonRsRl?p=preview)
Click the 'Launch in a seperate window' button, 
once the page has loaded, 
open the debugging tools
change the url from 

> /#/dashboard

 to 

> /#/heros

 (same hash as clicking on the heros button)

The errors will appear in the console.

Through debugging on my application I have found the the class of the required component is created, but the ngOnInit method is not called.

Any ideas / suggestions / workarounds (or better yet fixes) would be greatly appreciated.

**Comment by Foxandxss** [comment]
Not sure what is the status of this, but this is not an issue for this repository. This is only for docs issues.
