### ISSUE TITLE
Clicking Docs shouldn't change you to TypeScript

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#1060]
Say I'm in the Dart guide: https://angular.io/docs/dart/latest/guide/. When I click DOCS at the top of the page, it takes me to the TypeScript doc homepage (https://angular.io/docs/ts/latest/).

I'd expect to be taken to the Dart doc homepage: https://angular.io/dart (or, if need be, https://angular.io/docs/dart/latest/).

Without that, there's no way to get back to the Dart doc homepage.

**Comment by kwalrath** [comment]
In general, I'd like to stay on the Dart docs unless I explicitly go to the TS docs. That means once I've gone to docs under docs/dart, I'd expect the drop-down list to default to Dart until I explicitly go to a docs/ts or docs/js page.

**Comment by wardbell** [comment]
Done in #1144
