### ISSUE TITLE
Best practices for component communication

### ISSUE THREAD

**Issue by bampakoa** [angular/angular.io#1068]
It would be nice to add best practices for component communication chapter in the cookbook. Something like when to use each scenario or write down prons and cons of each one. What do you think?

**Comment by MarkPieszak** [comment]
This is a good idea.

Maybe even some information on Change Detection Strategy, how Push combined with Immutable's is a very good practice, etc. Definitely more advanced (I'm sure a lot of smaller apps won't need any of this), but still could be nice to have?

**Comment by wardbell** [comment]
[Component communication](https://angular.io/docs/ts/latest/cookbook/component-communication.html) cookbook exists. Change Detection guide underway. Closing for now. File again if we don't make good.
