### ISSUE TITLE
Step by Step Guide - Display Data discontinuity

### ISSUE THREAD

**Issue by drozzy** [angular/angular.io#107]
_Reposted from angular as requested_

The "DISPLAYING DATA" section in "Step by Step Guide" has got me very confused:
https://angular.io/docs/js/latest/guide/displaying-data.html

First of all, let me ask if there is a complete code for the guide - because that would solve most of my problems. I can even fix most of the mistakes myself. However, without it, I am truly stumped by the following:

1. Page starts off with "Let's walk through how we'd display a property, a list of properties, and then conditionally show content based on state.". What is a "property"? It's like we missed something...

2. "Create an entry point" - Where? The guide says to create "show-properties.html" file, and put the "display" tag in there, but nowhere in the tutorial does it actually say how it's related to "Step 1: Getting started". How is this linked to Index.html?

3. Weird wording: "So you can see Angular dynamically update content, add a line after" "to this" --- those two sentences don't mesh.

4. Next comes the additional script instruction: "Then give the DisplayComponent a starting value for time and a call to update time via setInterval."  But where should the line of code be inserted? Into constructor? Into class? Somewhere else?

5. Needless to say the instruction "Reload the page in your browser and you'll now see the seconds updating automatically." didn't work for me, as I was lost at that point, and my page looked like in Step 1. I tried navigating to "http://localhost:8080/show-properties.html" with no luck.

Questions left unanswered:

1. How are Components and Views related to the "class"? Is there some kind of default where all the code in a single .ts file makes up a "component"? The guide says "By associating your class with elements named 'display' in the DOM, Angular knows to automatically call new on DisplayComponent and bind its properties to that part of the template." --- but how? Is it because the class name should be "capitalize(display) + Component"?
2. Why does the Quickstart tutorial make use of the `<reference path="typings/angular2/angular2.d.ts" />` line, but the Step-by-Step Guide doesn't?
3. The disagreement on the http server between the Quickstart (which recommends npm's http-server) and the Guide (which advocate "python -m SimpleHTTPServer 8000") does not bode well for the consistency of the documentation.

N.B.: I just wanted to point out that I was an intermediate/advanced user of angular1, so if I am stumped by this tutorial, I can't imagine someone new getting very far with it.

**Comment by RinatMullayanov** [comment]
I faced the same problems. In my opinion in the guide forgot to mention that you want to import in DisplayComponent AppComponent and place <display> </ display> in a layout.
Details in my repository: https://github.com/RinatMullayanov/step-by-step-guide-with-angular2
Here is my solution:
main.ts
```typescript
/// <reference path="typings/angular2/angular2.d.ts" />
import {Component, View, bootstrap} from 'angular2/angular2';
// sample import another user component thanks to http://stackoverflow.com/questions/29121678/angular-2-component-inside-main-component
import {DisplayComponent} from './show-properties';

//The @Component annotation defines the HTML tag for the component by specifying the component's CSS selector
@Component({
  selector: 'my-app'
})
//The @View annotation defines the HTML that represents the component. The component you wrote uses an inline template, but you can also have an external template.
//To use an external template, specify a templateUrl property and give it the path to the HTML file.
@View({
  templateUrl: './layout.html',
  directives: [
    DisplayComponent // some user component
  ]
})
class AppComponent {

}

bootstrap(AppComponent);
```

layout.html
```html
<h1>My first Angular 2 App</h1>
<display></display>
```

show-properties.ts
```typescript
/// <reference path="./typings/angular2/angular2.d.ts"/>
import {Component, View, bootstrap, For} from 'angular2/angular2';

@Component({
  selector: 'display'
})
@View({
  templateUrl: './display.html',
  directives: [For]
})
export class DisplayComponent {
  myName: string;
  names: string[];

  constructor() {
    this.myName = 'Alice';
    this.names = ["Aarav", "Martín", "Shannon", "Ariana", "Kai"];
  }
}
```

**Comment by aciccarello** [comment]
I agree. I kept getting confused about where the lines of code were supposed to be added. For example what does this mean?

> Then give the DisplayComponent a starting value for time and a call to update time via setInterval.
````javascript
setInterval(function () { this.time = (new Date()).toString(); }.bind(this), 1000);
````

Should things be added to the constructor function? If this is a "Step by Step" guide things should not be so ambiguous. It makes it easy to get out of step.

**Comment by davideast** [comment]
@drozzy @RinatMullayanov @aciccarello 

Thank you all so much for your feedback. We'll in the middle of doing some updates. There are definitely some places right now where the either the definitions and code samples are vague. We hope the coming updates will clear up a lot of the issues stated above.

**Comment by aciccarello** [comment]
@davideast Glad to hear that. Thanks for making NG2 more accessible. Looking forward to updates to the docs.

**Comment by RinatMullayanov** [comment]
@davideast On page [User Input](https://angular.io/docs/js/latest/guide/user-input.html) in code todo-list component 
```typescript
import {Component, View, bootstrap, For, If} from 'angular2/angular2';
```
Imports "If" directive which is not used in the template component "todo-list"

**Comment by alexwolfe** [comment]
@davideast I'll let you close this when the updates are live. Assigned to you.

**Comment by fedy2** [comment]
Any update on this part of the guide?

**Comment by MarcusLlewellyn** [comment]
I was with the step by step guide until I got to the "Displaying Data" part. As others have already mentioned, the instructions become very confusing at this point. The first step "Getting Started" was very clear and specific about exactly what one needed to do, but this clarity was abandoned on the second step.

I'm brand new to Angular, and my intention was to go straight to Angular 2 so that I wouldn't have to unlearn any habits. But with the current state of the documentation, that just isn't possible as it simply does not appear to work. I appreciate that Angular 2 is a work in progress, and hope to see the guide follow that progress more aggressively.

**Comment by rpoitras** [comment]
I also am anxiously awaiting the guides to be updated.

**Comment by dmarsi** [comment]
Had no problems with the Quickstart guide, but the Displaying Data guide feels so incomplete. Still have yet to get it working.

**Comment by wardbell** [comment]
The QS and Displaying Data guides are as "up to date" as we think they should be. Please explain where you are stuck so we can improve them.

**Comment by dmarsi** [comment]
So far the guide leaves me with this after the "Showing properties with interpolation" section:

show-properties.html:

    <display></display>

show-properties.js (the guide says to make it a .ts file but I'm assuming is should be .js if I'm using JS):

    function DisplayComponent() {
        this.myName = "Alice";
    }
    DisplayComponent.annotations = [
        new angular.ComponentAnnotation({
          selector: "display"
        }),
        new angular.ViewAnnotation({
          template:
            '<p>My name: {{ myName }}</p>'
        })
      ];

-Where should these two files be located?
-I assume it should work similar to the Quickstart guide, right? If so, what needs to be in the package.json and app.js files?
-I tried just throwing those two files in the same directory as the Quickstart guide and going to localhost/show-properties.html but show-properties.js isn't loading with the page (I assume some script tag is need to load it). Added the script tag to show-properties.html and then got this error: "ReferenceError: angular is not defined"

Needless to say I'm lost.

**Comment by wardbell** [comment]
You are looking at the JavaScript language path which is woefully out-of-date (we will catch up).

The most current documentation is on the TS language path (see the combobox at the top of the page)

Here is the [TS version of "Displaying Data"](https://angular.io/docs/ts/latest/guide/displaying-data.html)

**Comment by rpoitras** [comment]
Noticed on the weekend the docs have been worked on.  Went through the
Tutorial (Typescript) and it was very good.  Did not hit any issues
what-so-ever.  Looking forward to see the continuations.  Really liking
what I'm seeing so far.  Curious about the routing.  Just keeping an eye on
things in my spare time.  Angular 2 has my interest peaked.  I'll be all
over the beta when it comes out.

**Comment by hearAllParties** [comment]
i got the same problem "ReferenceError: angular is not defined"

**Comment by wardbell** [comment]
Obsolete issue.
