### ISSUE TITLE
Please make it more prominent where to provide `ROUTER_PROVIDERS`

### ISSUE THREAD

**Issue by zoechi** [angular/angular.io#1076]
Seems to become the most frequently asked question lately - "why does routing not work in this code?"  
and then they have `provide: [ROUTER_PROVIDERS]` on several components.

For example 
https://angular.io/docs/ts/latest/guide/router.html (Booting with the router service providers) might be a good place.

I'm still not sure if adding `ROUTER_PROVIDERS` to the root component should work as well, or if it should always only be added to `bootstrap()`.

**Comment by zoechi** [comment]
#angular/angular#8020

**Comment by Foxandxss** [comment]
Works in both places.

The style guide will have a section about where to load your providers. When a decision is made, we will update the guides and examples.

**Comment by wardbell** [comment]
I'm closing because there does not appear to be an outstanding action item here. Happy to reopen if I misunderstood.
