### ISSUE TITLE
AsyncPipe example for Observables is missing

### ISSUE THREAD

**Issue by dmackerman** [angular/angular.io#1077]
https://angular.io/docs/ts/latest/api/common/AsyncPipe-class.html

![missing](https://dl.dropboxusercontent.com/spa/pkr1d5uhq1t8wz1/tkbxo0g1.png)

**Comment by wardbell** [comment]
Thanks. I know it is counter intuitive but API issues belong on the https://github.com/angular/angular/issues site. Please resubmit this issue there.
