### ISSUE TITLE
gulp serve-and-sync 100% cpu usage

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular.io#1082]
I know this is a known issue but lets have this issue as a reminder.

For those who don't know. The task we use to run the website locally uses the 100% of the CPU and puts my mac at 95ºC

**Comment by wardbell** [comment]
I'd rather not have an issue without a repro and without a course of action.

Please correct or close. Thanks.

**Comment by Foxandxss** [comment]
Oh sorry. For a repro.

```
gulp serve-and-sync
```

Leaving the command running puts my CPU to 100%

![](http://puu.sh/os0Db/0390d2e882.png)

**Comment by kwalrath** [comment]
I have the same 100% CPU problem on my Mac (OS X El Capitan, 10.11.4, 16GB memory). I usually do `gulp serve-and-sync-devguide`.

```
$ node --version
v4.2.1
```

**Comment by wardbell** [comment]
Old. No longer an issue
