### ISSUE TITLE
Broken web link to "PlatformBrowserLocation"

### ISSUE THREAD

**Issue by fletchsod-developer** [angular/angular.io#1087]
Go to https://angular.io/docs/ts/latest/api/router/PlatformLocation-class.html and click on "BrowserPlatformLocation" hyperlink. You get a 404 not found error.

This "BrowserPlatformLocation" link is at the top, in the 1st few paragraphs.

**Comment by rcarmich** [comment]
Note that the WebWorkerPlatformLocation link immediately below it also leads to a 404.

**Comment by rcarmich** [comment]
The BrowserPlatformLocation link appears to be working fine on master. Perhaps fixed in the move from router to common per https://github.com/angular/angular/pull/7962

**Comment by Foxandxss** [comment]
I am going to close this. That concrete link is deprecated and if there is a broken link, that should be reported at angular repo.

**Comment by fletchsod-developer** [comment]
Funny.  Angular GitHub said to report it here and you said to report it back over there.  **SMH**
