### ISSUE TITLE
Guide Setup deployed site doesn't match jade code

### ISSUE THREAD

**Issue by jtibble** [angular/angular.io#109]
![image](https://cloud.githubusercontent.com/assets/2126464/7618612/38adc084-f981-11e4-8042-e33aeb45421c.png)

 from https://angular.io/docs/js/latest/guide/setup.html

The deployed site example doesn't have the <my-app> tag, but the file appears to be changed here in the repo:  https://github.com/angular/angular.io/blob/master/public/docs/js/latest/guide/setup.jade#L69

Has the site been redeployed lately?

**Comment by naomiblack** [comment]
Yes, fixed yesterday. Thanks!
