### ISSUE TITLE
Developer Guide Upgrading page should explain how to use ng 1.5 one way binding from ng2 templates

### ISSUE THREAD

**Issue by sarod** [angular/angular.io#1090]
The "Upgrading from 1.x" developer guide page nicely explains the rules to follow to use the different types of ng1 bindings from ng2 but forgets the "one way binding" introduced in ng 1.5.

**Comment by gkalpak** [comment]
I think one-way binding wasn't there at the time the guide was written :smiley:

**Comment by wardbell** [comment]
I've asked Tero, the author of this chapter, to take a look at this issue.

**Comment by Foxandxss** [comment]
Ill close this and merge #1169 ASAP.
