### ISSUE TITLE
Chrome Version 50.0 EXCEPTION: Error during instantiation of AppComponent!.

### ISSUE THREAD

**Issue by josephshoop** [angular/angular.io#1092]
After upgrading from chrome 49 to:

Version 50.0.2661.75 (64-bit)

I am now seeing the following error:

EXCEPTION: Error during instantiation of AppComponent!.
angular2.dev.js:23941 EXCEPTION: Error during instantiation of AppComponent!.BrowserDomAdapter.logError @ angular2.dev.js:23941BrowserDomAdapter.logGroup @ angular2.dev.js:23952ExceptionHandler.call @ angular2.dev.js:1317(anonymous function) @ angular2.dev.js:12901promiseReactionJob @ es6-shim.js:2171(anonymous function) @ es6-shim.js:2159ZoneDelegate.invoke @ angular2-polyfills.js:332NgZoneImpl.inner.inner.fork.onInvoke @ angular2.dev.js:2111ZoneDelegate.invoke @ angular2-polyfills.js:331Zone.run @ angular2-polyfills.js:227(anonymous function) @ angular2-polyfills.js:576ZoneDelegate.invokeTask @ angular2-polyfills.js:365NgZoneImpl.inner.inner.fork.onInvokeTask @ angular2.dev.js:2103ZoneDelegate.invokeTask @ angular2-polyfills.js:364Zone.runTask @ angular2-polyfills.js:263drainMicroTaskQueue @ angular2-polyfills.js:482ZoneTask.invoke @ angular2-polyfills.js:434
angular2.dev.js:23941 ORIGINAL EXCEPTION: [object Object]BrowserDomAdapter.logError @ angular2.dev.js:23941ExceptionHandler.call @ angular2.dev.js:1326(anonymous function) @ angular2.dev.js:12901promiseReactionJob @ es6-shim.js:2171(anonymous function) @ es6-shim.js:2159ZoneDelegate.invoke @ angular2-polyfills.js:332NgZoneImpl.inner.inner.fork.onInvoke @ angular2.dev.js:2111ZoneDelegate.invoke @ angular2-polyfills.js:331Zone.run @ angular2-polyfills.js:227(anonymous function) @ angular2-polyfills.js:576ZoneDelegate.invokeTask @ angular2-polyfills.js:365NgZoneImpl.inner.inner.fork.onInvokeTask @ angular2.dev.js:2103ZoneDelegate.invokeTask @ angular2-polyfills.js:364Zone.runTask @ angular2-polyfills.js:263drainMicroTaskQueue @ angular2-polyfills.js:482ZoneTask.invoke @ angular2-polyfills.js:434
angular2.dev.js:23941 ERROR CONTEXT:BrowserDomAdapter.logError @ angular2.dev.js:23941ExceptionHandler.call @ angular2.dev.js:1333(anonymous function) @ angular2.dev.js:12901promiseReactionJob @ es6-shim.js:2171(anonymous function) @ es6-shim.js:2159ZoneDelegate.invoke @ angular2-polyfills.js:332NgZoneImpl.inner.inner.fork.onInvoke @ angular2.dev.js:2111ZoneDelegate.invoke @ angular2-polyfills.js:331Zone.run @ angular2-polyfills.js:227(anonymous function) @ angular2-polyfills.js:576ZoneDelegate.invokeTask @ angular2-polyfills.js:365NgZoneImpl.inner.inner.fork.onInvokeTask @ angular2.dev.js:2103ZoneDelegate.invokeTask @ angular2-polyfills.js:364Zone.runTask @ angular2-polyfills.js:263drainMicroTaskQueue @ angular2-polyfills.js:482ZoneTask.invoke @ angular2-polyfills.js:434
angular2.dev.js:23941 _Context {element: reading-assistant, componentElement: null, injector: Injector}componentElement: nullelement: reading-assistantinjector: Injector__proto__: ObjectBrowserDomAdapter.logError @ angular2.dev.js:23941ExceptionHandler.call @ angular2.dev.js:1334(anonymous function) @ angular2.dev.js:12901promiseReactionJob @ es6-shim.js:2171(anonymous function) @ es6-shim.js:2159ZoneDelegate.invoke @ angular2-polyfills.js:332NgZoneImpl.inner.inner.fork.onInvoke @ angular2.dev.js:2111ZoneDelegate.invoke @ angular2-polyfills.js:331Zone.run @ angular2-polyfills.js:227(anonymous function) @ angular2-polyfills.js:576ZoneDelegate.invokeTask @ angular2-polyfills.js:365NgZoneImpl.inner.inner.fork.onInvokeTask @ angular2.dev.js:2103ZoneDelegate.invokeTask @ angular2-polyfills.js:364Zone.runTask @ angular2-polyfills.js:263drainMicroTaskQueue @ angular2-polyfills.js:482ZoneTask.invoke @ angular2-polyfills.js:434

**Comment by Foxandxss** [comment]
Doing what exactly? We need more info.

**Comment by josephshoop** [comment]
What info do you need?   I am getting the error on loading an angular 2 app.

**Comment by Foxandxss** [comment]
This repository is for the documentation. So I figured you had a problem with one of our examples.

**Comment by josephshoop** [comment]
oh. my bad. I though this was the overall angular 2 issue system.

**Comment by Foxandxss** [comment]
No, it is not. That being said, if you are going to open an issue in the code repo, better have a plunker reproduction or something to work with. That stacktrace doesn't say anything relevant.

**Comment by josephshoop** [comment]
Thanks for your timely help.
