### ISSUE TITLE
dgeni: @deprecated tag has no visible output in API docs

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#1097]
See https://angular.io/docs/ts/latest/api/common/FORM_BINDINGS-let.html for an example of a live page that should have an @deprecated warning, per https://github.com/angular/angular/blob/2.0.0-beta.15/modules/angular2/src/common/forms.ts#L64-L64

@ericjim @IgorMinar @petebacondarwin

**Comment by ericjim** [comment]
I'll do this one next, I'll refer to the API doc proposal from here https://github.com/angular/angular.io/issues/964

**Comment by ericjim** [comment]
Work in-progress, but getting there.

<img width="1440" alt="screenshot 2016-04-18 21 43 18" src="https://cloud.githubusercontent.com/assets/1329167/14625167/bad37d30-05ae-11e6-9597-c81324018fb4.png">
<img width="1440" alt="screenshot 2016-04-18 21 43 02" src="https://cloud.githubusercontent.com/assets/1329167/14625168/bad49ae4-05ae-11e6-8102-34df7544410c.png">
<img width="1440" alt="screenshot 2016-04-18 21 42 44" src="https://cloud.githubusercontent.com/assets/1329167/14625169/bad508d0-05ae-11e6-9d1e-9ba0b085800a.png">

**Comment by ericjim** [comment]
@naomiblack as it stands, I am defaulting to stable. I can perform a check for `@stable`, however, in its current state every single page in the api doc will have an `experimental` label

**Comment by naomiblack** [comment]
on further reflection, I think we need to have four states: stable / experimental / deprecated / undefined.

Could you create both @stable and @experimental and then make the default (undefined) show no button at all? that gives us space to go through the API surface incrementally, and saves us from accidentally making something experimental look "done".

@IgorMinar  FYI
