### ISSUE TITLE
dgeni: add support for new @stable and @docsNotRequired tags

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#1098]
- `@stable` needed to allow the API docs to show an icon for experimental/stable docs
- `@docsNotRequired` needed to allow us to suppress "Not Yet Documented" in the API doc output for some terms.

It would be nice to also expose both statuses here https://angular.io/docs/ts/latest/api/overview-dump.html)

We need `@stable` rather than `@unstable` because we want the default state (if the author forgets about the special tag) to be to show an API doc page as experimental.

@IgorMinar @petebacondarwin @ericjim

**Comment by ericjim** [comment]
@naomiblack  We already have `@deprecated`, wouldn't the absence of this tag imply stable? If so, then we wouldn't need the `@stable` tag. However, I see how we could use @docsNotRequired.
