### ISSUE TITLE
New API Doc styles break in Safari at 600px width breakpoint

### ISSUE THREAD

**Issue by ericjim** [angular/angular.io#1099]
At 600px width or less the new API doc styles break, which is most prominent on iPhones. This issue, however, does not affect Chrome or Firefox.

# Safari
![screenshot 2016-04-16 12 00 17](https://cloud.githubusercontent.com/assets/1329167/14582138/ced14ae6-03ca-11e6-81dc-78a45e2c2841.png)

# Chrome
![screenshot 2016-04-16 12 02 14](https://cloud.githubusercontent.com/assets/1329167/14582148/4a73c214-03cb-11e6-984f-e54ed71f8d10.png)

# Firefox
![screenshot 2016-04-16 12 03 39](https://cloud.githubusercontent.com/assets/1329167/14582150/4edaee04-03cb-11e6-9fdb-16d7dab5315d.png)

**Comment by naomiblack** [comment]
closed by merge of #1100
