### ISSUE TITLE
"Displaying Data" example image is hard to read and has no descriptive text

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular.io#110]
On https://angular.io/docs/js/latest/guide/displaying-data.html, the first section contains an example UI.

This example is an image that does not have a descriptive text (e.g. ```alt``` attribute or ```title```). It is also too small to be easily understood.

**Comment by kwalrath** [comment]
The corresponding image in https://angular.io/docs/dart/latest/guide/displaying-data.html is larger, but it also needs an alt attribute.

**Comment by alexwolfe** [comment]
This has been resolved. Images updated and alt text has been added. I've also update the images to all use the same source.

**Comment by kwalrath** [comment]
:+1:
