### ISSUE TITLE
"Class export" on API docs shows the signature as one word

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular.io#1102]
For example

https://angular.io/docs/ts/latest/api/core/ElementRef-class.html
![image](https://cloud.githubusercontent.com/assets/13039652/14589269/54c8191a-04b4-11e6-8e1c-8c589673ac7a.png)

https://angular.io/docs/ts/latest/api/core/EventEmitter-class.html
![image](https://cloud.githubusercontent.com/assets/13039652/14589275/80388ac6-04b4-11e6-9b2b-95bf75fab5cb.png)

I checked if this was already reported, found nothing. Close if it was and I missed it.

**Comment by ericjim** [comment]
Thanks @ericmartinezr, I'll look into it.
