### ISSUE TITLE
Update Contribute page to point to Angular(2) source?

### ISSUE THREAD

**Issue by kevmoo** [angular/angular.io#111]
https://angular.io/contribute.html

Comment that folks can help in JS and Dart?

**Comment by naomiblack** [comment]
@alexwolfe what do you think of how I added it (visually)? I think these should both be part of one entry: 
![screen shot 2015-05-14 at 2 09 05 pm](https://cloud.githubusercontent.com/assets/2286589/7642086/0f6f571a-fa43-11e4-8f13-78b3462592ef.png)
