### ISSUE TITLE
dgeni: export Class Description programmatically and rename Class Interfaces

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#1110]
We’re not outputting a Class Overview, which should be generated based on the class type and similar to what is output to the d.ts. this applies to all classes (including directives)

The original mock for the API styles is here: https://drive.google.com/a/google.com/file/d/0B5PzLooin-9SRWotUDllRUZXZk0/view

The heading `Instance Members` should become `Class Details` for all classes and directives. The intent for the `Class Overview` section was to create a TOC (hyperlinked) to the `Class Details/Instance Members` lower down the page.

**Comment by ericjim** [comment]
While I wait on https://github.com/angular/angular.io/pull/1118, I'll work on this one.

**Comment by naomiblack** [comment]
#1118 is closed now! :)
