### ISSUE TITLE
Update Side Navigation 

### ISSUE THREAD

**Issue by amitafr** [angular/angular.io#1117]
Update Side Navigation to new styles and hierarchy of information.

VISUAL DESIGN:
![nav only](https://cloud.githubusercontent.com/assets/10601477/14645124/7c39ca06-0622-11e6-85b0-45c1f47eba85.png)
Note: Only one section can be opened at a time. Once a section is open it will go to the first item in that group. 

INFORMATION HIERARCHY: 

Angular.io

Quickstart

Tutorial
> 1. Introduction
> 2. The Hero Editor
> 3. Master/Detail
> 4. Multiple Components
> 5. Services
> 6. Routing

Basics
> 1. Overview
> 2. Architecture
> 3. Displaying Data
> 4. User Input
> 5. Forms
> 6. Dependency Injection
> 7. Template Syntax
> 8. Angular Cheat Sheet
> 9. Glossary

Developer Guide
> Attribute Directives
> Component Styles
> Hierarchical Injectors
> Http Client
> Lifecycle Hooks
> Npm Packages
> Pipes
> Routing & Navigation
> Structural Directives 
> Testing
> TypeScript Configuration
> Upgrading from 1.x

Cookbook
> Overview 
> Angular 1 to 2 Quick Ref
> Component Interaction
> Dependency Injection
> Dynamic Form
> TypesScript to JavaScript

API Reference

Support

**Comment by ericjim** [comment]
@alexwolfe I'll be working off these
