### ISSUE TITLE
Update Footer Organization and Links

### ISSUE THREAD

**Issue by amitafr** [angular/angular.io#1120]
Update Footer Organization & Links

Section 1: Resources 
- Downloads
- Libraries
- Press Kit
- Etc. 

Section 2: Learn
- Docs
- Books
- Videos
- etc 

Section 3: Help & Support
- Support Page
- File a Ticket
- Product Feedback

Section 4: Community 
- Events
- Twitter
- Facebook 
- Google+ 
- Github
- etc.

**Comment by ericjim** [comment]
@alexwolfe I'll be working off these for the footer
