### ISSUE TITLE
Create and Implement Press Kit 

### ISSUE THREAD

**Issue by amitafr** [angular/angular.io#1121]
The press kit will be a new page with a link located in the footer under Resources
![angular io press kit](https://cloud.githubusercontent.com/assets/10601477/14679934/f37c8f1e-06e9-11e6-991c-3063830c921d.jpg)

Downloadable assets will be sent directly to @ericjim.

**Comment by naomiblack** [comment]
I'd like some text that makes it more explicit that the images on this page are licensed under CC BY 4.0. Maybe just body text under the top heading, saying
`The logo graphics available for download on this page are provided under CC BY 4.0` with a link to the license.

**Comment by amitafr** [comment]
@naomiblack I like that text a lot! Will update the mock to reflect that
