### ISSUE TITLE
Warn against creating circular package dependencies

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#1122]
As https://github.com/angular/angular/issues/8093 shows, circular dependencies between Dart packages can cause transformer problems (as of b15, if not before).

Bad: package A depends on package B, which depends on package A.

Good: separate out the dependencies into one or more packages. E.g.:
- package A depends on package C.
- package B depends on package C.

I plan to document this somewhere on angular.io/dart. I also plan to file issues for Effective Dart & pub, since avoiding circular dependencies seems like a good thing to do, in general.

**Comment by chalin** [comment]
This issue was moved to dart-lang/site-webdev#255
