### ISSUE TITLE
ToH Routing leaves behind @Input (and possibly selector)

### ISSUE THREAD

**Issue by pauleveritt** [angular/angular.io#1126]
In the routing section, you start with the ``selectedHero`` passed in as an ``@Input``:

```html
<my-hero-detail [hero]="selectedHero"></my-hero-detail>
```

```typescript
export class HeroDetailComponent {
  @Input() hero: Hero;
}
```

You then show changing to use of a route:

> We will no longer receive the hero in a parent component property binding.

I _believe_ this means the ``@Input`` is no longer needed. But it still appears at the end in ``app/hero-detail.component.ts (latest)``. It also appears in the plunkr.

Also, though I'm not sure about this...I think the ``my-hero-detail`` selector should be removed from the component, as ``<my-hero-detail>`` is no longer used in a routing scenario.

**Comment by Foxandxss** [comment]
This is the kind of issues I love. Most people won't even notice that kind of stuff or simply ignore or assume that it has to be like that.

That is totally my fault, we did a refactor to change the way we were using the inputs and I wrongly assumed that all the new versions of the HeroDetailComponent would need it too.

I am fixing it right now.

Thank you.

**Comment by pauleveritt** [comment]
Thanks for the incredibly fast response and kind tone. I was hesitant to comment, as it sounds like whining, because the work all of you are doing on the ToH case study is fantastic. I like how you took the time to explain that ``@Input`` was no longer needed, including the "why" behind the change.

**Comment by Foxandxss** [comment]
Every time that you feel that something is "fishy", open an issue. No exception.

The worst outcome is that you end learning something new and you can't even call that a bad outcome.

**Comment by Foxandxss** [comment]
> Also, though I'm not sure about this...I think the my-hero-detail selector should be removed from the component, as <my-hero-detail> is no longer used in a routing scenario.

Sorry, missed that bit. They are not needed, but leaves some `<undefined>` on the DOM. I prefer to see the component name in there.
