### ISSUE TITLE
mobile: ensure new API type and status indicators are mobile-friendly

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#1128]
Could be improved:
![image](https://cloud.githubusercontent.com/assets/2286589/14679950/dfb7a32e-06d0-11e6-9104-55f63eb8505f.png)

**Comment by ericjim** [comment]
I think it would be reasonable to place the badges below the title.

**Comment by ericjim** [comment]
@naomiblack  How's that?

<img width="349" alt="screen shot 2016-04-20 at 2 45 24 pm" src="https://cloud.githubusercontent.com/assets/1329167/14686425/9a445ebe-0706-11e6-9325-97d6e8d01762.png">
<img width="455" alt="screen shot 2016-04-20 at 2 45 13 pm" src="https://cloud.githubusercontent.com/assets/1329167/14686426/9a48fea6-0706-11e6-9c3c-e003b41b2d48.png">

**Comment by naomiblack** [comment]
Make it so!
