### ISSUE TITLE
Small mistake in variable name in "Displaying Data" docs page

### ISSUE THREAD

**Issue by ibhi** [angular/angular.io#114]
There is a typo in the angular.io docs page under 'Displaying Data' section on the Typescript version of example code. Refer attached image.
![untitled image](https://cloud.githubusercontent.com/assets/7778638/7664157/7d7f2252-fb98-11e4-9dce-42dabd7a31f3.png)

**Comment by RinatMullayanov** [comment]
The repository has fixed 6 days ago
https://github.com/angular/angular.io/commit/443e4e5b5f7c710c3332a1385835fc26bab33261
But for some reason, the site is still old version.

**Comment by alexwolfe** [comment]
Probably wasn't pushed live yet. I'll close this as it's completed in terms of master.
