### ISSUE TITLE
Reorder Sidenav

### ISSUE THREAD

**Issue by ericjim** [angular/angular.io#1143]
We were going to get rid of `Reference` and make the last item in the list `API Reference`. The cheat sheet is already linked under `Basics`. Glossary should be 9 under `Basics`

Based on @naomiblack's feedback

**Comment by Foxandxss** [comment]
Perhaps not the best issue for this, but what do you think about moving "Basic - Overview" from where it sits now? It is like an awesome entry point for the doc itself but is not that visible in there.
