### ISSUE TITLE
[Typescript Suggestion] - Display a warning on functionality that isn't setup by default.

### ISSUE THREAD

**Issue by anakinjay** [angular/angular.io#115]
As far as I understand it, with the current angular2.d.ts and angular2.dev.js builds, the only functionality that will compile is Component, View, and bootstrap.   The rest of the functionality is there, but you have to manually declare them in your ts definition file, and there is no mention of that anywhere in the documentation.

So I propose adding a warning box to the top of doc pages that are not yet setup to be compiled by default.  Something like "Typescript functionality for this feature is not yet available by default, and requires manual entry in your TypeScript Definition file."

Maybe link that last bit to http://www.typescriptlang.org/Handbook#type-compatibility-advanced-topics.

At least give people new to typescript an entry point better understanding.  Right now, if they follow the documentation, it just looks like it's broken.

**Comment by jcoyne** [comment]
Yes. Exactly right.

**Comment by wardbell** [comment]
Obsolete issue.
