### ISSUE TITLE
StyleGuide - name routes the same way the components are called w/o suffix

### ISSUE THREAD

**Issue by johnpapa** [angular/angular.io#1154]
To be discussed ...

I copied several of these from early discussions and will list them as issues for future discussion after ngConf

cc // @mgechev @wardbell 
- Name the routes the same way the components associated with them are called without the `Component` suffix.
  
  _Why?_: This way there is only a single name associated to a given route. This avoids confusion in case a given route is called in a different way to the components associated with it.

**Comment by IgorMinar** [comment]
route names are going away in favor of paths being the primary identification mechanism for routes (names were interfering with lazy loading). we should however recommend that the routable component name should be derived from the route path.

**Comment by johnpapa** [comment]
no longer relevant, closing
