### ISSUE TITLE
H3 and H4 in dev guides look identical

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#1156]
a reminder to have a look into this...

**Comment by ericjim** [comment]
Here is an example of this, "Live example note" is an h4, whereas "Booting with the router service providers" is an h3. You can find this here: https://angular.io/docs/ts/latest/guide/router.html
![screen shot 2016-04-25 at 10 50 45 am](https://cloud.githubusercontent.com/assets/1329167/14787920/9a9f9e8e-0ad3-11e6-9005-a0a31eb46b47.png)

**Comment by ericjim** [comment]
Not sure what the solution should be, or if this is okay. @alexwolfe how do you feel about this?
```
.docs-content {
  h1 {
    font-size: 24px;
    opacity: 0.87;
  }
  h2 {
    font-size: 20px;
  }
  h3 {
    font-size: 16px;
  }
  h4 {
    font-size: 16px;
  }
}
```
