### ISSUE TITLE
StyleGuide - Where to Provide App Level Providers

### ISSUE THREAD

**Issue by johnpapa** [angular/angular.io#1165]
For the style guide we'll add some content to help folks know where app providers go. There are some who feel they go in bootstrap and some who feel they go in the app level component. Good reasons on both sides. We'll lay out the pros and cons.

1. Bootstrap (`main.ts`)
2. App (root) component (`app.component.ts`)
3. Child components

Examples to consider
- `ROUTER_PROVIDERS`
- `HTTP_PROVIDERS`
- App-wide services (e.g. `HeroDataService` or `LoggerService`)
- Feature specific services (e.g. `JobService`)

cc // @wardbell @mgechev

**Comment by IgorMinar** [comment]
main ts should almost never contain provider definition because then you'll need to redefine those providers in all tests.

**Comment by zoechi** [comment]
@IgorMinar how is that supposed to be and advantage when added to the root component? This only helps for testing the root component, doesn't it?

I guess for this case it would make more sense to suggest creating a `GLOBAL_PROVIDERS` (or whatever name) variable and refer it instead as provider (bootstrap, or root component) (like https://github.com/angular/angular/blob/d272f96e23f379e1b565435b3af010138e710ab9/modules/angular2/src/common/common_directives.ts#L49)

**Comment by johnpapa** [comment]
@IgorMinar That's also how I roll. I prefer all providers in the AppComponent.

@wardbell you had some concerns about this issue, which is why I raised it. Can you chime in with those?
