### ISSUE TITLE
Developer Guide - Http Client - res.json() should return a promise

### ISSUE THREAD

**Issue by mdhooge** [angular/angular.io#1166]
The guide says "The Angular HTTP client follows the ES2015 specification for the response object returned by the Fetch function. That spec defines a json() method that parses the response body into a JavaScript object."

But when you follow the link, or check MDN, res.json() returns a Promise that resolves to a JSON object. So I think the provided code always returns an empty object --- but I don't exclude the fact that I may be mistaken.

```
  let body = res.json();
  return body.data || { };
```

**Comment by dfsq** [comment]
Well maybe this is just a little misleading, because you are right, that `res.json()` indeed doesn't return a Promise, but rather parse JSON. I think that The Angular HTTP client follows specification in a way that the interface is the same. But yea, this is not a promise.

**Comment by Foxandxss** [comment]
I peeked into the source and it doesn't seem to return a promise. So I am closing this.
