### ISSUE TITLE
StyleGuide - Barrels

### ISSUE THREAD

**Issue by johnpapa** [angular/angular.io#1167]
Note to self ... add styles for how to use barrels

**Comment by IgorMinar** [comment]
do we still want to keep the barrel terminology?

with the most recent refactoring in angular, we will no longer have a concept of barrels as they were originally conceived  (public entry path/module id in a package) - we'll have separate packages instead.

index.ts reexports are useful and we do want to recommend them, but we should check if there is an existing terminology for this kind of reexporting in the node community. can someone check if there is an existing name for this technique?

**Comment by johnpapa** [comment]
This is specifically for the custom barrels that a developer creates. Barrels are fine for now. We can rename later if you like. There is no conventional term for this.

**Comment by johnpapa** [comment]
closed with the merge of PR https://github.com/angular/angular.io/pull/1204
