### ISSUE TITLE
invalid TS in HostBinding example 

### ISSUE THREAD

**Issue by drew-moore** [angular/angular.io#1179]
Lines 4 and 5 in the example code on the [`HostBinding` page](https://angular.io/docs/ts/latest/api/core/HostBinding-var.html) are missing parentheses on the getters:  

    @HostBinding('[class.valid]') get valid { return this.control.valid; } 
    @HostBinding('[class.invalid]') get invalid { return this.control.invalid; }

**Comment by ericjim** [comment]
@drew-moore thanks for pointing this out. This example could be fixed here https://github.com/angular/angular/blob/2.0.0-beta.16/modules/angular2/src/core/metadata.ts#L1418-L1424. If you'd like, submit a PR to the angular repo to fix this issue.

**Comment by zoechi** [comment]
And superfluous `[]` in @HostBinding('[class.valid]')`

**Comment by drew-moore** [comment]
@ericjim will do. For future reference, was this the right place to file the ticket, or should I have filed it on the angular repo since the problem is in the angular codebase?
 
@zoechi indeed. The [cheat sheet](https://angular.io/docs/ts/latest/cheatsheet.html) has this wrong too. It looks like this is the only instance of this mistake in the core codebase though - so do you think I ought to just push both fixes in on a single PR? (general contribution guidelines question)

**Comment by ericjim** [comment]
@drew-moore, that is a good question. I feel like this specific issue should be submitted to the angular repo, consider the [`CONTRIBUTING.md`](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type) guidelines in their repo. There is a `docs` type for only documentation changes which are in the doc string.

Note however that not all documentation of angular2 is in the angular2 repo, it just so happens that this one was.

Take the [HostBinding](https://angular.io/docs/ts/latest/api/core/HostBinding-var.html) for example, you'll notice that there is an `exported from angular2/core defined in angular2/src/core/metadata.ts (line 1438)` at the bottom of the api doc, this is indicative that the documentation was extracted from the angular repo.

When in doubt, I would suggest doing a quick search of the angular/angular.io repo, and that should clear things up.

With regards to the size of the PR you would be submitting, as long as it follows [`CONTRIBUTING.md`](https://github.com/angular/angular/blob/master/CONTRIBUTING.md), I see why not. Thanks!

**Comment by drew-moore** [comment]
@ericjim that was my intuition, thanks for confirming.
