### ISSUE TITLE
StyleGuide - Add link to the set of tslint rules based on the style guide

### ISSUE THREAD

**Issue by mgechev** [angular/angular.io#1185]
Codelyzer (which at the moment is only a set of tslint rules based on the style guide) can provide style checking based on static code analysis. This way developers will be automatically warned if there's an issue in their code based on the recommended styles.

It might be beneficial for developers to have a link to it somewhere in the docs.

Currently the set of rules is used in:

- angular-cli
- angular2-seed
- angular2-webpack-starter

Here's link https://www.npmjs.com/package/codelyzer.

// cc @johnpapa

**Comment by johnpapa** [comment]
Are you proposing adding a tslint.json to the guide?

Or are you proposing adding codelyzer link in the guide?

Or both?

I like both ideas :)

For the tslint.json, I'd like to compare it to what is here. Can you take a look? https://github.com/johnpapa/event-view/blob/master/tslint.json

**Comment by mgechev** [comment]
Suggesting both :-)
codelyzer is only a set of Angular specific tslint rules for now.

I merged your existing tslint.json with the specific configuration of codelyzer's rules that align to the style guide. You can find the [tsconfig here](https://github.com/IdeaBlade/angular.io/blob/nglint/tslint.json) in this PR https://github.com/IdeaBlade/angular.io/pull/19/files.

**Comment by johnpapa** [comment]
Should we show the tslint.json in the guide itself? I think that'd be cool. @wardbell can you merge this https://github.com/IdeaBlade/angular.io/pull/19/files and then verify that we can use the `makeExample` to link to that `tslint.json` file?

**Comment by johnpapa** [comment]
@mgechev this is now linked to from the guide. Please update your github repo to point to this guide's link instead of your former guide repo.

**Comment by mgechev** [comment]
I'll do that today.

**Comment by johnpapa** [comment]
this is all in the guide now.

we can close this (i dont seem to have permissions in this issue)

**Comment by mgechev** [comment]
Yes, the link is [updated as well](https://github.com/mgechev/codelyzer/commit/f177b3a0e3970a6b38ab5c029388b078e4b5d6ea).
