### ISSUE TITLE
Update Download Page Formatting

### ISSUE THREAD

**Issue by alexwolfe** [angular/angular.io#119]
This page needs a few facelift items: 

1. Remove the X from 1.X the titles should read "Angular 1" etc. not "Angular 1.X" 
2. Replace the links with download buttons (or it could be nice to use hover cards https://angular.io/docs/js/latest/guide/) 
3. Update Nav to say "Install" not "Download"

**Comment by alexwolfe** [comment]
@gorork Feel free to take a look at this one.

**Comment by WonSong** [comment]
Please see pull request #129
