### ISSUE TITLE
Location imports not included in API Preview

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular.io#1190]
The location imports were moved out of the router package into `angular2/platform/common` but don't have a section in the API Preview listing

**Comment by ericjim** [comment]
@brandonroberts, are you referring to https://angular.io/docs/ts/latest/api/router/Location-class.html? This page isn't accessible through search, and the hero title for this entry is also gone missing (it says `Angular` instead). Note sure why this happens... I'll investigate when I have some time.

**Comment by brandonroberts** [comment]
@ericjim yes. It also includes LocationStrategy, HashLocationStrategy, PathLocationStrategy, APP_BASE_HREF to name a few.The `angular/platform/common` was just recently introduced as of beta 16.

**Comment by naomiblack** [comment]
Ah, this is because the reorg moved the files but didn't tell dgeni where to find them. I'll fix it.

Thanks @brandonroberts!

**Comment by naomiblack** [comment]
I can't figure this out. @petebacondarwin do you know what I've missed to pull in the newly reorged classes for the router? See my attempt in https://github.com/angular/angular.io/pull/1203

**Comment by naomiblack** [comment]
fixed and live!
