### ISSUE TITLE
StyleGuide - Use tslint rules names for style codes

### ISSUE THREAD

**Issue by mgechev** [angular/angular.io#1191]
Today @IgorMinar suggested to use the codelyzer's rule names as codes for the styles in the style guide, instead of the current numbers.

Here are the current rule names:

```json
[
  "directive-selector-name",
  "component-selector-name",
  "directive-selector-type",
  "component-selector-type",
  "directive-selector-prefix",
  "component-selector-prefix",
  "use-input-property-decorator",
  "use-output-property-decorator",
  "use-host-property-decorator",
  "no-attribute-parameter-decorator",
  "no-input-rename",
  "no-output-rename",
  "no-forward-ref",
  "use-life-cycle-interface",
  "use-pipe-transform-interface",
  "pipe-naming",
  "component-class-suffix",
  "directive-class-suffix"
]
```

// cc @johnpapa @wardbell

**Comment by mgechev** [comment]
The rule names bring better semantics, however, we need to come-up with names for styles which doesn't have a corresponding rule yet.

**Comment by johnpapa** [comment]
Nice idea. Though I think names change. I think the names of the rules are not always the same as the title of the rule. We can strive for this but that's the role of the style code so we can keep them in synch.

**Comment by johnpapa** [comment]
I'm proposing we close this, as it would be  a pain to keep in synch. Instead , try our best to keep the names similar but instead we focus on the style codes.

**Comment by Foxandxss** [comment]
The majority of those rules are working nicely with the style guide (we have those rules in master right now), just two exceptions I removed at #1229
