### ISSUE TITLE
Need documentation on accessing specific validators on a given input in a form?

### ISSUE THREAD

**Issue by tchoulihan** [angular/angular.io#1209]
From here: https://github.com/angular/angular/issues/8311 .

**Comment by bampakoa** [comment]
@tchoulihan There is a reference on how to achieve this in **Show and Hide Validation Error messages** section of [Forms](https://angular.io/docs/ts/latest/guide/forms.html) documentation.

**Comment by tchoulihan** [comment]
That link doesn't show how to show specific error messages for specific validators failed. The issue I provided shows that you can use `.errors`, which should be in that Forms doc.

**Comment by bampakoa** [comment]
Sorry, I did not notice that you were referring to **.errors**. Nevertheless maybe I did not understand exactly your question.What if you provide a different error message for each validator such as:

```
<div [hidden]="firstname.valid" class="alert alert-danger">
 First name is required
</div>
<div [hidden]="lastname.valid" class="alert alert-danger">
  Last name is required
</div>
```

Isn't that you try to achieve?

**Comment by tchoulihan** [comment]
That is the incorrect way to do it. 

As described in https://github.com/angular/angular/issues/8311, the correct way is something like:

```
<div class="row col-sm-12 help-block text-danger">
  <small *ngIf="test.errors?.required">Name is required</small>
  <small *ngIf="test.errors?.pattern">Contains illegal characters</small>
</div>
```

It should be in the docs, but it isn't.

**Comment by bampakoa** [comment]
@tchoulihan you can check the new cookbook [Form Validation](https://angular.io/docs/ts/latest/cookbook/form-validation.html) that shows some examples on how to access **errors**.
