### ISSUE TITLE
Tutorial-6-routing: Html issue in the tutorial

### ISSUE THREAD

**Issue by aurrelhebert** [angular/angular.io#1216]
Hello,
I finished the tutorial "Tour of hero" and notice a small error than can lead to further mistake on it.
In the paragraph of the chapter 6. routing:

>     While we're in index.html, we add `<base href="/">` at the top of the `<head>` section.
`<head>`
 ` <base href="/">`

The balise base is opened but never close. It means, that if an user doesn't close it by himself, he will not be noticed and keep going on. Then he may have trouble to find where was its mistake.
The solution can be
`<head>`
`<base href="/"/>`

As specified in the html doc: https://developer.mozilla.org/en/docs/Web/HTML/Element/base, we shouldn't close this marker. I try without closing and it fails (mozilla and chrome). In the solution updated on [plunker](http://plnkr.co/edit/?p=preview), the marker is closed at the end. My suggestion is that you close it too in the tutorial.

**Comment by Foxandxss** [comment]
I am not seeing the issue on my machine. Are you sure you are using the right doctype?
