### ISSUE TITLE
StyleGuide - Single responsibility

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular.io#1231]
/cc @johnpapa @wardbell 

We talked about adding a section (or changing one) to talk about a component not injecting several services like `exceptionService` + `spinnerService` along some other services because it would couple the component.

I think that it is good to not couple the component (and also not having to repeat the implementation of exceptionService / spinnerService in all of them) but we need to figure out what can we consider coupling and what not.

**Comment by johnpapa** [comment]
Specifically this was your example where there are multiple things in one file. For example, 2 classes and a component all in one file where the component uses those classes. The classes also are not exported as they are only used internally.

Some of this is covered by the Rule of One `01-01` .

**Comment by Foxandxss** [comment]
I just realized that this is perfectly covered by 05-15.

**Comment by johnpapa** [comment]
cool.

let's #close then
