### ISSUE TITLE
broken gulp check-deploy from master branch due to style guide changes

### ISSUE THREAD

**Issue by ericjim** [angular/angular.io#1243]
@wardbell @johnpapa I've noticed that there have been some changes on the style guide. Whenever I try to do `gulp check-deploy` from the master branch I get the following error:

```
10:39:35] {
  "source": "Jade",
  "dest": "HTML",
  "filename": "/Users/ericjimenez/Workspace/angular.io/public/docs/ts/latest/guide/style-guide.jade",
  "lineno": 214,
  "name": "Error",
  "message": "unexpected token \"indent\"",
  "stack": "include ../_util-fns\n\n:marked\n
  ...
```

As a result, I am blocked from making any new deployments.

**Comment by Foxandxss** [comment]
There is one big issue that we missed, let me see if is that and I put a PR right away.

**Comment by Foxandxss** [comment]
#1244 That is your blocking issue @ericjim
