### ISSUE TITLE
design and implement a badge for labeling risky APIs

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#1258]
@ericjim @amitafr  could you adapt the Stability badge to a new badge (not a state, but a badge that appears next to the Stability one) that has the text "Security Risk" and is attention-getting?

We would use this on APIs that require extra care to ensure safety.

label in the API docs should be @security 

cc @petebacondarwin

**Comment by ericjim** [comment]
There are two ways of interpreting this from my end. It's either:

1.) [Directive][Stability: Risk Assessment]
OR
2.) [Directive][Stability: Experimental][Risk Assessment]

**Comment by naomiblack** [comment]
It is 2.) [Directive][Stability: whatever][Risk Assessment]

Some will have no [Risk Assessment]. It's only shown when True.
