### ISSUE TITLE
StyleGuide - 07-xx

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular.io#1273]
I will transcript here a discussion about loading providers at bootstrap or app component:

Ward said:

> For now ... the "rule" should be ​_Put app wide services in `AppComponent` unless there is a compelling reason to do otherwise_​
> 
> We have two compelling reasons so far:
> 
> 1) HTTP_PROVIDERS and configuration of them (e.g., HTTP or backend overrides)
> 2) ROUTE_PROVIDERS
> 
> One key reason is that you need to configure providers before they are used by AppComponent.
> 
> That's the reason for `ROUTE_PROVIDERS` which will soon patch `ROUTE_DIRECTIVES` into `PLATFORM_DIRECTIVES`, obviating the need to add `ROUTE_DIRECTIVES` everywhere.  Could not do this in `AppComponent`, it would be too late
> 
> Same idea with `HTTP_PROVIDERS` ... which you may need to patch before `AppComponent` sees it
> 
> So the key compelling reason is ​_Because we must patch something - providers, directives, pipes - before `AppComponent` can use it_

**Comment by johnpapa** [comment]
Let's #close this ... and move to #1152
