### ISSUE TITLE
BAD FILENAME for examples in API Reference

### ISSUE THREAD

**Issue by abdulhaq-e** [angular/angular.io#1283]
I think it applies to all examples in the api reference.

Here is one:

https://angular.io/docs/ts/latest/api/core/testing/beforeEach-function.html

and another:

https://angular.io/docs/ts/latest/api/common/index/AsyncPipe-class.html

> BAD FILENAME: ../../../../../_fragments/_api/core/pipes/ts/async_pipe/async_pipe_example-AsyncPipe.ts.md   Current path: docs,ts,latest,api,common,index,AsyncPipe-class PathToDocs: ../../../../../

**Comment by Foxandxss** [comment]
Thank you. Will take a look

**Comment by abdulhaq-e** [comment]
I had a quick look, could't find anything except the obvious!:

`frag` is null for those examples; [L164](https://github.com/angular/angular.io/blob/ce6c6455015a36a0c5a4412cffb369a046562644/public/_includes/_util-fns.jade#L164)

**Comment by Foxandxss** [comment]
Seems to be fixed at #1224 so we just need to wait :)

**Comment by Foxandxss** [comment]
This is fixed by now.
