### ISSUE TITLE
CookBook for VS2015

### ISSUE THREAD

**Issue by markanewman** [angular/angular.io#1284]
Can you please make a cookbook recipe for VS2015 and build in VSTS? It took me 8 hours to get it to work and I am interested is what the "official" steps would be.

[Cross linked](https://github.com/angular/quickstart/issues/89) from the quick start repo.

**Comment by DeborahK** [comment]
Hey Mark -
As a first draft, I created a [blog post with steps](http://blogs.msmvps.com/deborahk/angular-2-getting-started-with-a-visual-studio-2015-asp-net-4-x-project/). 
I hope to get feedback before converting the post to a cookbook on VS 2015. Could you take a look at see how close it is to the steps you came up with? Thanks!

**Comment by Foxandxss** [comment]
Let's continue in #1502
