### ISSUE TITLE
StyleGuide Style 07-03 BAD FILENAME

### ISSUE THREAD

**Issue by blackpr** [angular/angular.io#1289]
The file app/heroes/hero-list/hero-list.component.ts shows a BAD FILENAME error:

`BAD FILENAME: ../../../_fragments/style-guide/ts/07-03/app/heroes/hero-list/hero-list.component.ts.md   Current path: docs,ts,latest,guide,style-guide PathToDocs: ../../../
`

**Comment by wardbell** [comment]
It isn't now. The `hero-list.component.ts` is also a direct child of `heroes` and there is no `heroes/hero-list` folder. Maybe this was fixed before I looked.

**Comment by wardbell** [comment]
You're write. Merged in PR #1290
