### ISSUE TITLE
ES6 Documentation

### ISSUE THREAD

**Issue by ipriel** [angular/angular.io#1294]
Not sure if this counts as an "issue", but the documentation does not have information for those wanting to code in ES6 / ES2015. From what I've experienced, most of it is like the Typescript syntax, but some of it (like annotations) isn't.

Honestly, it might be sufficient to add pointers to the differences where necessary to create a sort of combined Typescript & ES6 doc.

**Comment by gnomeontherun** [comment]
I've actually written a guide that is in review. So this is on the way!

**Comment by Foxandxss** [comment]
Fixed at https://angular.io/docs/ts/latest/cookbook/ts-to-js.html
