### ISSUE TITLE
Tutorial ToH-pt5 Router-Deprecated Not Loading

### ISSUE THREAD

**Issue by Gregory-Buhler** [angular/angular.io#1296]
Original systemjs.config.js originally pulls on router, while tutorial uses router-deprecated causing load errors in browser and local hosted site not to load my-app.

**Comment by Foxandxss** [comment]
I need more information. the systemjs.config.js is pulling both so you should be able to use the deprecated one.

**Comment by deerawan** [comment]
I also have same problem. 

`Cannot find module '@angular/router-deprecated'.`

The error will be gone if I change it into `@angular/router` but it will complain about not found `RouterConfig`

**Comment by Foxandxss** [comment]
Are you following the tutorial from zero? (I mean copying the quickstart by hand, etc). Can I see your package.json?

**Comment by busches** [comment]
Wouldn't it be better to update the tutorial to use `@angular/router`? This is something I would help with, assuming that's the direction you want to go and isn't being done by someone else already.

**Comment by wardbell** [comment]
We are not using the new new router until it is ready

**Comment by wardbell** [comment]
We are not using the new new router until it is ready

**Comment by markh42** [comment]
I had the same issue and I realized that into package.json file, the dependency was missing "@angular/router-deprecated":  "2.0.0-rc.1", after put it there and npm update, systemjs is able to load it.

I hope this works for you
