### ISSUE TITLE
Fix typo in resources

### ISSUE THREAD

**Issue by bekos** [angular/angular.io#1297]
Library is called `ng-lightning` instead of `ng-lightening`  :-)

**Comment by bekos** [comment]
This seems to be fixed via 17769df8f5fc5bbbf0f486db4ec677868359de6c. Thx 👍 
Although, the typo still exists into `tooling.jade`, but I don't if this is used anywhere.

Feel free to close if you believe it's OK :-)

**Comment by ericjim** [comment]
@bekos, yeah we are currently not using `tooling.jade` we'll probably get rid of it.

**Comment by bekos** [comment]
@ericjim Cool. Thx again :-)
