### ISSUE TITLE
Docs (Router) Router Imports Bad Filename

### ISSUE THREAD

**Issue by deerawan** [angular/angular.io#1307]
## The Problem Doc URL 
https://angular.io/docs/ts/latest/guide/router.html#!#base-href 
section **Router Imports**

## Error Message
`BAD FILENAME: ../../../_fragments/router/ts/app/app.component.1-import-router.ts.md   Current path: docs,ts,latest,guide,router PathToDocs: ../../../`

**Comment by Foxandxss** [comment]
You are trying to read a work in progress guide. That link is not even "public".

We are working on it and will be up and ready soon :)

**Comment by deerawan** [comment]
Thanks for your response @Foxandxss 

Actually, I went there from this tutorial page that I'm following https://angular.io/docs/ts/latest/tutorial/toh-pt5.html

**Comment by Foxandxss** [comment]
Oh, that is a good catch.

The issue is that we moved the old guide from `router` to `router-deprecated` and used `router` for the new router documentation which is the one in the works. We forgot to update all links to it. Will fix.

**Comment by williamhallatt** [comment]
Busy working on this :)

**Comment by Foxandxss** [comment]
This got fixed I think but in any case, this document is never going to see daylight, we will rewrite it for the new router.
