### ISSUE TITLE
Docs (forwardRef) Link to example broken in API Docs

### ISSUE THREAD

**Issue by traviskaufman** [angular/angular.io#1314]
https://angular.io/docs/ts/latest/api/core/index/forwardRef-function.html

Within the example it says:

```
BAD FILENAME: ../../../../../_fragments/_api/core/di/ts/forward_ref/forward_ref-forward_ref.ts.md   
Current path: docs,ts,latest,api,core,index,forwardRef-function PathToDocs: ../../../../../
```

<img width="927" alt="screen shot 2016-05-06 at 17 27 09" src="https://cloud.githubusercontent.com/assets/1185269/15086580/cc3f6fd4-13af-11e6-88d2-bf0d2f89de05.png">

**Comment by Foxandxss** [comment]
Known issue.

**Comment by krimple** [comment]
FYI possible the path changed but now is specific to Naomi's environment on the site:

exported from @angular/core/index defined in /Users/naomib/github/angular/modules/@angular/core/src/di/forward_ref.ts (line 10)

**Comment by Foxandxss** [comment]
Fixed.
