### ISSUE TITLE
(docs) Spelling – "falsy" vs "falsey"

### ISSUE THREAD

**Issue by mmiszy** [angular/angular.io#1317]
I'm wondering about this particular choice of spelling, was it done intentionally?
Both "falsy" and "falsey" don't exist in any dictionaries (AFAIK) and both spellings are acceptable. However, in JavaScript world, it's much more common to use the first version: **falsy**. It's also the spelling used for example by Douglas Crockford.

As [MDN points out](https://developer.mozilla.org/en-US/docs/Glossary/Falsy):

> [Falsy] Sometimes written falsey, although in English usually turning a word into an adjective with a -y, any final e is dropped (noise => noisy, ice => icy, shine => shiny)

So the question is whether this spelling was chosen knowingly and is it a subject to change?

**Comment by williamhallatt** [comment]
For what it's worth, my vote definitely goes for "falsy" for the same reasons specified in MDN.

Just out of interest, where did you see "falsey" in the docs?

**Comment by mmiszy** [comment]
"falsey" is used repeatedly eg. here: https://angular.io/docs/ts/latest/guide/template-syntax.html

**Comment by Foxandxss** [comment]
@wardbell I like `falsy` more. What do you think?

**Comment by wardbell** [comment]
Go for it. As was noted, have seen it both ways. I'd [follow Crockford](http://javascript.crockford.com/style2.html)
