### ISSUE TITLE
DevGuide component-styles issues.

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#1319]
Issue summary (details given below):

- [x] 1. TS e2e test for this example fails.
- [x] 2. TS plunker isn't working.
- [ ] 3. Dart example is patched due to https://github.com/angular/angular/issues/8518.
- [x] 4. https://github.com/angular/dart-doc-syncer/issues/7.

(1) Attempting to run the protractor tests on this example, the following is reported:
```
> angular2-examples-master@1.0.0 tsc /.../public/docs/_examples/component-styles/ts
> tsc


[06:20:11] app/quest-summary.component.ts(7,13): error TS2304: Cannot find name 'module'.
```

This issue was raised in #1311 and #1312 was proposed as a fix.

(2) More importantly though, is that the [plunker for this example](https://angular.io/resources/live-examples/component-styles/ts/plnkr.html) no longer works; the following is reported on the JS console:
```
run.plnkr.co/:19 Error: ReferenceError: module is not defined
```

**Comment by chalin** [comment]
Cf. #1355

**Comment by wardbell** [comment]
Working on this. It may be that we switch back from commonjs to system (which DOES work in plunker albeit with `__moduleName` in place of `module.id`. Stay tuned.

**Comment by Foxandxss** [comment]
Hey @chalin. Is this still an issue? We fixed e2e tests to report the errors better, the plunkers are fixed too...

**Comment by chalin** [comment]
@Foxandxss : yes, all sub-items are complete except one, which will be tracked via #1459.
