### ISSUE TITLE
Docs (Quickstart) TypeScript hides essential systemjs config

### ISSUE THREAD

**Issue by GeertJohan** [angular/angular.io#1321]
When you hide the explanations, the essential systemjs.config.js file contents aren't shown. It's in between index.html content and `npm start`. When you get to the `npm start` section without the systemjs.config.js file in place, it obviously fails (browser errors).

**Comment by Foxandxss** [comment]
Thanks, I missed that point.

**Comment by wardbell** [comment]
Merged with PR #1304 in commit 142ad5d
