### ISSUE TITLE
Suggestion: Move Style Guide and Cheat sheet into their own Nav section

### ISSUE THREAD

**Issue by ChrisPearce** [angular/angular.io#1323]
As users get more familiar with Angular 2, it is likely that they will still find it useful to regularly refer to the Style Guide and Cheat Sheet.

To allow quick access for more experienced users, I think it would be helpful to have them more prominently displayed by having them in a separate section (i.e. at the same level as QuickStart, Tutorial, Basic, Cookbooks, etc.) rather than have them buried under the Basic section.

One suggestion for the heading is "Best Practices".

**Comment by naomiblack** [comment]
Thanks for the suggestion (and apologies for the slow reply). We're planning a docs edit and restructuring that will address this and other navigation issues, later this year.
