### ISSUE TITLE
Vertical scrollbar in single line example code

### ISSUE THREAD

**Issue by bampakoa** [angular/angular.io#1331]
A vertical scrollbar appears in some example code that is single line.

![image](https://cloud.githubusercontent.com/assets/7170892/15111361/361fafcc-15ef-11e6-9fc0-bf5fc52fc478.png)

**Comment by ericjim** [comment]
![screen shot 2016-05-11 at 1 10 12 pm](https://cloud.githubusercontent.com/assets/1329167/15194923/69d6dcdc-1793-11e6-908f-7f1b1f7ec9bf.png)
