### ISSUE TITLE
Add "Barrels" to Cookbook

### ISSUE THREAD

**Issue by jmcooper** [angular/angular.io#1334]
The style guide refers to creating barrels to aggregate and re-export imports. It will be helpful to have a cookbook recipe that demonstrates creating a barrel.

**Comment by jmcooper** [comment]
@wardbell do you want to assign me to this issue?

**Comment by Foxandxss** [comment]
Can you explain what you mean with "add barrels to cookbook"?

**Comment by jmcooper** [comment]
@Foxandxss I spoke to @wardbell last week and he mentioned that we could add a section in the cookbook demonstrating how to create barrels. Barrels are called out in the style guide and it will be helpful to have something in the cookbook to demonstrate creating barrels.  I plan to add this section and was just adding the issue to track it.

**Comment by Foxandxss** [comment]
Oh, I see. Always better to add a description, because I was thinking in something different :)

**Comment by jmcooper** [comment]
Added a description, thanks.  :)

**Comment by Foxandxss** [comment]
Let's close this in favor of #1458
