### ISSUE TITLE
ES6 Quickstart

### ISSUE THREAD

**Issue by splintercode** [angular/angular.io#134]
Would it be beneficial to create a ES6/ES7 quick start for the documentation in its current state? If so I have no problem getting this going. Proposed page angular.io/docs/js/latest/quickstart-es6 ?
Its not truly ES6 with the annotations technically thats ES7 so maybe thats not the most appropriate name. I think we do need this quick start to help ease some developers minds on not having to commit to TypeScript.

![capture](https://cloud.githubusercontent.com/assets/2021067/7900725/d7b63d38-072c-11e5-94b3-314186368d2d.JPG)

**Comment by PascalPrecht** [comment]
I'd keep a unified quickstart guide for ES5/6/7 and TS. The reason for that, is that the getting started part itself is pretty much the same for all of them. Examples could then be provided in all these languages. The docs could mentioned specific differences across the example code.

**Comment by korya** [comment]
I agree. It would be nice to have ES6 version of a documentation.

There is http://learnangular2.com/, an angular2 tutorial powered by Ionic. It looks pretty empty though.

**Comment by wardbell** [comment]
Cookbook "TypeScript to JavaScript" in PR #2606 covers this.
