### ISSUE TITLE
Indicate required NPM Version for Downloading package.json files for RC1

### ISSUE THREAD

**Issue by NoopDog** [angular/angular.io#1349]
Seems only the very latest or very recent version of NPM (3.8.9) works for downloading the files referenced in the package.json

Would be great to indicate that here.  
https://angular.io/docs/ts/latest/guide/npm-packages.html

Otherwise then unsuspecting may fumble around a bit  with errors like:

```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! Invalid name: "@angular/http"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true 
```

**Comment by escardin** [comment]
Npm 3.6.0 works fine for me.

**Comment by prijindal** [comment]
According to npm website,
Scoped packages should work on anything greater than 2.7.0

https://docs.npmjs.com/getting-started/scoped-packages

**Comment by prijindal** [comment]
Maybe this is an issue in that npm version on darwin
