### ISSUE TITLE
Filter by "only show stable" and "only show api referenced in the dev guides" on API list

### ISSUE THREAD

**Issue by ericjim** [angular/angular.io#1360]
Reminder for myself...

**Comment by naomiblack** [comment]
Let's revisit this soonish, as we now finally have stability tags on most of the API docs.
I'd like to have filters for
- only show stable
- only show "most used" where this maps to "things in the dev guide examples" probably based on a list somewhere

**Comment by naomiblack** [comment]
one more to add: I'd like the ability to link to a view of all APIs that pose a security risk. We should make it clear to the user that this is a filtered list, but I don't think we want a full button on the APIs page for it.

I need this to link to from the security doc...

**Comment by ericjim** [comment]
For reference, here is a story that is dependant on this one. https://github.com/angular/angular.io/issues/1705

**Comment by ericjim** [comment]
We need to clarify how to filter through the API list in a way that is fast, clear, and accessible. I am currently talking to @amitafr to figure out a way to accomplish this.

1.) We can currently filter by "Stable" elements in the API List, but we would like to filter by "All or Stable or Experimental". 

2.) We would also like to filter by "Most used" which will probably be feed by some list kept separately in JSON.

3.)  We would also like to search the API list by how secure an API element is

4.) We would like our filters to intersect. For example: "Give me all the decorators that are experimental and are a security risk", "Give me all constants that are stable or experimental", etc.

**Comment by amitafr** [comment]
Some initial thoughts are:

1. Make it visually known the status using the same colours used in the badges
e.g. Stable = Green Dot - adding that beside the filtered results
We may also need to add a text inside for colour blind accessibility 

2. Add a second level filter with the ability to select the status  

@ericjim

**Comment by naomiblack** [comment]
I'd like to do (1) re: @amitafr, but I am worried that the design will get visually overloaded really quickly.

**Comment by naomiblack** [comment]
We could also order the entries in the list by "stable" and "unstable" with a visual separator between them (maybe unstable get grey background)

Note though that content has states: stable, experimental, deprecated, and not-defined -- not-defined means we haven't reviewed it yet!

**Comment by koto** [comment]
Naomi, are the security-sensitive apis already annotated somehow in the documentation? I didn't see anywarning in e.g. https://ngdocsdev.firebaseapp.com/docs/js/latest/api/core/index/ElementRef-class.html

**Comment by chalin** [comment]
Btw, the stability badge seems a bit more verbose than it needs to be. Can we drop the "Stability:" prefix, and just write the stability status?
