### ISSUE TITLE
StyleGuide - Having the root /app folder export a barrel

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular.io#1361]
The CLI has a barrel in `/src/app` where they export the app.component.ts and some environment. Also the `main.ts` is at `/src` and not `/src/app`.

So we have to move `main.ts` up one level and then see if we want the `app` folder to export a barrel and if so, what should it export, only app.component or each subfolder (features and shared).

**Comment by wardbell** [comment]
Closing because (a) I don't think there should be a barrel with nothing but a component in it and (b) this should be handled by a PR (when we have proper resolution). 

Happy to reopen if you insist ... but I'd rather have your PR
