### ISSUE TITLE
Router Example code on website: @Router([]) should be @RouteConfig([])

### ISSUE THREAD

**Issue by danieldram** [angular/angular.io#1364]
<img width="973" alt="screen shot 2016-05-11 at 8 00 38 pm" src="https://cloud.githubusercontent.com/assets/4514000/15202882/15a7bf80-17b3-11e6-85e0-197601aa00b7.png">

Would you like me to submit a pull request for this? Or am I completely wrong? I ask as I was having issues with Router and this code produces the error:

`TypeError: (0 , _router2.Routes) is not a function`

**Comment by zoechi** [comment]
`@RouteConfig()` is `router-deprecated`. In the new router its `@Routes()`

**Comment by wardbell** [comment]
No bug. Closing
