### ISSUE TITLE
DecimalPipe TS docs not showing example

### ISSUE THREAD

**Issue by philp** [angular/angular.io#1367]
Following URL is not displaying example code:

https://angular.io/docs/ts/latest/api/common/index/DecimalPipe-class.html

Where there should be an example, shows the error:

```
BAD FILENAME: ../../../../../_fragments/_api/core/pipes/ts/number_pipe/number_pipe_example-NumberPipe.ts.md   Current path: docs,ts,latest,api,common,index,DecimalPipe-class PathToDocs: ../../../../../
```

**Comment by Foxandxss** [comment]
Those are known issues my friend. We need to make some fixes for the API.

**Comment by wardbell** [comment]
API issues must be fixed in angular/angular. Can't do anything about them here in angular.io. Please refile issue there. Closing
