### ISSUE TITLE
gulp e2e tests task should record failure in results.txt if compile fails

### ISSUE THREAD

**Issue by wardbell** [angular/angular.io#1371]
Today, if the `tsc` compile fails, the app launches with _previously transpiled_ JS and the tests succeed.

That can fool us into believing that the code/framework/library changes we _think_ we're testing are working.

Need to capture the compile failure and prevent e2e/protractor tests from running/reporting success.

**Comment by Foxandxss** [comment]
I think we fixed this when we did all those changes to protractor. I just tried and:

```
Doc Sample Protractor Results for (ts|js) on 2016-07-25 14:55:13
  Slow Mode: npm install, webdriver update, and boilerplate copy
  Filter: template-syntax

Application at public/docs/_examples/template-syntax/ts failed to transpile.


Suites passed:
Suites failed:
  public/docs/_examples/template-syntax/ts

Elapsed time: 3.553 seconds
```
