### ISSUE TITLE
Remove tooltips in the left menu items

### ISSUE THREAD

**Issue by siva636** [angular/angular.io#1374]
When hovering over the menu items in the left, tooltip pops up for every menu items. This tooltip hides other menu items, thus annoys rather than help. Please remove the tooltips in the menu items.

**Comment by Foxandxss** [comment]
@alexwolfe WDYT? I think it is fine as it is with the tooltips.

**Comment by Foxandxss** [comment]
Closing as we will migrate to a new design soon.
