### ISSUE TITLE
Webpack guide is missing fake-async-test.js in testing configuration

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular.io#1376]
Currently the configuration https://angular.io/docs/ts/latest/guide/webpack.html#!#test-configuration is missing this file that may cause issues. See this thread for more https://github.com/angular/angular/issues/8232 and this comment specifically https://github.com/angular/angular/issues/8232#issuecomment-214720135.

Probably this will be unnecessary if this is implemented https://github.com/angular/angular/issues/8353 but it may be good too keep an eye on this issue.

cc : @Foxandxss

**Comment by Foxandxss** [comment]
Didn't know about that. Will check.
