### ISSUE TITLE
Webpack guide package.json build script uses rm, fails on Windows

### ISSUE THREAD

**Issue by mattdistefano** [angular/angular.io#1392]
Pretty sure this will fail on most versions of Windows, due to the absence of rm on that platform:

`"build": "rm -rf dist && webpack --config config/webpack.prod.js --progress --profile --bail"`

Probably should use something like rimraf or implement clean-webpack-plugin inside the webpack config. I tend to prefer the latter, since it keeps the whole build cycle within webpack.

**Comment by Foxandxss** [comment]
And you are right, just to make it simpler I forgot about windows.

I vote for `rimraf`, less intrusive than having to add a whole plugin.

Will fix it.

**Comment by Foxandxss** [comment]
Oh, rimraf was already installed, so even better :)

**Comment by wardbell** [comment]
closed by a3400d0
