### ISSUE TITLE
Webpack guide img instructions missing

### ISSUE THREAD

**Issue by mattdistefano** [angular/angular.io#1394]
This is the `src/app/app.component.html` in the guide:

```html
<main>
  <h1>Hello from Angular 2 App with Webpack</h1>
  <img src="../../public/images/angular.png">
</main>
```

I'm not seeing where this image is supposed to come from, though. I like the idea of having this in the guide, since asset loading is IMO one of the neater features of webpack, but it probably needs more in the way of instructions (i.e. "download the image from _someurl_ and save to _somepath_").

Also, this may just be me, but the whole `public` folder concept seems odd. AFAIK ultimately everything in there will end up being a dependency of some module in `src` and packaged up by webpack anyway. And it looks like code/assets we'd author, vs. third-party files we'd give the `vendor` treatment. So I'm wondering why the `public` folder vs. having the files co-located with the modules, or, at least, directly under `src`? Does the style guide cover this at all?

**Comment by Foxandxss** [comment]
There is a link at the end with the image. 

About public, it exist that way to match what the CLI outputs. If we change that in the CLI, we will change it here too

**Comment by mattdistefano** [comment]
Oh! Yeah, I glanced right over that. Only suggestion I'd have is maybe moving it up closer to where the html is created? Feel free to just close this, though.

**Comment by mattdistefano** [comment]
Looks like 0c49b50cbe0b56f6e0dd2265814eae96dec30bc6 also included moving the image link up a bit. Closing.
