### ISSUE TITLE
Webpack guide webpack.test.js devtools should be devtool

### ISSUE THREAD

**Issue by mattdistefano** [angular/angular.io#1395]
In `config\webpack.test.js`, `devtools: 'source-map'` should be just **devtool** (singular).

Also, according to https://github.com/webpack/karma-webpack#source-maps the specified option should be `inline-source-map` rather than `source-map` (which I can sort of confirm - `source-map` doesn't seem to work).

**Comment by Foxandxss** [comment]
You are right an all points. Fixing.

**Comment by mattdistefano** [comment]
Thanks! And thanks for putting this together in the first place.

**Comment by wardbell** [comment]
Merged in 0c49b50
