### ISSUE TITLE
Linking to Styles in the Style Guide is currently hard to discover

### ISSUE THREAD

**Issue by KyleMcNutt** [angular/angular.io#1397]
Had [this](https://twitter.com/John_Papa/status/731622008996433922) short conversation with @johnpapa about this on Twitter, and decided to open up an issue on this.

Possible Solution:
Have links on each Style number in order to better expose that they can be linked to. This allows for ease of copying from the Browser Address and pasting elsewhere. This promotes not only sharing the Style Guide but also discussion on different styles.

More than open to other possible solutions or better ways to resolve this.

**Comment by KyleMcNutt** [comment]
[Here] (https://github.com/KyleMcNutt/angular.io/commit/d3baa9d3ffffabab5abdec6f4029efbf1156ca9a) is the commit for my proposed solution above, didn't want to open a PR for this though until I got the 👍 on this idea.

**Comment by johnpapa** [comment]
Thanks for the idea. The angular team would need their designer to approve any changes like this. But I love the idea in general. Really, it would be nice to have a way to see that the style titles (and the codes) are links. They do in fact work as deep links, but it's not very discoverable. For example, we cannot click on them, we have to type it in. I'd like to see them act more like a standard link.

cc for their thoughts // @naomiblack @wardbell

**Comment by Foxandxss** [comment]
I opened #1400 to research about the github way (icon on hover) and to be used in all the docs.

**Comment by olore** [comment]
I considered the material link icon in #1339 but wanted to make as little a splash as possible. Given it'll be developers that are accessing this site, the less flash the better IMO.

**Comment by KyleMcNutt** [comment]
I'm not sure if I'd consider an on-hover icon "flashy" personally. It's a familiar UI concept to developers due to GitHub's doc behavior.

**Comment by Foxandxss** [comment]
Yeah, personally it is not like the greatest idea ever, but nowadays, people is really familiar with Github and since they do it, I personally see for those hover icons when I want to share something.

**Comment by olore** [comment]
@KyleMcNutt I hear ya. We should also consider the accessibility and the affordance
