### ISSUE TITLE
docs(ts/tutorial/routing): Remove HeroDetailComponent in HeroesComponent file

### ISSUE THREAD

**Issue by LoganDupont** [angular/angular.io#1398]
After you remove `<my-hero-detail [hero]="selectedHero"></my-hero-detail>` from the `templateurl: 'app/heroes.component.html'` and use instead a router navigation to HeroDetail. I think you don't need the `import { HeroDetailComponent } `and `directives: [HeroDetailComponent]` anymore in the _HeroesComponent_ file.

**Comment by wardbell** [comment]
Good catch!  I took your suggestion in commit a4bc455030efb83bb23d442f58c6180faa2704c0 of PR #1066
