### ISSUE TITLE
Use TypeScript for the Quickstart page

### ISSUE THREAD

**Issue by kpko** [angular/angular.io#14]
Hi,

since AtScript is TypeScript now, I think we should use TypeScript in the example on https://angular.io/docs/js/latest/quickstart.html so we don't need an explanation of AtScript and es6-shim.

**Comment by cssensei** [comment]
:+1:

**Comment by davideast** [comment]
Hell all,

Right now we're waiting on TypeScript 1.5 which will have the features needed to fully drop AtScript in Angular 2.

The example in the quickstart will be valid TypeScript once 1.5 releases. The only change that will be needed is dropping the traceur/es6-shim setup in favor of the TypeScript compiler. The code should stay the same.

Once TypeScript 1.5 releases we'll update the quickstart. Until then it's not completely truthful to use TypeScript in the code samples.

**Comment by kpko** [comment]
This sounds very reasonable :-) looking forward to TS 1.5 then. Thank you very much.
