### ISSUE TITLE
Router guide looses crisis state

### ISSUE THREAD

**Issue by jmcooper** [angular/angular.io#1402]
The crisis list is lost after saving a crisis.  To reproduce:

1) Run the router example
2) Click on a crisis
3) Edit the crisis name
4) Save the crisis
5) Click on the Crisis Center link at the top
6) Notice that the crisis list is missing

**Comment by wardbell** [comment]
This is a KNOWN REPORTED bug in the "new" Release Candidate router.  It should disappear when that router is "fixed". Closing

p.s. Not a problem in the Deprecated Router.
