### ISSUE TITLE
Source code links are referencing local build files

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular.io#1403]
Example page: https://angular.io/docs/ts/latest/api/core/index/createPlatform-function.html

The link that points to the place where the source code was exported from is going to a 404 page.

The link displays `exported from @angular/core/index defined in /Users/naomib/github/angular/modules/@angular/core/src/application_ref.ts (line 23)`

The link to the source code is `https://github.com/angular/angular/tree/2.0.0-rc.1/modules//Users/naomib/github/angular/modules/@angular/core/src/application_ref.ts#L23-L45`

**Comment by wardbell** [comment]
Hi Brandon.  All API doc issues need to be posted to angular/angular.  We can't do anything about them here in angular.io. Please repost there.
