### ISSUE TITLE
Upgrade site to Angular2

### ISSUE THREAD

**Issue by billfranklin** [angular/angular.io#1409]
I believe it is time to, as they say, "eat your own dog food", and upgrade the Angular.io site to Angular 2.  Hard to convince people that it is almost production ready if it isn't even being used by the site that is touting Angular 2.

**Comment by wardbell** [comment]
Thanks but this is not a priority.  We eat our own dog food where it counts ... in the samples.  Using A2 to drive a web site is NOT even a secondary use case for A2. 

I honestly don't think we will do this. Closing.
