### ISSUE TITLE
Directives are NgFor, NgSwitch, etc. and not For, Switch

### ISSUE THREAD

**Issue by SamVerschueren** [angular/angular.io#141]
Hi

In the documentation, the directive `For` is used to iterate over a collection in the view. This is not correct anymore because they changed it to `NgFor`. This is described over here https://github.com/angular/angular/issues/1598

This is one of the pieces of code that will not work because of this https://angular.io/docs/js/latest/guide/displaying-data.html#Create-an-array

I will make a PR to try and fix all these.

**Comment by kwalrath** [comment]
I'm making the corresponding Dart changes in #139.

**Comment by SamVerschueren** [comment]
Issue can be closed as PR https://github.com/angular/angular.io/pull/142 is merged.
