### ISSUE TITLE
Move lengthy SystemJS description from QuickStart into "Module Bundler Alternatives"

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#1413]
The [5 min QuickStart](https://angular.io/docs/ts/latest/quickstart.html) for TypeScript contains a **_lengthy_** explanation of SystemJS. 

Now that we have an [_Introduction to Webpack_](https://angular.io/docs/ts/latest/guide/webpack.html), we might consider factoring out the QuickStart SystemJS prose so as to keep the 5 min QuickStart to 5 min :).

How about creating a chapter, possibly with a title like "**_Module Bundler Alternatives_**", having two subsections:
- SystemJS
- Webpack

**Comment by chalin** [comment]
@Foxandxss, @filipesilva, @wardbell : thoughts?

**Comment by wardbell** [comment]
Intriguing. Maybe we should. But it isn't all that long ... not as long as the Webpack chapter ... and we're about to revisit the QS _yet again_ when we move toward the CLI QS.

Putting this on ice for a while.

**Comment by Foxandxss** [comment]
We don't have SystemJS Stuff on quickstart right now, but what about SystemJS explanations?

**Comment by chalin** [comment]
Will likely be addressed by #2762.
