### ISSUE TITLE
Expanded testing docs soon?

### ISSUE THREAD

**Issue by abierbaum** [angular/angular.io#1416]
As Angular is targetted for solid testing and in general a test first methodology, our team has tried to stay focused on testing all Angular code. Unfortunately it has been very painful because there is no solid documentation about how to test Angular 2 applications and components. There is some documentation about how to setup jasmine, etc and that has proven very useful. [1]

I don't want to sound like I am complaining though. Angular 2 is great, the docs are superb, and up to this point it has been in alpha and beta releases with much of the code changing rapidly. We have tried to make do by patching together community blog posts about testing and trying to read through the test helpers to decipher how to use them.

Now that RC versions are out I am wondering what the timeline is for more complete documentation of how to test Angular 2 applications?

I know it would help our team tremendously and I expect it would help others if the "forthcoming" sections of the test docs [1] could be fleshed out sooner rather than later. I know there are many other things pending as well, but I think this one would be very well received by Angular 2 developers.

1: https://angular.io/docs/ts/latest/guide/testing.html

**Comment by mitsuruog** [comment]
I agree. testing documentation is not enough now.
so I have some documentation about testing. (but those written by Japanese.)
following, in my views of table contents at that time.

1. setup and tools
	- Learning about what tools and setup required for begin the test
1. 5 minute quick start of testing
	- Learning about elements that make up the test. (describe, it, ...)
1. How to test pipe
	- Learning about how to test pipe (pure class)
1. How to test service
	- Learning about how to test the service
	- Learning about beforeEachProviders and way of module override
	- Learning about how to inject our made service into test context 
	- Learning about how to test the XHR
1. How to test component
	- Learning about how to test component
	- Learning about how to use TestComponentBuilder and test the DOM
1. How to test directive
	- Learning about how to test directive
1. How to take a code coverage
	- Learning about how to take code  coverage

How do you think?
maybe, I can rewrite those to English. but it needs a lot of review.

**Comment by Foxandxss** [comment]
Testing docs is a work in progress. There is nothing to worry about :)

**Comment by wardbell** [comment]
I appreciate the nudge. Keep complaining! It's a great story. We just have to tell it!

**Comment by hartjus** [comment]
I'd like add a request for the testing docs as well.  I commonly run into situations where my components pull in an ng2 object, say a `Router` object, and mocking/providing this object in my jasmine tests is a real pain--mostly due to the lack of documentation around this.  

Please, when you write up the testing docs, include snippets for how to properly inject, provide, and/or mock these objects in our tests. (`Router`, `Location` -> `SpyLocation`, `RouteSegment`, `Http`, etc.)

Otherwise, I'm left guessing and googling my way along, which can take quite awhile with how quickly the ng2 code changes.

**Comment by abierbaum** [comment]
@wardbell Just pinging this one again.  Our company has decided to go from just prototyping some Angular 2 apps to jumping in fully for some new products.  We would really like to be testing them completely from the beginning though and it is still unclear what the recommended ways to test components and front-ends in Angular 2.  We don't need a book on it, even just an example test suite that shows all the pieces involved and how to use them.  We can sort it out from there, but right now it isn't even clear to us what methods / helpers should be used and in what combination.

**Comment by wardbell** [comment]
I am rewriting the testing doc this week. Lots of improvements coming for the next RC which is the version I'm targeting. 

If you're using RC4 and want to see some example testing code, you can look at `.specs` in the testing chapter example in [current angular.io master](https://github.com/angular/angular.io/tree/master/public/docs/_examples/testing/ts/app). But it's going to be so much better in another week. If you can wait that long, I suggest you do.

**Comment by canda** [comment]
@wardbell any news on this?

**Comment by abierbaum** [comment]
@wardbell Is there a branch where we can see some of the new docs?  I am about to start porting several of our projects and I would like to make them TDD from the start.

**Comment by crehn** [comment]
I would also like to have more guidance on testing Angular2 apps. At least the quickstart code on github provides some sample code on how to set up karma. But I found it only by accident. I am normally a backend developer so it took me quite a while to get this running.

If there was a hint in the tutorial that the code on github is ahead of the tutorial and already contains a setup for karma, this would have saved me hours --- literally! Please at lest provide a pointer to the quickstart code.

I understand that writing tutorials is not the top priority when there is still no final version of the framework. But it would be *really* helpful if there was more sample code.

**Comment by Foxandxss** [comment]
There is #2198 so we will continue there.
