### ISSUE TITLE
Javascript Documentation for Angular 2?

### ISSUE THREAD

**Issue by dcharles525** [angular/angular.io#1418]
There barely seems to be any documentation on Javascript + Angular 2. I am attempting to learn how to use this new version, but without the documentation it is quite difficult.

**Comment by AntonyBaasan** [comment]
Agree.
In my case, I copy TypeScript(TS) code from examples and read the Javascript(JS) conversions. Yes, it helped me a lot, but eventually, I started to feel that typescript is much better than JS :) Now I completely moved to TS.
Of course, I think, Angular need robust Javascript documentation to bring more developers.

**Comment by wardbell** [comment]
This is on the roadmap. Thanks for your interest. Closing as a duplicate

**Comment by sushantkhanna** [comment]
Any updates to this?
I still see largely everything is TypeScript only.

**Comment by tilwinjoy** [comment]
@wardbell Please refer the original in ticket so that we can follow up on this. I could not find an open ticket/any info on roadmap about this...

**Comment by chalin** [comment]
@tilwinjoy - see #2930

**Comment by tilwinjoy** [comment]
@chalin  That issue is now closed, but there is no JavaScript equivalent of the documentation. Except this [TS to ES6 to ES5 cookbook](https://angular.io/guide/ts-to-js).

Is that all there will be, or are there any plans to have specific docs for JavaScript?

**Comment by chalin** [comment]
@tilwinjoy - as is mentioned in the README, this repo is closed. I'll let @wardbell comment on any possible followup to this request.
