### ISSUE TITLE
typings code / documentation needs updating to make typings 1.x

### ISSUE THREAD

**Issue by pauldhawk** [angular/angular.io#1425]
typings v 1.x changed ambient to global. 
https://angular.io/docs/ts/latest/quickstart.html / typings.json now should be 
```
 "globalDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160317120654",
    "jasmine": "registry:dt/jasmine#2.2.0+20160505161446",
    "node": "registry:dt/node#6.0.0+20160514165920"
  }

```
**https://angular.io/docs/ts/latest/guide/typescript-configuration.html#!#typings**

change :` npm run typings -- install jasmine --ambient --save`
to `npm run typings -- install dt~jasmine --global --save  `

the folder structure is now 
```
├── globals
│   ├── es6-shim
│   │   ├── index.d.ts
│   │   └── typings.json
│   ├── jasmine
│   │   ├── index.d.ts
│   │   └── typings.json
│   └── node
│       ├── index.d.ts
│       └── typings.json
└── index.d.ts
```
change : 
```
{
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}

```
to
```
{
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by wardbell** [comment]
Thanks. Done in 650a4d17e82d06e4af0d8d937dbd8fdd8cfba2f8. 

Don't need _any_ exclude anymore as TS compiler now excludes `node_modules` automatically
