### ISSUE TITLE
Tutorial - Part 5 - Note about Module-Relative Path

### ISSUE THREAD

**Issue by busches** [angular/angular.io#1428]
This note appears in Part 5 of the Tour of Heroes:
`We specify the path all the way back to the application root. Angular doesn't support module-relative paths.`
I believe this is no longer true, as I'm successfully able to just use `templateUrl: 'dashboard.component.html',` and it works just fine.

If this should be removed or improved, I can create a PR.

**Comment by wardbell** [comment]
It is ***half* true**.  You cannot simply remove the `app/` prefix; the app fails. Go ahead and try it in the [plunker](http://localhost:3000/resources/live-examples/toh-5/ts/plnkr.html).

We can use module-relative paths if we set `moduleId: module.id` in the `@Component` metadata. That wasn't an option when the chapter was written. I'll correct the prose.

**Comment by busches** [comment]
Ah, that makes sense. I was using the cli, so I did have `moduleId: module.id`. Thanks for the help Ward.

**Comment by wardbell** [comment]
I updated the prose and added a cookbook on *Component-relative paths* that attempts to explain the whole deal.
