### ISSUE TITLE
(dgeni) local paths in footer for API doc pages

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#1433]
the generated link for the bottom of the API doc pages seems to be broken and showing a local path. (Live on angular.io)

![image](https://cloud.githubusercontent.com/assets/2286589/15396658/08a4c6fe-1dab-11e6-8387-73e70c5ba38d.png)

**Comment by ericjim** [comment]
I suspect this occurred right about the time beta crossed to RC0. I will poke around.
