### ISSUE TITLE
Docs (quickstart): Systemjs.Config.js is missing!

### ISSUE THREAD

**Issue by kabua** [angular/angular.io#1436]
In the 5 Min Quick Start, under Step 1.b, the last tab marked 'systemjs.config.us' states the following:
"BAD FILENAME: ../../_fragments/quickstart/ts/systemjs.config.1.js.md   Current path: docs,ts,latest,quickstart PathToDocs: ../../"

Obviously, this is invalid JS code; therefore, I believe that some kind of link is broken.

**Comment by kabua** [comment]
The missing file can be found [here](https://github.com/angular/angular.io/blob/master/public/docs/_examples/quickstart/ts/systemjs.config.1.js)!

**Comment by jevenson** [comment]
+1

**Comment by Foxandxss** [comment]
@jevenson There is a new option to add reactions to issues. +1 comments doesn't help.

**Comment by wardbell** [comment]
Fixed by #1438

**Comment by VickyRonnen** [comment]
Perhaps it is fixed, but it is certainly not tested.
The [https://angular.io/docs/ts/latest/quickstart.html](quick start guide) still shows 
BAD FILENAME: ../../_fragments/quickstart/ts/systemjs.config.1.js.md   Current path: docs,ts,latest,quickstart PathToDocs: ../../
In the mentioned tab.
Further more the getting started example does not work.
npm start gives error message:

npm ERR! Linux 4.4.9-300.fc23.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! angular2-quickstart@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular2-quickstart@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" '.
npm ERR! This is most likely a problem with the angular2-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run lite" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls angular2-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vicky/angular2-quickstart/app/npm-debug.log

node.js is installed according to the docs 
as root:
curl --silent --location https://rpm.nodesource.com/setup_4.x|bash -
dnf install nodejs

Removing all things and stick to AngularJS 1 for another year at least.
AngularJS2 project is missing any quality control on documentation and thus also on the software it self. Documentation is integral part of the software.
It should work out of the box following the instructions in the docs by every one else.
Simple step for introducing quality control to the AngularJS2 project: create a new clean VM. Do exactly the steps from the docs. If it doesn't work the docs and/or software is wrong.
Quality control is so simple to implement...

**Comment by Foxandxss** [comment]
You need to use node 5 and npm 3.x to make this work.

Also, the bad region issue is fixed in master and will be live soon.

**Comment by VickyRonnen** [comment]
Conclusion the AngularJS2 project is missing any form of quality control. 
The required versions are not mentioned in the documentation.
Getting started is for newbies.
The documentation is not suited for people who wants to get started. 
A waste of their time and a waste of writer's time. 
They delivered something that that is the wrong product, not suitable for getting started at all.
Getting disappointed is the best title at this moment.
Will try next year.

**Comment by naomiblack** [comment]
Hi @VickyRonnen. I'm deleting your comment because it does not meet the guidelines set out in our [Code of Conduct](https://github.com/angular/code-of-conduct).
