### ISSUE TITLE
code snippets shouldn't be bold

### ISSUE THREAD

**Issue by mahonnaise** [angular/angular.io#144]
Syntax themes generally don't use bold fonts. Sometimes bold is used for keywords, but not for everything.

Maybe it doesn't look that bad with Linux or Mac OS, but it certainly looks terrible with Windows' font rendering.

The code is a lot easier to read with the normal font weight:

![angular2-code2](https://cloud.githubusercontent.com/assets/533423/8010727/e0cd01c4-0bb2-11e5-80d6-64742fae8313.png)

**Comment by wardbell** [comment]
Obsolete issue.
