### ISSUE TITLE
Style Guide - Add CONSTANT guideline

### ISSUE THREAD

**Issue by johnpapa** [angular/angular.io#1451]
UPPER_SNAKE_CASE

why? because @wardbell says so :)

**Comment by wardbell** [comment]
That should be good enough.

For those who need more, Angular itself follows this convention as does Microsoft and most of the programming world. Citations when we have a moment. 

Like many conventions, it's difficult to justify in the abstract. We can say that many developers care about the naming conventions that proclaim how an identifier is defined: class or property, constant or variable. These needs change with time: the 'i' in interface, the '_' for privates, Hungarian notation for data type... once essential, now proscribed.

It's far from my favorite recommendation. I'd put this one in the "consider" category.

**Comment by Foxandxss** [comment]
SOUNDS_GOOD_TO_ME

**Comment by johnpapa** [comment]
Agreed. Make it consider

**Comment by shairez** [comment]
+1

**Comment by Foxandxss** [comment]
We added this already.
