### ISSUE TITLE
guide/template-syntax: port to doc design scheme using Jade extends/blocks

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#1460]
Use Jade `extends` with `block`s rather than copying prose.

For the record, here are the differences in the HTML: [diff-ts-dart-html.txt](https://github.com/angular/angular.io/files/275856/diff-ts-dart-html.txt)

**Comment by wardbell** [comment]
Are you making a PR?

**Comment by chalin** [comment]
Working on it now.
