### ISSUE TITLE
ToH Ch7:HTTP - correction to main.ts

### ISSUE THREAD

**Issue by jchatkinson** [angular/angular.io#1474]
Working my way through the ToH tutorial (Great job by the way!)

In the _Simulating the web api_ section I need the following correction to my _app/main.ts_ file in order to successfully compile and run

`import { InMemoryBackendService, SEED_DATA } from 'angular2-in-memory-web-api';`

should be changed to:

`import { InMemoryBackendService, SEED_DATA } from 'angular2-in-memory-web-api/in-memory-backend.service';`

**Comment by Foxandxss** [comment]
Thanks, but this one is actually legit.

We updated the in-memory-web-api like yesterday and we put an `index.js` so importing from `angular2-in-memory-web-api` now does the job directly.

So, you only need to bump your version to latest.

**Comment by wardbell** [comment]
Closing

**Comment by chrisjordanme** [comment]
Hey guys, experiencing the same issue @jchatkinson reported. I took @Foxandxss advice and upped my `angular2-in-memory-web-api` to version `0.0.10` but am receiving a 404.

I'm needing to use the following in _app/main.ts_ line 5, in order to compile correctly:

`import { InMemoryBackendService, SEED_DATA } from 'angular2-in-memory-web-api/src/in-memory-backend.service';`

**Comment by Foxandxss** [comment]
Why are you importing from src folder?

**Comment by Foxandxss** [comment]
How are you trying to use it?

**Comment by MatMath** [comment]
I noticed the same thing. It is because the fix inside the systemjs.config for the Typescript doc was not propagated. 
`'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' }`  
This fix the problem for me. 
I made the pull request.

**Comment by chrisjordanme** [comment]
Thanks. I thought the correct fix should have been made in the system config. I tried changing the property in the map object and overlooked this part of the config. 

Problem solved. Thanks, guys.

**Comment by csharpee** [comment]
This fixed the problem for me too - thank you for sharing. I been tinkering with this for 2 hours now and finally found a solution / fix.
