### ISSUE TITLE
ToH Ch7:HTTP - consistent variable naming with other parts of the tutorial

### ISSUE THREAD

**Issue by jchatkinson** [angular/angular.io#1475]
Ch7 uses `_router` and `_heroService`  while previous sections of the tutorial use `router`
and `heroService`.

**Comment by Foxandxss** [comment]
Thank you!

Tutorial was written before we made those changes and we forgot to make those adjustments when we published it.

Good catch.

**Comment by wardbell** [comment]
closed by #1477
