### ISSUE TITLE
ToH Ch7:HTTP - missing instructions to edit method goBack() in hero-detail.component.ts

### ISSUE THREAD

**Issue by jchatkinson** [angular/angular.io#1476]
At the end of Ch6, the goBack method in _app/hero-detail.component.ts_ looks like:
```
goBack() {
      window.history.back();
}
```

Instructions should be added to modify this method to:
```
goBack(savedHero: Hero = null) {
    this.close.emit(savedHero);
    if (this.navigated) { window.history.back(); }
  }
```

so that it can be used as shown in the save method:
`this.goBack(hero);`

**Comment by wardbell** [comment]
Closed by #1478
