### ISSUE TITLE
text error in TS Tutorial Docs(HTTP Section)

### ISSUE THREAD

**Issue by AAAnderson7301** [angular/angular.io#1493]
Hello,

There are 2 errors with file names in the Tutorial Documents HTTP Section. I followed all the instructions to contribute to fix this issue however I am still getting an Permission error when pushing . Maybe the CLA takes 24 hours?

File Path (angular.io/public/docs/ts/latest/tutorial/toh-pt6.jade)

Lines 262 & 267

Please see image below for the changes needed.

![image](https://cloud.githubusercontent.com/assets/8826208/15484239/1ba262ca-2107-11e6-9fd8-b044f12af5d7.png)

**Comment by Foxandxss** [comment]
You are probably trying to push to our repo and since you don't have permission, you get an error. You need a fork, a branch there and then create a PR.

Or I can fix that for you, your choice.

**Comment by AAAnderson7301** [comment]
Awesome think I got it. Thank you for your help

**Comment by AAAnderson7301** [comment]
somehow the commit picked up on my work email address so it was flagged as CLA: No. I have since added that email to my Github one that has a CLA. Do I need to close this Pull request and request a new one? I do not see the flag being updated as CLA signed.

**Comment by wardbell** [comment]
Closing in favor of a PR
