### ISSUE TITLE
full example for UpgradeAdapter? 

### ISSUE THREAD

**Issue by vance** [angular/angular.io#1495]
I've done the quickstart, now I'm trying to add ng2 to to my ng1.5 app... I *think* i've configured it properly, but I'm not certain without a full project reference. I get some funky compile errors and I'm not sure why without checking against a reference. Any way to get a repo of an example `1.5->2RC1` upgrade project? 

thanks!

**Comment by bringking** [comment]
The Phonecat tutorial is fantastic - 

https://angular.io/docs/ts/latest/guide/upgrade.html
https://github.com/angular/angular-phonecat

Also, here are a few other samples you could take a look at-

https://github.com/juristr/angular2-ngUpgrade-sample
https://github.com/cwadrupldijjit/ng-upgrade-meetup
https://github.com/danielrasmuson/Angular2-UpgradeAdapterExample

**Comment by vance** [comment]
Awesome. research on ng2 is hit or miss. It's hard to ensure examples are up to date. I guess that's my only concern with 3rd party examples, they might not hold up to the same rigor in testing as the angular team =)

**Comment by vance** [comment]
I think the [angular2-ngUpgrade-sample](https://github.com/juristr/angular2-ngUpgrade-sample) might be what I'm looking for but it hasn't been updated since RC1 came out.

**Comment by dancancro** [comment]
@vance, have you had any luck? I'm doing it the other way. I started with a brand new Angular 2 app and am trying to use an Angular 1 directive in it.

I'm following instructions from here:
https://angular.io/docs/ts/latest/guide/upgrade.html#!#using-angular-1-component-directives-from-angular-2-code

and getting this error:
Property 'upgradeNg1Component' does not exist on type 'typeof UpgradeAdapter'.

[plunk](http://plnkr.co/edit/kRzCSm?p=preview)

**Comment by bringking** [comment]
@dancancro you are missing the instantiation step. UpgradeAdapter is a class that needs to be instantiated. 

Here is a snippet from the [official guide](https://angular.io/docs/ts/latest/guide/upgrade.html#!#bootstrapping-a-hybrid-1-2-phonecat) (which I suggest you read, it is great) 

```js
import { UpgradeAdapter } from '@angular/upgrade';
export const upgradeAdapter = new UpgradeAdapter();
```

Then you can use the exported singleton to upgrade and downgrade components

**Comment by dancancro** [comment]
Thanks. I was just following the instructions from the [official guide](https://angular.io/docs/ts/latest/guide/upgrade.html#!#using-angular-1-component-directives-from-angular-2-code) which doesn't do a `new`

```
import { Component } from '@angular/core';
import { upgradeAdapter } from './upgrade_adapter';
const HeroDetail = upgradeAdapter.upgradeNg1Component('heroDetail');
@Component({
  selector: 'my-container',
  template: `
    <h1>Tour of Heroes</h1>
    <hero-detail></hero-detail>
  `,
  directives: [HeroDetail]
})
export class ContainerComponent {
}
```

My next hurdle is loading the Angular 1 directive I want to use - "angucomplete-alt", from [github](https://www.npmjs.com/package/angucomplete-alt) and [npmjs](https://www.npmjs.com/package/angucomplete-alt)

I'd like to get that working in my [app](https://github.com/dancancro/ang-cli) and my [plunk](http://plnkr.co/edit/kRzCSm?p=preview)

Ideas?

**Comment by vance** [comment]
It seemed too unstable to proceed on a production app. This will be
revisited after it's 1.0 release.


On Sun, May 29, 2016 at 10:06 AM, Dan Cancro <notifications@github.com>
wrote:

> Thanks. I was just following the instructions from the official guide
> <https://angular.io/docs/ts/latest/guide/upgrade.html#!%23using-angular-1-component-directives-from-angular-2-code>
> which doesn't do a new
>
> import { Component } from '@angular/core';
> import { upgradeAdapter } from './upgrade_adapter';
> const HeroDetail = upgradeAdapter.upgradeNg1Component('heroDetail');
> @Component({
>   selector: 'my-container',
>   template: `
>     <h1>Tour of Heroes</h1>
>     <hero-detail></hero-detail>
>   `,
>   directives: [HeroDetail]
> })
> export class ContainerComponent {
> }
>
> My next hurdle is loading the Angular 1 directive I want to use -
> "angucomplete-alt", from github
> <https://www.npmjs.com/package/angucomplete-alt> and npmjs
> <https://www.npmjs.com/package/angucomplete-alt>
>
> I'd like to get that working in my app
> <https://github.com/dancancro/ang-cli> and my plunk
> <http://plnkr.co/edit/kRzCSm?p=preview>
>
> Ideas?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular.io/issues/1495#issuecomment-222371277>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAI4P9E0pxtZyiRiSlEnJ-fQ_RJFxqkwks5qGcezgaJpZM4Ik5cx>
> .
>



-- 


The World's Longest Ongoing Illustration
ForeverScape.com <http://www.foreverscape.com/> | @foreverscape
<https://twitter.com/foreverscape>  | On Github
<https://github.com/vance/foreverscapecore> | In the News
<http://www.foreverscape.com/art/reviews/>
