### ISSUE TITLE
docs(upgrade): Advice on upgrading from Angular 1

### ISSUE THREAD

**Issue by bampakoa** [angular/angular.io#1497]
It would be nice, if there was a paragraph in **Upgrading from 1.x** developer guide that will explain whether someone should start upgrading an application from Angular 1 to Angular 2 according to the application context. It should be written as an advice to those developers that wish to start upgrading but do not know if is really the good time to do so. I would create a PR myself but I have not answered that question yet 😄 

Also it would be really nice, if there was a separate section in the documentation site that will explain whether someone should start using Angular2 for new applications. Maybe that could be in the **Features** section or in the landing page.

**Comment by Foxandxss** [comment]
I am not sure about this :/

/cc @wardbell

**Comment by bampakoa** [comment]
@Foxandxss Since my suggestion was referring to the beta version of Angular2, I think this issue is already outdated. What do you think about closing it now?

**Comment by Foxandxss** [comment]
Yeah :)
