### ISSUE TITLE
fix alignment of stability badges

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#1500]
The vertical alignment with the header looks funny to me. could we try align center instead of what seems to be align top? or maybe just more whitespace?

paging @alexwolfe 

![image](https://cloud.githubusercontent.com/assets/2286589/15515184/c3a1a25c-21a1-11e6-8280-e7111dafd1b9.png)

**Comment by ericjim** [comment]
<img width="1191" alt="screen shot 2016-05-25 at 10 48 43 am" src="https://cloud.githubusercontent.com/assets/1329167/15544339/4a56874e-2266-11e6-9c55-91155b5548a1.png">

How's that? The badges are aligned within a flexbox, so I can center them perfectly within their container.

@naomiblack
