### ISSUE TITLE
Shadow box around pages

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular.io#1505]
/cc @ericjim @naomiblack 

I am working on some ideas for an article with embedded editors and stuff and the shadow box that wraps the articles is a bit claustrophobic.

![](http://puu.sh/p4yqe/f1b6f91f88.png)

I personally read this better:

![](http://puu.sh/p4yrG/73b7e67c9c.png)

I am not an UX expert, but removing the box around is like giving freedom to my mind.

I want to do something like:

![](http://puu.sh/p1v4k/08dbdbd764.png)

And since the plunker has some borders and the article itself have more borders, it feels like everything is smaller than they really are.

I guess that if we need a visual hint to see what is the article width, we could use something else.

Cheers.

**Comment by ericjim** [comment]
@naomiblack @Foxandxss would this work https://no-shadow-angular-io.firebaseapp.com/ ?

**Comment by Foxandxss** [comment]
For me is perfect, easier for the eye.
