### ISSUE TITLE
docs(dev guide): issue on "latest/guide/forms.html"

### ISSUE THREAD

**Issue by georgedim** [angular/angular.io#1507]
[Angular2 for javascript]

    app/hero-form.component.js  
it misses:

    " })(window.app || (window.app = {}));"
at the end

**Comment by wardbell** [comment]
It appears to have that now.

**Comment by georgedim** [comment]
This seems that has been fixed on "live example" [http://plnkr.co/edit/?p=preview](url), but not on the page [https://angular.io/docs/js/latest/guide/forms.html](url) from where you can see and copy the code.
