### ISSUE TITLE
Update Basics to new design scheme using Jade extends/blocks

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#1508]
- [x] overview - #1410
- [x] architecture - #1807
- [x] displaying-data - #1819
- [ ] user input
- ~forms: TS and Dart versions have diverged too much~
- [x] dependency-injection - #1573
- [x] template-syntax - #1465
- ~cheatsheet~
- ~style guide (no Dart version yet)~
- [x] glossary - #2100

Contributes to #1506.

**Comment by wardbell** [comment]
Please hold on this project!

**Comment by chalin** [comment]
> Please hold on this project!

Ok. FYI, I am almost done (95%) with the dependency-injection chapter. I'll commit on Tuesday. Will hold off working on the other chapters until I hear news from you. 

cc: @kwalrath

**Comment by chalin** [comment]
We will no longer be implementing this new scheme.
