### ISSUE TITLE
angular.io Broken on IE9, IE11 and Firefox - Failed to instantiate module angularIOApp due to

### ISSUE THREAD

**Issue by acostaf** [angular/angular.io#1519]
Opened this issue on the wrong site

https://github.com/angular/angular/issues/8835#issuecomment-221628464

NG2 site it is broken, I am getting "Failed to instantiate module angularIOApp due to:"

Error: [$injector:modulerr] http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=angularIOApp&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.4.8%2F%24injector%2Fmodulerr%3Fp0%3Dfirebase%26p1%3D%255B%2524injector%253Anomod%255D%2520http%253A%252F%2......

**Comment by pkozlowski-opensource** [comment]
Are you sure that you report is about https://angular.io/ and not https://www.angularjs.org/? Asking since the error in the issue points to https://www.angularjs.org/.

In any case both sites work for me without errors in FFox...

**Comment by acostaf** [comment]
I am trying to hit https://angular.io/, noticed that have been broken  for me for the whole week from my PC in all my browsers, works fine on my mobile phone

**Comment by acostaf** [comment]
Forget it, false alarm, my company is blocking one of the CDN
