### ISSUE TITLE
docs(resources): fixes manning publications link

### ISSUE THREAD

**Issue by jesselpalmer** [angular/angular.io#1531]
The **Manning Publications** link at [https://angular.io/resources/](https://angular.io/resources/) should point to [https://www.manning.com/search?q=angular](https://www.manning.com/search?q=angular) instead of [https://www.manning.com/search](https://www.manning.com/search).

**Comment by wardbell** [comment]
Please submit a PR

**Comment by jesselpalmer** [comment]
I'm not sure if I can. The resources look like they are pulling from Firebase: [https://github.com/angular/angular.io/blob/5a0a0160ce365370640a11229a6d32f1a510206e/public/resources/js/controllers/resources-controller.js](https://github.com/angular/angular.io/blob/5a0a0160ce365370640a11229a6d32f1a510206e/public/resources/js/controllers/resources-controller.js). /cc @ericjim

**Comment by wardbell** [comment]
Right you are. Handing off to @naomiblack

**Comment by ericjim** [comment]
@juleskremer has access to the database. Could you also fix the Rangle.io link? The link for rangle.io under Online Training appears to be broken. Could you replace (https://rangle.io/services/javascript-training/training-angular1-angular2-with-ngupgrade/) with (https://rangle.io/services/javascript-training/angular-2-online-training/)

**Comment by ericjim** [comment]
@jesselpalmer can you verify now, I changed the link.

**Comment by jesselpalmer** [comment]
@ericjim lgtm
