### ISSUE TITLE
Specify the main entry point for angular2-in-memory-web-api

### ISSUE THREAD

**Issue by bouzlibop** [angular/angular.io#1541]
**Overview of the Issue**

Today I was following both [5 minutes quickstart](https://angular.io/docs/ts/latest/quickstart.html) and [tour of heroes tutorial](https://angular.io/docs/ts/latest/tutorial/). Great resources!

What I found is that in `systemjs.config.js` example shown in *5 minutes quickstart* the main entry point for `angular2-in-memory-web-api` [is not set](https://github.com/angular/angular.io/blob/master/public/docs/_examples/quickstart/ts/systemjs.config.1.js#L21). On the other hand it is properly set everywhere else, eg [here](https://github.com/angular/quickstart/blob/master/systemjs.config.js#L20).

Not having this field set is causing following errors once one gets to [the last part of the tutorial](https://angular.io/docs/ts/latest/tutorial/toh-pt6.html):
````
zone.js:101 GET http://localhost:3000/node_modules/angular2-in-memory-web-api/ 404 (Not Found)
node_modules:17 Error: Error: XHR error (404 Not Found) loading 
```

***Motivation for or Use Case***

This won't be an issue for someone who is following `Run the live example` links to Plunker or is using code from https://github.com/angular/quickstart.

Nonetheless, if someone (like me for example) took this advice: 

>Create a folder called angular2-tour-of-heroes and follow the QuickStart steps which provide the prerequisites, the folder structure, and the core files for our Tour of Heroes.

and used the `systemjs.config.js` mentioned above, one will run into some issues.

**Operating system**
OS X El Capitan Version 10.11.5

**Browsers**
Chrome Version 51.0.2704.63 (64-bit)

**Suggested Fix**

Change [this line](https://github.com/angular/angular.io/blob/master/public/docs/_examples/quickstart/ts/systemjs.config.1.js#L21) to `'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },`

**Comment by Foxandxss** [comment]
Fix on its way.

Thank you.

**Comment by wardbell** [comment]
We know. We fixed and merged it. Awaiting publication
