### ISSUE TITLE
Documentation: Tutorial: Chapter7 Http: .ts file endings for for HTML files

### ISSUE THREAD

**Issue by rskokan** [angular/angular.io#1546]
The Angular 2 tutorial at https://angular.io/docs/ts/latest/tutorial/toh-pt6.html several time has in the header of file excerpts .ts extension instead of .html.

Example:

> Add the following HTML to the **heroes.component.html**, just below the hero list (the *ngFor).
> 
> **app/heroes.component.ts (add)**
> ... HTML code here ...

**Comment by wardbell** [comment]
We know. We fixed and merged it. Awaiting publication
