### ISSUE TITLE
Overuse of `hero` and `heroes`

### ISSUE THREAD

**Issue by jerlich** [angular/angular.io#1548]
I am a relatively experienced programmer and software engineer and I've been doing the "heroes" example to learn angular.

The examples use the variable name `hero` and `heroes` in many different places which makes it confusing for a new angular user to understand variable scope and how data is passed around between components / templates / services, etc.

For example in lesson 4 there is a `heroes` that is passed from the service to the AppComponent. But this does not have to have the same variable name. 

in the `<li *ngFor="let hero of heroes"...` the `heroes` there must match the variable name in the exported `AppComponent` class, but because of the overuse, that isn't clear. The `hero` in the list element only has to match the variable name within that list element and is independent of the `hero` variable in the HeroDetailComponent.

I appreciate the time that you have taken to make these tutorials, just added my 2 cents to try to improve them.

**Comment by wardbell** [comment]
Thanks. And I "fix" this kind of thing from time to time. But I don't see how to make your point actionable and there is no use pretending that we're going to do it on our own.

**Comment by jerlich** [comment]
I'm a bit confused by your response: one way to make it _actionable_ would be to rename the variables, like in the li tag call the variable `liHero` in the `HeroDetailComponent` call it `hdcHero`, etc.
