### ISSUE TITLE
dgeni: provide a section for documentation when an API doc uses @deprecated

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#1567]
Similar to https://github.com/angular/angular.io/issues/1566

- [ ] deprecated badge should display regardless of whether text is included
- [ ] add a new doc section "Deprecation Notes" before "How to Use" that exports any text associated with an @deprecated label. if no text found, export "Not Yet Documented"
- [ ] include @deprecated text existence in the JSON export file for the api docs

**Comment by ericjim** [comment]
The third point, there already exists a `stability` slot in the `api-list.json` which will match to `deprecated` if the API is deprecated. Does this cover your needs on this point? @naomiblack
