### ISSUE TITLE
dgeni/jade: fix warnings coming from API docs

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#1577]
This one is a little mysterious...

Running `check-deploy` produces a large number of warning messages that look like `Warning: missing space before text for line 35 of jade file "..."` coming from the API docs.

Can we figure out what in the template is doing this, and fix it?

Low priority but it's an ongoing annoyance that would be nice to fix

**Comment by ericjim** [comment]
This issue remains a bit elusive to me.

**Comment by Foxandxss** [comment]
Closing as we are migrating to the new site and we don't jade anymore !
