### ISSUE TITLE
[Dart][example] tutorial/toh-5: hosted sample is always "Loading..."

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#1608]
When I go to http://angular-examples.github.io/toh-5/, it just says "Loading..." Looking at the console, I see these messages:

```
http://angular-examples.github.io/styles.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://angular-examples.github.io/main.dart.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://angular-examples.github.io/styles.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

Note the lack of `toh-5/` in those URLs. Those files _are_ in https://github.com/angular-examples/toh-5/tree/gh-pages. For example, http://angular-examples.github.io/toh-5/styles.css works. Ah, routing. Perhaps we can change the example to use a base that works for the hosted version? We should probably put a visible note about this in the index.html, since this is a common stumbling block.

cc @chalin

**Comment by chalin** [comment]
I've identified the problem. Will fix shortly.

**Comment by chalin** [comment]
Oups, sorry, I had not read the full text of the issue before I signed off yesterday (and seen that you outlined the problem :). Will look into this shortly.

**Comment by chalin** [comment]
Temporarily fixed by manually changing the `base href` to
```html
<base href="/toh-5/">
```

Let's leave this open until we find a permanent solution (where the dart-doc-syncer can generate the proper `index.html`).

**Comment by chalin** [comment]
Fixed by https://github.com/angular/dart-doc-syncer/pull/14.
