### ISSUE TITLE
[Dart][example] tutorial/toh-*: main.dart not found

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#1610]
It looks like the dart-to-js rewriter hasn't run, making these examples slow to start up. It seems to me that we should run it for our hosted apps; devs can always create their own, Dart-first copy of the app.

(I haven't checked to see whether our other samples use the rewriter.)

**Comment by chalin** [comment]
I'm not sure how this came about. I noticed the problem only for some examples (e.g. toh-1 to 3). Just re-running the dart-doc-syncer fixed those. I am re-syncing all examples, so this issue is likely fully resolved.

**Comment by chalin** [comment]
All hosted Dart examples have been updated and I confirm that the "main.dart not found" error no longer occurs for any of the examples.

**Comment by kwalrath** [comment]
Thanks!
