### ISSUE TITLE
Style-guide - don't import from `.../src` of dependencies

### ISSUE THREAD

**Issue by zoechi** [angular/angular.io#1617]
I haven't seen this mentioned anywhere 
because `src` is considered being private implementation that should not be accessed from the outside.

**Comment by Foxandxss** [comment]
Could you put an example? I'm not really sure if I follow.

**Comment by zoechi** [comment]
Sorry for not being more clear

Like mentioned in http://stackoverflow.com/a/37695504/217408

> `import {isString, isArray} from "@angular/common/src/facade/lang";`

As far as I know one should not import from the `.../src/... directory of a dependency because it is considered private.

**Comment by Foxandxss** [comment]
You can't do that anymore, so closing!
