### ISSUE TITLE
QuickStart CLI integration into the docs - discussion

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#1624]
Use of the CLI for QuickStart makes the creation of the QS app very easy :). Stagehand offers the equivalent on the Dart side.

What is the plan to integrate this prose? My suggestion would be to keep the current QS chapter as is and add a (short) section at the end showing how to create the QS app using CLI. My reasoning is there is value in explaining all the app parts in details first (and this once for QS), before showing how awsome CLI is :). Esp. if the tutorial is rewritten to use CLI.

Thoughts? @kwalrath @wardbell @Foxandxss @filipesilva

**Comment by filipesilva** [comment]
The plan is to keep both the CLI and the normal quickstart, I believe.

**Comment by chalin** [comment]
QS is such a simple application, it doesn't seem appealing to have two long chapters dedicated to it. With two full chapters, there is, inevitably, (unnecessary?) repetition of some of the information. (My 2 cents)

**Comment by kwalrath** [comment]
There's also the fact that most people don't use Stagehand from the command line—they get its functionality for free when they use an IDE like WebStorm.

It might be nice to have all the text in one file, letting the user choose which approach they want to take. That way the user has one place to go, and they can see how their choice (vanilla/CLI/WS) affects the process.

**Comment by chalin** [comment]
Quickstart CLI is now part of the site. Closing.
