### ISSUE TITLE
Proof read toh-1 to -5

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#1628]
Proof reading tutorial: prose, code
 
 - [ ] toh-1 - #1614, #1615.
 - [ ] toh-2 - #1621, #1622.
 - [ ] toh-3 - #1629, #1630.
 - [ ] toh-4 - #1637, #1638.
 - [ ] toh-5 - #1643, #1644.

**Comment by wardbell** [comment]
closed by PRs

**Comment by chalin** [comment]
Extending this issue to also cover toh-6.
