### ISSUE TITLE
Missing part in quickstart guide, part 6

### ISSUE THREAD

**Issue by sergous** [angular/angular.io#1631]
I'm submitting a bug report

Current behavior
here https://angular.io/docs/ts/latest/tutorial/toh-pt6.html there is no part about

import { Http, Response } from '@angular/http';
..
constructor (private http: Http) {}
currently it's not working

Expected/desired behavior
working step by step guide with all the code from Live demo.

**Comment by Foxandxss** [comment]
Not really sure if I follow. 

Could you give more details?

**Comment by sergous** [comment]
Today i finish the guide  and so working solution in the chapter end. Problem was in my expectation of all parts of code covered in text, not only at the end in review like in previous parts. Notice about this at the end will be useful.
Anyway I succeed with the guide, so closing case.
