### ISSUE TITLE
Style 05-15 Avoid example doesn't align with Tutorial

### ISSUE THREAD

**Issue by ShaneCourtrille** [angular/angular.io#1639]
In Style 05-15 the Avoid example shows the usage of Observables but the http page in the Tutorial specifically uses Promises.  I find this a bit confusing since the http usage of Promises makes it appear that this is the preferred way of accessing http so I would expect the style guide to align with that.

**Comment by Foxandxss** [comment]
We still recommend Observables, but we decided to show how to use Promises in the tutorial and then move that to Observables in the next part (which is going to be released soon).

**Comment by ShaneCourtrille** [comment]
That makes sense as it helps people to transition their current skills.
Thanks for the response.
