### ISSUE TITLE
Heroes tutorial toh-pt1.html does not mention to add platform_directives to pubspec.yaml

### ISSUE THREAD

**Issue by sturmf** [angular/angular.io#1642]
* **I'm submitting a because for a beginner it is not obvious if you add ngModel that you need to add platform_directives to the pubspec.yaml**
- [x ] bug report

**Expected/desired behavior**
Info in the tutorial step about this

Forgot to add that I am doing the Angular2-Dart heroes tutorial.

**Comment by Foxandxss** [comment]
Let's ping @chalin in here.

**Comment by chalin** [comment]
Thanks again for having reported this issue. A fix has been submitted (#1647) which brings all `pubspec.yaml` files to a common baseline, that includes common directives.
