### ISSUE TITLE
Dart heroes tutorial source is inconsistent

### ISSUE THREAD

**Issue by sturmf** [angular/angular.io#1651]
Hi, one more small inconsistency in the heroes tutorial. Between 

  https://github.com/angular/angular.io/blob/master/public/docs/_examples/toh-4/dart/lib/mock_heroes.dart

and

  https://github.com/angular/angular.io/blob/master/public/docs/_examples/toh-5/dart/lib/mock_heroes.dart

you change the definition from final List<Hero> mockHeroes to final List<Hero> HEROES. This can be confusing for beginners.

@chalin Btw. I hope it's ok me reporting these issues, if not, I will stop. Besides this the tutorial is great! And I am eagerly awaiting the next chapters for dart.

**Comment by chalin** [comment]
Hi Fabian: please continue to report such issues; this kind of feedback is greatly appreciated :).

You are right, there is a switch in name. The issue will have been fixed once #1643 is merged; e.g. see https://github.com/angular/angular.io/pull/1643/files#diff-94b44f4a8e4e22d08e9d2410a861de6bL10

**Comment by kwalrath** [comment]
#1643 has been merged. It might take a few days for the change to appear on the website.
