### ISSUE TITLE
Heroes tutorial uses pub serve which does not support pushState

### ISSUE THREAD

**Issue by sturmf** [angular/angular.io#1652]
I had the problem that I could not refresh a deep link into the heroes tutorial. E.g. http://localhost:8080/heroes would produce an 404 error.

After some help from the nice guys in the slack channel the following solves my issue.
In app_component.dart add:

`import 'package:angular2/platform/common.dart';`

and 

```
  providers: const [
    ROUTER_PROVIDERS,
    const Provider(LocationStrategy, useClass: HashLocationStrategy),
    HeroService
  ]
```

After that urls change into a form with a # but now refreshes work fine! The reason seems to be that `pub serve` does not support pushState.

**Comment by chalin** [comment]
cf. https://github.com/dart-lang/pub/issues/1374

@kwalrath we'll need to have a general discussion about how we want to handle this in the tutorial and elsewhere in the docs.

**Comment by chalin** [comment]
Btw, AFAIK, this has nothing to do pushState, although it is correct that `pub serve` doesn't play nice with routes, by default. I'm looking into this now.

**Comment by chalin** [comment]
@kwalrath : we should probably close this issue as a duplicate of #1919.

**Comment by kwalrath** [comment]
Closing as duplicate of #1919...
