### ISSUE TITLE
API doc generation broken by angular commit f39c9c9 [style(lint): re-format modules/@angular]

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#1662]
Hey @alexeagle and @ericjim and @petebacondarwin -- this lint change introduced jade errors in the API docs and is preventing us from deploying the site any later than https://github.com/angular/angular/commit/f39c9c9. 

The first error encountered is in `@angular/core/src/metadata/directives.ts` which produces http://localhost:3000/docs/ts/latest/api/core/index/ComponentMetadata-class.html but it's possible this is just the first file we hit with the issue. 

It looks like a bunch of `div` tags that should be output to jade as `.div` are being incorrectly formatted by the template.

<img width="1171" alt="screen shot 2016-06-13 at 9 55 41 pm" src="https://cloud.githubusercontent.com/assets/2286589/16031620/f120e5d8-31b1-11e6-9d0e-cdfab7c7aa29.png">

What's odd is that other API doc pages, e.g. http://localhost:3000/docs/ts/latest/api/core/index/ComponentRef-class.html are not affected. 

I need some help figuring out 1) which dgeni template to fix and 2) how to actually fix it.

Urgent, because we cannot publish RC2 API docs without a fix.

**Comment by petebacondarwin** [comment]
The actual jade error is due to lines 37-55, where the list of options is heavily indented. 

```
    div(layout="column")
      pre(class="prettyprint no-bg-with-indent")
        a(class="code-anchor" href="#constructor")
          code(class="code-background api-doc-code") constructor
        code(class="api-doc-code") ({selector,
                       inputs,
                       outputs,
                       properties,
                       events,
                       host,
                       exportAs,
                       moduleId,
                       providers,
                       viewProviders,
                       changeDetection = ChangeDetectionStrategy.Default,
                       queries,
                       templateUrl,
                       template,
                       styleUrls,
                       styles,
                       animations,
                       directives,
                       pipes,
                       encapsulation}?: {
            selector?: string,
            inputs?: string[],
            outputs?: string[],
            /** @deprecated */ properties?: string[],
            /** @deprecated */ events?: string[],
            host?: {[key: string]: string},
            providers?: any[],
            exportAs?: string,
            moduleId?: string,
            viewProviders?: any[],
            queries?: {[key: string]: any},
            changeDetection?: ChangeDetectionStrategy,
            templateUrl?: string,
            template?: string,
            styleUrls?: string[],
            styles?: string[],
            animations?: AnimationEntryMetadata[],
            directives?: Array&lt;Type|any[]&gt;,
            pipes?: Array&lt;Type|any[]&gt;,
            encapsulation?: ViewEncapsulation
          })
```

**Comment by naomiblack** [comment]
is this something we can fix in dgeni, or do we need to un-lint-format these entries in the API itself?
