### ISSUE TITLE
Google search redirects to invalid links

### ISSUE THREAD

**Issue by zoechi** [angular/angular.io#1678]
Google search results show

https://angular.io/docs/js/latest/api/core/OpaqueToken-class.html (broken)

angular.io search shows

https://angular.io/docs/ts/latest/api/core/index/OpaqueToken-class.html

Some redirect would be great. I encoutered this several times already today.

**Comment by Foxandxss** [comment]
Yes, we had the API twice in the past, one really old version and a modern one. We got rid of the old, but old links will still show. 

Something to fix yes

**Comment by eddhannay** [comment]
The guide on Dependency Injection has a broken link related to this: https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/guide/dependency-injection.jade#L761

Leads to the missing page: https://angular.io/docs/js/latest/api/core/OpaqueToken-class.html, which actually exists at https://angular.io/docs/ts/latest/api/core/index/OpaqueToken-class.html works fine.
