### ISSUE TITLE
Document `@Component` interpolation config

### ISSUE THREAD

**Issue by vicb** [angular/angular.io#1692]
see https://github.com/angular/angular/pull/9158

The PR should land soon and will allow overriding the interpolation symbols (`{{`, `}}`)

**Comment by Foxandxss** [comment]
Victor, what could we do in our end for this? I see that the interpolation config is on the ComponentMetadata API, couldn't we put a little text on there? All the other configs have explanation but this one.

**Comment by vicb** [comment]
Yes we can, can't do that before next week but I'll try then

**Comment by vicb** [comment]
@IgorMinar is handling this on the angular repo
