### ISSUE TITLE
Missing Steps in Tutorial 7

### ISSUE THREAD

**Issue by lucaseverett** [angular/angular.io#1697]
There are a few areas in the HTTP tutorial where instructions are missing.

1) There is no instruction to add the save button to hero-detail.component.html in the tutorial. However, the tutorial implies that instruction has been given because the text reads, `Here is HeroDetailComponent with its new save button.`

The only appearance of the save button is in the final code at the end of the tutorial.

2) There are instructions missing for several additions to hero.service.ts. The tutorial states `After these additions our HeroService looks like this:`

At that point in the tutorial, instructions have not been given to add 
`import { Headers, Http } from '@angular/http';` or `private heroesUrl = 'app/heroes';  // URL to web api`,
or `constructor(private http: Http)` but that code shows up in the final code.

3) There are missing instructions for additions to hero.component.ts.

`addingHero = false;` and `error: any;` are in the final code for the HeroesComponent class at the end of the tutorial, however that is the only appearance of that code in the tutorial.

4) The final code for heroes.component.html is slightly different than what is derived from following along with the tutorial.

There is a new span `<span class="hero-element">` wrapped around the hero information in the final code at the end of the tutorial that is not introduced in the tutorial.

**Comment by Foxandxss** [comment]
Thanks mate, all that feedback is really appreciated.

I will take a look at all those points.

**Comment by diegotascon** [comment]
I opened by mistake issue https://github.com/angular/angular/issues/10851 for angular instead of angular.io. It seems they're not fixed yet :?

**Comment by Foxandxss** [comment]
Still open, so I don't think so. I will leave it open so I can fix it.

**Comment by Foxandxss** [comment]
We changed the ToH chapter quite a bit lately and I checked all this points and I believe they are all fixed. Please open a new issue if you feel like something is still missing.
