### ISSUE TITLE
Update docs to use ngSwitchCase instead of ngSwitchWhen

### ISSUE THREAD

**Issue by Blasz** [angular/angular.io#1698]
RC2 has added the `ngSwitchCase` directive to replace `ngSwitchWhen`: https://github.com/angular/angular/commit/e1fcab7

The docs should be updated to reflect this, especially since the API docs for `ngSwitchWhen` 404's: https://angular.io/docs/ts/latest/api/common/index/NgSwitchWhen-directive.html

**Comment by thomasjosephgreco** [comment]
@Blasz granted that you are not working on this, and haven't assigned anyone to work on this, I can definitely lend a hand 😄 I am really trying to get as involved as much as possible with Angular2 based projects, and would love to help out here (as well as any other areas similar to this that may need fixing). Let me know !

**Comment by Foxandxss** [comment]
All the API is generated automagically from the Angular repository.

That means that all issues / fixes about the API should be made there. Here we just pull it from there and present it on screen.

That being said, if you go to the API REFERENCE and look for "ngSwitch" you can see the new "ngSwitchCase" and not the old "ngSwitchWhen". Same with the search box.

So I am not sure if there is any other course of action needed here.

**Comment by Blasz** [comment]
@Foxandxss I was referring to it's use in the guides/documentation, not the API reference.

E.g. https://www.google.com.au/search?q=ngSwitchWhen+site%3Ahttps%3A%2F%2Fangular.io%2Fdocs%2Fts%2Flatest%2Fguide%2F

**Comment by Foxandxss** [comment]
Oh, I shouldn't really read issues asleep, you are right. My bad.

Feel free to send a PR or I can do that for you if you want.

**Comment by Blasz** [comment]
No worries. I'll send a PR through.

**Comment by Foxandxss** [comment]
There are a lot of more usage of that than what that search gives to you.

I will fix the cheatsheet myself since that is not that obvious to fix.

**Comment by Foxandxss** [comment]
I am closing this in favor of #1710 

Sorry, he didn't see it and pushed a PR.
