### ISSUE TITLE
Add superpowers?

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular.io#17]
Angular since the early beginings uses superpowers or superheroes for theming various aspects of the project.

examples:

- all releases are published with a release name that describes a superpower (often quirky ones)
- many talks about Angular make reference to super heroes or super powers
- many blog posts build on top of the superhero theme (see the [ionic example](http://ionicframework.com/blog/angular-2-ionic/) )
- ng-conf used super-powers in their environment design
- some tools for angular use references to superheros as well (e.g. batarang)
- our t-shirts are superhero like

Overall, the community really likes this quirky part of the project and it would be great to preserve it lightly in the angular.io design.

**Comment by irthos** [comment]
@IgorMinar from your perspective, which superhero is most like Angular?
