### ISSUE TITLE
Allow search results to be opened in a new tab

### ISSUE THREAD

**Issue by Blasz** [angular/angular.io#1701]
Currently, I must left click a search result which opens in the same window.

This detracts from usability when I want to view multiple results as I can only view one result at a time and must repeat my search for each new page I want to view.

Example: When searching ngFor, I'd like to see both the api docs and see where its used the Displaying Data/Template Syntax guides.

![image](https://cloud.githubusercontent.com/assets/2231370/16183220/731cd28c-36f2-11e6-9d39-9395f429d726.png)

With this setback and the fact that the search results cannot display on a separate page, I'm preferring to just use site-specific google searches, e.g.  `ngFor site:https://angular.io/docs/ts/`.

**Comment by Foxandxss** [comment]
We are implemeting a new search box. We will have this in mind.

**Comment by lazaridis-com** [comment]
[issue.keep]

**Comment by Foxandxss** [comment]
@lazaridis-com I am curious, is that an script or something you have? I see you write a lot of stuff between []

**Comment by lazaridis-com** [comment]
@Foxandxss , "[]" marks an "not directly related to the content" (e.g. when you place remarks into someone elses writings. Or in your own writings, it means "not directly related to the writing". So, if my comment contains something off-topic, its placed within "[]". And when its just an "issue.keep", like here, it just helps me to find issues later with a search, to continue.

I saw your "We will have this in mind.", and used "issue.keep", to help me keeping this issue in mind (as its closed now, and thus off my radar).

But you thought is correct, i could(!) be a script/tool, too - but it's not, it's a manual process.
