### ISSUE TITLE
Document the classlist shim for IE compatibility

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular.io#1703]
See angular/angular#6327

Internet Explorer doesn't support the `classlist` property on SVG elements. So things like `NgSwitch` don't work without a shim.

```
"dependencies": {
  "classlist.js": "1.1.20150312"
}
```
provides a working solution

**Comment by Foxandxss** [comment]
Now we have a "browser support" guide that cover this.

**Comment by snolflake** [comment]
Here's the link:
https://angular.io/docs/ts/latest/guide/browser-support.html
