### ISSUE TITLE
Precompiled HTML for offline docs usage 

### ISSUE THREAD

**Issue by blackjyn** [angular/angular.io#1704]
Would be very nice if there is option to build the docs into static HTML files rather than render the jade files on the fly. That's required fairly huge resource on my PC.

**Comment by Foxandxss** [comment]
There is an `www` folder that gets created with the static HTML files. You could use that.

**Comment by Foxandxss** [comment]
Now that I mention it, I am not really sure in how to generate it. Will peek.

**Comment by blackjyn** [comment]
I would like to see npm commands for building "true" local offline docs, that precompiles to static HTML

**Comment by Foxandxss** [comment]
with `gulp check-deploy` a true offline docs are generated. We should separate that process from check-deploy tho.

**Comment by Foxandxss** [comment]
You can use `gulp build-compile`
