### ISSUE TITLE
Style Guide - Use {file}.routes.ts for routes

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular.io#1720]
**Why**
1. Even though we aren't using decorators, we need to build a route tree that rolls up to a central routes file
2. Easy to follow standard naming convention for route configuration files

**app.routes.ts**

``` js
import { RouterConfig } from '@angular/router';

import { FeatureRoutes } from './feature/feature.routes';

const routes: RouterConfig = [
  ...FEATURE_ROUTES
];
```

**feature.routes.ts**

``` js
import { RouterConfig } from '@angular/router';

import { FeatureComponent} from './feature.component';

export const FEATURE_ROUTES: RouterConfig = [
  { path: '/feature', component: FeatureComponent }
];
```

**Comment by delasteve** [comment]
A couple things...

1. `FEATURE_ROUTES` or `FeatureRoutes`? Technically, you are exporting constants, and according to https://angular.io/docs/ts/latest/guide/style-guide.html#!#03-02 you should use SCREAMING_SNAKE_CASE.
2. Where does `provideRouter()` get used? Is it in the `app.routes.ts` or in the `main.ts`'s `bootstrap` function? Assuming the first point, if the first, I would suggest removing the export off `routes` and export `APP_ROUTER_PROVDERS`. If the second, it would make me suggest changing `routes` to `APP_ROUTES`.

**Comment by bampakoa** [comment]
1. According to the styleguide, I think that @delasteve has a point. On the contrary, `FeatureRoutes` is a constant of type `RouteConfig`, seems to be a special purpose constant??. If that is the case, I think it should be better documented as whether it does not follow the SCREAMING_SNAKE_CASE rule.
2. @delasteve I think that is already exported as `APP_ROUTE_PROVIDERS` in the `app.routes.ts` according to the Routing & Navigation section in Developer Guide.

**Comment by delasteve** [comment]
@bampakoa Yeah, I saw that in another PR. My question is whether or not `routes` should be exported in `app.routes.ts`. In the other PR, it's only used for:

```js
export const APP_ROUTER_PROVIDERS = [
  provideRouter(routes),
  Service,
  Guard
];
```

If you do suggest exporting it, it should follow the rules of other route files and have it's name changed to `AppRoutes` or `APP_ROUTES`.

**Comment by bampakoa** [comment]
@delasteve OK, I see your point! I am too wondering If this export needs to be there.

**Comment by Foxandxss** [comment]
Is not needed.

**Comment by brandonroberts** [comment]
Agreed that it is not needed at the top level

**Comment by brandonroberts** [comment]
I also vote for using the screaming snake case for consistency with the style guide rules

**Comment by brandonroberts** [comment]
Closing as the convention has been resolved.
