### ISSUE TITLE
Style Guide - Use {file}.guard.ts for route guards

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular.io#1721]
**Why**
- Guards are essentially services used by the router
- Provides standard naming convention for generation

**auth.guard.ts**

``` js
import { Injectable }             from '@angular/core';
import { CanActivate,
         ActivatedRouteSnapshot,
         RouterStateSnapshot }    from '@angular/router';

@Injectable()
export class AuthGuard implements CanActivate {
  canActivate(
    next:  ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<boolean> | boolean {
    return Observable.of(true);
  }
}
```

**Comment by brandonroberts** [comment]
Guards should be in a shared folder if they are common to the entire application, such as a `CanActivate`  Auth guard. 

Guards should also be in their own feature area if they are specific to a component, such as a `CanDeactivate` guard on a specific route.

**Comment by delasteve** [comment]
Should Guards go under `my-feature/shared` or directly under `my-feature`?

**Comment by brandonroberts** [comment]
What else is in `shared`? I think the same rules applies. If its commonly used across routes, it should be shared.

**Comment by delasteve** [comment]
https://angular.io/docs/ts/latest/guide/style-guide.html#!#04-07

So the component shared contains things specific to that component (models, services, etc) that aren't shared across other components.

That said, I think the answer is it should go in `my-feature/shared`, but I just wanted a confirmation.

**Comment by PascalPrecht** [comment]
TBH I find the `shared` folder *inside* a feature rather confusing as most of the time, there feature === component. Feels a bit over-engineered to me. However, as it is right now, I'd also put it in the shared folder then.

**Comment by brandonroberts** [comment]
Closing as the convention has been resolved.
