### ISSUE TITLE
Style Guide - export APP_ROUTER_PROVIDES from main routes file

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular.io#1722]
**Why**

Can be provided to bootstrap instead of `provideRouter` directly
Includes services, guards that need to be provided at the same level of the router

**app.routes.ts**

``` js
import { provideRouter, RouterConfig }  from '@angular/router';
import { Service } from './service';
import { Guard } from './route.guard';

export const routes: RouterConfig = [
  {
    path: '/route',
    component: RouteComponent
  }
];

export const APP_ROUTER_PROVIDERS = [
  provideRouter(routes),
  Service,
  Guard
];

```

**Comment by Foxandxss** [comment]
I like this style but I don't really like that *Why* (is not really clear for me).

**Comment by brandonroberts** [comment]
Another _Why_ is that is allows you to add services and guards that the router needs without having to continually modify your bootstrap. And it keeps your router dependencies grouped together

**Comment by bampakoa** [comment]
Maybe we could say that it simplifies registration of router dependencies in **main.ts** as stated in the docs:

> Finally, we export this provider in the APP_ROUTER_PROVIDERS array so we can simplify registration of router dependencies later in main.ts. We don't have any other providers to register right now. But we will.

**Comment by brandonroberts** [comment]
Closing as the convention has been resolved.
