### ISSUE TITLE
Style Guide - Break down routes based on levels

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular.io#1724]
Originated from a conversation with @delasteve about how grouping should be handled in the routes file.

**Why**
- Developers don't want to dig through multiple routes files to see where the routes end
- Routes with no children should live in their parent route

``` js
const ROUTES = [
  {
    path: '',
    component: HomeComponent
  },
  ...PARENT_ROUTES
]

const PARENT_ROUTES = [
  {
    path: '/parent',
    component: ParentComponent,
    children: [
      ...CHILD_ROUTES
    ]
  }
]

const CHILD_ROUTES = [
  {
    path: '/child',
    component: ChildComponent,
    children: [
      {
        path: '/grandchild',
        component: GrandChildComponent
      }
    ]        
  }
]
```

**Comment by delasteve** [comment]
👍 

There are two extremes, one where all routes are defined at the top level, and the other where they are using the spread operator for child routes. I think this is a good compromise. @brandonroberts nails it with the first bullet point as to why this compromise works.

**Comment by brandonroberts** [comment]
Closing as the convention has been resolved.
