### ISSUE TITLE
Angular 2 Tutorial "Tour of Heros" currently doesn't work

### ISSUE THREAD

**Issue by abductedMind** [angular/angular.io#1725]
This is a bug with content in documentation. Angular 2 Tutorial "Tour of Heros" currently doesn't work: https://angular.io/resources/live-examples/toh-6/ts/plnkr.html.

This is linked to from https://angular.io/docs/ts/latest/tutorial

The issue has to with how content is getting loaded on the page because there are 404 errors.

**Comment by AndresRicardoTorres** [comment]
This is related to #1728, '@angular/router-deprecated' freezes on RC 2, "system.config.js" in Plunker must point to the right version

**Comment by rjpalermo1** [comment]
I'm submitting a ... (check one with "x")

[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
# **Angular2 Tour of Heroes tutorial broken**

The PLUNKR example (and my follow-along code) is working fine on the SERVICES step https://angular.io/docs/ts/latest/tutorial/toh-pt4.html

HOWEVER, when I add the Appendix: Take it slow suggestion the app breaks down.

getHeroesSlowly() {
  return new Promise<Hero[]>(resolve =>
    setTimeout(() => resolve(HEROES), 2000) // 2 seconds
  );
}
In the next step in the TUTORIAL for ROUTING here: https://angular.io/docs/ts/latest/tutorial/toh-pt5.html 
the PLUNKR reflects the issues and will not load correctly.

**Comment by SiXoS** [comment]
To fix this issue: Open the file systemjs.config.js and change ngVer from "@2.0.0-rc.3" to "@2.0.0-rc.2".

**Comment by Foxandxss** [comment]
Proper solution will land possibly today.

**Comment by juniorsatanas** [comment]
private heroesUrl = 'http://localhost:3000/api/heroes'; 

  Dont up ?
