### ISSUE TITLE
Quickstart points to non-existant version of router-deprecated

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular.io#1728]
`    "@angular/router-deprecated":  "2.0.0-rc.3",` on https://angular.io/docs/ts/latest/quickstart.html

References to the deprecated router should be removed, as this is not a dependency developers should need.

**Comment by Foxandxss** [comment]
That is definitely wrong. We can't remove it yet until we sweep all docs.

**Comment by StephenFluin** [comment]
Can we fix the link then, I don't believe there is a `router-deprecated@2.0.0-rc.3`.

**Comment by Foxandxss** [comment]
Yes. There is a pr for that. We can merge that

**Comment by Foxandxss** [comment]
Closing it since there is a PR for it.
