### ISSUE TITLE
Making the examples to be style-guide compliant.

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular.io#1733]
So there is a big big PR I am cooking and there is a bit of confusion and misunderstanding so let's address it here and discuss about it.

As today, our examples lies as following:

![](http://puu.sh/pCiFM/74f439c4a6.png)

As you can see, we have an `app/` folder with everything in it. The style-guide [recommends](https://angular.io/docs/ts/latest/guide/style-guide.html#!#04-06) a folder structure with a `src/` folder that contains the `main.ts` and `index.html`:

![](http://puu.sh/pCiTP/7896b75825.png)

So having the CLI folder structure in mind, @wardbell and I agreed on creating the following structure:

![](http://puu.sh/pCj64/8601b19711.png)

Smells like the CLI but it is not CLI, is the same thing we had before but reorganized to be style-guide compliant.

I raised an issue yesterday, because I discovered that the CLI was going to change a bit. I was worried that this new structure wouldn't match the CLI anymore so we would need to change yet again.

I see this as a first step if we want to make the examples to be CLI applications in the future.

So we can either put this on hold if you have a better idea for this (my PR is half baked and still needs a lot of work) or I can continue doing it.

/cc @wardbell @naomiblack @filipesilva @robwormald @StephenFluin @johnpapa

**Comment by filipesilva** [comment]
The examples you've shown make a lot of sense and the dir layout proposed doesn't comply to the CLI per se, but more to the style guide. I'm all for it then.

There's still the question of where assets go: images, fonts, global css/sass/less, pdfs, you name it. Those need a place, and for the lack of a better suggestion I would say `src/assets`.
