### ISSUE TITLE
[Router] Missing parts of documentation

### ISSUE THREAD

**Issue by ocombe** [angular/angular.io#1736]
I've started using the new new new router (v3 alpha) and I have noticed a few things missing from the documentation. @Foxandxss asked me to open an issue here to list them.
I will update this issue whenever I find new stuff missing.
Current list:
- [ ] Directive `queryParams` to add query params to a `routerLink`: `<a routerLink="foo" [queryParams]="params">linky</a>`. Even if you know its name, it's nowhere to be found in the doc
- [ ] How to access url parameters from a parent component. Let's say that you have a route like: `/hero/:id/edit`, and when you're in the `/edit` view & you want the hero id, you need to do: `this.router.routerState.parent(this.route).params`
- [ ] How to lazy load components with the router (using the SystemJSComponentResolver, or a custom one like I did to make it work with Webpack)
- [ ] How to dynamically add new routes to the config https://github.com/angular/angular/issues/9527
- [ ] How to define a default route when there is no match, for example a 404 page, and how to redirect all to one route (if you don't want a 404 but prefer to redirect to a default route), currently it seems that you have to do:

``` ts
{
    path: '**',
    redirectTo: ''
}
```

**Comment by valorkin** [comment]
Thanks, this is nice!

**Comment by wardbell** [comment]
See also [this stackoverflow issue](http://stackoverflow.com/questions/38242584/clear-all-queryparams-with-new-router-v3-angular2/38415980) which reminds us that we have some documenting to do.

**Comment by Foxandxss** [comment]
What's the status of this @brandonroberts ?

**Comment by brandonroberts** [comment]
- Query Params are covered in the dev guide
- Route tree information will be in the advanced chapter
- Lazy loading is covered in the dev guide
- Dynamically adding new routes could go in the upcoming advanced chapter
- Wildcard routes are mentioned in the dev guide
