### ISSUE TITLE
Angular 2 Tutorial "Tour of Heros" get stuck in toh-pt6(http)

### ISSUE THREAD

**Issue by gogobook** [angular/angular.io#1738]
Angular 2 Tutorial "Tour of Heros" get stuck in toh-pt6(http).

I got an error, "EXCEPTION: TypeError: dep is null".

I think it maybe cause by 'angular2-in-memory-web-api', but I don't know.

Could change 'angular2-in-memory-web-api' to a docker image as a backend server? I think it will make angular more easy to learn.

**Comment by Foxandxss** [comment]
We would need more information than that and if possible, a reproduction in plunker.

**Comment by gogobook** [comment]
I found what's wrong. I missed '@Injectable()' in hero.service.ts.
