### ISSUE TITLE
RC3 Tutorial does not compile

### ISSUE THREAD

**Issue by matejkramny** [angular/angular.io#1744]
`npm install` fails with

```
npm ERR! peerinvalid The package @angular/core@2.0.0-rc.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/common@2.0.0-rc.3 wants @angular/core@2.0.0-rc.3
npm ERR! peerinvalid Peer @angular/compiler@2.0.0-rc.3 wants @angular/core@2.0.0-rc.3
npm ERR! peerinvalid Peer @angular/forms@0.1.1 wants @angular/core@2.0.0-rc.3
npm ERR! peerinvalid Peer @angular/http@2.0.0-rc.3 wants @angular/core@2.0.0-rc.3
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.3 wants @angular/core@2.0.0-rc.3
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.3 wants @angular/core@2.0.0-rc.3
npm ERR! peerinvalid Peer @angular/router@3.0.0-alpha.7 wants @angular/core@^2.0.0-rc.2
npm ERR! peerinvalid Peer @angular/router-deprecated@2.0.0-rc.2 wants @angular/core@^2.0.0-rc
npm ERR! peerinvalid Peer @angular/upgrade@2.0.0-rc.3 wants @angular/core@2.0.0-rc.3
npm ERR! peerinvalid Peer angular2-in-memory-web-api@0.0.12 wants @angular/core@2.0.0-rc.2

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/m/p/scootfleet/frontend/npm-debug.log
```

**Comment by Foxandxss** [comment]
Whats your node and npm?

**Comment by matejkramny** [comment]
```
$ npm --version
2.14.4

$ node -v
v4.1.1
```

**Comment by matejkramny** [comment]
I copied from the 5min tutorial, but it seems like the `angular/in-memory-web-api` package needs `angular/core` rc2.

**Comment by Foxandxss** [comment]
On the one hand, new angular packages need node 5.x and npm 3.x. We recommend Node 5.11.1 and latest npm.

On the other hand the `in-memory-web-api` will be updated in the coming days (you can still work with the project, that is a minor warning).

**Comment by Foxandxss** [comment]
Seems like latest npm works too with node 4.x :)

**Comment by matejkramny** [comment]
Ok will upgrade node.. srsly sometimes, node/npm is the biggest PITA.

**Comment by nadavten** [comment]
node v6.2.2
npm 3.9.5

still having the problem

**Comment by Foxandxss** [comment]
What error gives you?

**Comment by matejkramny** [comment]
I upgraded node and issue got solved.

**Comment by Paolac** [comment]
@matejkramny did you fix the angular/in-memory-web-api package needs angular/core rc2 by updating the node version ?

**Comment by jmdelatorreloza** [comment]
@Paolac i did and doesn't work

**Comment by Foxandxss** [comment]
That will be fixed soon

**Comment by Paolac** [comment]
Thanks :) @Foxandxss

**Comment by nadavten** [comment]
@Foxandxss soon like RC 4 ?

**Comment by warner-pinz** [comment]
What should be the versions to use for npm and node?

**Comment by Foxandxss** [comment]
latest NPM (3.x) and node 4.x+

**Comment by cooervo** [comment]
Hey @Foxandxss npm version 3.10.5 and I installed node v 5.11.1 as suggested by you before I also even tried with 5.12 but when I run `meteor npm install --save angular2-meteor` I get the error:
`The package @angular/common2.0.0-rc.4 does not satisfy its siblings peerDependencies requirements!`

**Comment by Foxandxss** [comment]
That seems to be a problem of that concrete library. I suggest that you open a issue there. I believe that they have their peerDependencies wrong.
