### ISSUE TITLE
Barrel glossary code example issue

### ISSUE THREAD

**Issue by cknightdevelopment** [angular/angular.io#1746]
There seems to be an issue with one of the code examples in the glossary for [barrel](https://angular.io/docs/ts/latest/glossary.html#!#barrel). The code example after the text "That's why we can write this:" has this in the code example area:

```
BAD FILENAME: ../../_fragments/../docs/_fragments/quickstart/ts/app/app.component-import.ts.md
Current path: docs,ts,latest,glossary PathToDocs: ../../
```

Thanks, and let me know if more information is needed

**Comment by Foxandxss** [comment]
We have an issue with double glossary as seen #1123.

So we will continue there.

Thanks.
