### ISSUE TITLE
Remove Reflect Metadata polyfill for core-js

### ISSUE THREAD

**Issue by splintercode** [angular/angular.io#1748]
It looks like es7 reflect metadata is now in core-js. The CLI & Material are removing the separate package in favor of using core-js. The live examples and demos will need to be updated as well.

https://github.com/angular/angular-cli/pull/853
https://github.com/angular/material2/pull/505

**Comment by Foxandxss** [comment]
We are aware of that, but we haven't made a decision yet. 

I'll put it on my list of things to discuss. 

/cc @filipe.silva

**Comment by filipesilva** [comment]
Let's talk about it early next week.

**Comment by kylecordes** [comment]
core-js appears to do the whole job, and work very well. The advantage of fewer dependencies seems transparently obvious. So I will be very interested to see (and I hope a rationale is published) if the decision is made to keep the extra reflect-metadata.

**Comment by schmuli** [comment]
What about updating angular/core too?

https://github.com/angular/angular/blob/master/modules/%40angular/core/src/util/decorators.ts#L266

**Comment by filipesilva** [comment]
@schmuli `core-js` *includes* `reflect-metadata`, and more. Angular itself just requires that `reflect-metadata` is present.

**Comment by schmuli** [comment]
My confusion was because there is the `reflect-metadata` NPM package, so I thought it was referring to the package, not the feature.
