### ISSUE TITLE
error TS2307: Cannot find external module 'angular2/angular2'

### ISSUE THREAD

**Issue by languorous001** [angular/angular.io#175]
I try learn Angular 2 Quickstart. I use 'tsc --watch -m commonjs -t es5 --emitDecoratorMetadata app.ts'.

Then error TS2307: Cannot find external module 'angular2/angular2'.

How I can fix it. Thank you.

**Comment by magiccrafter** [comment]
Check here for the answer: https://github.com/angular/angular/issues/3188

**Comment by wardbell** [comment]
Obsolete issue.
