### ISSUE TITLE
Update Visual Studio 2015 QuickStart docs to reflect ASP.NET Core

### ISSUE THREAD

**Issue by technoloG** [angular/angular.io#1752]
Regarding the Visual Studio 2015 QuickStart documentation:
https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html

The current QuickStart structure is geared toward ASP.NET 4.x projects.

With the release of ASP.NET Core all static files are hosted in `wwwroot`, however packages obtained via NPM are in a sibling  `node_modules`, which cannot be accessed from files in `wwwroot`.

Ideally, the necessary files could be obtained via Bower, which creates a copy of files in `wwwroot/lib`. At the minimum, there should be additional capabilities to copy the files obtained from NPM to  wwwroot/lib , or it should be clearly stated in the documentation.

To be more specific: as of Step 3 in the Visual Studio 2015 QuickStart documentation, it is suggested to open a new ASP.NET project in Visual Studio. While suggested workflow works for ASP.NET 4.x projects, things have changed in ASP.NET 5 - better known as ASP.NET Core - projects.

As of recent updates to Visual Studio 2015 and the introduction of ASP.NET Core, the project structure has changed slightly, including explicitly having `wwwroot` in the root of the project - where static files are intended to reside and be run or in the browser. As a result, the steps provided in the QuickStart for Visual Studio 2015 don't necessarily apply.

**Comment by Foxandxss** [comment]
We have something going on #2850
