### ISSUE TITLE
Angular loads only modules that are in src/app folder

### ISSUE THREAD

**Issue by evgdim** [angular/angular.io#1753]
I have created an angular2 project with angular-cli(version 1.0.0-beta.8, angular version is 2.0.0-rc.3) 
But the components are loaded only if they are in src\app\ folder. If I move the module folder in a sub folder angular cant load the js file for that module.
See my SO question for more details:   http://stackoverflow.com/questions/38041493/angular-2-load-components-only-from-root-app-folder

**Comment by Foxandxss** [comment]
This repository is only for the docs. Please repost at the [angular-cli](https://github.com/angular/angular-cli) repository.
