### ISSUE TITLE
Style Guide (06-03) - Allow use of host property in @Component if intended values are static strings

### ISSUE THREAD

**Issue by eppsilon** [angular/angular.io#1763]
I think it should be acceptable to use the host property in component/directive decorators as long as the keys are being set to `string` values. For example, this code:

``` ts
@Component({
  selector: 'my-component',
  host: {
    class: 'some-base-class some-modifier-class other-modifier-class'
  }
})
class MyComponent {}
```

seems more readable than:

``` ts
@Component({
  selector: 'my-component'
})
class MyComponent {
  @HostBinding('class.some-base-class')
  someBaseClass = true;

  @HostBinding('class.some-modifier-class')
  someModifierClass = true;

  @HostBinding('class.other-modifier-class')
  otherModifierClass = true;
}
```

Related: mgechev/codelyzer#61

**Comment by zoechi** [comment]
Shouldn't that be

```ts
@Component({
  selector: 'my-component',
  host: {
    '[class]': "'some-base-class some-modifier-class other-modifier-class'"
  }
})
class MyComponent {}
```

and the equivalent would be

```ts
@Component({
  selector: 'my-component'
})
class MyComponent {
  @HostBinding('class')
  someBaseClass = 'some-base-class some-modifier-class other-modifier-class';
}
```

**Comment by eppsilon** [comment]
My first example (with `host: { class: '...' }`) works for me. However, you're right that your examples produce the same compiled template and mine don't.

Compiled template from your examples:

```js
var currVal_0 = 'some-base-class some-modifier-class other-modifier-class';
if (jit_checkBinding9(throwOnChange,self._expr_0,currVal_0)) {
  self.renderer.setBindingDebugInfo(self._el_0,'ng-reflect-class-name',((currVal_0 == null)? null: currVal_0.toString()));
  self.renderer.setElementProperty(self._el_0,'className',currVal_0);
  self._expr_0 = currVal_0;
}
```

My second example's template looks sort of like yours (only showing one property here):

```js
var currVal_0 = self._HomeComponent_0_4.someBaseClass;
if (jit_checkBinding9(throwOnChange,self._expr_0,currVal_0)) {
  self.renderer.setElementClass(self._el_0,'some-base-class',currVal_0);
  self._expr_0 = currVal_0;
}
```

But my first example produces a template more like what I intended:

```js
self.renderer.setElementAttribute(self._el_0,'class','some-base-class some-modifier-class other-modifier-class');
```

I think setting `host` should be allowed if you want the value to be static.

**Comment by valorkin** [comment]
+1 allowing static bindings is a must have
Having things like this https://github.com/valor-software/ng2-bootstrap/blob/development/components/accordion/accordion.component.ts#L13-L14
Seems to be an anti pattern

**Comment by devoto13** [comment]
I understand that it's not the most important issue, but it's pretty annoying to fight with it every time we want to set static attribute on the component's host element. `codelyzer` implements it according to style guide and we need to resolve it in Style Guide before changing behaviour in `codelyzer` (see mgechev/codelyzer#61). 

It sounds absolutely logical and clear choice to use `host` property to perform one-time attribute/property initialization with a static value and `@HostBinding()`/`@HostProperty()` to handle dynamic properties/events.

@wardbell can you review this suggestion? I can prepare PR if we have a green light on this change.

**Comment by wardbell** [comment]
I've been lobbying to remove this rule. Haven't got it done yet. 

BUT ... you can stop Codelyzer from enforcing that rule. Codelyzer relies on tslint so do what you would do to configure/control tslint behavior.

### 1. Everywhere in your app

Open `tslint.json` and set ` "use-host-property-decorator": false,`

### 2. Disable in one file

Above the offending line add: `/* tslint:disable:use-host-property-decorator */`

**Comment by devoto13** [comment]
Thanks for your reply! Happy you're working on this. 

I know how to disable the check, but the problem is that it will also disable it for cases where it's more appropriate to use `@HostBinding()`/`@HostListener()`. In such cases rule is actually very useful (much easier to refactor code, since you don't have method/property name as a string). That's why I'm more up to relaxing the rule to allow using `host` for static values and not to remove it completely.

**Comment by wardbell** [comment]
It turns out that we have followed advice (1) in our documentation development. You can keep that rule for yourself if you find it valuable and pursue advice (2) on a case-by-case basis.  I don't see us changing the rule implementation itself.

**Comment by chris-malloy-mri** [comment]
I think a similar issues is binding to an object field. I.e:
```TypeScript
  host: {
    '[style.left.px]':   'model.rect.left',
}
```

In this case I don't see how you could use a @HostBinding because the field is inside the `model` object. Let me know if you want me to open a separate issue.

**Comment by devoto13** [comment]
It can be done with getter:

    @HostBinding('style.left.px')
    get left() {
        return this.model.rect.left;
    }

**Comment by chris-malloy-mri** [comment]
Thanks!
