### ISSUE TITLE
API Docs for TestComponentBuilder are gone

### ISSUE THREAD

**Issue by gionkunz** [angular/angular.io#1792]
Hi guys

Anyone knows why the API docs for `TestComponentBuilder` are no longer on angular.io? I'm referencing this site from my book: https://angular.io/docs/ts/latest/api/testing/TestComponentBuilder-class.html

The inline docs seem to be fine: https://github.com/angular/angular/blob/master/modules/@angular/core/testing/test_component_builder.ts

Cheers
Gion

**Comment by Foxandxss** [comment]
It changed to another place in RC4 and our generated API is not showing it yet, if you need to reference a link, you will need this one:

https://angular.io/docs/ts/latest/api/core/testing/TestComponentBuilder-class.html

Is not working yet, but that ill be.

**Comment by gionkunz** [comment]
Thanks for the Link! Yeah that seems to work. However, searching for `TestComponentBuilder` does not seem to work though. I'm closing the issue, thanks for your help!

**Comment by Foxandxss** [comment]
Everything will be fixed when RC4 gets out. That originated this URL move.
