### ISSUE TITLE
Documentation Mistake:  path shouldn't start with '/' for RouterConfig

### ISSUE THREAD

**Issue by gaokun** [angular/angular.io#1798]
Hey Guys,
I was following the Tutorial of ng2
After define RouterConfig as tutorial, I got error: **path shouldn't start with '/'**. Got fixed after remove '/'. 

But the documentation still be there, need to be updated.

Thanks
Ken

Here is the link: https://angular.io/docs/ts/latest/tutorial/toh-pt5.html

Here is screenshot:
![image](https://cloud.githubusercontent.com/assets/7044628/16495182/d91528c6-3f1e-11e6-90c8-711f5689b9a8.png)

**Comment by Foxandxss** [comment]
To be fixed at #1783
