### ISSUE TITLE
Translate website?

### ISSUE THREAD

**Issue by jhonmike** [angular/angular.io#180]
Português-Brasil/Portuguese-Brazil

**Comment by saharj** [comment]
I can help with this if guid me through the process.

**Comment by jhonmike** [comment]
I think that the process does not yet exist, but also want to help.

**Comment by brunobelarmino** [comment]
I could help to translate to portuguese. :smile:

**Comment by laco0416** [comment]
:+1: 
I would like to translate to Japanese.
there're not any plan?

**Comment by seekerlee** [comment]
I would like to translate to Chinese. If there's plan in the future.

**Comment by wardbell** [comment]
Keeping this open for when we are ready. Nice to know who is volunteering.

**Comment by xuan9230** [comment]
I can also help translate to Chinese:-) Ready to start any time

**Comment by lv7777** [comment]
I want translated page because i'm novice about anglar2.

**Comment by onyoon7** [comment]
I have a plan to translate the angular.io to Korean.

**Comment by jhonmike** [comment]
pt-br #1876

**Comment by Foxandxss** [comment]
Translation is under way, so I am closing this.
