### ISSUE TITLE
universal.angular.io does not appear on iOS devices

### ISSUE THREAD

**Issue by ClickSimply** [angular/angular.io#1802]
When I go to universal.angular.io on my iPhone and iPad the screen is completely white, nothing shows up.

I have an iPhone SE with iOS 9.3.2 and an iPad 2 with iOS 9.3.1. 

I hooked up the phone to my MacBook and opened the inspector in Safari (This is inspecting the mobile safari page through the USB cable).  The issue seems to be the container element just under the body of class ".mdl-layout", it has "display:flex" in it's style.  When this is disabled or changed to "display:block" in the inspector the page suddenly appears, although not styled correctly.

**Comment by Foxandxss** [comment]
This repo is for `angular.io` and not any of the subdomains. You are better opening an issue at the universal repo.
