### ISSUE TITLE
EXCEPTION: No value accessor for '' in

### ISSUE THREAD

**Issue by ridaKourchal** [angular/angular.io#1806]
EXCEPTION: No value accessor for '' in [inventory.PlannedStart in AddComponent@16:61]

@Component({
    selector: 'add',
    template: require('./add.html'),
    directives: [LiveTile, DataTableDirectives],
    inputs: ["inventory","list_items"],
    pipes: [dateFormatPipe, DatePipe, FilterArrayPipeItem],

})

export class AddComponent  {
    @Input()
    inventory = { PlannedStart: new Date() }
    @Input()
    list_items: any = []
    PlannedStart: Date;
    constructor() {
        this.inventory = { PlannedStart: new Date() }
       
        this.PlannedStart = new Date();
    }
}
 
and in add.html
....datetime id="datetimePlannedStart"  [(ngModel)]="inventory.PlannedStart"></datetime>

**Comment by Foxandxss** [comment]
Sorry, this is not a support issue tracker.

Is better to use stackoverflow for this kind of questions.

Thanks!
