### ISSUE TITLE
Step by Step Guide: User Input : Minor Issue

### ISSUE THREAD

**Issue by flobrflo** [angular/angular.io#182]
Hi,
https://angular.io/docs/js/latest/guide/user-input.html#section-final-code

On Final Code part (TypeScript), there is a syntax error on directives : 
directives: \[NgFor, NIf\] ( instead of \[NgFor, NgIf\] )

Also NgIf can be remove cause it not used.

**Comment by khyamay** [comment]
btw there is already pull request for this https://github.com/angular/angular.io/pull/170

**Comment by flobrflo** [comment]
Oh yep.
sorry for dupplicate
