### ISSUE TITLE
TS router and router-deprecated issues

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#1840]
There are two broken links in the `router` and `router-deprecated` guides:
```
http://localhost:3000/docs/ts/latest/guide/router.html
  [316, HTTP_404] http://localhost:3000/docs/ts/latest/api/router/index/Route-class.html
http://localhost:3000/docs/ts/latest/guide/router-deprecated.html
  [1986, HTTP_404] http://localhost:3000/docs/ts/latest/api/router-deprecated/index/APP_BASE_HREF-let.html
```

Comments about these:
- The `router` guide contains a reference to the `router-deprecated/Route` class (such a back reference doesn't seem right, but I haven't investigated further).
- `APP_BASE_HREF` doesn't seem to exist anymore.

/cc @Foxandxss @wardbell @brandonroberts

**Comment by Foxandxss** [comment]
I see.

Let me take a peek.
