### ISSUE TITLE
Error TS6064 while executing tsc --watch as per QuickStart.html

### ISSUE THREAD

**Issue by harshapat** [angular/angular.io#185]
Error while executing the below command, as command suggests "experimentalDecorators" option to be included. 
tsc --watch -m commonjs -t es5 --emitDecoratorMetadata app.ts
error TS6064: Option 'experimentalDecorators' must also be specified when option 'emitDecoratorMetadata' is specified.
message TS6042: Compilation complete. Watching for file changes.
  
Executed without an error.
tsc --watch -m commonjs -t es5 --emitDecoratorMetadata --experimentalDecorators app.ts
message TS6042: Compilation complete. Watching for file changes.

**Comment by neeklamy** [comment]
Just ran across the same issue here.

```
OS X 10.10.5
Node 4.1.0
NPM 2.14.4
TypeScript 1.5.0 – and tried 1.6.2
TSD 0.6.0 – and tried 0.6.4
```

Same fix too, add `--experimentalDecorators`.

**Comment by wardbell** [comment]
Obsolete issue.
