### ISSUE TITLE
Add ng-bootstrap to UI Component resources list

### ISSUE THREAD

**Issue by wesleycho** [angular/angular.io#1855]
The ng-bootstrap team just released an alpha 0 version of [ng-bootstrap](https://ng-bootstrap.github.io) today - we would like the project added to the UI Component section of the resources list [here](https://angular.io/resources/).

Also I notice the list has no particular ordering - perhaps this list should be in alphabetical order?

Name: ng-bootstrap
url: https://ng-bootstrap.github.io
description: Library of UI components built on top of Bootstrap 4 by the UI Bootstrap team

**Comment by Foxandxss** [comment]
I am part of that team too (along with @pkozlowski-opensource) and yeah, we would like an entry there. I also agree on the alphabetical order, not giving anyone any "promoted position".

/cc @naomiblack @ericjim

**Comment by ericjim** [comment]
I believe @StephenFluin has access to the database.

**Comment by pkozlowski-opensource** [comment]
This is done now, thnx @StephenFluin ! https://angular.io/resources/

@wesleycho I think this can be closed now.

**Comment by wesleycho** [comment]
I still think that list should be alphabetized, but I guess the main part of this issue is done.

**Comment by ericjim** [comment]
I'll look into alphabetizing the content.
