### ISSUE TITLE
Style 05-17 exmaple issue

### ISSUE THREAD

**Issue by ashishdoneriya** [angular/angular.io#1859]
In style guide Style 05-17 https://angular.io/docs/ts/latest/guide/style-guide.html#05-17

In the examples there is no difference between "AVOID example" and "DO examples" except the "DO example" has one more method.

**Comment by Foxandxss** [comment]
The important part is more the  html than the typescript. When we say "don't put logic", we mean:

```html
Average power: {{totalPowers / heroes.length}}
```

That is logic, you are doing some computation on the html.

The DO example removes that computation from there and moves it to the class.

**Comment by ashishdoneriya** [comment]
Is this mean that we should use {{ }} for only displaying values and NOT for any type of calculation, even a simple division or multiplication

**Comment by Foxandxss** [comment]
That is our recommendation.
