### ISSUE TITLE
RC4 Router children property issue

### ISSUE THREAD

**Issue by InoMind** [angular/angular.io#1863]
**When I have 'children' property in my 'Routes' component, the router is not recognized/called.
I am getting an error like below**

![rc2router](https://cloud.githubusercontent.com/assets/5118662/16723577/6bb16326-476b-11e6-9b07-9d220ba9d2ca.png)

**The Router code is like below**
_export const TenantRoutes = [
  {
    path: 'tenant',
    component: TenantsComponent,
    index: true,
    children: [
      { path: 'register', component: TenantRegisterComponent },
      { path: 'login', component: TenantLoginComponent },
      { path: 'forgotPwd', component: TenantForgetPasswordComponent }
    ]
  },
  ...PanelistsRoutes,
  ...UserstsRoutes
];_

Does anyone know the reason for the above issue?

**Comment by Foxandxss** [comment]
Hello!

This repository is only for the documentation. If you have any question regarding Angular 2 usage, please go to StackOverflow and use the `angular2` tag.

Thank you!
