### ISSUE TITLE
Server-communication: ClassMethodRef -> FatArrow Function

### ISSUE THREAD

**Issue by cebor** [angular/angular.io#1866]
In the server-communication chapter the `app/toh/hero.service.ts` uses references to class methods for the rxjs callbacks.
I think this is not the best approach cause you loosing the `this`-context of the service in these methods.

I know that example does not require a `this`, but users do not need it rare, so you might as well use a fatArrowFunction.

https://angular.io/docs/ts/latest/guide/server-communication.html

Code: https://github.com/angular/angular.io/blob/master/public/docs/_examples/server-communication/ts/app/toh/hero.service.ts#L42-43

Think binding a fatArrowFunction to a class property should also work.

``` typescript
// change this
private extractData(res: Response) {
  // "this" does not work here
  let body = res.json();
  return body.data || { };
}

// to
private extractData = (res: Response) => {
  // "this" works here
  let body = res.json();
  return body.data || { };
};
```

**Comment by bampakoa** [comment]
Alternatively we could change the **addHero** method as:

`.map( (res:Response) => { this.extractData(res); })`

Which do you think is best approach?
