### ISSUE TITLE
WEBPACK: AN INTRODUCTION Tutorial Requires Updated Package.json

### ISSUE THREAD

**Issue by marlowp** [angular/angular.io#1869]
I've run through the WebPack tutorial featured here https://angular.io/docs/ts/latest/guide/webpack.html and it looks like by default it does not build correctly due to the angular2-template-loader dependency missing from the package.json file.

I've fixed the issue locally by simply adding the following to the dependencies section of the package.json file:

"angular2-template-loader": "^0.4.0"

**Comment by bampakoa** [comment]
@marlowp It has been already fixed with PR #1864.
