### ISSUE TITLE
Step by Step guide - Not so through

### ISSUE THREAD

**Issue by VikramTiwari** [angular/angular.io#187]
https://angular.io/docs/js/latest/guide/displaying-data.html

On this page, user creates a new file to work upon. But there is no mention of the changes that user needs to do in order to build his app.

Issues:
1. The ```tsc``` server that is running in background on ```main.js``` needs to run on ```show-properties.ts```
2. Even while running server on ```show-properties.ts``` and running a node server on the app index, if the user tries to run the app, the page at ```/``` is still index. Hence can't see the changes.
3. On changing the url to ```/show-properties.html``` a blank page is served without any data cause if someone is following the tutorials by point, they didn't made the html structure for the app in show-properties.html nor imported the correct file. Errors shown in the console though.
4. Even after making the structure and importing the correct file using ```System.import``` the app fails to display any data.

Stuck!

**Comment by fedy2** [comment]
I think this problems can be reported in #107

**Comment by wardbell** [comment]
Obsolete issue.
