### ISSUE TITLE
Typo on ProtoViewRef documentation

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular.io#188]
I don't know if  this should go on angular's github or here (since it is a typo in documentation). 

Anyway

`A ProtoView is a foctary for creating Views.`

it should say

`A ProtoView is a factory for creating Views.`

In the same page you can see this

`(See AppViewManager and AppViewManager).`, both `AppViewManager` are links to different methods of the class, but it may be confusing when reading it. I think it should say something like `(See AppViewManager#createViewInContainer and AppViewManager#createRootHostView).`

See https://angular.io/docs/js/latest/api/core/ProtoViewRef-class.html

**Comment by PascalPrecht** [comment]
@ericmartinezr I think this needs to be fixed in the API docs, which are written in the source code itself.

**Comment by ericmartinezr** [comment]
Thanks @PascalPrecht. I'll try during the day pulling a request myself.

**Comment by PascalPrecht** [comment]
@ericmartinezr let me know if you need any help with this.

**Comment by ericmartinezr** [comment]
@PascalPrecht It would be really nice if you can point me out where and how to start. I'm really new to github. I've been reading https://github.com/angular/angular/blob/master/CONTRIBUTING.md#submit but it's not quite what I need.

**Comment by PascalPrecht** [comment]
@ericmartinezr you need to edit this file right here at the marked line: https://github.com/angular/angular/blob/master/modules/angular2/src/core/compiler/view_ref.ts#L99

This can be done entirely through the GitHub interface :)
