### ISSUE TITLE
Documentation proposal: It should be more confined and targeted

### ISSUE THREAD

**Issue by SetTrend** [angular/angular.io#1883]
Trying to learn how to use Angular 2 I feel that the current documentation is far too verbose and random.

I personally don't understand what the documentation is trying to convery.

Topic | Perceived Purpose
--- | ---
QuickStart | Some explanation on how to work with _node_ and _npm_, but no particular information on _Angular 2_, its prerequisites and why it requires any prerequisites at all.
Tutorial | Loads of kindergarten waffle. Too much node. No table or bullet list of what's required to get a simple Angular 2 setup up and running.<br/>Content doesn't focus on header topic (see Master/Detail). Menu on the left should be more fine grained. Trying to retaliate what you have read, you cannot find any of the information read in Master/Detail (e.g. styling) by browsing the menu.
Basics | Well made. Yet, it's just dealing with the code, not the setup. No table or bullet list of what's required to get a simple Angular 2 setup up and running.
Developer Guide | Visual Studio 2015 chapter: Why should some experienced programmer want to "copy the QuickStart files we downloaded from github into the folder containing the .csproj file"? Why isn't there a basic "add the _Angular2_ package to _dependencies_ in _package.json_ and set your module loader to load "Angular2.js"?
Cookbook	 | Why isn't it just called a _FAQ_? Who'd be looking for a "cookbook" when it comes to programming?
API Reference | Many items show "not yet implemented" - so why are they in the documentation anyway?

I would very much prefer if the Quickstart was a simple "add the _Angular2_ package to _DevDependencies_ in _package.json_ and set your module loader to load "Angular2.js". No more prerequisites, no other factors described. That should be enough in the Quickstart for getting the _**quick**_--start to work.

I suggest to keep all the module design (and module philosophic chit-chat) out of the Quickstart chapter. My suggestion: Put everything into a single file - period; no futile _import_ or _export_ statements. Strip everything from the text/sample not absolutely necessary to get the sample running. - Quickstart is not about philosophy - Quickstart is about the most simple and rudimentary way of getting _Angular 2_ to work.

Don't diverge readers from your text by proudly presenting your live samples to them. The reader is faithful in that the description in the docs is profound enough so that (s)he can create his/her own live examples from the description in the docs alone. If that's not the case, then the docs are just not good.

The API Reference should only list items having a documentation avaliable. Anything else is just confusing and irritating. If you don't want to omit these orphans, dim 'em, so the user doesn't get frustrated by not getting any results from investigating throughout the API reference.

**Comment by naomiblack** [comment]
Hi -- thanks for your feedback. We're working on a project to edit and further improve our docs over the summer, in particular editing for length.
