### ISSUE TITLE
Missing "Loved by Millions" by icons on India region

### ISSUE THREAD

**Issue by ultrasonicsoft** [angular/angular.io#1884]
Hi There,

On home page (https://angular.io/), the section "Loved by Millions" shows Angular icons from various countries but there is not a single icon on "India".

I am sure there are lots of people from India who are actively following and involved in Angular 2.0 code base.

It will be great to show at least one Angular icon on India (at least for me :) ).

Thanks!

Best regards,
Balram

**Comment by Foxandxss** [comment]
Hello,

It is not an accurate map to show where Angular is used. If it were accurate, we would need to paint the whole world in red :)

I am from Spain, I work for this project and we don't have an icon either.

**Comment by micronyks** [comment]
@ultrasonicsoft: I agree!!

 There are many **Indian followers** and I'm one of them. Its a good idea/suggestion to have an icon over **India** in map. I don't know what is the main purpose of showing  icons over few regions. 'Angular Team' must have some purpose behind it I think.
But, yes if it is possible, we'd like to see an icon over **India**. 
Let's see if **Angular Team** comes up with it or not.

@Foxandxss: true. If it were accurate, we would need to paint the whole world in red :).

**Comment by amitafr** [comment]
@ultrasonicsoft @micronyks @Foxandxss 
The image was not created as an accurate representation but no worries, I will update the image with an icon on India and Spain :)

**Comment by micronyks** [comment]
@amitafr : great to know this update from your end. Thanks.

**Comment by micronyks** [comment]
@amitafr: I still can't see an icon over India.

**Comment by amitafr** [comment]
@micronyks Did you check the PR?
https://github.com/angular/angular.io/pull/1951

**Comment by micronyks** [comment]
@amitafr : Opps! I didn't see it. Yes, It is there. Thanks !

**Comment by wardbell** [comment]
Closed by #1951
