### ISSUE TITLE
Quickstart: Why are zone.js/reflect.js loaded traditionally?

### ISSUE THREAD

**Issue by SetTrend** [angular/angular.io#1886]
@ https://angular.io/docs/ts/latest/quickstart.html#!#index shim.min.js, zone.js and reflect.js are loaded traditionally from within the HTML file.

Why aren't they automatically being imported by `@angular/core` or `@angular/platform-browser-dynamic` if they are required anyway?

**Comment by Foxandxss** [comment]
Dependencies shouldn't never be required by a library, that is my opinion.

Both zone.js and reflect.js are third party dependencies. You could replace reflect.js with core-js if you find it to be a better alternative.

On the other hand, Zone needs to be required as soon as possible, before everything else (except some shims), angular, tooling... So the best way is requiring it using a script tag.

**Comment by SetTrend** [comment]
Hmm.. But they are *dependencies*, i.e. _internal dependencies_, of Angular2, aren't they? So why should the programmer be required to deal with any internal peculiarities of Angular2?

**Comment by Foxandxss** [comment]
Closing in favor of https://github.com/angular/angular/issues/10072
