### ISSUE TITLE
TSC command should use an outDir build target

### ISSUE THREAD

**Issue by matsko** [angular/angular.io#189]
After playing around with the tutorial contents I was unable to get my app to work. It turns out that I had to set `--outDir build` in the TSC command like this:

```
tsc --watch --outDir ./build -m commonjs -t es5 --experimentalDecorators ./app.ts
```

and to also change the System import to look like so:

```html
<script>System.import('build/app');</script>
```

This makes it so that the application directory doesn't get polluted with JS files (everything goes into build).

Should we update this?

**Comment by wardbell** [comment]
Obsolete issue.
