### ISSUE TITLE
Importing barrels with '../shared' fails

### ISSUE THREAD

**Issue by francisoud** [angular/angular.io#1896]
Importing barrels as explain in https://angular.io/styleguide#!#04-10 doesn't work with @angular2@2.0.0.rc3 or angular-cli@1.0.0.beta.8 (I don't know which one is faulty ;) )

I have a `contract-list/contract-list.component.spec.ts `
Karma fails:
```
[2016-07-15 14:35:08.959] [WARN] web-server - 404: /base/dist/app/contracts/shared.js
Missing error handler on `socket`.
```
...

```
import { By }           from '@angular/platform-browser';
import { DebugElement } from '@angular/core';

import {
  beforeEach, beforeEachProviders,
  describe, xdescribe,
  expect, it, xit,
  async, inject
} from '@angular/core/testing';

import { ContractListComponent } from './contract-list.component';
import { ContractService }    from '../shared';

describe('Component: ContractList', () => {
  it('should create an instance', () => {
    let component = new ContractListComponent(new ContractService());
    expect(component).toBeTruthy();
  });
});
```

Workaround:
`import { ContractService }    from '../shared';`
with
`import { ContractService }    from '../shared/index';`

I think I got the same issue inside a component (not a test)...

**Comment by Foxandxss** [comment]
do you have the index.ts file that exports the component and that added to the system config?

/cc @filipesilva

**Comment by filipesilva** [comment]
It also seems to me that it's not being added to system-config. Basically, System does not know that `app/contracts/` has an entry point of `index.js`, which is why you get `web-server - 404: /base/dist/app/contracts/shared.js`.

**Comment by francisoud** [comment]
I create a sample project from scratch to reproduce the problem:  https://github.com/francisoud/angular.io.issue.1896
I have same problem during runtime (in console log) in `contract-list.component.ts` and for test (as describe above).

You were right the problem is in [system-config.ts](https://github.com/francisoud/angular.io.issue.1896/blob/bug/src/system-config.ts) there are 2 lines that are missing and should have been added during `ng generate` (see command line below)
```
// App specific barrels.
  'app',
  'app/shared',
  'app/contracts',
  **'app/contracts/shared',**
  'app/contracts/contract-list',
  **'app/contracts/contract-list/shared'**
```

I think it's a bug in angular-cli 
I think something is missing during `ng generate component ...` somewhere near this line:
https://github.com/angular/angular-cli/blob/master/addon/ng2/blueprints/component/index.js#L117

## Additional info

### Errors
[Error at runtime](https://github.com/francisoud/angular.io.issue.1896/blob/master/ERROR_LOG_RUNTIME.md)
[Error in tests](https://github.com/francisoud/angular.io.issue.1896/blob/master/ERROR_LOG_TEST.md)

### index.ts
It seems to me all index.ts are referencing the correct component:
https://github.com/francisoud/angular.io.issue.1896/blob/bug/src/app/index.ts
https://github.com/francisoud/angular.io.issue.1896/blob/bug/src/app/shared/index.ts
https://github.com/francisoud/angular.io.issue.1896/blob/bug/src/app/contracts/index.ts
https://github.com/francisoud/angular.io.issue.1896/blob/bug/src/app/contracts/contract-list/index.ts
https://github.com/francisoud/angular.io.issue.1896/blob/bug/src/app/contracts/contract-list/shared/index.ts

And they where updated when I created I used `ng generate ...`

### ng generate
```
C:\tmp\myapp>ng generate component contracts
installing component
  create src\app\contracts\contracts.component.css
  create src\app\contracts\contracts.component.html
  create src\app\contracts\contracts.component.spec.ts
  create src\app\contracts\contracts.component.ts
  create src\app\contracts\index.ts
  create src\app\contracts\shared\index.ts

  
C:\tmp\myapp>ng generate component contracts/contract-list
installing component
  create src\app\contracts\contract-list\contract-list.component.css
  create src\app\contracts\contract-list\contract-list.component.html
  create src\app\contracts\contract-list\contract-list.component.spec.ts
  create src\app\contracts\contract-list\contract-list.component.ts
  create src\app\contracts\contract-list\index.ts
  create src\app\contracts\contract-list\shared\index.ts

C:\tmp\myapp>ng generate service contracts/shared/contract
installing service
  create src\app\contracts\shared\contract.service.spec.ts
  create src\app\contracts\shared\contract.service.ts
  
C:\tmp\myapp>tree src
C:\TMP\MYAPP\SRC
└───app
    ├───contracts
    │   ├───contract-list
    │   │   └───shared
    │   └───shared
    └───shared
```


### Sample project
This version with the 2 issues (runtime and test):
https://github.com/francisoud/angular.io.issue.1896/tree/bug

The branch 'workaround': 
https://github.com/francisoud/angular.io.issue.1896/tree/workaround ([diff](https://github.com/francisoud/angular.io.issue.1896/commit/5caf258bdc802a372d0d3150fbcd68615cdec021))

The branch 'fix': 
https://github.com/francisoud/angular.io.issue.1896/tree/fix

### Version
```
C:\tmp\myapp>ng --version
angular-cli: 1.0.0-beta.8
node: 6.2.1
os: win32 x64
```

**Comment by filipesilva** [comment]
@francisoud can you open this issue in https://github.com/angular/angular-cli instead then? It does sound like a bug in the CLI.

**Comment by francisoud** [comment]
Closing this one :)
Will be tracked in https://github.com/angular/angular-cli/issues/1418
