### ISSUE TITLE
Add Print Styles

### ISSUE THREAD

**Issue by alexwolfe** [angular/angular.io#19]
Be sure to create a separate scss file for print `print.scss` and include the print styles in there. 

Print styles should hide the following items: 
1. Top Nav
2. Side Nav
3. Footer

They should also update the layout so that during print the full page is used and the margins are correct.

**Comment by alexwolfe** [comment]
@gorork Here's another one. We don't currently have print styles for the site.

**Comment by saharj** [comment]
I can't see this issue anymore. Is it resolved?

**Comment by wardbell** [comment]
Closed by PR
