### ISSUE TITLE
Mention Angular 2.0 on _Contribute_ page

### ISSUE THREAD

**Issue by gkalpak** [angular/angular.io#191]
On `angular.io`'s [_Contribute_][1] page, there is no mention/link to Angular 2.0.
This might be intentional, since atm it is in alpha, but it is confusing for people that spot issues in the ng2 docs and are then directed to the ng1 repo ([example][2]).

It might make sense to add something about ng2 on the [_Contribute_][1] page (or at least make it more explicit that the current links refer to ng1).

[1]: https://angular.io/contribute.html
[2]: https://github.com/angular/angular.js/issues/12624

**Comment by wardbell** [comment]
Closed by PR
