### ISSUE TITLE
iframe [src] property binding not updating

### ISSUE THREAD

**Issue by iam1me** [angular/angular.io#1914]
I have a component with a template like so: 

```
        <iframe 
            
            [src] = "_sourceFile"

            allowfullscreen webkitallowfullscreen>
        </iframe>

```

As you can see the component has a _sourceFile property that is being bound to as the src for the iframe in the template. The initial value is bound to correctly and the page is loaded successfully. However, when I modify _sourceFile to a new URI the iframe makes no attempt to update and load the new resource.... 

I believe this to be a bug, but if I am simply missing something please let me know. I've tried to research the issue, but I can only find Angular 1 resources on the matter.

**Comment by zoechi** [comment]
This repo is for Angular2 documentation.

Your question sounds like a support question.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

If you don't think it is a support question please open an issue in https://github.com/angular/angular with a Plunker that allows to reproduce.

**Comment by iam1me** [comment]
I'd say this is a bug - unless it is documented somewhere that the iframe src property is unsupported by the present version of angular2?

**Comment by zoechi** [comment]
If it's actually a bug you need to provide a plunker that allows to reproduce it **and** the bug needs to be reported in the https://github.com/angular/angular repository where Angular2 bug reports are maintained. This repo is only for Angular2 **documentation** (the http://angular.io site)

**Comment by kwayne11** [comment]
@iam1me I am having the same issue and I was wondering if you have figured out a workaround for this issue?

**Comment by k1ng440** [comment]
@iam1me i am also having the issue.

**Comment by jiggy1com** [comment]
Toggle the iframe...

I was trying to force a file to download, and went the iframe route (sure, there are other ways). Here are the relevant parts I used to get the iframe to reload (so a user could download the file more than once (how likely is that??? i know)):

```
...
import { DomSanitizer, SafeResourceUrl, SafeUrl} from '@angular/platform-browser';

@Component({
    ...
    template : `
<!-- iframe for download -->
<iframe [src]="url" *ngIf="download" height="0" width="0" frameborder="0"></iframe>`
})

export class SomeComponent(){

    // url for iframe
    private url:SafeResourceUrl;

    // toggle iframe 
    private download:boolean = false;
    
    constructor(private sanitizer: DomSanitizer){
    }

    mediaDownload(_id:string){
        this.download = false; // hide iframe
        this.url = this.sanitizer.bypassSecurityTrustResourceUrl('//api.' + window.location.hostname + '/content/media/download/' + _id);
        this.download = true; // show iframe
    }

}
```
