### ISSUE TITLE
pub serve issues with default angular2 routing strategy

### ISSUE THREAD

**Issue by challe** [angular/angular.io#1919]
Pub serve doesn't support `PathLocationStragety`, which is the angular2 default routing strategy, and because of that, reloading a routed page gets you a 404. I think this should be documented somewhere.

I encountered this a when staring out with angular2, Here is a stackoverflow question with an accepted answer that also mentions a pub package that could solve this: http://stackoverflow.com/questions/36780516/routing-doesnt-work-for-me-when-doing-a-hard-refresh.

**Comment by kwalrath** [comment]
@chalin: My first thought is that we might want to cover this in the guide somewhere, and then refer to that coverage in the API reference docs. What do you think?

**Comment by chalin** [comment]
As a means of addressing this issue, a [PR enhancing `pub serve`](https://github.com/dart-lang/pub/pull/1437) has been submitted.

**Comment by chalin** [comment]
Btw, @kwalrath, I'm unsure why this was tagged with `api`. Maybe drop the `api` label and remove `[API]` from the title since this issue applies to a few chapters in the docs, though not to API docs themselves.

**Comment by kwalrath** [comment]
Talking with an engineer today, he suggested that `#` mode should perhaps be the default for Dart.

**Comment by chalin** [comment]
This issue was moved to dart-lang/site-webdev#252
