### ISSUE TITLE
API not working at all

### ISSUE THREAD

**Issue by demiro** [angular/angular.io#1922]
So I cannot check API at all (chrome)

(Empty content... only seeing the select box to change the language (js, ts, dart)

the console says this:

Uncaught SyntaxError: Unexpected token =>    - api-list.js:42 
GET https://platform.twitter.com/widgets.js net::ERR_TUNNEL_CONNECTION_FAILED   - (index):42 

which points to...
 if (isForDart) $ctrl.apiTypes = $ctrl.apiTypes.filter((t) => 
        !t.cssClass.match(/^(stable|directive|decorator|interface|enum)$/));

Or am I missing something?

**Comment by Foxandxss** [comment]
I cannot reproduce. Is this still happening to you? If so, please, reopen :)
