### ISSUE TITLE
TSLint error: object access via string literals is disallowed

### ISSUE THREAD

**Issue by wembernard** [angular/angular.io#1923]
I'm forwarding some issue explained here https://github.com/angular/angular/issues/10002

[Documentation](https://angular.io/docs/ts/latest/guide/router.html) suggests to use `params['id']` to access observer's result properties after subscribing which leads to some TSLint error `object access via string literals is disallowed`. 

Angular team suggests to cast the result into `any` (which didn't work for me btw). I'm not sure how to handle this properly. Right now, I just disabled (`/* tslint:disable */` ... `/* tslint:enable */`) tslint on this block of code but I guess it would be wise from angular.io's team to warn users about this message and maybe give some insight on how to fix it.

**Comment by Foxandxss** [comment]
Will investigate.

**Comment by wembernard** [comment]
I like @rixrix approach from the other thread suggesting to use 

```typescript
.subscribe((data: { email: string }) => {...
```

This way, you can directly use `data.email` instead of `data['email']` 👍

**Comment by rixrix** [comment]
another 2 options that you could do here:

- 1. modify tslint.json rule and set `no-string-literal` to `false` this will allow you to access object eg. `[1]` or `['id']` across your app [1], this way you don't have to add the ugly tslint:disable line suppressant 
- 2. create a custom interface for your params eg.

```
export interface RouteParams {
   email: string;
}
...
  this.sub = this.route.params.subscribe(params: RouteParams => {
     let email = params.email;
   });
...
```
- 3. optional but highly recommended - there are a bunch of helpful human beings at https://gitter.im/angular/angular - they'll help you FAST! ;)

I could be wrong though but in the previous releases of TypeScript, types are implicitly set to `any` if you don't provide anything - I'd suggest to keep an eye of TypeScript releases too - well as mentioned from my early comment [2]

[1] https://palantir.github.io/tslint/rules/no-string-literal/
[2] https://github.com/angular/angular/issues/10002#issuecomment-233843515

**Comment by Foxandxss** [comment]
It is false in our tslint. That shouldn't happen.

**Comment by wembernard** [comment]
I've been looking into angular.io's documentation looking for some tslint best practices but found none. @Foxandxss Have you provided "your" tslint somewhere I didn't look yet?

Again, maybe it's just me and I'm sorry to bother, but
> I guess it would be wise from angular.io's team to warn users about this message and maybe give some insight on how to fix it.

or, since it seems you suggest to have this parameter set to false in our tslint config, to have some documentation about Angular's team tslint.conf best practices :)

**Comment by Foxandxss** [comment]
Ok ok, I understand your problem properly now.

Let me first ask you a question: You have a tslint.json (obviously). From where did you pick it? Is from one of our repos or did you made it up?

**Comment by wembernard** [comment]
My tslint conf comes directly from https://github.com/FountainJS/generator-fountain-angular2

**Comment by Foxandxss** [comment]
I see.

Then where you need to look for this errors is the [tslint webpage](http://angular-tips.com/blog/2014/02/introduction-to-unit-test-toc/)

You need to understand our position. There are dozens of rules for `tslint` and that gives you hundred of possible combinations.

That concrete error is simple enough. It discourages you of doing `foo['bar']`. As any other rule, they are optional and there are people who likes it on or off.

I suggest you to compile the set of rules that you like and if reading a guide you get a conflicting rule, modify our code to fit your needs.

The set of rules that we have is what we agreed back in the day, but that doesn't mean that our set of rules are the best rules, is simply yet another opinion.

**Comment by wembernard** [comment]
Thanks for this great clarification. That makes sense. 

Perhaps, as my final suggestion (I'll stop bothering you, I promise 👍), you could copy/paste your explanation on [Angular.io TypeScript Configuration page](https://angular.io/docs/ts/latest/guide/typescript-configuration.html). This might help newcomers who are a bit lost with so much tools to learn :)
