### ISSUE TITLE
angular.element().off('click'); substitute / remove and bind events programmatically to html element in angular 2

### ISSUE THREAD

**Issue by rashfmnb** [angular/angular.io#1944]
I want to remove the bind event for the specific button programmatically and then rebind it after completion of specific task call can someone tell me the substitute of these in angular 2 RC4

angular.element($("#btnSubmit")).off('click');
angular.element($("#btnSubmit")).on('click', vm.add);

**Comment by ericmartinezr** [comment]
This repo is for the website. You also need to read this https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by rashfmnb** [comment]
ok thanks for the information.
