### ISSUE TITLE
error to install angular Quickstart 

### ISSUE THREAD

**Issue by hmuschett** [angular/angular.io#1948]
npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

angular2-quickstart@1.0.0 postinstall C:\Users\hmuschett\Desktop\testnode\angular
typings install

typings ERR! message Unable to connect to "https://api.typings.org/entries/dt/node/tags/6.0.0%2B20160621231320"
typings ERR! caused by connect ECONNREFUSED 104.24.112.177:443

typings ERR! cwd C:\Users\hmuschett\Desktop\testnode\angular
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\hmuschett\Desktop\testnode\angular\node_modules\typings\dist\bin.js" "install"
typings ERR! node -v v6.2.1
typings ERR! typings -v 1.3.2
typings ERR! code EUNAVAILABLE

typings ERR! If you need help, you may report this error at:
typings ERR! https://github.com/typings/typings/issues

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN angular2-quickstart@1.0.0 No description
npm WARN angular2-quickstart@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v6.2.1
npm ERR! npm v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-quickstart@1.0.0 postinstall: typings install
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-quickstart@1.0.0 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs angular2-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls angular2-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\hmuschett\Desktop\testnode\angular\npm-debug.log

windows 7

    Angular version: 2.0.0-rc.X

    Browser: Firefox47
    Language: [all | TypeScript X.

**Comment by alexeagle** [comment]
looks like a transient error, I am able to fetch https://api.typings.org/entries/dt/node/tags/6.0.0%2B20160621231320 right now.

Also we should use npm to fetch typings now that TypeScript supports it.

**Comment by Foxandxss** [comment]
I am closing this.

The typings thing will come as soon as a bug is fixed on a type.
