### ISSUE TITLE
RouterState information sentence correction.

### ISSUE THREAD

**Issue by micronyks** [angular/angular.io#1953]
https://angular.io/docs/ts/latest/guide/router.html

Go to different **Route Part** table. In there, check **RouterState** information

RouterState :  The current state of the router including a tree of the currently **_activated activated_** routes in our application along with the URL query params, fragment and convenience methods for traversing the route tree.

Two times **activated activated** written. Please correct it.

**Comment by Foxandxss** [comment]
Closing in favor of #1957 

Thanks for reporting it :)
