### ISSUE TITLE
Style of the Style Guide

### ISSUE THREAD

**Issue by siva636** [angular/angular.io#1958]
Currently the `Do` is in blue and the `Consider` is in green. I think it is more appropriate to change the CSS styles as follows:

Green for the `Do` and light-green for the `Consider`.

**Comment by johnpapa** [comment]
Thanks for the feedback. The docs team discussed this and we agreed that it would be clearer to do:

Do = green
Consider = blue
Avoid = red


See PR link above

**Comment by wardbell** [comment]
Closed by #2257
