### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by matiishyn** [angular/angular.io#1959]
![image](https://cloud.githubusercontent.com/assets/3661065/17082890/84209e96-518d-11e6-9a79-239d61460b5b.png)

**Comment by kylerob** [comment]
Are you still having problems loading the site? Looks good to me now.

**Comment by Foxandxss** [comment]
Seems like it is related to https://github.com/angular/angular.io/issues/1875

**Comment by uirajeev** [comment]
![image](https://cloud.githubusercontent.com/assets/11752612/19377075/d6096e28-9200-11e6-8d13-5223c85b7044.png)
angular.io id down.

**Comment by QuBaR** [comment]
Website been down for a couple of days for me also, please try to bring back the site 👍 
![image](https://cloud.githubusercontent.com/assets/6781888/19417019/c75ddf7e-93a1-11e6-9113-3d57464967a6.png)


Kindly regards
 
Robert Jansz
Web developer and solution architect, founder of Webking AB
phone: +46 (0) 72-711 11 84 | mail: robert@webking.se  | www.webking.se/en/
 

 
”With his high level of ambition Robert makes the complicated seem simple,
and he adds the invaluable knowledge that creates security for his clients”

**Comment by Foxandxss** [comment]
I am going to lock this thread. Please continue at #1875 so we don't have the same discussion twice.
