### ISSUE TITLE
Add README.md to generated plunkers

### ISSUE THREAD

**Issue by wardbell** [angular/angular.io#1965]
The plunkers generated from documentation source examples should have a README.md.

### Implementation suggestion
We can have a stock `plunker.README.md` in the `_examples` folder. If the sample's `plnkr.json` doesn't provide a README.md, we add this default version.

Not sure what it should say. We could start with this:
```
### Angular 2 Documentation Example 

{{description from the plnkr.json}}
```

**Comment by Foxandxss** [comment]
I'll do tomorrow
