### ISSUE TITLE
Update typings installation in the quickstart

### ISSUE THREAD

**Issue by alexeagle** [angular/angular.io#1969]
We should direct users to get typings from https://www.npmjs.com/~types and stop using typings altogether.

Note that our current instructions are out-of-date: https://github.com/angular/angular/issues/8754

**Comment by Foxandxss** [comment]
That is on the works, but is not available right now because there are some blocking issues with @types (that doesn't affect the core but affect us).

If you don't mind, I am going to close this and continue at #1872
