### ISSUE TITLE
Outdated Architecture section

### ISSUE THREAD

**Issue by Pablo-Ivan** [angular/angular.io#1970]
[Architecture](https://angular.io/docs/ts/latest/guide/architecture.htmll)
In the **libraries** section it says

> There are other important Angular libraries too, such as @angular/common, @angular/router, and @angular/animate. We import what we need from an Angular library module.

But apparently, _@angular/animate_ doesn't exist (as far as I can see). Am I wrong?

**Comment by micronyks** [comment]
Yes you are right ! It doesn't exist.

**Comment by Pablo-Ivan** [comment]
Can we close?
