### ISSUE TITLE
Angular 2 Resources Typo

### ISSUE THREAD

**Issue by Pablo-Ivan** [angular/angular.io#1994]
I wanted to make a PR but it seems those resources are fetched from a database, so here it go:
[Angular Resources](https://angular.io/resources/)
_IDES_ should be _IDEs_

_Celerio Angular Quickstart Generate a CRUD *applicatoin*_ should be _application_.

**Comment by Foxandxss** [comment]
Ping @StephenFluin

**Comment by StephenFluin** [comment]
@Pablo-Ivan It's "IDES" because all subcategories are full uppercase. Other typo has been corrected. Thanks!
