### ISSUE TITLE
Tour of Heros: hero-search documentation not included in dashboard

### ISSUE THREAD

**Issue by GeoTracker2016** [angular/angular.io#1996]
In https://angular.io/docs/ts/latest/tutorial/toh-pt6.html, the Tour of Heroes tutorial on HTTP, hero-search is introduced. Some linkage is missing to get the search box to show up. I have tracked down the issue and now have it working. Here is what needs to be added:

1. In dashboard.component.html the last line should be:
`<hero-search></hero-search>` 
so we know where to put the search component.

2. In dashboard.component.ts, we need to import the service with:
`import { HeroSearchComponent } from './hero-search.component';`
and include the directive for the component with:
`directives: [HeroSearchComponent]` 
as the last line of @Component.

All of this was supposed to be inferred from the sentence:

> Finally, we add the HeroSearchComponent to the bottom of the DashboardComponent. Run the app again, go to the Dashboard, and enter some text in the search box below the hero tiles. At some point it might look like this.

These needs to be fixed to appropriately describe how to get the search component into the dashboard.

**Comment by Foxandxss** [comment]
Thanks. I will take a peek :)

**Comment by wardbell** [comment]
Closed by PR #2002
