### ISSUE TITLE
Developer Guide(tab) content(Testing) click should change position of scroll bar in desktop view

### ISSUE THREAD

**Issue by micronyks** [angular/angular.io#1998]
Steps of reproduction of the issue

In desktop mode,
1)  go to `developer guide tab`.
2)  clicking on `Pipes`, `Routing & Navigation`, `security` & 'structural directives' behaves as expected.

**NOTE**:  In my case , in my desktop,  `structural directives` is the last one when page is loaded. other contents are out of current window or hidden.

3)  clicking of `Testing` only seems like refreshes the window and sets scroll bar back to top again. 
4)  clicking on any other content below to `Testing` works as expected. 

 **Expected behavior :**

If you click on `Testing`, scroll bar position should change to appropriate position as it happens with clicking on any other content below to `Testing`.

In general if you scroll towards hidden content and if you click it, it should remain there after clicking it.

**Comment by Foxandxss** [comment]
Sorry I cannot reproduce. A video / gif would be lovely.

**Comment by micronyks** [comment]
Whatever the last content you are having, scroll to the next hidden content and click it. it should reproduce the issue.

**Comment by Foxandxss** [comment]
Sorry, I don't follow or cannot reproduce still :/
