### ISSUE TITLE
Can not iterate over objects, only arrays and iterables...

### ISSUE THREAD

**Issue by pstephenwille** [angular/angular.io#2006]
I know this is by design in NG2, but its not clear on exactly why.  I wonder if NG2 isn't sacrificing function over form, which would be a huge mistake.   

I'd like to suggest making objects iterable, like they were in NG1.

**Comment by Foxandxss** [comment]
Sorry but this repo is for the docs.

**Comment by pstephenwille** [comment]
Sorry about that.  Where's the right place to post this?

**Comment by Foxandxss** [comment]
At angular/angular
