### ISSUE TITLE
In  Angular 2, ngIF is not working when i am trying with two way binding

### ISSUE THREAD

**Issue by SasikalaNagarajan** [angular/angular.io#2012]
Hi Guys, I am working with angular 2 with two way binding concept [(ngModel)].I have form with my page and i have to validate the pristine state of the element. So for validation i have used ngIf to check the pristine state of the element. But the condition is not working. I need to check the condition for every model change.Below id my app.component.html page.

       <form (ngSubmit)="angular2form(myAngular2Form.employeeDob)" [ngFormModel]="myAngular2Form">

       <input type="text" class="form-control" id="employee" name="employee" [(ngModel)]="employeeDob" required  />            
        <div *ngIf="employeeDob.pristine">
          <p>Please enter the date</p>
        </div>
           <button type="submit" class="btn btn-primary">Register</button>

        </form>

Also please get my ts file below

 export class AppComponent {

employeeDob: String;

  constructor(private myform: FormBuilder) {
    this.employeeDob = '';
 }
 angular2form(date) {
     alert("date submitted successfully");
 }
 }
Thanks for any suggestion

**Comment by Foxandxss** [comment]
Hello,

This is more an issue to be opened at stackoverflow under the `angular2` tag.
