### ISSUE TITLE
Tutorial https://angular.io/docs/ts/latest/tutorial/toh-pt6.html is broken 

### ISSUE THREAD

**Issue by ghoben** [angular/angular.io#2014]
I'm submitting a ... (check one with "x")

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Current behavior
The last steps within the tutorial are not given. furthermore the example contents provides a bad MD file.

BAD FILENAME: ../../../_fragments/toh-6/ts/app/rxjs-operators.ts.md Current path: docs,ts,latest,tutorial,toh-pt6 PathToDocs: ../../../

Expected/desired behavior

All steps are shown
Reproduction of the problem
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

What is the expected behavior?

What is the motivation / use case for changing the behavior?

Please tell us about your environment:

    Angular version: 2.0.0-rc.X

    Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

    Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by Foxandxss** [comment]
Weird, I can't see it.

**Comment by ghoben** [comment]
![screenshot-rxjs-operator ts-selection](https://cloud.githubusercontent.com/assets/6631653/17300047/05506f4e-5811-11e6-99e5-64839b471728.PNG)

**Comment by Foxandxss** [comment]
Ah, hidden!

Thanks.

**Comment by franciscoruiz** [comment]
It should be `rxjs-extensions.ts` instead of `rxjs-operators.ts`. I'll create PR if I have time today.

**Comment by niwsa** [comment]
Also the hero-search.service.html is the wrong file name although contents are correct, should be hero-search.component.html

**Comment by niwsa** [comment]
I am not able to get the search component working does that have to do with the incompleteness as reported here?

**Comment by Foxandxss** [comment]
I believe this got fixed. If there is any standing issue in here, please open a new issue.
