### ISSUE TITLE
Update the docs to use `system.config.ts` instead of `systemjs.config.js`

### ISSUE THREAD

**Issue by DeborahK** [angular/angular.io#2016]
Update the getting started docs to use `system.config.ts` instead of `systemjs.config.js` to match with the CLI.

**Comment by Foxandxss** [comment]
But that would require us to do extra magic to put the system.config to typescript.

**Comment by DeborahK** [comment]
Does the CLI already do that magic at this point?

**Comment by Foxandxss** [comment]
Yes, but the docs doesn't use the CLI yet.

**Comment by Foxandxss** [comment]
Closing this, I don't think we are going to do this for the time being.
