### ISSUE TITLE
Dart syntax error in tutorial toh-pt3

### ISSUE THREAD

**Issue by ben4ever** [angular/angular.io#2019]
In the Angular Dart [toh-pt3 tutorial](https://angular.io/docs/dart/latest/tutorial/toh-pt3.html), in the section "Separating the Hero Detail Component", there is a code sample which contains the following code:

``` dart
@Component(
    selector: 'my-hero-detail',
    )
```

There is a syntax error in this code sample because of the leading comma at the end of the second line.

Source file for this tutorial: [public/docs/dart/latest/tutorial/toh-pt3.jade](https://github.com/angular/angular.io/blob/master/public/docs/dart/latest/tutorial/toh-pt3.jade)
Source file for this code sample: [public/docs/_examples/toh-3/dart/lib/hero_detail_component.dart](https://github.com/angular/angular.io/blob/master/public/docs/_examples/toh-3/dart/lib/hero_detail_component.dart)

**Comment by kwalrath** [comment]
@chalin

**Comment by chalin** [comment]
Yes, thanks for the detailed report @ben4ever.

@kwalrath: this is one of the reasons why I am generally against `docplaster`. I would suggest just dropping `docplaster` so that it will be clear that there is more code than what is shown in the excerpt. Do you agree?

**Comment by chalin** [comment]
@kwalrath : have you decided how you would like to handle this? (E.g., dropping `docplaster`?)

**Comment by kwalrath** [comment]
Interestingly, the `,` will soon be legal. 

In this case, you're telling the reader to add something, so it'd be a little weird to have `...` in there.

Could you work around this, somehow, @chalin?

**Comment by chalin** [comment]
My preference, atm, would be to leave this as is. Workarounds are possible but not worth it (esp. if that will become legal syntax :).

**Comment by chalin** [comment]
This is now legal syntax.
