### ISSUE TITLE
Update the link to the dart change log

### ISSUE THREAD

**Issue by challe** [angular/angular.io#2021]
The link to the Angular 2 Dart change log over at https://angular.io/docs/dart/latest/index.html is now located at https://github.com/dart-lang/angular2/blob/master/CHANGELOG.md. The link should be changed to this adress.

Also, the latest version as of now says it's 2.0.0-beta.18, but according to the changelog (and Pub), it's 2.0.0-beta.19. This should also be updated if it has not already been done when this is looked at.

**Comment by kwalrath** [comment]
I can fix the changelog link. @chalin, what's your plan for beta.19?

**Comment by chalin** [comment]
Given that beta.19 is mostly "cleanup" (no new functionality). I was going to wait beta.20 before updating the docs, and focus on other work in the meantime. Of course users can still use beta.20 from pub. Thoughts?

**Comment by kwalrath** [comment]
SGTM. Updating to a new version is quite a production, even when there are no API changes.

**Comment by kwalrath** [comment]
I've fixed the changelog link in #2025.
