### ISSUE TITLE
Make re-building the API docs an optional part of gulp check-deploy task

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#2022]
Since we only re-build the API docs when there's a new release, it would greatly speed up site deploy if we could break those out and make them optional. I'm imagining something like:

- run check-deploy
- if check-deploy finds generated API docs in the local client are current with the checked-out local repositories for angular and angular-dart, skip re-generating API docs
- if the local repositories are newer, *remove* old API docs under angular.io and generate new ones
- on completion print a status message to stdio with the version that API docs were generated at

it would be a good idea to include some way to force generating the API docs (eg no version change, but testing a small tweak) but make the default be to not generate them.

**Comment by kwalrath** [comment]
This capability would also help if we decide that generating the dartdocs on Linux is necessary.

**Comment by chalin** [comment]
To regenerate the site after only a few minor changes to .jade or Harp data files, try using the `--fast` command line argument.

**Comment by chalin** [comment]
For the record: currently a `check-deploy` takes ~18 mins on my laptop, and ~15 with `--fast`, so that isn't much of a savings, but is 15 min. Is that too long? To reduce that further would involve performing the harp compilation itself piecewise.

**Comment by chalin** [comment]
Fixed by #2202.
