### ISSUE TITLE
Why is angular.io offline for the past two days?

### ISSUE THREAD

**Issue by pfaffventer** [angular/angular.io#2027]
I am new to front end web development and have been playing with angular2 the past week or so, however, when trying to access the website https://angular.io/ I get the following error:

This site can’t be reached
The connection was reset.
Try:
•	Reloading the page
•	Checking the connection
•	Checking the proxy and the firewall
ERR_CONNECTION_RESET

Regards

**Comment by bampakoa** [comment]
Possible dup of #1875 ?

**Comment by pfaffventer** [comment]
I did do an update of my NOD32 software in the last week or so, uninstalling the newer version and reinstalling the previous version solved my problem. Thank you very much bampakoa!
