### ISSUE TITLE
Misleading statement about Decorator

### ISSUE THREAD

**Issue by trotyl** [angular/angular.io#2031]
In the Glossary, it says:

> A Decorator is a function that adds metadata to a class, its members (properties, methods) and function arguments.
> 
> Decorators are a JavaScript language feature, implemented in TypeScript and proposed for ES2016 (AKA ES7).
> ...
> Always include the parentheses () when applying a decorator. A decorator is a function that must be called when applied.

It would be easy to mislead beginners to regards `Component`, `Injectable` to be decorators and `Component()`, `Injectable()` to be the usage of the decorators.

Actually, the `Component()` and `Injectable()` are decorators, and `Component`, `Injectable` are the factories of decorator.

It seems to be ambiguous in the statement of the conception of Decorator.

Reference: https://github.com/wycats/javascript-decorators/blob/master/README.md

**Comment by wardbell** [comment]
While you are technically correct, I don't see how we're misleading anyone into making a mistake nor do I see how the distinction you're making between decorators and factories would have practical value.

You are welcome to submit a PR with improved language. I'm closing for lack of a specific action.
