### ISSUE TITLE
Tutorial pt. 6 Routing, problem/concern

### ISSUE THREAD

**Issue by CaesarOG** [angular/angular.io#2038]
The following code below in pt. 6 of the Tutorial (Routing) doesn't work. Specifically, the getHero.then promise in the ngOnInit is async so it causes an error in the template. That is, when the first attempt to interpolate hero.name or hero.id occurs, hero is still undefined and you get all sorts of ugly red errors saying "cannot read property name/id of undefined". I found that moving the promise to the constructor works, but this doesn't seem like a good practice for debugging. What is a good solution?

import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { Hero } from './hero';
import { HeroService } from './hero.service';

@Component({
selector: 'my-hero-detail',
templateUrl: 'app/hero-detail.component.html',
})
export class HeroDetailComponent implements OnInit, OnDestroy {
hero: Hero;
sub: any;

constructor(
private heroService: HeroService,
private route: ActivatedRoute) {
}

ngOnInit() {
this.sub = this.route.params.subscribe(params => {
let id = +params['id'];
this.heroService.getHero(id)
.then(hero => this.hero = hero);
});
}

ngOnDestroy() {
this.sub.unsubscribe();
}

goBack() {
window.history.back();
}
}

Please tell us about your environment:

    Angular version: 2.0.0-rc.X

    Browser: [all]

    Language: [ES6 typescript]

**Comment by Foxandxss** [comment]
ping @brandonroberts. Can you give some insight?

**Comment by brandonroberts** [comment]
I'll have to check this and verify that the issue still exists. Unless the template is trying to access the hero before it's set I don't think this should be an issue.

**Comment by brandonroberts** [comment]
I don't think this issue is relevant anymore. The template for the hero detail checks to make sure the hero property is set before displaying the details, so something else is going on.

**Comment by CaesarOG** [comment]
yeah the hero detail uses the structural *ngIf directive to ensure hero property exists before displaying the detail template. So this *ngIf is the best practice for these situations then?

**Comment by brandonroberts** [comment]
Yes. If you have some variables in the template that are resolved async
then you need to protect against failure in the case that they aren't there
yet.

**Comment by CaesarOG** [comment]
This last response really cleared the confusion in my head. Thanks @brandonroberts

**Comment by brandonroberts** [comment]
@CaesarOG close this one since your issue is resolved.
