### ISSUE TITLE
Style Guide: Naming Observable variables with $

### ISSUE THREAD

**Issue by jbalbes** [angular/angular.io#2039]
There is a convention out there to always name variables that are observables with a $ at the end. Is this something that the style guide should take a stance on, and if so, what should it be?

**Comment by jbalbes** [comment]
Using the language of the style guide, I would put this as a 'consider'. Anyone feel more strongly either way and if so, why?

**Comment by wardbell** [comment]
We do not recommend the `$` suffix. It smacks of [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation).

**Comment by kylecordes** [comment]
I have nothing against the Hungarian people, but I also loathe Hungarian notation...  It reminds me of the super-bad super-old days, when I first learned BASIC in 19xx and had to put $ at the end of string variable names. Never again. :-)
