### ISSUE TITLE
[Dart][example] tutorial/toh-6: 

### ISSUE THREAD

**Issue by ptrwis** [angular/angular.io#2055]
In the file **main.dart** there should be 
`provide(Client, useFactory: () => new BrowserClient(), deps: [])`
instead of
`provide(BrowserClient, useFactory: () => new BrowserClient(), deps: [])`

**Comment by chalin** [comment]
The `main` function is presented in two versions. I cannot make the change as you suggested; i.e., version 1 of main is correct as it stands. But I have added a comment in the final version of `main`:
```
    // Using a real back end? Import browser_client.dart and change the above to
    // [provide(Client, useFactory: () => new BrowserClient(), deps: [])]
```
