### ISSUE TITLE
Error  while follow code example in cordova

### ISSUE THREAD

**Issue by ravinsinghd** [angular/angular.io#2058]
while follow the `QuickStart ` code in cordova environment, the angular files not loaded in android mobile.
the problem is urls which are generated by systemjs having two slash's 
![1](https://cloud.githubusercontent.com/assets/9314601/17520096/0e125140-5e6c-11e6-87e6-52d61476cb13.png)

so i removed the slash before `bundle` in `systemjs config`. then it started working,
**Original**
` function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
  }`
**updated**
` function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: 'bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
  }`

**Comment by Foxandxss** [comment]
There is a fix for this on a PR. Let's continue there.
