### ISSUE TITLE
es5 getting started is missing a `bootstrap` call

### ISSUE THREAD

**Issue by rkirov** [angular/angular.io#206]
see https://github.com/angular/angular/issues/4176

**Comment by albertosantini** [comment]
The quick start guide has been deprecated. 
See angular/angular.io#207

**Comment by mmieluch** [comment]
Quick start - yes, but the step by step guide is missing that part too. Or are they considered to be the same thing?

**Comment by naomiblack** [comment]
no longer relevant in new docs
