### ISSUE TITLE
Update Angular 2 Quick Start to Include Pollyfills for Safari

### ISSUE THREAD

**Issue by robinkedia** [angular/angular.io#2063]
http://stackoverflow.com/questions/35017800/ionic-2-using-angular-2-pipe-breaks-on-ios-cant-find-variable-intl

Angular 2 Quick Start doesn't include any information on how to fix pipes issue. Pipes doesn't work untill we use this Intl polly fill.

Browser : Safari

**Comment by Foxandxss** [comment]
We added a message at `pipes` chapter where we tell the user about this problem.

We decided not to add all the needed warnings to the quickstart.
