### ISSUE TITLE
Update Angular 2 Forms Documentation for Reset functionality

### ISSUE THREAD

**Issue by robinkedia** [angular/angular.io#2066]
Hi - It seems Angular 2 forms documentation is still referring the old way to reset forms using active. Please help update the documents to reflect new api.

https://angular.io/docs/ts/latest/guide/forms.html

**Comment by paragpkulkarni** [comment]
Yes.Angular docs are not updated to demonstrate the form.reset() method. It still shows the old way using *ngIf="active" to reset the form.

**Comment by bogomips** [comment]
I was implementing my first form in agular2, fortunately it came in my mind to check here before to use the workaround suggested in the documentation!
