### ISSUE TITLE
Sample Mistake.

### ISSUE THREAD

**Issue by Pablo-Ivan** [angular/angular.io#2069]
In https://angular.io/docs/ts/latest/tutorial/toh-pt2.html at the Displaying Our Heroes section, it says:

> Let’s create an array of ten heroes _at the bottom_ of app.component.ts

But at the end of the page the array is after the Hero class, not at the bottom.

**Comment by Foxandxss** [comment]
I made that mistake, moved that, never realized that there was a precise explanation of where to find it.

Will fix. Thank you.

**Comment by Pablo-Ivan** [comment]
You're welcome!
