### ISSUE TITLE
ROUTING & NAVIGATION - RouterLink section example does not work

### ISSUE THREAD

**Issue by WonSong** [angular/angular.io#2084]
https://angular.io/docs/ts/latest/guide/router.html#!#router-link

Below code example does not work:

```
<h1>Component Router</h1>
<nav>
    <a routerLink="/crisis-center" routerLinkActive="active">Crisis Center</a>
    <a routerLink="/heroes" routerLinkActive="active">Heroes</a>
</nav>
<router-outlet></router-outlet>
```

This worked:
```
<h1>Component Router</h1>
<nav>
    <a [routerLink]="['/crisis-center']" routerLinkActive="active">Crisis Center</a>
    <a [routerLink]="['/heroes']" routerLinkActive="active">Heroes</a>
</nav>
<router-outlet></router-outlet>
```

Also, it does not mention having to use ```import { ROUTER_DIRECTIVES } from '@angular/router';```
and  ```directives: [ROUTER_DIRECTIVES]```.

**Comment by Foxandxss** [comment]
The last part is not needed anymore with NgModule, about the issue, ping @brandonroberts

**Comment by brandonroberts** [comment]
@WonSong the code example is correct. If you don't need to use an expression binding, you can do a one-time binding to a string and the navigation will work just the same. The live example shows this.

**Comment by WonSong** [comment]
Hm - I will try again, but it did not work in project generated by the latest version of angular-cli.
Other people having similar issues: http://stackoverflow.com/questions/38832851/routerlink-does-not-work

**Comment by brandonroberts** [comment]
@WonSong do you have a reproduction of this issue we can see?

**Comment by WonSong** [comment]
Thanks. This bug is now obsolete with the RC5 update.
