### ISSUE TITLE
Property Inconsistency

### ISSUE THREAD

**Issue by Pablo-Ivan** [angular/angular.io#2094]
![angular modules ngmodule - ts - google chrome 11_08_2016 05_33_21 p m](https://cloud.githubusercontent.com/assets/10409758/17607476/9614a798-5feb-11e6-9e72-d21f4bcfb71c.png)
As you can see the properties are inconsistent, in one file it is *user* and the other says *userName*.

**Comment by Foxandxss** [comment]
I don't have a strong opinion, but you can open a PR :)

**Comment by wardbell** [comment]
Thanks. Your suggestion is incorporated in PR #2179
