### ISSUE TITLE
Tutorial 6.Routing: Need to import HeroDetailComponent

### ISSUE THREAD

**Issue by yamasy1549** [angular/angular.io#2096]
In [Tutorial 6. Routing - Create AppComponent](https://angular.io/docs/ts/latest/tutorial/toh-pt5.html#!#create-appcomponent-) section, it says
> The app still runs and still displays heroes.

but it doesn't work.

It seems the sample code ( `app/app.module.ts (v1)` ) lacks `HeroDetailComponent` .

**Comment by wardbell** [comment]
closed by #2137
