### ISSUE TITLE
favicon is missing from second-level pages

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#21]
angular.io has a favicon
https://angular.io/about/ does not

**Comment by alexwolfe** [comment]
hmm, seems to be working now
![Uploading Screen Shot 2015-04-07 at 4.56.20 AM  - Apr 7, 2015.png . . .]()

**Comment by naomiblack** [comment]
I can't see your screenshot, but I'm still seeing this issue on https://angular.io/docs/dart/latest/guide/making-components.html

![screen shot 2015-04-23 at 9 47 55 am](https://cloud.githubusercontent.com/assets/2286589/7302385/ea0b1a8c-e99d-11e4-9a22-dc2dbe0675fb.png)

**Comment by naomiblack** [comment]
I note there's a missing icon file that 404s. Related? https://angular.io/resources/images/favicons/android-chrome-192x192.png

**Comment by alexwolfe** [comment]
fix in branch, added favicon
