### ISSUE TITLE
"live example" text in "Angular Modules (NgModule)" document not shown as hyperlink in IE 11

### ISSUE THREAD

**Issue by hhubik** [angular/angular.io#2114]
Just opened https://angular.io/docs/ts/latest/guide/ngmodule.html# in IE 11 on Windows 8.1 x86.

 "Try the live example." text is shown, but is not a hyperlink. See the screenshot below.

 The text should be a link to a  plunker, which is what happens in Firefox/Chrome.

![ngmoduledocexamplelink](https://cloud.githubusercontent.com/assets/14813201/17651496/46e62a46-6236-11e6-92aa-1e0e2eadf5bf.PNG)

**Comment by hhubik** [comment]
@wardbell If the plunkers did not work in IE11, that is a separate issue.  This issue is about the fact that, in IE 11, the text "Try the live example" is *not* a hyperlink.  If you click that text, nothing happens (no plunker shows up).  I just tested the documentation page referenced at the top of this issue, and the problem still exists there: "Try the live example" text is not clickable in IE11 on Windows 8.1 (x64).

**Comment by Foxandxss** [comment]
I fixed that in #3095 @hhubik. You will see it as soon as we upload the site again

**Comment by hhubik** [comment]
@Foxandxss sounds good.  How often does the site get uploaded?
