### ISSUE TITLE
Unnecessary character

### ISSUE THREAD

**Issue by saharj** [angular/angular.io#212]
On the [website](https://angular.io/docs/js/latest/guide/displaying-data.html) you will see this window:

![screen shot 2015-09-15 at 6 36 17 pm](https://cloud.githubusercontent.com/assets/1468463/9894443/bbb41460-5bd8-11e5-87a2-74b2bfab916e.png)

In this code there shouldn't be any character after `template` to wrap the HTML tags.

**Comment by ericmartinezr** [comment]
@saharj I think it is for the example that follows

```
//Typescript
import {Component, View, bootstrap, NgFor} from 'angular2/angular2';
@View({
  ... // Here it goes your example, you need the comma
  directives: [NgFor]
})
```
