### ISSUE TITLE
Extra quotation marks

### ISSUE THREAD

**Issue by saharj** [angular/angular.io#213]
In the guid section of [angular.io website](https://angular.io/docs/ts/latest/guide/displaying-data.html) you see this window:

![screen shot 2015-09-15 at 10 40 42 pm](https://cloud.githubusercontent.com/assets/1468463/9897266/27adf682-5bfb-11e5-9a64-21eaec627d26.png)

In the es5 tab, there is extra single quotations wrpping the `template` strings.

**Comment by wardbell** [comment]
Obsolete issue.
