### ISSUE TITLE
Quickstart typo: bootstrapModule with AppComponent

### ISSUE THREAD

**Issue by spcfran** [angular/angular.io#2130]
In [Step 4 in Quickstart guide](https://angular.io/docs/ts/latest/quickstart.html#!#main). 

Code snippet is:
`platformBrowserDynamic().bootstrapModule(AppModule);`

Whereas the description:
> Then we call `platformBrowserDynamic().bootstrapModule` with `AppComponent`.

Shouldn't it say `AppModule` instead?

**Comment by wardbell** [comment]
Closed by #2158
