### ISSUE TITLE
Not mobile friendly: https://angular.io/docs/ts/latest/guide/ngmodule.html

### ISSUE THREAD

**Issue by Martin-Wegner** [angular/angular.io#2147]
The page https://angular.io/docs/ts/latest/guide/ngmodule.html is not mobile friendly:

![image](https://cloud.githubusercontent.com/assets/8995517/17808631/718ed638-6611-11e6-8741-fb4e1f0d38d0.png)

![image](https://cloud.githubusercontent.com/assets/8995517/17808653/8cd788e0-6611-11e6-845e-954435cee460.png)

It should be like the other pages (e.g. https://angular.io/docs/ts/latest/guide/animations.html):

![image](https://cloud.githubusercontent.com/assets/8995517/17809102/7c5f94d2-6614-11e6-8ce8-210886acd302.png)

**Comment by Foxandxss** [comment]
Each page that contains images or other kind of things that are not text, will get that effect.

Ping @naomiblack @ericjim

**Comment by Foxandxss** [comment]
Closing as we are migrating to a new design. I will make sure this won't happen.
