### ISSUE TITLE
NgModule: BrowserModule Vs. CommonModule not explained

### ISSUE THREAD

**Issue by SamVerschueren** [angular/angular.io#2166]
The docs state the following

> We also replaced BrowserModule by CommonModule for reasons we explain [soon](https://angular.io/docs/ts/latest/guide/ngmodule.html#root-vs-feature-module).

Does `soon` mean it will be added in the near future, or that it will be explained later on in the documentation? Because currently, the link is not pointing to anything.

After reading the entire document, I believe this is the same reason as to why you have `SharedModule.forRoot()` and `SharedModule`. Because in this case, `BrowserModule` bootstraps application-wide providers. If you would use `BrowserModule` everywhere, lazy-loaded feature modules will create a new instance of those providers in their child-injector. 

I'm not sure though, just guessing here. Would be nice if it was explained more explicitly.

**Comment by Foxandxss** [comment]
If the link is not sending you anywhere that is a bug and I will fix it.

**Comment by wardbell** [comment]
Thanks. Incorporated in #1911
