### ISSUE TITLE
Webpack Docs Sample Test Fails

### ISSUE THREAD

**Issue by pthalacker** [angular/angular.io#2172]
When I create all the files in the Webpack: Introduction and run npm test in the terminal,  I get an error in karma-test-shim.js that it " Cannot resolve module 'zone.js/dist/proxy-zone'"  When I check node_modules, there is no proxy-zone in the zone.js folder.  I am not sure how to resolve this issue.

**Comment by Foxandxss** [comment]
Zone changed twice in a day. Will fix later

**Comment by karptonite** [comment]
I also just hit this issue. The test seems to pass if you just comment out that line, but it took me a while to figure out that it wasn't something I was doing wrong.
