### ISSUE TITLE
Homepage not displaying correctly in IE & Firefox browsers.

### ISSUE THREAD

**Issue by camerondrennan** [angular/angular.io#2182]
The CSS used for the [homepage](https://angular.io/) is not displaying correctly in IE and Firefox browsers.

On first inspection, it would appear the problem lies within the following CSS (angular-material.min.css - line 6):

`.layout, .layout-column, .layout-row {
    box-sizing: border-box;
    display: flex;
}`

I feel the `display: flex;` is causing the issue. 

I have tested on Mozilla Firefox 38.2.0, Internet Explorer 11 and the latest Microsoft Edge browser.

**Comment by flyer1** [comment]
How is it not displaying properly? What issues do you see?

**Comment by naomiblack** [comment]
can't repro. please re-open with a screen shot.
