### ISSUE TITLE
[TS] API entry missing for http._createDefaultCookieXSRFStrategy

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#2184]
Visit https://angular.io/docs/ts/latest/api/http/index/ and click on the link to `_createDefaultCookieXSRFStrategy` which is found towards the end of the page. Result: 404, page not found.

The relevant code excerpt from `modules/@angular/http/http.ts` is:
```
/**
 * @experimental
 */
export function _createDefaultCookieXSRFStrategy() {
  return new CookieXSRFStrategy();
}
```
Notice that the function is exported.

Is the page for this entry being skipped because of the leading underscore? If so, then it should not appear in the index summary.

@ericjim @petebacondarwin 
cc @Foxandxss @kwalrath 

This is one of the broken links reported in #2150. (There is also a similar issue with `platform-browser/index/_WORKER_UI_PLATFORM_PROVIDERS-let.html`, but let's see how this issue is resolved first).

**Comment by petebacondarwin** [comment]
The document indeed is not rendered because it starts with `_`.
Equally the code appears to indicate that the document should not be included in the module's exports. See https://github.com/angular/dgeni-packages/blob/823d3f9e06b08f49b0a4c177da94486ec8ea9ad1/typescript/processors/readTypeScriptModules.js#L98

**Comment by petebacondarwin** [comment]
I think the problem is here: https://github.com/angular/angular.io/blob/master/tools/api-builder/angular.io-package/processors/addJadeDataDocsProcessor.js#L70

We either need to iterate over a different collection than `doc.exports` (perhaps `doc.members`) or we should do a similar filtering to what is in `readTypeScriptModules.js`

**Comment by chalin** [comment]
@petebacondarwin: thanks for the feedback!

@wardbell @Foxandxss: doing similar filtering in both places would seem like a reasonable solution.

**Comment by petebacondarwin** [comment]
(but not very DRY)

**Comment by chalin** [comment]
Not DRY, but an ok incremental improvement IMHO. (Of course, if someone wants to invest time in creating a DRY solution that would be great too.)

**Comment by petebacondarwin** [comment]
Ah I see that the lines I was pointing to are regarding exportDoc members not exportDocs themselves... So I am not sure why the doc is not being rendered.

**Comment by petebacondarwin** [comment]
Ahah! It is a jade problem. The file is being generated but files that start with an underscore are ignored by harp/jade.

**Comment by chalin** [comment]
Ah! Of course! Thanks @petebacondarwin.

Hmm, that will be an interesting issue to solve.

@wardbell @Foxandxss: it might be best to check with the angular folks to see if the two exported entities whose names start with an underscore are _actually meant_ to be exported (my guess is that it is not the case).

**Comment by wardbell** [comment]
Please follow up with the Angular team. They should **not** be exporting public API members with leading underscore. Therefore, this appears to be a solution looking for a non-existent problem.

**Comment by chalin** [comment]
Well, underscores for private members is a Dart convention, I'm not sure that it is 100% enforces in Angular 2 (TS).

**Comment by IgorMinar** [comment]
+1 to what @wardbell said
