### ISSUE TITLE
404 error for Live Example in guide

### ISSUE THREAD

**Issue by rojaster** [angular/angular.io#2190]
I'm reading docs (https://angular.io/docs/ts/latest/guide/) and found in paragraph a live example with next link(see below):
https://angular.io/resources/live-examples//ts/plnkr.html 

But it is responding with 404 error.

Detailed:

> Look for a link to a running version of that sample near the top of each page, such as this [_live example_ ](https://angular.io/resources/live-examples//ts/plnkr.html )from the **Architecture chapter**.

**Comment by Foxandxss** [comment]
That is wrong, let me check.

**Comment by rojaster** [comment]
thx :+1:
