### ISSUE TITLE
#angularjs -alpha.37 causes --module required error on 5 minute QS but it works for alpha.36 ?

### ISSUE THREAD

**Issue by peterennis** [angular/angular.io#220]
Using this command line:

tsc --watch -m commonjs -t es5 --experimentalDecorators --emitDecoratorMetadata app.ts

![capture10](https://cloud.githubusercontent.com/assets/140737/10032349/6b34d8f8-6137-11e5-8e7a-e0361c68eada.PNG)

**Comment by wardbell** [comment]
Obsolete issue.
