### ISSUE TITLE
Can't connect to the web site

### ISSUE THREAD

**Issue by vmarquis** [angular/angular.io#2215]
I have the folowing error with IE, chrome and firefox since 2016/08/25 when try to browse https://angular.io
ERR_BAD_SSL_CLIENT_AUTH_CERT
Best
Same issue have been reported on the wrong repo https://github.com/angular/angular/issues/9945

**Comment by Foxandxss** [comment]
And that issue contains a link to an issue already reported here https://github.com/angular/angular.io/issues/1875
