### ISSUE TITLE
Broken Links in Tutorial HTTP section

### ISSUE THREAD

**Issue by moniquefjones** [angular/angular.io#2229]
A few sections of sample code is not displaying due to "BAD FILENAME" error.

**Comment by ericmartinezr** [comment]
@moniquefjones this was reported a few days ago (see https://github.com/angular/angular.io/issues/2213) but it seems to be fixed. I checked https://angular.io/docs/ts/latest/tutorial/toh-pt6.html and I can't see that error anymore, can you double check?

**Comment by moniquefjones** [comment]
Hi Eric,

Thanks for looking into this!  Yes it is showing as resolved for me as well
now!  =)  I rechecked that it was still an issue a few moments before
submitting the request, but maybe I didn't refresh the page?  Either that
or someone works REALLY fast.  Thanks again!

Thanks,
Monique Jones
