### ISSUE TITLE
Tour of Heroes - HTTP - create method for HeroService never defined

### ISSUE THREAD

**Issue by jzissu** [angular/angular.io#2231]
In the Tour of Heroes, the HTTP page has a section called "Add a hero" where the user makes a new button that will create a new hero using a name entered in an input field on the Heroes page of the application. However when following the steps in the tutorial it doesn't work because they never tell you to add the create method to the HeroService class, which means that when the Add button is clicked the function being called doesn't exist. Now looking at the bottom of the page will show the method, and looking at the Plunkr page also has the method, but you should add the create method to the explanation for that section.

**Comment by bignimbus** [comment]
If no one else is working on this, I can submit a fix for this issue.
