### ISSUE TITLE
Missing ngNonBindable entry in API Reference

### ISSUE THREAD

**Issue by ericjim** [angular/angular.io#2236]
When I search for `ngNonBindable` in the API Reference, I do not find an entry. I suspect that dgeni is not picking up on ngNonBindable.

**Comment by Foxandxss** [comment]
I am going to close this @ericjim. If I remember correctly, @IgorMinar decided to remove the compiler API from the reference, so that one shouldn't show in this case.

**Comment by ericjim** [comment]
Thanks for the reply @Foxandxss, hmm, if the API reference is not the place for canonizing the compiler `ngNonBindable` flag. Where would be the official point of reference?
