### ISSUE TITLE
Same example in OnDeactivate and OnReuse

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular.io#224]
Both OnDeactivate and OnReuse show the same example

https://github.com/angular/angular.io/blob/master/public/docs/js/latest/api/router/OnDeactivate-interface.jade
https://github.com/angular/angular.io/blob/master/public/docs/js/latest/api/router/OnReuse-interface.jade

I know the docs are being rewritten, but in case this hasn't been noticed yet. If it is just close it.

**Comment by wardbell** [comment]
API doc issues go in [**angular source code**](https://github.com/angular/angular/issues)
