### ISSUE TITLE
Request to update quickstart to RC6

### ISSUE THREAD

**Issue by sanket360** [angular/angular.io#2240]
As per CHANGELOG.md, RC6 is released yesterday. However, quick-start guide is not updated. Still referring to RC5. Could anyone please update quick-start article for RC6?

https://angular.io/docs/ts/latest/quickstart.html

![capture1](https://cloud.githubusercontent.com/assets/16756121/18154679/7312c150-7024-11e6-8810-e0a3a2320b89.PNG)

**Comment by Foxandxss** [comment]
Everything will be updated shortly
