### ISSUE TITLE
Enhance documentation for migration from RC4 to RC5

### ISSUE THREAD

**Issue by wembernard** [angular/angular.io#2249]
After reading [this](https://github.com/angular/angular/issues/9813#issuecomment-244158447), I suggested to add the `No provider for Token Platform Pipes! (CompilerConfig -> Token Platform Pipes)` error in the [migration doc](https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html).

What do you think? :)

**Comment by Foxandxss** [comment]
We removed this doc, so I am closing this.
