### ISSUE TITLE
Tutorial missing create() function on AngularJS 2 Typescript tutorial

### ISSUE THREAD

**Issue by qazqwezxc** [angular/angular.io#2268]
**I'm submitting a ...**  (check one with "x")
```
[X] Missing Documentation
```

**Current behavior**

MISSING

**Expected/desired behavior**

Hi, 
I'm a little new to contributing and was working through the AngularJS tutorial. I noticed that in the HTTP section, there is a missing function for create(), although provided at the end of the section, it was not documented in the tutorial. Can someone please add it and fix it so that other newcomers like me can learn and not worry about missing functions?

Thanks,
Andrew H

**Comment by Foxandxss** [comment]
Thanks, that got fixed recently, will be shown as soon as we publish the site again.
