### ISSUE TITLE
Dev Guide/Routing & Nav live Plunkr example: some router links do not work with Chrome v52 (fixed with v53)

### ISSUE THREAD

**Issue by SN2014J** [angular/angular.io#2270]
The Angular 2 (2.0.0-rc.6) documentation in the Developers' Guide for Routing and Navigation provides a live example that runs in Plunkr. When running this live example in Chrome v52, the 'Heroes' and 'Login' routes work properly but the 'Crisis Center' and 'Crisis Admin' routes do not, i.e. nothing happens when you click their respective links and a 404 error appears. The dead links were previously reproducible but I cannot now recall which file couldn't be found as the browser update (see below) has made it impossible for me to currently reproduce the error.

This problem is with the browser, not with Angular, and has already been resolved by a browser update. However, I report it here because it presents itself as a buggy version of Angular and this report may help others identify the source of the problem and fix it (by updating their browser). It may also give the Angular team some insight into an edge case that needs investigation. (e.g. Even if the problem was with Chrome, does this issue betray a fragile element in Angular?)

This problem only occurs with Mac Chrome version 52 (i.e. 52.0.2743.116 64-bit) and is fixed when Chrome is updated to version 53 (i.e. 53.0.2785.89 64-bit). The problem does not occur for:

- Mac Firefox 48.0,
- Mac Safari 9.1.3,
- Mac Opera 36.0.2130.46,
- Windows Firefox 48.0.2,
- Windows Chrome 51.0.2704.103m (see below) and
- Windows Opera 39.0.2256.48.

I am not currently able to upgrade Windows Chrome to either version 52 or 53 so I am currently unsure if this problem also occurs for Windows Chrome version 52 but not 53.

**Comment by Foxandxss** [comment]
It doesn't happen for me.

![](https://puu.sh/r3VUD/1860166f08.png)

The entire plunker works perfect, all options and all routes. Also OSX.

I updated to 53 and surprise, that did happen to me *once* but I reloaded it and now it works correctly.

I believe this can be on plnkr side and not browser / Angular itself.

So what I am going to do, is keep an eye on that and investigate it with Plnkr author.

Thanks a bunch.
