### ISSUE TITLE
Broken link to EventEmitter

### ISSUE THREAD

**Issue by filiph** [angular/angular.io#2273]
This page: 
https://angular.io/docs/dart/latest/guide/template-syntax.html

Links to EventEmitter thusly:
https://angular.io/docs/dart/latest/api/core/index/EventEmitter-class.html

But it lives here:
https://angular.io/docs/dart/latest/api/angular2.core/EventEmitter-class.html

I tried to make a PR but the offending file that seems not to include the link directly (it probably does through some include) and I didn't dig any deeper.
https://github.com/angular/angular.io/blob/master/public/docs/dart/latest/guide/template-syntax.jade

**Comment by Foxandxss** [comment]
@chalin

**Comment by chalin** [comment]
Will address this soon when I sync up the Dart template-syntax page.

**Comment by chalin** [comment]
I'm updating the template-syntax page, but addressing the issue with links into the API reference will be tackled via #1895.
