### ISSUE TITLE
syntax clarity concern

### ISSUE THREAD

**Issue by mikois** [angular/angular.io#2275]
I am just learning the ropes with ng2 and from an "outsider's" perspective, the following section of the tutorial used to showcase how the code works seems to be confusing:

`const HEROES: Hero[]`
AFAIK what we are doing above is declaring a constant object HEROES of type Hero that is an array. My problem with this is that depending on how you look at it, the above declares Hero type is an array.

What follows are constructive ideas, so please do not bomb me with "invalid code".

In my humble opinion this would make more sense: ` const HEROES[]: Hero`. Here we are specifically creating a constant object that is an array and of type Hero.

I think the basic problem here is that if you look at this like a sentence (like we are supposed to in typescript), that is wrong with it is lack of specific indication of what the subject is at the moment. In other words, simply doing this `const (HEROES: Hero)[]` would solve it as well.

In case I am being stupid and/or ignorant, I'd love to hear the reasoning behind status quo.

**Comment by Foxandxss** [comment]
I hear you, but this repo is about angular 2 documentation and not really about typescript syntax. So I am closing this because there isn't anything we can do from here.
