### ISSUE TITLE
Live example in ngmodule-faq is not found

### ISSUE THREAD

**Issue by ericjim** [angular/angular.io#2276]
`/docs/ts/latest/cookbook/ngmodule-faq.html` makes reference to a live example that should be found under `/resources/live-examples/ngmodule-faq/ts/plnkr.html`. After building the docs, the corresponding folder `ngmodule-faq` is not found under the `live-examples` folder. This leads the end user to the 404 page.

cc @chalin

**Comment by Foxandxss** [comment]
I can fix, and will fix that

**Comment by ericjim** [comment]
You sir, are the best.
