### ISSUE TITLE
There are no example of how to reference tsd.d.ts in the getting started guide

### ISSUE THREAD

**Issue by fedy2** [angular/angular.io#228]
In the getting started guide, "Add Type Definition Files (optional)" section, there should be an example on how to reference the "tsd.d.ts" file for the cited editors (Visual Studio Code and Web Storm).

Something like:
In Visual Studio Code add the following line to the begin of your app.ts file:
/// <reference path="typings/tsd.d.ts" />

**Comment by wardbell** [comment]
Obsolete issue.
