### ISSUE TITLE
Compiler should detect invalid property binding

### ISSUE THREAD

**Issue by hhubik** [angular/angular.io#2310]
If possible, Angular2 compiler should detect and flag the following as an error:

Component A has an input property defined as follows:
`@Input() rows: number;`

The template in a parent component (hosting Component A) references the property `rows` as an attribute like this:
`<comp-a ... rows="5">`
instead of 
`<comp-a ... [rows]="5">`

In Angular RC6/Typescript 2.0.2, this compiles, but the value of `this.rows` in Component A is the string `"5"` as opposed the number `5`.

**Comment by Foxandxss** [comment]
This repo is for documentation. So I am closing this.
