### ISSUE TITLE
the search box in left nav menu can't response the `enter` key

### ISSUE THREAD

**Issue by asnowwolf** [angular/angular.io#2311]
when i enter `provider` as keyword and press `enter` key, it will navigate to <https://angular.io/docs/ts/latest/#!#stq=provider&stp=1>.

**Comment by Foxandxss** [comment]
Yes, that always happened and that is wrong. You shouldn't click enter, just wait for the popup to appear.

I am closing this because this has been reported in the past and there is a different solution incoming.
