### ISSUE TITLE
AfterContentInit should mention that it gets called before structural directives are being initialized

### ISSUE THREAD

**Issue by SmaugTheGreat** [angular/angular.io#2316]
The documentation for [AfterContentInit](https://angular.io/docs/ts/latest/api/core/index/AfterContentInit-class.html) states:

> Implement this interface to get notified when your directive's content has been **fully** initialized.

Note the word "fully". I think it's misleading. I spent multiple hours trying to find out why the stuff I was trying didn't work. Structural templates like *ngFor don't get resolved before the code reaches AfterContentInit, which means using `@ContentChildren(ChildComponent)` works for

```
<ChildComponent><ChildComponent></ChildComponent></ChildComponent>
```

but it fails for

```
<ChildComponent><ChildComponent *ngFor="..."></ChildComponent></ChildComponent>
```

I think this behaviour is not always intuitive (especially for people new to Angular) and should be clarified.

**Comment by Foxandxss** [comment]
Sorry that it took soooooo long to answer. Not sure how I missed it, I check all the issues once a month.

API issues belong to the angular/angular repo because that text you quote is extracted from there.

If you see that it is still an issue, please open an issue there.
