### ISSUE TITLE
Webpack tutorial fails with reflect-metadata failure when running unit tests

### ISSUE THREAD

**Issue by dparish** [angular/angular.io#2317]
I've followed the webpack introduction as closely as possible. Everything runs except the unit tests. 

When they run I get:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  reflect-metadata shim is required when using class decorators
  at /Users/dparish/dev/projects/bp3-angular-spring-seed/frontend/config/karma-test-shim.js:10519 <- webpack:///~/@angular/core/bundles/core.umd.js:697:0
```

If this works for you perhaps I fat fingered something? If I did, it would be great if the working source of the webpack introduction was hosted some someone like me can see that it should work and compare with what we created.

**Comment by Foxandxss** [comment]
Yes, will fix tomorrow.

**Comment by dparish** [comment]
@Foxandxss thank you, I'm glad it's not just me...
