### ISSUE TITLE
list of APIs is broken with current angular/angular master

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#2322]
After running `check-deploy`, dgeni seems to correctly generate `angular.io/public/docs/ts/latest/api/api-list.json`, but the page at docs/ts/latest/api/index.html doesn't list the existing APIs.

@petebacondarwin @ericjim could you have a look?

**Comment by IgorMinar** [comment]
this is because of the issue I mentioned earlier. partial fix is in #2321

**Comment by petebacondarwin** [comment]
This should be fixed now, right?

**Comment by naomiblack** [comment]
it is fixed!
