### ISSUE TITLE
Dart router docs misleading refer to TS docs

### ISSUE THREAD

**Issue by danellis** [angular/angular.io#2333]
The [Dart routing page](https://angular.io/docs/dart/latest/guide/router.html) refers the reader to the [TypeScript docs](https://angular.io/docs/ts/latest/guide/router.html):

> This chapter is not yet available in Dart. We recommend reading the TypeScript version.

The Dart implementation and usage is significant different to the TypeScript one, so the information there only leads users down a wrong path.

**Comment by chalin** [comment]
Until the new page is created (https://github.com/dart-lang/site-webdev/issues/198), we'll be directing readers to https://webdev.dartlang.org/angular/tutorial/toh-pt5.
