### ISSUE TITLE
angular dont accept <ul> inside <p>

### ISSUE THREAD

**Issue by tmleeek** [angular/angular.io#2356]
[localhost-1473916534686.txt](https://github.com/angular/angular.io/files/473887/localhost-1473916534686.txt)
![screen shot 2016-09-15 at 8 18 22 am](https://cloud.githubusercontent.com/assets/1878832/18539096/0f899cc2-7b1d-11e6-9c3c-142ee42c49bf.png)

**Comment by Foxandxss** [comment]
This is not the right repo for questions, it is only for documentation.

Now, that being said. That is **invalid** HTML. Angular 2 doesn't like invalid HTML so it refuses to work.

**Comment by tmleeek** [comment]
ok , angular should be amature and  told us that is invalid html , so we at
least get an idea, instead of totally stop working and show us a 7
unrelated error messages like a teenager , what a funny language  .
