### ISSUE TITLE
UX of the left side nav column should be improved

### ISSUE THREAD

**Issue by siva636** [angular/angular.io#2357]
The style of the left side navigation column should borrow the style from Google material design website:
https://material.google.com/ 

Some good features of the left side navigation column of the Google material design website:
(1) It can toggle
(2) Sub menus can appear without full page refresh 
(3) Sub menus are intended to the right a bit
(4) Active top menu & sub menu are colored differently

**Comment by Foxandxss** [comment]
Closing since we are migrating to a new design using material design :)
