### ISSUE TITLE
Navigation anchors are broken in advanced documentation

### ISSUE THREAD

**Issue by Martin-Wegner** [angular/angular.io#2359]
The navigation anchors are broken in advanced documentation :(

e.g. https://angular.io/docs/ts/latest/guide/ngmodule.html#!#lazy-load

**Comment by Foxandxss** [comment]
Ah, that is true. Will investigate.

**Comment by wardbell** [comment]
Thank you!  We're working on it pronto!

**Comment by chalin** [comment]
Fixed! :)
