### ISSUE TITLE
Webpack intro doc page refers to obsolete ts-loader

### ISSUE THREAD

**Issue by BrainCrumbz** [angular/angular.io#2369]
[Webpack introductory page](https://angular.io/docs/ts/latest/guide/webpack.html) currently uses *awesome-typescript-loader*, but the reported *package.json* still has an obsolete reference to *ts-loader* devDependency that can be dropped.

![ts-loader-dep](https://cloud.githubusercontent.com/assets/3185573/18563888/9209e528-7b89-11e6-9f1f-41d4312a6d53.png)

HTH

**Comment by Foxandxss** [comment]
Thanks, there is a pr (#2361) to fix it.

**Comment by BrainCrumbz** [comment]
Cool. I've searched through current/past issues, did not come to mind to search among PRs as well!
