### ISSUE TITLE
Getting started (dart) - tutorial says that transformer is not available

### ISSUE THREAD

**Issue by kasperpeulen** [angular/angular.io#237]
from: https://angular.io/docs/dart/latest/guide/setup.html
> The generated JavaScript will be smaller once Angular's transformer becomes available.

Isn't the transformer already available?

**Comment by kwalrath** [comment]
Oops.

**Comment by kwalrath** [comment]
My understanding is that this page will go away, in favor of the [Quick Start](https://angular.io/docs/dart/latest/quickstart.html). I'll leave this open until that happens.

**Comment by wardbell** [comment]
Gone.
