### ISSUE TITLE
Search result popup doesn't stay near search box.

### ISSUE THREAD

**Issue by ultrasonicsoft** [angular/angular.io#2375]
Hi There,

I have observed one defect with search result popup. 

Steps to reproduce:
1. Go to https://angular.io/docs/ts/latest/guide/forms.html - Any page where document content panel has vertical scroll bar more than one page. In this case forms.html
2. in left side bar, type something in "SEARCH DOCS.."
3. When search result pop up shows, do scroll up/down using mouse wheel.

Expected result:
Search result popup should have been fixed position below search doc text box.

Actual result:
Search result popup scroll along with page upside down.

![image](https://cloud.githubusercontent.com/assets/4145169/18575015/71c73d94-7bf0-11e6-80be-0cbb322689db.png)

**Comment by naomiblack** [comment]
should be fixed now.

**Comment by ultrasonicsoft** [comment]
I am still able to reproduce this issue.
