### ISSUE TITLE
Getting started (dart) - style.css file is not included

### ISSUE THREAD

**Issue by kasperpeulen** [angular/angular.io#238]
minor nit maybe, but the index.html file depends on style.css that is not included in the tutorial

not sure, if this was intended, the screenshot also uses a style.css file

Maybe link to a github repo for the full source? Or just remove the style.css reference?

**Comment by kwalrath** [comment]
My understanding is that this file will go away, in favor of the [Quick Start](https://angular.io/docs/dart/latest/quickstart.html). I'll leave this open until that happens.
