### ISSUE TITLE
Quickstart title is "Angular"

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#2385]
@alexwolfe - Quickstart "lost" its title in https://github.com/angular/angular.io/commit/65db6b9268310d4811a5d37069aa1e59489183e7 so that now it shows up as the default title "Angular". Was this intentional?

cc @naomiblack @ericjim @Foxandxss 

p.s. Creating this issue since @Foxandxss says that he can't see the commit comment.

**Comment by Foxandxss** [comment]
yes, I feel like this title change is a bit weird.

**Comment by alexwolfe** [comment]
@chalin @Foxandxss good catch, the title should def be "Quickstart", my fault guys. :P

**Comment by chalin** [comment]
Np, thanks for confirming.
@Foxandxss, I'll fix this along with other changes I need to make.
