### ISSUE TITLE
Getting started (Typescript) tutorial missing "npm install traceur" step?

### ISSUE THREAD

**Issue by ultrasonicsoft** [angular/angular.io#239]
Hi,

I was going through each step given in updated getting started page below:
https://angular.io/docs/ts/latest/guide/gettingStarted.html

When I ran "live-server --open=src" command to load website, browser couldn't load page as it didn't find traceur-runtime.js file.

I think the npm install package command given in tutorial is missing for traceur package.
Currently npm install command is as below

    npm install --save angular2@2.0.0-alpha.37 systemjs@0.19.2

As alpha 38 doesn't require traceur anymore, I think given step on website should be updated with either of below command

    npm install --save angular2@2.0.0-alpha.38 systemjs@0.19.2

Or

    npm install --save angular2@2.0.0-alpha.37 systemjs@0.19.2 traceur

Thanks!

Balram

**Comment by gnomeontherun** [comment]
Angular no longer requres Traceur, so instead of adding it to the project the reference should be removed.

**Comment by ultrasonicsoft** [comment]
Agree.
But this step should be updated on website so that newbie people can
understand.

**Comment by wardbell** [comment]
Old.
