### ISSUE TITLE
obsolete help and resource pages?

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#2390]
@alexwolfe @kwalrath @naomiblack are these pages still relevant?
- https://angular.io/docs/ts/latest/help.html
- https://angular.io/docs/ts/latest/resources.html

Each of these pages exists for TS, Dart and JS.

Note that we have a global
- https://angular.io/resources/

cc @ericjim

**Comment by Foxandxss** [comment]
I am closing this Patrice. Since we are migrating, we are cherry picking what we want to translate.
