### ISSUE TITLE
Systemjs error trying to use current version (alpha39) in quickstart

### ISSUE THREAD

**Issue by filipesilva** [angular/angular.io#241]
The current quickstart uses alpha28 and doesn't seem to work when updating  `https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js` to `https://code.angularjs.org/2.0.0-alpha.39/angular2.dev.js`.

A console error is generated in the browser:

```
GET https://registry.jspm.io/app.js 404 (Not Found)
Potentially unhandled rejection [3] Error loading "app" at https://registry.jspm.io/app.js
Not Found: https://registry.jspm.io/app.js (WARNING: non-Error used)
```

Updating `traceur` and `system` and changing the import to `/app` seems to fix it though.

I'll submit a PR.

**Comment by ericmartinezr** [comment]
@filipesilva just in case, since alpha38 you don't need traceur anymore.

**Comment by filipesilva** [comment]
Thanks for the heads up, I did not know that. Lemme update the PR.

**Comment by naomiblack** [comment]
Apologies -- that doc is soon to be obsolete. We have a separate project (with several authors) working on large-scale improvements to the docs, so it's not actually all that useful to submit small fixes like this.

You should see some big improvements very soon.

**Comment by filipesilva** [comment]
Oh nice! What's the project repo?
