### ISSUE TITLE
Sidenavbar search-box result window/popup scrolls up-down with scrolling of rightside window

### ISSUE THREAD

**Issue by micronyks** [angular/angular.io#2411]
**NOTE**: I have observed this issue with **desktop screen**.

Please follow steps to reproduce mentioned problem.

1). Go **angular.io**.
2). Click on **docs tab**
3). Click on **Quickstart link** (left side).
4). Scroll **right-side window** to half of the screen.
5). Type in something `eg. DOM` in **search box** given at **sidenavbar**
6). As result window/popup appears, scroll **right-side window** up or down.

**Issue** : You will notice that **search result window/popup** also goes up and down.

**Expectation**:  **_It should be fixed exact below to search box_**.

**Comment by chalin** [comment]
I confirm that I can reproduce the issue. @alexwolfe, can you investigate? cc @ericjim

**Comment by Foxandxss** [comment]
We are migrating to a new design, so we will make sure this doesn't happen.
