### ISSUE TITLE
Tutorial & Advanced Documentation are not in alignment

### ISSUE THREAD

**Issue by ShaneCourtrille** [angular/angular.io#2412]
When you complete the tutorial you end up with a code base that doesn't match what's expected by the Advanced Documentation section.

The Advanced Documentation uses Crisis Center and Hero List where as the Tutorial uses Dashboard and Heros.  It would be nice if these were in sync so you could use what you had created from the Tutorial and add on chunks as you go through the Advanced Documentation.  

Minor but still nice to have at some point.

**Comment by Foxandxss** [comment]
The problem is that certain tutorials could use variations of what the tour of heroes provides, so reusing part of tour of heroes is not always possible.

We try to make all guides to match our heroes style, but it is better to leave each guide to have freedom to implement what is best for it.

**Comment by wardbell** [comment]
I hear you. TBH, we've got higher priorities than striving for perfect alignment of our samples. As @Foxandxss says, our goal is _thematic_ consistency (so we're not repeatedly explaining the sample use case). We do not aspire to cross-sample _code_ consistency.
