### ISSUE TITLE
Tutorial link broken (HTTP services, TypeScript)

### ISSUE THREAD

**Issue by neeklamy** [angular/angular.io#2419]
In the (really excellent) tutorial for writing HTTP services ([HTTP tutorial on the Angular site](https://angular.io/docs/ts/latest/tutorial/toh-pt6.html)), there’s a link to the Observables section later on:

    We'll learn about [Observables](#observables) later in this chapter.

(Located here: [public/docs/ts/latest/tutorial/toh-pt6.jade line 156](https://github.com/angular/angular.io/blob/693f6ae462d22a1ff96da46b06a2cf2d60a28a3f/public/docs/ts/latest/tutorial/toh-pt6.jade#L156))

But the link is malformed. Here’s where it should take us to:

    ## !{_Observable}s
(Located here: [public/docs/ts/latest/tutorial/toh-pt6.jade line 352](https://github.com/angular/angular.io/blob/693f6ae462d22a1ff96da46b06a2cf2d60a28a3f/public/docs/ts/latest/tutorial/toh-pt6.jade#L352))

This works as expected (but looks a bit ugly):

    We'll learn about [Observables](#-_observable-s) later in this chapter.

**Comment by chalin** [comment]
Glad that you are enjoying the tutorial. Thanks for reporting the broken link.
