### ISSUE TITLE
Can we remove the cardboard page?

### ISSUE THREAD

**Issue by ericjim** [angular/angular.io#2423]
@naomiblack It appears we have an abandoned page on https://angular.io/cardboard/ since we are in the process of migrating stuff. Do you think we could get rid of this page? The amount of effort to port this isn't a lot, but it is one more page to bundle and maintain. It also has broken styles in narrow displays.

cc @chalin @alexwolfe

**Comment by naomiblack** [comment]
I think we can get rid of this in the migration.
