### ISSUE TITLE
[API Page Generation] ContentChild Apit doc page is empty

### ISSUE THREAD

**Issue by ocombe** [angular/angular.io#2429]
The page https://angular.io/docs/ts/latest/api/core/index/ContentChild-decorator.html of the API documentation is empty, it should contain this: https://github.com/angular/angular/blob/2.0.0/modules/%40angular/core/src/metadata/di.ts#L232-L270

ContentChildren (which is in the same file) works fine: https://angular.io/docs/ts/latest/api/core/index/ContentChildren-decorator.html

**Comment by petebacondarwin** [comment]
This  is because the source code docs are in the wrong place.

See this commit for a similar fix by @vsavkin for `ContentChildren` https://github.com/angular/angular/commit/b6287ccc5126da9c1a052bd28b3a9e2743f67eae
