### ISSUE TITLE
sidebar scrolling issue in firefox browser

### ISSUE THREAD

**Issue by emostafa** [angular/angular.io#2432]
the sidebar is working fine in chrome, but in firefox it doesn't work as expected,
for example "webpack: an introduction" is not visible in firefox, i keep scrolling but it doesn't show up, same to "Cookbook" menu item when the advanced menu is opened, i cant scroll down to it.

browser: firefox version 48

screenshot: 

[![Screen Shot 2016-09-21 at 5.58.10 PM.png](http://s22.postimg.org/z63ihrxfl/Screen_Shot_2016_09_21_at_5_58_10_PM.png)](http://postimg.org/image/5qxu8rsvx/)

in the above image i can barely scroll to advanced, but that's the end of it, can't scroll to "Cookbook"

**Comment by chalin** [comment]
cc @ericjim

**Comment by emostafa** [comment]
issue still exists

**Comment by Foxandxss** [comment]
We are migrating to a new design, 200% new. I will make sure this doesn't happen there.
