### ISSUE TITLE
Broken Link to "Testing"

### ISSUE THREAD

**Issue by cosban** [angular/angular.io#2434]
Link in question: https://angular.io/docs/ts/latest/testing/index.html

Location of link: https://angular.io/docs/ts/latest/guide/dependency-injection.html#!#testing-the-component

At "Learn more in _Testing_"

**Comment by cosban** [comment]
perhaps it is referencing https://angular.io/docs/ts/latest/guide/testing.html

**Comment by Foxandxss** [comment]
Seems to be fixed.
