### ISSUE TITLE
User-Input demo (typescript) page has typo for NgIf 

### ISSUE THREAD

**Issue by ultrasonicsoft** [angular/angular.io#244]
Hi,
The Getting started tutorial has section called User-Input at below url:
https://angular.io/docs/ts/latest/guide/user-input.html

There is a typo for NgIf which mentioned as NIf. Please update below line from 

    directives: [NgFor, NIf]
To

    directives: [NgFor, NgIf]

Thanks!

**Comment by jannickv** [comment]
Submitted a PR to fix this.

**Comment by wardbell** [comment]
Long gone
