### ISSUE TITLE
Docs for <ng-container>

### ISSUE THREAD

**Issue by laco0416** [angular/angular.io#2442]
`<ng-container>` is a feature released in the final, but not documented in angular.io.

The element is not an angular *directive*/*component*, and doesn't have its own class. so maybe it needs a special documentation.
I think it should be documented as a template-syntax. 

* **Angular version:** 2.0.0

**Comment by Foxandxss** [comment]
There is an issue already. Thanks.

**Comment by laco0416** [comment]
oh sorry. is it https://github.com/angular/angular.io/issues/2303 ?

**Comment by Foxandxss** [comment]
Yes

**Comment by laco0416** [comment]
Thanks. It was not easy to find that...

![image](https://cloud.githubusercontent.com/assets/1529180/18744191/ceb43302-80f7-11e6-838e-7ec1c8602346.png)

**Comment by Foxandxss** [comment]
The search box gave you the answer, that is not hard!

Anyway, if you feel like you can fix it, please open a PR.
