### ISSUE TITLE
quickstart project/tutorial not explained deeply enough...

### ISSUE THREAD

**Issue by razorree** [angular/angular.io#2454]
I've used files from quickstart project, i've copied them to:
mypro\src\main\resources\public (as this is a place for public files in my Spring-Boot project)

also i've run npm install (there is node_modules folder within public folder now - not sure if it's a good idea to store 90MB of data in a public folder....)

Where should i place tsconfig.json ? in mypro\src\main\resources\public together with other files ?
However typescript plugin from Eclipse doesn't want to pickup app*.ts files.... (plugin works with simple typescript examples).

Quickstart tutorial lacks explanation of project structure and configuration and i guess that keeping node_modules (sources, configuration etc.) in a public folder is a bad habit.
In AngularJS1.4 it was enough to 'import' files with a < script src=... > tag in index.html
I'm confused now...

**Comment by pauldubois777** [comment]
You can find the whole Quickstart app here:  [Angular 2 Quickstart](https://github.com/angular/quickstart)

**Comment by razorree** [comment]
yes, i know, i took code from it.

but how to use it/integrate with Java backend project ? i dont want to use nodejs

**Comment by mattdistefano** [comment]
>but how to use it/integrate with Java backend project ? i dont want to use nodejs

In fairness, that's a little beyond the scope of a quickstart, no?

**Comment by Foxandxss** [comment]
And beyond the scope of this issue tracker I am afraid.
