### ISSUE TITLE
Migrate Angular.io to Angular2

### ISSUE THREAD

**Issue by martinmcwhorter** [angular/angular.io#2456]
Now that Angular2 is out it seems like it is time to migrate angular.io to Angular2.

**Comment by Foxandxss** [comment]
Please, use the search, that topic is being discussed in different issues.

**Comment by martinmcwhorter** [comment]
Yes. I used search first on these term combinations "migrate angular2"
"migrate angular 2" "migrate" "angular2" "angular 2".

**Comment by Foxandxss** [comment]
You missed the "Upgrade" one :P

https://github.com/angular/angular.io/issues/1409
