### ISSUE TITLE
Typo in testing guide

### ISSUE THREAD

**Issue by mattdistefano** [angular/angular.io#2457]
`The tester creates a test instance of the class with new, supplying test doubles for the constructor parameters as needed, and then probes the test instance API surface.`

The "with new" doesn't make much sense - probably a typo?

**Comment by Foxandxss** [comment]
No, it means that you do a `new` on it.

`new Foo()` vs `Foo()`

**Comment by mattdistefano** [comment]
Ah gotcha.

TBH even w/ that explanation I find it a little confusing. Is the point just that, in isolated tests, you are manually instantiating the class vs. letting the test platform give you an injected instance?

**Comment by Foxandxss** [comment]
I hear you, but it is a really common expression.
