### ISSUE TITLE
Template reference var scope guidance doesn't match framework's actual behaviour

### ISSUE THREAD

**Issue by variable-content** [angular/angular.io#2458]
In the docs: https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ref-vars

It mentions:

"We can reference a template reference variable on the same element, on a sibling element, or on any child elements."

However, it appears as though a template reference variable can be accessed outside of a sibling scope: 
http://plnkr.co/edit/pBHQZ3wKNVroRvOLnskh?p=preview

If this is expected behaviour, the docs should be updated to reflect that.

**Comment by wardbell** [comment]
You are correct. Have merged a correction in PR #2458
