### ISSUE TITLE
The module ... was bootstrapped, but it does not declare "@NgModule.bootstrap" components nor a "ngDoBootstrap" method

### ISSUE THREAD

**Issue by squarewave24** [angular/angular.io#2466]
getting this error after following the latest Quick Start example from scratch. 

according to the FAQ this shouldn't be needed? 

> 
> Most application developers won't need to add components to the entryComponents.
> 
> Angular adds certain components to entry components automatically. Components listed in @NgModule.bootstrap are added automatically. Components referenced in router configuration are added automatically. These two mechanisms account for almost all entry components.

not quite sure how to troubleshoot it. The entire error looks like this: 

> core.umd.js:3468 Error: The module AppModule was bootstrapped, but it does not declare "@NgModule.bootstrap" components nor a "ngDoBootstrap" method. Please define one of these.
>     at PlatformRef_._moduleDoBootstrap (core.umd.js:6966)
>     at eval (core.umd.js:6928)

main.ts

```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';
const platform = platformBrowserDynamic();
platform.bootstrapModule(AppModule);
```

app.module.ts

```
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

@NgModule({
  imports:      [ BrowserModule ]
})
export class AppModule { }
```

**Comment by Foxandxss** [comment]
Continue reading it.

**Comment by squarewave24** [comment]
ahh, yes there is a bit that goes back to app module.ts 

adding these lines fixed it: 

import { AppComponent }   from './app.component';
declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
