### ISSUE TITLE
Angular.io broken on mobile

### ISSUE THREAD

**Issue by arikrak** [angular/angular.io#2471]
As pointed out [on Reddit](https://www.reddit.com/r/Angular2/comments/54d35o/angular2_docs_need_fixing_does_this_for_every_page/), the Angular.io site is broken on mobile. It looks like the `<div class="banner">` on top should have its fixed height removed.

**Comment by arikrak** [comment]
https://github.com/arikrak/angular.io/commit/16c05fde7401d5cedc12dddc91f663e576935dde

**Comment by chalin** [comment]
cc @alexwolfe @ericjim

**Comment by arikrak** [comment]
https://github.com/angular/angular.io/pull/2473
