### ISSUE TITLE
Angular2 Dart Heroes tutorial is missing @Output

### ISSUE THREAD

**Issue by sturmf** [angular/angular.io#2474]
In the Angular2 Dart heroes tutorial at one point it is missing the @Output() decorator.

https://angular.io/docs/dart/latest/guide/template-syntax.html#!#sts=Custom%20Events%20with%20EventEmitter

Of course I copied and pasted that part :-)

Instead of: 

`final deleteRequest = new EventEmitter<Hero>();`

Write:

`@Output() final deleteRequest = new EventEmitter<Hero>();`

**Comment by chalin** [comment]
Actually, it is declared an output via the `@Component` `outputs` list; see https://webdev.dartlang.org/angular/guide/template-syntax#declaring-input-and-output-properties

cc @kwalrath
