### ISSUE TITLE
can not install for: Linux 64-bit; node 5 and node 6

### ISSUE THREAD

**Issue by aplatypus** [angular/angular.io#2479]
For some reason that's beyond my modest ken, I may not install Angular r2 on Linux (Debian) 64-bit

Initial attempts followed this pattern:

```
$ sudo npm  -g --save install 'angular'
$ #  as well as alternative that also don't work
$  sudo npm  -g install 'angular'
$  sudo npm  -g install '@angular'
$  sudo bower -g --allow-root install '@angular'
```
The reason I took to bower is because there was a recommendation to use bower -- But, initially I just want the local global repository updated.  _Anyway_ using the update or install for a local project ALSO doesn't work.

Oh I ought to mention that initially I used the 
     ``sudo npm -g update angular``
command form.

I began this exercise with node v5 and matching npm -- Eventually I used apt-get to update to node v6.6, now.

I was _helped_ by someone who said I should use "@angular" for updates.  

The _best_ I get is a anguar 1.15 or a variety of NOENT messages.

**Question ...** 
1.  What is the correct version for the command:

```
 sudo npm  -g --save install 'angular'
##               ~ OR ~
 sudo npm  -g --save install '@angular'
##               ~ OR ~
 sudo npm  -g --save install 'angular@2'
```

I haven't included different _version_ strings attempted; nothing better than 1.5 is upgraded and I get NOENT responses from _all_ other variations.

Other 'standard' bits of Javascript middleware appear to be installing FINE . .. Might there been some kind of version or release numbering mismatch?  

- jquery
- yeoman
- grunt
- browserfify

**Comment by Foxandxss** [comment]
You tried all combinations but the right one.

First of all, angular is not a global package, so you need to drop the `-g`.

Then angular is separated in different packages like `@angular/core`, `@angular/common` so you would need to do stuff like `npm i --save @angular/core @angular/common ...`.

The best thing you could do to follow the guides in this page is to clone the [quickstart](https://github.com/angular/quickstart) that has everything in place.

Cheers.
