### ISSUE TITLE
Angular 2 Quick Start package.json in docs does not match that in repo

### ISSUE THREAD

**Issue by Bucabug** [angular/angular.io#2486]
The package.json specified in the Create Configuration Files section of the quickstart guide:

https://github.com/angular/angular.io/blob/master/public/docs/_examples/quickstart/ts/package.1.json

Does not match the package.json in the latest quickstart repo:

https://github.com/angular/quickstart/blob/master/package.json

This leads to a breaking build if following from the Quick Start guide onto the Tour of Heroes tutorial as you will have "angular2-in-memory-web-api" in your package.json whereas this package has been renamed to "angular-in-memory-web-api".

**Comment by Foxandxss** [comment]
Thanks. Will fix
