### ISSUE TITLE
Bad font for code snippets

### ISSUE THREAD

**Issue by alirezamirian** [angular/angular.io#2500]
When I was reading DI guide, I was struggling with myself why `OldLogger` is spelled `oldLogger`! I was about to file a bug until I copied that and pasted into some editor and suddenly the `oldLogger` became `OldLogger`!

![image](https://cloud.githubusercontent.com/assets/3150694/18934382/3e5f22f0-85e6-11e6-905b-5c91c739feed.png)
I'm not saying it's indistinguishable from its lowercase, but I prefer a font in which uppercase and lowercase letters are more different.

**Comment by Foxandxss** [comment]
What OS are you using? In Mac (and chrome) it is quite better:

![](https://puu.sh/rE3p9/bf49e547dc.png)

**Comment by alirezamirian** [comment]
You are right, it's actually quite ok on Mac. It's actually a different font I guess.
I'm using Chrome on Windows.

**Comment by alirezamirian** [comment]
When I remove the **Monaco** font for `code` in styles, nothing happens. it seems that it's falling back to second or even third font family which are **Lucida Console** and **monospace**. 
Maybe Mac has Monaco by default but Windows doesn't have it and you need to load it by CSS.

**Comment by Foxandxss** [comment]
We are moving to a new design. When we do that, if you think it is still a problem (we use different fonts). Please open a new issue.
