### ISSUE TITLE
Router resolver

### ISSUE THREAD

**Issue by manofearth** [angular/angular.io#2503]
Created from https://github.com/angular/angular/issues/11607

Resolving doesn't whork if resolver returns not closed observable

```ts
resolve():Observable<any> | Promise<any> | any {
        let subject = new BehaviorSubject<number>(777);

        return subject.asObservable(); //won't work
        return subject.asObservable().first(); //will work
}
```

Please, document it somewhere. May be even [here](https://angular.io/docs/ts/latest/guide/router.html#!#resolve-guard)

**Comment by manofearth** [comment]
Same issue: https://github.com/angular/angular.io/issues/2358

**Comment by vicb** [comment]
> Same issue: #2358

No need to post duplicate issues, please close this one
