### ISSUE TITLE
Bug in Windows: rollup.js config file.

### ISSUE THREAD

**Issue by kaplan81** [angular/angular.io#2507]
Following this cookbook:
https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

And executing this command:
node_modules/.bin/rollup -c rollup.js 

It turns out that, at least on Windows environment, it just opens the file rollup.js in your default code editor.

It should package the Angular 2 application into the file ./dist/build.js

My conclusion here is that the config file cannot be called rollup.js, I do not know why.
I changed it providing a random name: rollup-config.js
Then it worked perfectly :)

**My environment:**
Windows 8 64bit
Visual Studio Code 1.5.3
Node: 6.4.0
npm 3.10.3
Angular version: 2.0.0
Typescript 2.0.3

**Comment by georgeedwards** [comment]
I've found this too - exactly the same result!

**Comment by Foxandxss** [comment]
That is a bug (node or npm or whatever) in Windows.

We are changing that in a separate PR to have a different name.

So I close this and we continue at #2496
