### ISSUE TITLE
Tutorial part 7 "HTTP" Issue

### ISSUE THREAD

**Issue by thefliik** [angular/angular.io#2509]
Hi, just a heads up:

I was just completing the "HTTP" section of the "Tour of Heroes" tutorial on Angular.io and the instructions told me to import from "angular-in-memory-web-api" however the module found in `node_modules` (automatically created for me during the course of the tutorial) is titled "angular2-in-memory-web-api". Updating the text to import from "angular2-in-memory-web-api" fixed the error I was experiencing.

The instructions in question are found in the [Simulating The Web API](https://angular.io/docs/ts/latest/tutorial/toh-pt6.html#simulating-the-web-api) section

Originally:
`import { InMemoryWebApiModule } from 'angular-in-memory-web-api';`

Correction:
`import { InMemoryWebApiModule } from 'angular2-in-memory-web-api';`

Thanks!!

**Comment by johnthad** [comment]
`angular2-in-memory-web-api` is set correctly in `package.json`. It is _incorrect_ in `systemjs.config.ts`, `app/app.module.js`, and `app/in-memory-data.service.ts`. In these locations it reads `angular-in-memory-web-api`, missing the `2` (in fact, it's wrong in 3 places in `systemjs.config.ts`). Make these changes and the demo runs.

**Comment by Foxandxss** [comment]
Package was renamed to `angular-in-memory-web-api` recently.

If you started the tutorial before that, just go to the quickstart and get the new version.
