### ISSUE TITLE
Dart documentation footer is floating in the middle of the page

### ISSUE THREAD

**Issue by thso** [angular/angular.io#2510]
<img width="981" alt="ng2_dart_doc" src="https://cloud.githubusercontent.com/assets/16721021/18973164/245e89e6-8694-11e6-93e3-6489f071d77f.png">

I traced this down to be due to the `styles.css` being imported from dartdoc:
https://github.com/dart-lang/dartdoc/blob/f8cd4c8ae8f733be98ffa0e3d14725b341c692c6/lib/resources/styles.css#L328

Removing the `position:absolute` does the trick.

**Comment by chalin** [comment]
cc @ericjim

**Comment by chalin** [comment]
@thso - could you open an issue over `dartdoc`?

cc @kwalrath

**Comment by chalin** [comment]
Actually, I think I've found a way to resolve this by some other means. Let me test that next week and get back to you.
