### ISSUE TITLE
Routing guide - Milestone #3 - Service isolation

### ISSUE THREAD

**Issue by nponiros** [angular/angular.io#2527]
I find that part to be a bit misleading and confusing compared to the providers part of the NgModule guide. Especially this line:

"This limits the scope of the CrisisService to the Crisis Center routes. No module outside of the Crisis Center can access it."

My understanding is that any provider defined in any module with the exception of asynchronously loaded modules is accessible to the entire application.

I also find this part a bit confusing:

"Second, we can delay loading this service into memory until we need it. We can remove it from the application launch bundle, reducing the size of the initial payload and improving performance."

My understanding here is that I can only lazy load a whole module and not a provider so I don't really understand if this sentence means that we have other ways to lazy load a provider or if it has to do with the last sentence saying: "We can load it optionally, asynchronously with the other Crisis Center components if and when the user begins that workflow.". Perhaps the sentence needs to be a bit re-written to make the intention clearer.

[Link to the guide](https://angular.io/docs/ts/latest/guide/router.html#!#service-isolation)

**Comment by wardbell** [comment]
The statement 
>This limits the scope of the CrisisService to the Crisis Center routes. No module outside of the Crisis Center can access it."
is incorrect for precisely the reasons you state. We are doing a small rewrite of this chapter and the modules part in particular in PR #2478 and I'll make sure this is corrected if it hasn't been already.

I agree that the statement about service loading needs to be revisited at the same time.

Thanks.

**Comment by wardbell** [comment]
In the re-write we dropped the entire "Service Isolation" section. It's not relevant to routing and requires a discussion best left to the NgModule chapter. Closed by PR #2478
