### ISSUE TITLE
Docs Error: Module Providers Scope

### ISSUE THREAD

**Issue by alindsay55661** [angular/angular.io#2532]
Migrated from https://github.com/angular/angular/issues/12047

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The docs are inconsistent with regards to providers and module scope. Here are two contradictory explanations:

From https://angular.io/docs/ts/latest/guide/ngmodule.html#!#providers

"The ContactService provider is application-scoped because Angular registers a module's providers with the application's root injector... ...We might expect Angular to offer a module-scoping mechanism to enforce this design. It doesn't. Angular module instances, unlike components, do not have their own injectors so they can't have their own provider scopes."

From https://angular.io/docs/ts/latest/guide/router.html#!#child-routing-component

"The CrisisService is neither needed nor wanted outside the Crisis Center domain. Instead of registering it with the AppModule's providers — which makes it visible everywhere — we register the CrisisService in the CrisisCenterModule providers array... ...This limits the scope of the CrisisService to the Crisis Center routes. No module outside of the Crisis Center can access it."

**Expected behavior**
Either the provider scope is limited to the module its declared in or not. I expect the docs to reflect the correct behavior everywhere. Which one of these paradigms is the real McCoy?

**Angular version:** 2.0.0

**Comment by wardbell** [comment]
I think you missed the critical difference between the _eagerly_ loaded `AppModule` and the lazy_ loaded `CrisisCenterModule`. That difference resolves the apparent contradiction.

We talk about this difference in numerous places including the FAQs. Do you have a specific recommendation about how we can make that more clear?

**Comment by alindsay55661** [comment]
Closing the issue? Seems to me I am not the only one that feels this is unclear: https://github.com/angular/angular.io/issues/2527

> I think you missed the critical difference...

A sign that the docs need work.

I would clarify this by explicitly stating everywhere that module providers can be scoped. In other words, delete the following:

"We might expect Angular to offer a module-scoping mechanism to enforce this design. It doesn't. Angular module instances, unlike components, do not have their own injectors so they can't have their own provider scopes."

This is false based on what you are now telling me as Angular does provide a module-scoping mechanism--the loading paradigm. 

> We talk about this difference in numerous places including the FAQs. Do you have a specific recommendation about how we can make that more clear?

Yes, talking about this in the FAQ would be ok if you linked to the FAQ every time you mention module provider scope. Because the loading paradigm *critically* alters scope behavior you need to disclose that *any time you talk about scope*. Without referencing the loading paradigm when talking about module provider scope, you are simply saying that module providers do AND do not have their own scope.

**Comment by falconmick** [comment]
I also agree that this is confusing and imo bad practice. What if later for whatever reason a developer decided to make the module eagerly loaded. All of a sudden the app blows up. 

Also if we provided the service via the root level component that the router defines, doesn't that scope it to only that component and all directives, pipes, components and (this is the one im not 100% on) services?

**Comment by wardbell** [comment]
@alindsay55661: My statement isn't false. It's true. You ONLY get something resembling module scoping if you lazy load the module. And that is not an aspect of modules, it's an aspect of how the router works.

I agree that this is not as easy to follow as I would like.  I do not have a better way of expressing it at this time. With respect I must say that your proposal does not strike me as sufficiently better. Others have asked me to remove much of the repetition. 

@falconmick Suppose you do eagerly load a module that you formerly loaded lazily? Something "bad" (i.e., breaking) happens ONLY if your feature module deliberately tried to shadow (replace) a provider defined in the root injector. Now you may have a reason to do that! But I'll bet it is rare and that you'll be aware that you did that intentionally ... in which case you will not be tempted to eagerly load that module.

There is very little risk from having a feature-specific provider in the Feature Module promoted to the root injector. Who is going to know? Who (outside of the feature) will inject it?  You can object on purist grounds but there is little to worry about in practice. And if you are a purist, you will have followed my advice to purists and provided the service in the top component for that feature. 

If you added a provider to the root level component (`AppComponent`), that service will be available to every routed component from an _eagerly loaded module_.

Lazy loaded modules are different. They do NOT have access to anything provided in the `AppComponent` (or its subcomponents). They only have access the root injector services (above `AppComponent`) and the provided services within the context of the lazy loaded module.

I wish I knew an easy way to say this. If you wish to challenge the design, please send your comments to the `angular` site.

**Comment by alindsay55661** [comment]
> My statement isn't false. It's true.

@wardbell Sorry for the confusion, I wasn't referring to your statement. I was referring to the following line from the documentation (this could be your statement if you are the only author):

> We might expect Angular to offer a module-scoping mechanism to enforce this design. It doesn't.

Since module scoping is dictated via the loader this line isn't correct. Or if argued to be correct, it is misleading. Generally if the documentation is difficult to write it indicates a problem with the design, so I can appreciate your challenge. In your case I would push back on those asking to remove documentation... a very odd request for a new framework with a large degree of ceremony.
