### ISSUE TITLE
Conflict in Style Guide between app structure and demo 

### ISSUE THREAD

**Issue by pthalacker** [angular/angular.io#2533]
In the Style Guide, the Module and Structure section (https://angular.io/docs/ts/latest/guide/style-guide.html#!#app-structure-and-angular-modules ) shows the app.component.ts file in src/app
But the demo code for app.module.ts, which resides in the root of src has this line of code
`import { AppComponent }   from './app.component';`

Either the app structure should be changed or the line of code should be
`import { AppComponent }   from './app/app.component';`

**Comment by wardbell** [comment]
Please reference the specific place.

I'm not following you. If`AppModule` and `AppComponent` source files are siblings, then `import { AppComponent } from './app.component';` is correct.

**Comment by pthalacker** [comment]
https://angular.io/docs/ts/latest/guide/style-guide.html#!#app-structure-and-angular-modules

Sorry.  I cut and pasted from an issue incorrectly posted in the main angular project.  Misses the most important part

**Comment by wardbell** [comment]
Ah. Ugh

**Comment by wardbell** [comment]
Closed by #2535
