### ISSUE TITLE
dgeni: footer link in API docs is generated from the dev branch, not 2.0.x

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#2536]
This is fixed on the live site via the temporary means of editing the angular/angular package.json to manually set version to "2.0.1".

What's odd here is that VersionInfo for the *cheatsheet* is set correctly. So why isn't the API doc processor getting it right?

API doc shows version link as: `https://github.com/angular/angular/tree/2.1.0-beta.0/modules/@angular/http/src/backends/xhr_backend.ts#L194-L232`

@petebacondarwin can you have a look? I am guessing this is a quick fix for you...

**Comment by petebacondarwin** [comment]
The version is acquired by the `git` dgeni-package from the package.json. So it makes sense that the version number will be the same as that found in the package.json.

**Comment by petebacondarwin** [comment]
The only difference between the version shown in the API docs compared to the cheatsheet could be that in API templates we have :

```
{$ versionInfo.currentVersion.isSnapshot and versionInfo.currentVersion.SHA or versionInfo.currentVersion.raw $}
```

whereas in the cheatsheet we have

```
{$ doc.version.currentVersion | json | ... $}
```
(where `doc.version` is the same `versionInfo` object as above)
