### ISSUE TITLE
search results overlay not working

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#2537]
swiftype is supposed to be providing an overlay with the results when you hit "enter" in the search widget, but it never shows up. This seems likely to be related to some of our other css overrides.

@alexwolfe could you investigate?

**Comment by alexwolfe** [comment]
@naomiblack so apparently this bug is caused by a conflict of some sort between angular and swyftype, I've confirmed this on my local env. I'll continued to dig in and let you know when I have a fix. Installed 2.0 and have it working locally as well.

**Comment by alexwolfe** [comment]
Ok, closing this one. Reopen if you feel like we haven't addressed it.
