### ISSUE TITLE
Angular2 Tutorial HTTP Page Typo

### ISSUE THREAD

**Issue by joeyjgarcia** [angular/angular.io#2540]
On this page of the Tour of Heroes Tutorial
https://angular.io/docs/ts/latest/tutorial/toh-pt6.html

There is mention of an import in the app/app.module.ts (v2) file: 
import { InMemoryWebApiModule } from 'angular-in-memory-web-api';

It should be:
import { InMemoryWebApiModule } from 'angular2-in-memory-web-api';

per the package.json that has this dependency.
"angular2-in-memory-web-api": "0.0.18",

Also, I am getting an error on the

**Comment by Foxandxss** [comment]
It is not a typo, we renamed the library not long ago.

**Comment by joeyjgarcia** [comment]
That is fine then update the tutorial so it is accurate.

**Comment by enzeart** [comment]
The tutorial doesn't work until I update the import line to read as 'angular2-in-memory-web-api' which is different from what is in the tutorial itself. @Foxandxss what is your suggested solution to the issue if you're saying that this is not a type?

**Comment by Foxandxss** [comment]
Still happening to you today? Tell me more, what are you doing, etc.

**Comment by enzeart** [comment]
@Foxandxss I was going through the tutorial and got to part 7 which goes over HTTP. I go from the "Simulate the web API" section to the end of "Heroes and HTTP" where the documentation says "Refresh the browser. The hero data should successfully load from the mock server". This was not the case. The browser instead display the error message "C:/Users/enzea/Desktop/angular-tour-of-heroes/src/app/app.module.ts (16,38): Cannot find module 'angular-in-memory-web-api'".

The line causing the issues was "import { InMemoryWebApiModule } from 'angular-in-memory-web-api';". Some googling brought me to this issue thread where I saw the proposed solution from @joeyjgarcia .
Changing this to "import { InMemoryWebApiModule } from 'angular**2**-in-memory-web-api';" remedied the situation immediately.

**Comment by Foxandxss** [comment]
is your package.json modern? Sounds like a couple of months old.

**Comment by enzeart** [comment]
The package.json that I have is the one that was generated by the cli when I started the tutorial. Here are the contents:

```json
{
  "name": "blep",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
```

**Comment by Foxandxss** [comment]
You are missing the `angular-in-memory-web-api`

**Comment by enzeart** [comment]
Ok thanks! I don't recall seeing anything in the tutorial instructing me to install that. If it's missing then I expect that others may face the same issue while going through the tutorial.

**Comment by Foxandxss** [comment]
It does not because it comes with the quickstart already. We should add a note or something.
