### ISSUE TITLE
Add theme-color meta tag site wide

### ISSUE THREAD

**Issue by amitmerchant1990** [angular/angular.io#2541]
Hi guys,

As angular.io is built upon the principles of material design of Google, I slightly feel the site should have the theme-color for better looking browsing experience on mobiles and would look like below.

![](https://wolstenhol.me/sites/default/files/articleimages/theme-color_0.png)

We just need to add `<meta name="theme-color" content="#999999" />`. Of course, the color of your choice.

Thanks!

**Comment by Foxandxss** [comment]
ping @alexwolfe

**Comment by Foxandxss** [comment]
We have this in the new design (yet to come) so closing it.
