### ISSUE TITLE
Ignore packages/ and build/ when generating _fragments

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#255]
After I run `gulp build-devguide-docs`, I get a few hundred *.json.md files that'll never be used.

If you ignore `packages` directories, then you won't create these unnecessary files.

I'm adding `packages` to `.gitignore`, fwiw.

**Comment by kwalrath** [comment]
We also need to ignore `build` directories.

**Comment by wardbell** [comment]
This was done, right?

**Comment by kwalrath** [comment]
It doesn't seem to be a problem any more, so yes, I guess it was done.
