### ISSUE TITLE
Please provide a reference to the containing/owning module for every feature in the API

### ISSUE THREAD

**Issue by autopulous** [angular/angular.io#2550]
Suggestion:

Presently the [Angualr 2 API preview](https://angular.io/docs/ts/latest/api/) groups the features of the API by module and within every feature of the API an _exported from_ and _defined in_ references are provided, for example _@Input:_

exported from [@angular/core/index](https://angular.io/docs/ts/latest/api/core/index/index.html), defined in [@angular/core/src/metadata/directives.ts](https://github.com/angular/angular/blob/2.0.1/modules/%40angular/core/src/metadata/directives.ts#L828-L829)

The API feature _exported from_ and _defined in_ are referencing documentation that doesn't specifically reference the Angular module an application would need to import...

A reference within the individual features to the Angular module to import would be handy and would make it obvious for new developers which module is required to use the feature.

This (former)...

_exported from [@angular/forms/index](https://angular.io/docs/ts/latest/api/forms/index/index.html)_ 

...is significantly different from providing a usage example (latter)...

**import {FormBuilder, FormGroup, Validators} from '@angular/forms';**

in that the latter is instructive / authoritative whereas the former is passive requiring interpretation (foreknowledge) to understand or use with confidence

https://github.com/angular/angular/issues/12036

**Comment by Foxandxss** [comment]
Reported at #1535 and I believe there is some new effort on doing that already, so stay tuned :)
