### ISSUE TITLE
live example link not working

### ISSUE THREAD

**Issue by zoechi** [angular/angular.io#2560]
https://angular.io/docs/ts/latest/cookbook/form-validation.html#!#live-example

I used the link below "COMMITTING HERO VALUE CHANGES" just before "Custom validation"

**Comment by Foxandxss** [comment]
Is working for me. Weird.

**Comment by zoechi** [comment]
Sorry, I misinterpreted what "live example" means. Usually this opens a Plunker but here it't an embedded Plunker. Haven't seen that before.
