### ISSUE TITLE
Possible typo in ToH-5

### ISSUE THREAD

**Issue by AlpBilgin** [angular/angular.io#2562]
I think the plus sign in the example where router parameters are fed into the service is a typo. Does this sort of thing require individual PRs? I don't really know the conventions here.

`ngOnInit(): void {
  this.route.params.forEach((params: Params) => {
    let id = **+**params['id'];
    this.heroService.getHero(id)
      .then(hero => this.hero = hero);
  });
}`

**Comment by bampakoa** [comment]
Actually it is not a typo. It converts the **id** into a number as it comes from router parameters.
