### ISSUE TITLE
Quickstart links to non-existent styles.css file

### ISSUE THREAD

**Issue by mhujer** [angular/angular.io#2571]
In [the quickstart](https://angular.io/docs/ts/latest/quickstart.html#!#index)  there is a link to `styles.css` in this text:
> For the full set of master styles used by the documentation samples, see [styles.css](https://github.com/angular/angular.io/blob/master/public/docs/_examples/styles.css).

But the target https://github.com/angular/angular.io/blob/master/public/docs/_examples/styles.css does not exist

**Comment by Foxandxss** [comment]
It does not. We changed the place and we forgot to update the link.

thanks a bunch. I will fix it shortly.
