### ISSUE TITLE
Possible typo in NgModule tutorial docs

### ISSUE THREAD

**Issue by togakangaroo** [angular/angular.io#2572]
[In the NgModule tutorial/docs](https://angular.io/docs/ts/latest/guide/ngmodule.html) I see the following line

> We export the ContactComponent so other modules that import the ContactModule can include it in their component templates.

This makes no sense...the thing being exported in the related code is `ContactModule` not `ContactComponent`. Also note that the way it is currently phrased is specifically about components since the contents of a module might be included in many places, *not* just in templates. That sentence therefore needs to be rephrased in general. Seems like it should read something like

> We export the module so that others that import the `ContactModule` can include it's contents.

**Comment by wardbell** [comment]
Sorry the passage confused you. It is factually accurate and makes an important point. 

We are declaring a number of things in `ContactModule`. All of those things belong to that module. NONE of them would be usable in any component outside of `ContactModule` ...

... unless they were listed in `ContactModule.exports` ... which `ContactComponent` is.

Having exported  `ContactComponent`, any OTHER module that imports `ContactModule` (e.g., `AppModule`) will be able to reference `ContactComponent` in one of its component templates (e.g, `AppComponent`).

Had we not done so, `AppComponent` could not display the `ContactComponent`.

Where do you see us exporting `ContactModule`?  Ahhh. You mean the ES2016 `export class ContactModule` statement.

You have fallen victim to the unfortunate similarity (and confusion) of ES2016 export statements and NgModule export properties.

This is a distinction you just have to learn.
