### ISSUE TITLE
Invalid dependency in Angular 2.0.2 Quick Start guide

### ISSUE THREAD

**Issue by Shakyamuni177te** [angular/angular.io#2573]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

"angular-in-memory-web-api": "~0.1.5", listed in Quick Start guide: https://angular.io/docs/ts/latest/quickstart.html is not a valid version. `Npm install` error lists 0.0.21 as latest version.
 
**Expected behavior**

Version 0.1.5 of angular-in-memory-web-api would install when running `npm install`.

**Minimal reproduction of the problem with instructions**

Try to install dependencies using latest version of Angular2 Quick Start guide.

**What is the motivation / use case for changing the behavior?**

So the Quick Start is easy to follow for beginners.

**Please tell us about your environment:**

Ubuntu 16:04 Server; Vim; node; lite-server.

* **Angular version:** 2.0.X

Introduced as of 2.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
Not browser issue.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

n/a

* **Node (for AoT issues):** `node --version` =   

6.7.0

**Comment by Foxandxss** [comment]
Are you sure you are using `angular-in-memory-web-api` and not `angular2-in-memory-web-api` ? Check out https://www.npmjs.com/package/angular-in-memory-web-api

**Comment by Shakyamuni177te** [comment]
When I update the dependency to `angular-in-memory-web-api` from `angular2-in-memory-web-api` and update the corresponding app.module entry to match (e.g. `import { InMemoryWebApiModule }   from 'angular-in-memory-web-api';`, the module fails to load with an  error showing in the server log: 

`404 GET /angular-in-memory-web-api`. 

The HTTP tutorial [(https://angular.io/docs/ts/latest/tutorial/toh-pt6.html)] show this as the correct formal for importanting `in-memory-web-api` but it's not being loaded in...

Is this a problem with the framework itself, or the documentation?

**Comment by Foxandxss** [comment]
It is probably a problem with your app.

Did you update your system.js configuration?

**Comment by Shakyamuni177te** [comment]
I haven't changed it. I had the exact same problem when I started out, following the documentation to the letter. I haven't changed anything in system.js from the default values.

Code is here: [(https://github.com/Shakyamuni177te/Ang2Mouse)] (with angular2-in-memory-web-api in place, but everything else as it was).

**Comment by Foxandxss** [comment]
Perhaps the doc was updated while you were doing it, but you have to change your systemjs config.

**Comment by Shakyamuni177te** [comment]
Ah, ok. I'll have a look as system.js. Thanks.

**Comment by Shakyamuni177te** [comment]
All working now. JEESS that new in memory database is quicker that the old one!
