### ISSUE TITLE
Pipe for Dates not working on edge 

### ISSUE THREAD

**Issue by CKGrafico** [angular/angular.io#2574]
The pipe operator with dates is not working on edge for desktop or mobile phone, when I use 'a'

<span class="item-footer-text">{{report.time | date:"hh:mm a"}}</span>

Works in chrome but not on edge
![Chrome](http://i.imgur.com/bTN5oux.png)
![Edge](http://i.imgur.com/wkq7S63.png)

And also I think that the docs are not ok
https://angular.io/docs/ts/latest/api/common/index/DatePipe-pipe.html#!#sts=Pipe
![Docs](http://i.imgur.com/SqeevYM.png)

Working if I use
{{report.time | date:"shortTime"}}

Seems that the problem are the custom formats like {{hh:mm}} and these things :/

**Comment by Foxandxss** [comment]
API issues goes to angular/angular. So open an issue there if you feel that the docs are not ok.

On the other hand, this repo is not a place to report angular isues themselves.
