### ISSUE TITLE
Question / Possible bug:  Need to refresh the page for hero search to work right?

### ISSUE THREAD

**Issue by daBishMan** [angular/angular.io#2578]
I followed the example in the documentation in the  HTTP Tutorial: Search-by-name section.   I am trying to do the same thing trying to create search functionality to learn observables (I created a repository https://github.com/daBishMan/ng2-observables to help me out).   

In the TOH when the user find what they are searching for he/she clicks on the button /hero on go to a different page.  What I am trying to accommodate is the user select and stay and the same page, and can delete the selection and start again.  

This does not seem to work, it seems that we are per the documentation inside the class, it states "switch to new observable each time", I think that is the problem since we are using the "async" pipe.

How can I change (or is this a possible bug) to accommodate what I am asking?  Can you help?

**Comment by Foxandxss** [comment]
Sorry for mega late response.

How is this going? You shouldn't ever need a refresh. That is the idea behind SPAs :P

**Comment by daBishMan** [comment]
NP, thank for responding.  Yes, I addressed this.  I will close it.
