### ISSUE TITLE
Is there a bare minimum package.json for Angular 2 to work with in the docs?

### ISSUE THREAD

**Issue by SetTrend** [angular/angular.io#2587]
The Quickstart already comes with loads of modules not related to Angular 2.

My learning approach is to start with the bare minimum and to add required modules when I need them. This way I learn which modules belong to which kind of purpose.

Can we have sort of a Quickstart beginning with nothing but the bare minimum to _add_ Angular 2 to an existing project?

I would expect this to be a single `dependencies: { "@angular/common": "~2.0.2" }` line.

**Comment by Foxandxss** [comment]
at dependencies, with the exception of `angular-in-memory-web-api` they are all related to angular 2. No exception (perhaps core-js, but you still need that for older browsers).

**Comment by SetTrend** [comment]
I comprehend. But aren't they optional? I learned that all these modules are only required if you require their special services. So the bare minimum should be a single line of dependency, shouldn't it?

**Comment by Foxandxss** [comment]
You need yes or yes:

zone.js
@angular/common
@angular/core
@angular/compiler
@angular/platform-browser
@angular/platform-browser-dynamic
system.js / webpack / ...
es6-shim / core-js
reflect-metadata
rxjs

The other are optional.

**Comment by SetTrend** [comment]
Are you sure these are the absolutely bare minimum dependencies? 

system.js / webpack / ...
es6-shim / core-js

are optional, aren't they?

**Comment by Foxandxss** [comment]
We can keep this conversation to all eternity, but that is what we have.

You need a module loader (system.js or webpack or ...) and you need es6-shim if you want to target the most common browsers. Es6-shim is contained in core-js, so one or the other.

You could say that es6-shim / core-js is optional, but it is not a good idea to leave it out.

I am going to close this tho.

**Comment by SetTrend** [comment]
Well, the main question is: What is required for Angular 2 and what it a personal bias/preference?

I have a strong feeling that Angular 2 keeps people from using it because it comes with to much personal biased modules which interfere with others' preferences.

There should be a bare minimum solution, requiring folks to only add one single dependency to their `package.json` file. If that single module required other modules compulsively, then that single module should come with its own `package.json` file, downloading all required additional `npm` packages.

We can continue this discussion on Gitter, if you prefer.
