### ISSUE TITLE
[Question] Why is Rollup used?

### ISSUE THREAD

**Issue by laco0416** [angular/angular.io#2593]
Angular-CLI uses webpack 2 officially. But AoT guide documentation uses Rollup for bundling. Why? 
It can give confusion to beginners. 

https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

**Comment by laco0416** [comment]
BTW, Tour of Heroes tutorial uses System.js. There is further confusion. 😩

**Comment by ovrmrw** [comment]
+1

**Comment by Foxandxss** [comment]
Angular is completely agnostic on which tools to use. Webpack is one option, so is System.js or Rollup.

Angular-CLI decided to go to Webpack 2, but that doesn't make Webpack 2 the official bundling tool for Angular, it is just one option and the Angular team works hard on making Angular (and AoT, lazy loading, etc) to work with all bundling tools.

>Angular-CLI uses webpack 2 officially. But AoT guide documentation uses Rollup for bundling. 

The objective of the docs is to teach something, and you cannot teach proper AoT with the CLI.

CLI does AoT for you automagically, it has a lot of hidden magic and a cookbook saying "To do AoT, please use the --aot flag when building" is not a tutorial after all.

So this mean that we need to teach AoT by hand, that means getting the quickstart and adding everything you need to achieve proper AoT with it. Creating a different main.ts file to load a ngFactory, generate those factories. The idea is to teach people what is this AoT and how to run the tools by hand to achieve the desired result.

So why Rollup? We use it for tree shaking and bundling. But again, why? Is just a tool like the others and being honest is the one that does the best tree shaking right now, so it is a good moment to show how it works. Again, this is just to teach AoT, the tool chosen is just one option.

We will teach eventually how to configure a Webpack config to do AoT as well, so we cover all the angles.

>Why? It can give confusion to beginners.

It is more confusing if you go directly with the CLI, use they commands they provide to generate AoT and one day it doesn't work and you don't know how it works. First learn it by hand, then look for the CLI or any other starter that does it for you.

>BTW, Tour of Heroes tutorial uses System.js. There is further confusion.

Like AoT, our objective is to teach Angular but for teaching Angular we need to use a tool. System.JS works great, the Quickstart gives no issue and does everything you ask it to do.

Could we move everything to Webpack? Sure, but then we are in the same spot, why Webpack and not System.js? They are only a necessity, the point is to teach Angular.

>I think documentation should say that what is best way...

The best way is always really subjective. There is no a perfect tool, Webpack is far from being "the tool" and let alone the "best way". Is just one more way.

There are people who likes the CLI, people who doesn't. People that prefer to code a Webpack config by hand, people that doesn't want to see Webpack at all. People that likes the speed of Rollup and of course people that thinks that System.js is more robust and does an awesome job.

**Comment by jetlogs** [comment]
it's a good sign that a Webpack + AOT guide is in the works, since right now I am completely stuck on that set-up following the cookbook:

http://stackoverflow.com/questions/40003205/webpack-angular2-aot-uncaught-syntaxerror-unexpected-token-import

I'll be following the developments closely, and hopefully I can make the webpack + AOT build work. Thanks!

**Comment by wardbell** [comment]
@laco0416 The documentation samples adopt _a standard approach_ that relies on SystemJS. It is a good approach that will carry you safely to a production app of any scale.  We are comfortable encouraging people to follow it.

As @Foxandxss observes it is _not the only approach_.  The CLI, for example, takes a different approach, one that relies on Webpack.  That's also great ... when you have the CLI to help you.  In our opinion, it is much harder to explain how to setup and build the app correctly with Webpack _without the CLI_. We want people to focus on Angular, not setting up the environment for Angular.

As @Foxandxss explains, Angular itself is independent of the module bundling and loading technology. You have choices. Which choice is best for you? You'll have to decide. We've decided that the SystemJS path is _our_ best option for samples that do not depend upon the CLI. As it happens, a significant number of users will not be able to use the CLI. They may find comfort in our SystemJS-based guidance; they may develop their own tooling to go the WebPack way. 

In any case, we need to be clear that there is **no best way for everyone**.  Our commitment is to steer you down a _viable path_ and to _be consistent_. I think we've met that goal.

@jetlogs I cannot say for sure but I'm guessing that webpack has nothing to do with the error. I'm betting the problem relates to AoT compilation constraints. Unfortunately, we don't have the resources to debug everyone's application code. You'll have to seek community help or create a simple repro ... and submit that to the `angular` site, not this documentation site.
