### ISSUE TITLE
I wasn't able to find where basic principles like `[(prop)]="xxx"` are explained

### ISSUE THREAD

**Issue by zoechi** [angular/angular.io#2598]
in https://angular.io

for example how to do "2-way binding" banana-in-a-box can be used with custom components (not only with `ngModel`).

**Comment by Foxandxss** [comment]
There is a cookbook in the backlog that shows you that. Hope it gets here soon.

**Comment by wardbell** [comment]
I just addressed this in an update to "Template Syntax" in PR #2639.

**Comment by wardbell** [comment]
Closed by PR #2639
