### ISSUE TITLE
Deploy script

### ISSUE THREAD

**Issue by Admdebian** [angular/angular.io#2608]
Which is the best way to build a package to deploy on a web server?

I asked to quickstart project:
https://github.com/angular/quickstart/issues/188#issuecomment-241262984

They said I should ask here, then they have closed my question:
Wardbell: That's a great question for angular.io. It is out-of-scope for quickstart. Closing

**Comment by Foxandxss** [comment]
Sorry for the late response. We have documentation for that now.
