### ISSUE TITLE
[DOC] Missing step into the tutorial

### ISSUE THREAD

**Issue by cbarbet** [angular/angular.io#2615]
Hi,

It seems that they is a missing step into the tutorial. It localize on this page: https://angular.io/docs/ts/latest/tutorial/toh-pt2.html

Title : **Expose the selected hero**

Indeed, in order to correctly expose this object, we should have to import **FormsModule** in the **app.module.ts**, and refer it in **@NgModule**
```
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule }   from '@angular/forms';
...
@NgModule({
  imports: [
    BrowserModule,
    FormsModule
  ],
...
```

`

**Comment by Foxandxss** [comment]
That was added in part 1, so when you get into part 2, you will have the FormsModule already loaded.
