### ISSUE TITLE
Typo - HttpClient Guide (json results section)

### ISSUE THREAD

**Issue by MarkPieszak** [angular/angular.io#2619]
https://angular.io/docs/ts/latest/guide/server-communication.html

Can put a PR in tomorrow just putting the issue out there.

> JSON results
> As with getHeroes(), we extract the data from the response using the extractData() helper.
> 
> Back in the HeroListComponent, we see that its addHero() method subscribes to the observable returned by the service's addHero() method. When the data, arrive it pushes the new hero object into its heroes array for presentation to the user.                ^^^^^^^^^^^^^^^^^
>

**Comment by Foxandxss** [comment]
Yes, sounds weird. Please open a PR.
