### ISSUE TITLE
Mobile "docs" menu not accessible via iphone 6s

### ISSUE THREAD

**Issue by matsko** [angular/angular.io#2623]
If using an iphone 6s or a device with a resolution of <= 320px the site-menu link overlaps with the docs link. This makes it impossible to interact with the sub docs link.

<img width="325" alt="screen shot 2016-10-17 at 1 22 48 pm" src="https://cloud.githubusercontent.com/assets/93018/19454191/04cffb78-946d-11e6-9fe6-7f745b5db757.png">

**Comment by chalin** [comment]
@alexwolfe 
cc @naomiblack @ericjim

**Comment by Foxandxss** [comment]
Closing as we are moving to the new design with proper mobile version.
