### ISSUE TITLE
doc pages should link to tests/spec files

### ISSUE THREAD

**Issue by esinek** [angular/angular.io#2634]
Currently, the docs link to the code via "exported from ..., defined in ..."
e.g. `exported from @angular/common/index, defined in @angular/common/src/directives/ng_switch.ts`
It would be really useful to include a link to the test/spec file as well since that is often the best way to see how the code should work.

**Comment by wardbell** [comment]
Thanks but I think that's something that will confuse many and people in the know can figure that out. Judgment call to be sure but I'm making it and closing.
