### ISSUE TITLE
Missing documentation for ViewChildren decorator

### ISSUE THREAD

**Issue by canda** [angular/angular.io#2636]
If you enter
https://angular.io/docs/ts/latest/api/core/index/ViewChildren-decorator.html
It's empty

**Comment by ti1024** [comment]
The same issue happens also for ContentChild:
https://angular.io/docs/ts/latest/api/core/index/ContentChild-decorator.html

**Comment by Foxandxss** [comment]
All of this needs to be reported to the angular repo, they manage the API.

Thanks.
