### ISSUE TITLE
Cannot find module './in-memory-data.service'

### ISSUE THREAD

**Issue by mannyzhuo** [angular/angular.io#2637]
![image](https://cloud.githubusercontent.com/assets/13795608/19546906/fb458ac2-96c5-11e6-84fb-230595a902cd.png)

there is no 'angular-in-memory-web-api/in-memory-web-api.module'

**Comment by mannyzhuo** [comment]
there is no 'angular-in-memory-web-api/in-memory-web-api.module'

**Comment by Foxandxss** [comment]
First import is

```
import { InMemoryWebApiModule } from 'angular-in-memory-web-api';
```

And the second one is an external file as @savurself11 said.
