### ISSUE TITLE
window.location.href  does not works with schemas: [CUSTOM_ELEMENTS_SCHEMA]

### ISSUE THREAD

**Issue by RamitAnandSharma** [angular/angular.io#2646]
if i add schemas: [CUSTOM_ELEMENTS_SCHEMA] in my @NgModule then i am not able to redirect to external URL.

@NgModule({
schemas: [CUSTOM_ELEMENTS_SCHEMA]
......
})
 
window.location.href = "https://jqueryui.com/";

**Comment by Foxandxss** [comment]
If you believe this is a bug, please open an issue at angular/angular. This repo is only for documentation.

Thank you.
