### ISSUE TITLE
Karma testing from Webpack guide is not working

### ISSUE THREAD

**Issue by klinki** [angular/angular.io#2649]
I created webpack and karma config based on guide: https://angular.io/docs/ts/latest/guide/webpack.html but I have issues with running karma tests.

It fails with error 

> ReferenceError: Can't find variable: __decorate

which seems like there is some issue with compilation. Maybe karma got executed before source code was compiled?

Here is console output:

> webpack: bundle is now VALID.
> webpack: bundle is now INVALID.
> 
> webpack: bundle is now VALID.
> 21 10 2016 12:42:45.642:WARN [karma]: Port 9876 in use
> 21 10 2016 12:42:45.643:INFO [karma]: Karma v1.3.0 server started at http://localhost:9877/
> 21 10 2016 12:42:45.644:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
> 21 10 2016 12:42:45.755:INFO [launcher]: Starting browser PhantomJS
> 21 10 2016 12:42:46.513:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket /#AKRqtA5qb58TKbSjAAAA with id 34722869
> PhantomJS 2.1.1 (Linux 0.0.0) ERROR
>   ReferenceError: Can't find variable: __decorate
>   at webpack:///src/app/services/abtract.service.ts:5:0 <- config/karma-test-shim.js:40220

**Comment by Foxandxss** [comment]
I believe the error is in your application somehow.

**Comment by klinki** [comment]
You are right, I had `"noEmitHelpers": true` in tsconfig.json and it caused those issues.
