### ISSUE TITLE
 question: angular2 docs for offline reading

### ISSUE THREAD

**Issue by lordKnighton** [angular/angular.io#2651]
Where, or how can i read ang2 docs for offline reading? ⚡️

**Comment by Foxandxss** [comment]
clone this repo, clone also the angular repo. Have them inside the same parent folder:

```
docs |
-- angular.io
-- angular
```

Inside `angular.io` you can do `npm install && gulp build-compile`. That will generate a `www` folder that you can serve with `lite-server` (or any other server) for offline reading.

**Comment by lordKnighton** [comment]
@Foxandxss  ![screen shot 2016-10-24 at 8 50 38 am](https://cloud.githubusercontent.com/assets/1773260/19652799/0ef73c74-99c7-11e6-9d9a-24e2a5343475.png)

**Comment by Foxandxss** [comment]
You need the angular repo too as I specified :)

**Comment by lordKnighton** [comment]
![screen shot 2016-10-24 at 8 59 11 am](https://cloud.githubusercontent.com/assets/1773260/19653146/37a57a0e-99c8-11e6-8641-86139e87118d.png)

![screen shot 2016-10-24 at 8 59 21 am](https://cloud.githubusercontent.com/assets/1773260/19653149/3b876dc6-99c8-11e6-9337-3d0a7751142f.png)

**Comment by lordKnighton** [comment]
I have them both in the docs file

**Comment by Foxandxss** [comment]
Sorry, we need to do `gulp build-compile --lang="ts|js"`

**Comment by lordKnighton** [comment]
and I'm gonna run in the `docs folder`  
```bash
gulp build-compile --lang="ts|js"
```
then 

```bash 
npm install && gulp build-compile
```

is this correct?

**Comment by Foxandxss** [comment]
no no, `npm install && gulp build-compile --lang="ts|js"`

**Comment by lordKnighton** [comment]
![screen shot 2016-10-24 at 9 06 22 am](https://cloud.githubusercontent.com/assets/1773260/19653371/2b4b4904-99c9-11e6-9c31-e503dc8fb2a7.png)

**Comment by Foxandxss** [comment]
inside angular.io folder

**Comment by lordKnighton** [comment]
k

**Comment by lordKnighton** [comment]
So now, how do i run it? 
![screen shot 2016-10-24 at 9 30 24 am](https://cloud.githubusercontent.com/assets/1773260/19654290/8c66c5f8-99cc-11e6-91df-0955817ae046.png)

**Comment by lordKnighton** [comment]
do i install ? 

That will generate a www folder that you can serve with lite-server (or any other server) for offline reading.

**Comment by Foxandxss** [comment]
Uhm, I think we have a bug on that, you should get no error and a www folder.

**Comment by chalin** [comment]
You can ignore the "cannot rename" error for the Dart API. The rest of the www folder should be complete.

**Comment by lordKnighton** [comment]
Thanks, how to i run this?

**Comment by chalin** [comment]
There are a few ways, one is: `gulp serve-www`

**Comment by lordKnighton** [comment]
Thanks it working 🐋

**Comment by sajidali** [comment]
@Foxandxss I followed the instructions, `npm install` complete, even ran the `./script/install.sh` inside angular.io that installed the examples too.
but for some reason, running `gulp build-compile --lang="ts|js"` does not generated the www folder. It showed a lot of output, but no www folder was present in angular.io after build-compile ended.

I was scratching my head, what to do next, and then I checked screenshot provided by @lordKnighton 
![](https://cloud.githubusercontent.com/assets/1773260/19654290/8c66c5f8-99cc-11e6-91df-0955817ae046.png)
And in it I found a call `npm run harp -- compile . www`. I ran this command manually, and voila, the www folder is present and I can run `gulp serve-www` from angular.io and LATEST docs were served.

Can you please let me know why `gulp build-compile` failed to generate www folder, all the info on internet says, running this should generate www folder.
I am using latest angular.io and angular checkout as of now.

**Comment by kirtangajjar** [comment]
This solution doesn't work now :( 

Any idea how to get it working for the 4.4.x branch?

As far as I know this repo is not maintained anymore and to get current docs, we have to clone [angular/angular](https://github.com/angular/angular) and then run `yarn docs` in the `aio` subdirectory.

I've done that and still I'm getting compile error like as posted [here](https://github.com/angular/angular/issues/19130)

Can someone help me?
