### ISSUE TITLE
Online Docs broken link 

### ISSUE THREAD

**Issue by daslicht** [angular/angular.io#2653]
See:
https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/tutorial/toh-pt5.jade#L658

https://angular.io/docs/ts/latest/tutorial/toh-pt5.html

```htm``` should be ```html```:
https://angular.io/docs/ts/latest/guide/router.htm#!#routing-module

**Comment by Foxandxss** [comment]
Thanks! Seems like it is fixed already :)
