### ISSUE TITLE
Broken links online docs

### ISSUE THREAD

**Issue by Devinsuit** [angular/angular.io#2655]
1. https://angular.io/docs/dart/latest/tutorial/toh-pt5.html - master styles given here (https://raw.githubusercontent.com/angular/angular.io/master/public/docs/_examples/styles.css)

2. https://angular.io/docs/ts/latest/guide/router.html - Dependency Injection chapter (https://angular.io/docs/ts/latest/guide/dependency-injection#!#bootstrap)

3. https://angular.io/docs/ts/latest/api/core/index/Injectable-decorator.html -  NoAnnotationError (https://angular.io/docs/ts/latest/api/core/index/NoAnnotationError)

4. https://angular.io/docs/ts/latest/api/core/index/Compiler-class.html - compileModuleAsync (https://angular.io/docs/ts/latest/api/core/index/compileModuleAsync)

**Comment by Foxandxss** [comment]
First is fix, second is fixed as well and the other two are API that belongs to the angular/angular repo.

I am asking to see whether or not we should report them. So I can continue from here.

Thank you.
