### ISSUE TITLE
wishlist for the map of angular api

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#266]
- [ ] double-check that the names are right. looks like this was pulled from older api than 42 (_BINDINGS -> _PROVIDERS)
- [ ] contrast in bubbles
- [ ] align of text in icon bubbles
- [ ] make it more obvious that the legend is clickable buttons
- [ ] make "show all" more obvious
- [ ] pre-populate the autocomplete box with some good suggestions
- [ ] why is that one alias missing an icon?
- [ ] on the Dart version left margin padding style issue

**Comment by naomiblack** [comment]
only fake assigned to you. I'm going to work on these -- the names I can do on the plane easily. don't worry about it.

**Comment by johnpapa** [comment]
Those are good ... also

- [ ] when nothing is found, either hide the section or indicate it in some way
- [ ] properties/events should be inputs/outputs
- [ ] `bootstrap` seems to be missing

**Comment by naomiblack** [comment]
obsolete
