### ISSUE TITLE
How can I add script or css file out of Angular environment based on specific situation?

### ISSUE THREAD

**Issue by mahyari** [angular/angular.io#2660]
I have make an internationalization website with Angular and want add some CSS library like `bootstrap-rtl` and so on just when current language is `ar` or `fa` but find no way to add link element in head of html. 
So my question is, How can I add file out of Angular environment based on specific situation.
I know I can add it in server but it need to reload site.

**Comment by Foxandxss** [comment]
Thanks for your issue, but this kind of questions belong to stackoverflow. There you can explain what kind of environment are you using so you could get some concrete solution.
