### ISSUE TITLE
Quickstart systemjs.config.ts in docs will break heros tutorial at http stage

### ISSUE THREAD

**Issue by Stexxen** [angular/angular.io#2667]
Currently https://github.com/angular/angular.io/blob/master/public/docs/_examples/quickstart/ts/systemjs.config.1.js

breaks when you get to stage 7 of the heroes tutorial with an obscure traceur 404 error
![image](https://cloud.githubusercontent.com/assets/4494301/19687469/5f2fe154-9abd-11e6-949f-5853d44aae63.png)

its related to this
![image](https://cloud.githubusercontent.com/assets/4494301/19687364/0645432c-9abd-11e6-9012-8cdede39de33.png)

and just needs updating to the one in the quickstart repo
https://github.com/angular/quickstart/blob/master/systemjs.config.js

Quickstart was updated here 
https://github.com/angular/quickstart/commit/541bdc5f634e1142860c56cace247234edfaf74b

**Comment by wardbell** [comment]
Closed by #2668
