### ISSUE TITLE
Links to Plnkr in Testing docs returning 404

### ISSUE THREAD

**Issue by marinho** [angular/angular.io#2674]
Hi, quite often, when I click in one of the links to Plnkr in https://angular.io/docs/ts/latest/testing/, I get a 404 page.

Right now I'm trying it from Paris, but it often happens to me also from Germany.

The links which are failing are:
- The sample application
- The first spec
- The complete application specs
- A grab bag of demonstration specs

**Update:** same issue happens to clickable screenshots which point to Plnkr too, such as in **"The sample application and its tests"** section

**Comment by Foxandxss** [comment]
They are broken indeed. I will fix.

**Comment by Foxandxss** [comment]
Fixed
