### ISSUE TITLE
router documentation is unclear about CanActivate vs. CanActivateChild with component-less routes

### ISSUE THREAD

**Issue by JohannesRudolph** [angular/angular.io#2679]
I initially created this Stackoverflow question, but was asked to file this as an issue here for further discussion: http://stackoverflow.com/questions/40163348/canactivate-vs-canactivatechild-with-component-less-routes?noredirect=1#comment67759108_40163348

**Comment by thekalinga** [comment]
Is it possible for anyone from Angular to respond to this?

**Comment by wardbell** [comment]
As one S.O. respondent noted, the difference is explained in the docs (my _emphasis added_):
>As we learned about guarding routes with `CanActivate`, we can also protect child routes with the `CanActivateChild` guard. The `CanActivateChild `guard works similarly to the `CanActivate` guard, but the difference is its _run before each child route_ is activated. We protected our admin feature module from unauthorized access, but we could also protect child routes within our feature module.

The issue becomes apparent when you consider navigating from child-to-child (see respondent's example).  The `CanActivate` on the parent component presumably allowed navigation to the first child. The parent's `CanActivate` is not called again as long as sibling children navigate among themselves. But the parent's `CanActivateChild` will be called.

I'm not sure if this clarification is needed in the docs. @brandonroberts ?

**Comment by brandonroberts** [comment]
If any clarification could be added, its that `CanActivateChild` can be used without a component-less route, but the difference between it and `CanActivate` is already explained.

**Comment by JohannesRudolph** [comment]
Well, at least now that the SO answer is there and properly google-indexed people (like me) that don't get the docs on a first read can find the relevant information and an example. :-)

**Comment by DzmitryShylovich** [comment]
@brandonroberts 
Looks like [CanActivateChild documentation](https://angular.io/docs/ts/latest/guide/router.html#!#milestone-5-route-guards) is incorrect.

> We can have multiple guards at every level of a routing hierarchy. The router checks the CanDeactivate and **CanActivateChild guards first, from deepest child route to the top**. Then it checks the CanActivate guards from the top down to the deepest child route.

It doesn't make sense to me at all to run `CanActivateChild` from bottom to top + it doesn't actually work like this http://plnkr.co/edit/H7plpGEh83LjWKWtUtff?p=preview
what do you think?
