### ISSUE TITLE
Mistake in step 8 of quickstart tutorial

### ISSUE THREAD

**Issue by matthewjh** [angular/angular.io#27]
Hi,

I noticed that in [Step 8 of the quickstart](https://angular.io/docs/js/latest/quickstart.html), the instructions state that a HTTP server should be spun up serving from the directory containing index.html.  However, in index.html, paths used for `System.paths` and the `es6-shim` script tag assume that the *parent* directory of `quickstart` is being served:

```javascript
System.paths = {
    'angular2/*':'/quickstart/angular2/*.js', // Angular
    'rtts_assert/*': '/quickstart/rtts_assert/*.js', // Runtime assertions
    'app': 'app.es6' // The my-app component
  };
```

**Comment by davideast** [comment]
I'm not clear on where you're running into an issue. The directory structure should be as follows:

```
--- app
   --- quickstart
       --- angular
       --- rtts
       --- dist
          --- es6-shim.js
   --- index.html
   --- app.es6
```

The System paths above should be fine for running the server from the root.

**Comment by matthewjh** [comment]
Ah. I had cd'd into `quickstart` after cloning the repo out of habit, so my app.es6, index.html, were inside `quickstart`. 

My mistake then!

**Comment by davideast** [comment]
No problem! Glad to know everything is working okay.
