### ISSUE TITLE
cookbook 

### ISSUE THREAD

**Issue by jvpf** [angular/angular.io#2714]
I do not manage to compile cookbook "dynamic forms" example. There is no packge.json  among the files neither in the "live example". Could this be included? Cf. "quickstart" example where package.json is included

**Comment by jvpf** [comment]
Cf. "quickstart" example where package.json is included

**Comment by jvpf** [comment]
the current cookbook example assumes the types to be places two steps up in file hierarchy:

$ diff tsconfig.json.old tsconfig.json.new 
13c13
<       "../../node_modules/@types/"
---
>       "node_modules/@types/"

**Comment by Foxandxss** [comment]
You need to run the `/scripts/install.sh` that will install all dependencies and copy the boilerplate files like that package.json.

For a plunker, you don't need a package.json at all.
