### ISSUE TITLE
Tutorial: Master/Detail - The Hero Editor - closing input tag?

### ISSUE THREAD

**Issue by jan-dh** [angular/angular.io#272]
Following the tutorial on https://angular.io/docs/ts/latest/tutorial/toh-pt1.html I wonder why they use a seperate closing tag for an input field in the following template:

template:`
  <h1>{{title}}</h1>
  <h2>{{hero.name}} details!</h2>
  <div><label>id: </label>{{hero.id}}</div>
  <div>
    <label>name: </label>
    <div><input value="{{hero.name}}" placeholder="name"></input></div>
  </div>
  `

**Comment by wardbell** [comment]
It's gone now.
