### ISSUE TITLE
Tutorial: Master/Detail: The Hero Editor: wrong syntax for styles

### ISSUE THREAD

**Issue by jan-dh** [angular/angular.io#273]
In the tutorial there is an error in the styling sections.

![styling](https://cloud.githubusercontent.com/assets/5801781/10542031/75a1e506-7415-11e5-8b0b-96542ecbcf94.png)

styling should be wrapped in an array like so (don't forget the backticks, can't seem to get them working in the code here): 
styles:[` .heroes {list-style-type: none; margin-left: 1em; padding: 0; width: 10em;}
  .heroes li { cursor: pointer; position: relative; left: 0; transition: all 0.2s ease; }
  .heroes li:hover {color: #369; background-color: #EEE; left: .2em;}
  .heroes .badge {
    font-size: small;
    color: white;
    padding: 0.1em 0.7em;
    background-color: #369;
    line-height: 1em;
    position: relative;
    left: -1px;
    top: -1px;
   } 
   .selected { background-color: #EEE; color: #369; } `]

**Comment by PascalPrecht** [comment]
@jan-dh hey, fancy sending a PR? :)

**Comment by jan-dh** [comment]
Would love to but cant' seem to find where the tutorial section is.

**Comment by Gillespie59** [comment]
I think this issue has already been solved with  93a646d63fcde7055382d7a319a8f51c78fd3593

**Comment by Gillespie59** [comment]
Oh I did not see the comment from @wardbell here #271 . 
Issues solved.
