### ISSUE TITLE
[ng2] menus don't toggle on the api reference page

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#2733]

**Comment by ericjim** [comment]
Could you elaborated a bit more on this issue, I am not sureI can reproduce it.

**Comment by chalin** [comment]
On the deployed site, if you visit the API reference page, try to click on any of the menus (main, sidenav, language): none of them pop up.

**Comment by chalin** [comment]
I can't reproduce locally. I redeployed and the problem is still there. Will investigate.

**Comment by chalin** [comment]
Ah, its just because the API Reference HTML page simply wasn't updated (because I regenerated w/o updating the API pages).

**Comment by chalin** [comment]
A full build fixed the problem.
