### ISSUE TITLE
the performance of custom control. access the get method very often

### ISSUE THREAD

**Issue by juchunwei** [angular/angular.io#2769]
hello,

I did a custom control, but I notice the get method of the value was access very often. even it's not visible. the system access it when I click my mouse or move my mouse on the page. is that the normal? and I even try some sample on the internet, the same.

Thanks.

**Comment by Foxandxss** [comment]
Hello!

This issue tracker is for documentation issues. Id recommend you to create a nice reproduction on a plunker and post it directly to angular/angular. You will get more insight there ;)
