### ISSUE TITLE
API Reference - Missing Http Body documentation, no base classes or implemented methods

### ISSUE THREAD

**Issue by peku33** [angular/angular.io#2780]
The issue does not correspond to angualr itselt, but to the API Reference available at https://angular.io/docs/ts/latest/api/

In many Http examples, users use .text() and .json() method directly on Http.Response object.

I tried to find at least basic information about those methods in API Reference, but with no luck. In https://angular.io/docs/ts/latest/api/http/index/Response-class.html there is not a single word about those methods, except an example showing the usage.

I found a source of Response class in https://github.com/angular/angular/blob/master/modules/%40angular/http/src/static_response.ts

The Response class derives from Body class which provides .text() and .json() methods.

However, in API Reference there is no information about Body. There is also no information about base classes or implemented interfaces (probably for all classes, not only Response).

**Comment by Foxandxss** [comment]
All API issues needs to be reported at angular/angular. Thank you.
