### ISSUE TITLE
firefox not all ".sidenav-links" are shown when scrolling to bottom

### ISSUE THREAD

**Issue by nimo23** [angular/angular.io#2782]
Actually, in firefox (v. 49) 
the left sidebar (menu class '.sidenav-links') on desktop mode 
does not show all menu-items when scrolling to bottom, 
because it is hidden by the drop down bottom ( .dropdown').

![1](https://cloud.githubusercontent.com/assets/3045549/20146460/4cb55566-a6a4-11e6-8afb-546862e5ed8e.png)

**Comment by CamusAran** [comment]
Still an issue in Firefox 50.0.2

**Comment by Foxandxss** [comment]
We are migrating the site, I will make sure this doesn't happen. Closing.
