### ISSUE TITLE
Tutorial: Creating NPM modules

### ISSUE THREAD

**Issue by Dyljyn** [angular/angular.io#2834]
I would like to request to add documentation on how to create an Angular NPM module.

This is my first time attempting to create an NPM module in general and though there is a decent amount of information about how to publish an NPM module. After also looking at other Repos, I still don't understand how I am able to set one up myself with Angular (Typescript), including: transpiling to `/dist`, testing, etc.

There are sure more people who would love to make an NPM module out of their reusable code, so a Tutorial/Cookbook on this would certainly serve its purpose, I believe.

**Comment by Foxandxss** [comment]
We are going to publish soon a guide about creating libraries. I don't think it covers creating a NPM package itself, but that is kinda generic.

**Comment by Dyljyn** [comment]
Looking forward to it! :)

**Comment by lazaridis-com** [comment]
[issue.feature]
