### ISSUE TITLE
Tour of Heros two way data binding is not working.

### ISSUE THREAD

**Issue by zxhfirefox** [angular/angular.io#2855]
I follow the tutorial, but I find that when I am editing the name of hero, the h2 does not change.
I find 
`
EXCEPTION: Error in ./AppComponent class AppComponent - inline template:3:28 caused by: Cannot read property 'id' of undefined
`.
I check the code with source in public/docs/_examples/toh-1/, I really does not see any different.
My app.component.ts
`
import { Component } from '@angular/core';

export class Hero {
    id: number;
    name: string;
}

@Component({
    selector: 'my-app',
    template: `
    <h1>{{ title }}</h1>
    <h2>{{ hero.name }} details</h2>
    <div><label>id: </label> {{ heor.id }} </div>
    <div>
        <label>name: </label> 
        <input [(ngModel)]="hero.name" placeholder="name" />
    </div>
    `
})

export class AppComponent {
    title = 'Tour of Heroes';
    hero : Hero = {
        id: 1,
        name: 'Windstorm'
    };
}
`

**Comment by ericmartinezr** [comment]
>heor.id

**Comment by micronyks** [comment]
You need to correct the typo.

`{{ heor.id }} `

 should be 

`{{ hero.id }} `

and please close this issue if it resolves your problem.

**Comment by zxhfirefox** [comment]
So stupid = =
