### ISSUE TITLE
Dart sample code omits `moduleId`

### ISSUE THREAD

**Issue by mehaase** [angular/angular.io#2859]
On https://angular.io/docs/dart/latest/guide/forms.html, the text says:

> 3. The moduleId property sets the base for module-relative URLs such as the templateUrl.

But the example code that is being described doesn't actually use `moduleId`.

**Comment by chalin** [comment]
Hi Mark, thanks for filing an issue. The forms page is in need of an overhaul. Hopefully that will happen soon. In the meantime you can ignore that step since Dart doesn't need a `moduleId`.

cc @kwalrath
