### ISSUE TITLE
package.json sample missing from TypeScript quickstart

### ISSUE THREAD

**Issue by chliebel** [angular/angular.io#2863]
Hi, I’m missing the package.json sample which could be found on the quick start page for TypeScript until yesterday. We recently use this to check our node packages’ versions. Could you please bring it back?

https://angular.io/docs/ts/latest/quickstart.html

**Comment by Ganapathi004** [comment]
Hii @chliebel, I am pasting down the package.json contents used in the Quickstart tutorial.

`{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "lite": "lite-server",
    "tsc": "tsc",
    "tsc:w": "tsc -w"
  },
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/angular/angular.io/blob/master/LICENSE"
    }
  ],
  "dependencies": {
    "@angular/common": "~2.2.0",
    "@angular/compiler": "~2.2.0",
    "@angular/core": "~2.2.0",
    "@angular/forms": "~2.2.0",
    "@angular/http": "~2.2.0",
    "@angular/platform-browser": "~2.2.0",
    "@angular/platform-browser-dynamic": "~2.2.0",
    "@angular/router": "~3.2.0",
    "@angular/upgrade": "~2.2.0",
    "angular-in-memory-web-api": "~0.1.15",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "zone.js": "^0.6.25"
  },
  "devDependencies": {
    "@types/core-js": "^0.9.34",
    "@types/node": "^6.0.45",
    "concurrently": "^3.0.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.3"
  }
}`

**Comment by chliebel** [comment]
@Ganapathi004 Thanks. But where did you find that? For me, the TypeScript quickstart doesn’t show any package.json… All it suggests is downloading a seed.

**Comment by wardbell** [comment]
Get it from the [Quickstart Seed repository](https://github.com/angular/quickstart/blob/master/package.json) which we keep in sync with the documentation.

**Comment by Ganapathi004** [comment]
Before they had changed the tutorial, I had that setup in my machine. Glad it helped you :)

**Comment by chliebel** [comment]
@wardbell Perfect! Thanks.

@Ganapathi004 Thank you as well.
