### ISSUE TITLE
A strange thing I have encountered

### ISSUE THREAD

**Issue by arunkumars08** [angular/angular.io#2874]
I have a strange issue while using Angular2 imports. I am not sure if anybody has faced that. I have a component let's say in 'app2d3.component.ts' file. When I tried importing this component in another place, using 
import {NameOfTheComponentClass} from 'app2D3.component'; 
it still works fine. I am wondering how.
The thing is not the missing of '.ts' extension but capital 'D' in the name instead of the small 'd'. Any info on this?

Is this meant to happen this way?

Thanks.

**Comment by Foxandxss** [comment]
This kind of questions are better for stackoverflow.
