### ISSUE TITLE
Checkbox - attribute binding with "for"

### ISSUE THREAD

**Issue by jan-dh** [angular/angular.io#288]
I'm trying to bind a label attribute "for" as such:

    <input id="checkbox-{{todo.id}}"  class="checkbox">
    <label for="checkbox-{{todo.id}}" class="checkbox-label"> 

to generate something like this:

    <input id="checkbox-1" class="checkbox">
    <label for="checkbox-1" class="checkbox-label">

But it seems that Angular is tripping over the "for" statement.
I get the following erorr:

    EXCEPTION: Template parse errors:
    Can't bind to 'for' since it isn't a known native property in AppComponent > ul:nth-child(7) > li:nth-       child(1) > label:nth-child(3)[for={{todo.id}}]

Same result with only the `for="{{todo.id}}"`. If I remove the Id it seems to work altogether, but I'm looking for a way to dynamically both the label `for` property to the input id. 

The binding on the id works perfectly. `id="checkbox-{{todo.id}}"`gives the result: `id="checkbox-1"`.

**Comment by Gillespie59** [comment]
Hi @jan-dh 

I think you use the wrong mailing list. For this kind of question, you should first ask in the Angular2 gitter chat room. 

but maybe a solution ;) Have you tried with the `[prop] syntax : 

```html
<label [for]="'checkbox-' + todo.id" class="checkbox-label"> 
```

Manu

**Comment by jan-dh** [comment]
Oops, wrong place to mention this. Sorry.
Thanks for the propsed solution but it's not working.
