### ISSUE TITLE
StyleGuide - exception for avoiding renaming inputs?

### ISSUE THREAD

**Issue by karptonite** [angular/angular.io#2891]
The style guide suggest that we avoid renaming inputs and outputs, when possible.
https://angular.io/styleguide#!#05-13

I suggest that we add an exception for attribute directives, when the attribute directive doubles as an input.

For example, you might have a selector, `[prefixHighlightColor]`, and want to pass it as an input without the prefix, `@Input('prefixHighlightColor') highlightColor: string;`.

I'm suggesting this here, because of the no-input-rename rule in Codelyzer (which implements the style guide rules for linting). https://github.com/mgechev/codelyzer/issues/138 It seems that removing the prefix should not count as "renaming" for the no-input-rename rule. The rule seems sensible rule in any other case I can think of, so it would be a shame not to use it.

@mgechev

**Comment by wardbell** [comment]
That's a bad rule. There is absolutely nothing wrong with renaming a property.  I will lobby hard to have it reversed.

**Comment by Foxandxss** [comment]
I am with you on that one.
