### ISSUE TITLE
Query on quickstart article missing .json files

### ISSUE THREAD

**Issue by sanket360** [angular/angular.io#2898]
Earlier in [quickstart](https://angular.io/docs/ts/latest/quickstart.html) article on angular.io, I used to refer these configurations files - package.json, systemjs.config.js, tsconfig.json and typings.json

Now, I am not able to find these files and their explanation. Could anyone please share exact link from angular.io for these files and explanation?

**Comment by wardbell** [comment]
See the "[Setup Anatomy](https://angular.io/docs/ts/latest/guide/setup-systemjs-anatomy.html)" guide
