### ISSUE TITLE
The selector "my-heroes" did not match any elements during the Routing tutorial

### ISSUE THREAD

**Issue by a14n** [angular/angular.io#2904]
Following the [Routing part of the tutorial](https://angular.io/docs/dart/latest/tutorial/toh-pt5.html) I get the following error at the end of the part _Add Routing_ :

```
Exception: The selector "my-heroes" did not match any elements
```

So far, there was no issue and I think that my code is the same as the snippets provided in the tutorial.

(Dart VM version: 1.20.1 + angular-2.1.1)

/cc @chalin @kwalrath

**Comment by chalin** [comment]
Bonjour Alexandre: thanks, I'll look into it this afternoon.

**Comment by chalin** [comment]
Alexandre, you wrote:
> I get the following error at the **end** of the part Add Routing

Just _before_ the "Add Routing" section we have the text:
> The app still runs and still displays heroes. Our refactoring of AppComponent into a new AppComponent and a HeroesComponent worked! We have done no harm.

Did you test your app at that point and if so, did it run with out errors?

I carefully redid the tutorial and I'm not getting the error that you mention neither at the start, nor once I reach the end of the "Add routing" section. Maybe double check spellings of selectors and element tags? Otherwise, I might need to see the actual code.

**Comment by a14n** [comment]
humm, I think I figure out what was the issue.

When I renamed `app_component.dart` file to `heroes_component.dart` and `AppComponent` to `HeroesComponent` my IDE (intellij) refactored also `main.dart` and I ended up with the following `main.dart`:

```dart
import 'package:angular2/platform/browser.dart';
import 'package:ng_tuto/heroes_component.dart';

void main() {
  bootstrap(HeroesComponent);
}
```

instead of :

```dart
import 'package:angular2/platform/browser.dart';
import 'package:ng_tuto/app_component.dart';

void main() {
  bootstrap(AppComponent);
}
```

BTW I noticed a little issue with the `lib/heroes_component.dart (showing renamings only)` snippet. There's a `_router` formal parameter that remains undefined at the step :

>The app still runs and still displays heroes. Our refactoring of AppComponent into a new AppComponent and a HeroesComponent worked! We have done no harm.

Thanks for your time :)

**Comment by chalin** [comment]
Ah, that is a real problem (and will likely happen again). Reopening this until we find a way to address this in the prose. @kwalrath, any ideas?

> BTW I noticed a little issue with the lib/heroes_component.dart (showing renamings only) snippet. There's a _router formal parameter that remains undefined at the step

Yes, thanks, that is addressed in #2907

**Comment by kwalrath** [comment]
@jwren might have an opinion on whether writing around this is the best/only approach.

**Comment by chalin** [comment]
Maybe it would be sufficient to add a short note suggesting that the reader **just do a local file rename (without triggering IDE refactoring)** would be sufficient.  How does that sound to you?
