### ISSUE TITLE
Test docs "Always get the service from an injector"

### ISSUE THREAD

**Issue by zoechi** [angular/angular.io#2910]
I don't understand what this means. 

https://github.com/angular/angular.io/blob/424645e1df0a39a9318c68a0994530f71e1c293f/public/docs/ts/latest/guide/testing.jade#L633

A few paragraphs above 

```ts
userServiceStub = {
  isLoggedIn: true,
  user: { name: 'Test User'}
};
```

is provided with `useValue`

    providers:    [ {provide: UserService, useValue: userServiceStub } ]

How can this lead to get a different instance?

**Comment by zoechi** [comment]
I guess this is because one is created outside `beforeEach` and another one inside.

See also http://stackoverflow.com/questions/40882395/why-does-angular-2-provider-usevalue-clone-objects?noredirect=1#comment68979871_40882395

**Comment by wardbell** [comment]
That answer didn't make sense to me. I still don't know why this is so. It has nothing to do with testing, btw. You get the same effect in a production app.

I filed as a bug a long time ago. Still unresolved. See https://github.com/angular/angular/issues/10788
