### ISSUE TITLE
Why is the final Heroes Tour example so slow?

### ISSUE THREAD

**Issue by ubershmekel** [angular/angular.io#2939]
It's as though there's a 1 second delay between click to response.

Compare the performance between the two last chapters:

* https://angular.io/resources/live-examples/toh-5/ts/eplnkr.html
* https://angular.io/resources/live-examples/toh-6/ts/eplnkr.html

Something in the in-memory webserver is making everything slow to the point I feel this makes angular look bad.

**Comment by wardbell** [comment]
The in-memory-web-api adds a default delay of 500ms to simulate latency. This is documented in the [readme](https://github.com/angular/in-memory-web-api#default-delayed-response)

**Comment by firecodergithub** [comment]
This really should be documented in the tutorial, was ready to give up on angular thinking that simple JSON parsing and such was making it perform so badly

**Comment by Foxandxss** [comment]
Good point, will have it in mind for an update we have in the pipeline
