### ISSUE TITLE
StyleGuide - Lazy Loaded Folder Naming

### ISSUE THREAD

**Issue by anorborg** [angular/angular.io#2944]
I've seen a few references to prefixing lazy-load folder with a plus ('+'), but nothing in the documentation. Its even used in the angular universal seed application and I see references in blogs:

https://medium.com/@daviddentoom/angular-2-lazy-loading-with-webpack-d25fe71c29c1#.rp4lte8fp

Seems like maybe it should be in the style guide.

**Comment by wardbell** [comment]
No. That idea was floating about for awhile but is officially dead. Don't do it.
