### ISSUE TITLE
Help page : Should use an Angular2 plunkr app instead of AngularJS

### ISSUE THREAD

**Issue by Gillespie59** [angular/angular.io#298]
The plunkr defined in the `help` page redirect to an AngularJS 1 sample application. Should be maybe Angular 2 ;)

https://angular.io/docs/ts/latest/help.html

**Comment by manekinekko** [comment]
Here: http://plnkr.co/edit/xTyGA7Klq8Mta2T1yANh?p=preview

**Comment by PascalPrecht** [comment]
This will be fixed with https://github.com/angular/angular.io/pull/368

Can this be closed?

**Comment by wardbell** [comment]
The plunker owner should update it to remove the traceur script load as it isn't needed. Keeping up with the parade of alphas is a different matter ;-)

**Comment by ericmartinezr** [comment]
Shouldn't be the owner of the plnkr be an angular team member? Assuming @manekinekko is not, if he is then shame on me.

**Comment by manekinekko** [comment]
@ericmartinezr I'm not part of the Angular core team. But I am an Angular GDE if this may help.

**Comment by PascalPrecht** [comment]
I think this is fine for now as examples will be moved to the docs anyways.
This is just a temporary solution.

**Comment by manekinekko** [comment]
Yes. this was a temporary fix so we can close this issue. I think having an *official* plunkr for alphas doesn't make sense since it's time consuming. 
We should instead have a official plunkr starter for betas and RCs.
