### ISSUE TITLE
Creating a PDF from the Docs section for offline reading and for placing on corporate networks

### ISSUE THREAD

**Issue by havascolino** [angular/angular.io#2986]
I am creating a learning site on an internal network to learn Angular 2. Creating a PDF of the docs to download would be very useful.

**Comment by JBusch** [comment]
I second that. would love to read the docs on my ebook reader!

**Comment by Foxandxss** [comment]
We will have offline support soon in a new site. But no PDF creation.

**Comment by lazaridis-com** [comment]
[issue.feature]
