### ISSUE TITLE
ngIf can use a <template>

### ISSUE THREAD

**Issue by infofromca** [angular/angular.io#2987]
on page of
https://angular.io/docs/ts/latest/guide/structural-directives.html#!#definition
according to 
https://github.com/angular/angular/issues/13490#event-894961894
this is wrong now:
What does this have to do with ngIf and ngFor? We didn't use a <template> tag with those directives.

**Comment by wardbell** [comment]
What is "_wrong now_"? Where is the contradiction?

#13490 comment says:
>You can use `<template [ngIf]="expression"><li>....</li></template>`. Closing as already supported.

Structural Directives mentions: 
```ts
<template [ngIf]="condition">
  <p>
    Our heroes are true!
  </p>
</template>
```
Closing as not-actionable. Happy to re-open once you clarify and show us what's wrong.

**Comment by infofromca** [comment]
What does this have to do with ngIf and ngFor? We didn't use a tag with those directives.

**Comment by Foxandxss** [comment]
I fail to see your problem.

**Comment by infofromca** [comment]
is "What does this have to do with ngIf and ngFor? We didn't use a tag with those directives"  a problem?
if yes, look for it in the middle on the page.

**Comment by Foxandxss** [comment]
Sorry, I keep failing to see your problem. Let's start over.

Do you want to know the difference between `*ngIf` and using a template with `[ngIf]` ?

**Comment by zoechi** [comment]
Shouldn't this be mostly obsolete or at least discouraged, since the introduction of `<ng-container>`?

**Comment by Foxandxss** [comment]
No, the use of <ng-container> is not yet the "preferred way"

**Comment by zoechi** [comment]
@Foxandxss There seems to be missing something from your comment
Is `<ng-container>` not yet the preferred way?

**Comment by Foxandxss** [comment]
It is a proposal to replace <template> with that, but as far as I know, not yet accepted.
