### ISSUE TITLE
Documentation Issues in angular for javascript - API Reference

### ISSUE THREAD

**Issue by rajkumarui** [angular/angular.io#2989]
Please give examples using JavaScript and proper guidance for API Reference. When I select Angular for JavaScript in API Reference. It shows same page for both Typescript and JavaScript. There is know proper documentation for JavaScript. Hope in feature we have very good documentation JavaScript. There current Angular2 documentation forcing me to learn Typescript.  Please provide a documentation for JavaScript which gives confidence that we can build Angular2 with JavaScript alone.

**Comment by Foxandxss** [comment]
API reference needs to be reported at the angular repo.

**Comment by tilwinjoy** [comment]
It's funny that I requested for the missing JS documentation in the Angular repo and I was told to re-open it here. I come here and see this...

**Comment by Foxandxss** [comment]
One thing is documentation per se (which we manage) and other thing is API documentation (which the core team manages on their repo, because it is embedded in the code)

**Comment by khuongduybui** [comment]
Please reopen.
All developer guide pages are empty.
Please either DECLARE that Javascript is not supported, or actually SUPPORT it.

**Comment by Foxandxss** [comment]
This is entirely a different issue.

**Comment by khuongduybui** [comment]
What did you mean, then, by "documentation per se"? I'm clueless as for who (which repository) is responsible for developer guides / tutorials / etc.

**Comment by khuongduybui** [comment]
Oh, if you mean "developer guides" should be another issue in this repository, I will find or create one.

**Comment by Foxandxss** [comment]
This issue was for API not the guides. That is why I closed it, it is not related to this repo.

And there is no need for new issues, we have some already.

**Comment by khuongduybui** [comment]
Is there anyway we (enthusiasts) can track the (lack of) Javascript documentation issue?

**Comment by wardbell** [comment]
**JavaScript _is_ supported and the docs say so.**

Have you looked at the "[TypeScript to JavaScript](https://angular.io/docs/ts/latest/cookbook/ts-to-js.html)' cookbook? It explains in great detail how to translate between Angular-in-TS and Angular in several dialects of JS.

What you won't find is translations of every TS doc into their JS equivalents.  That is big job and the appropriate resources are very busy adding/fixing TS documentation.

So I'm curious ... in what ways is that cookbook inadequate? If that cookbook was all you had, would you still say that Angular doesn't support JS? Why?

**Comment by khuongduybui** [comment]
I took a look at the cookbook. Apart from some inconsistencies between the examples it's fairly easy to follow. I will definitely give it a try this weekend, but so far there's no real inadequacy to call out. Thank you very much for pointing it out. To be honest that cookbook (or the link to it) should be on the home page of JS docs.

**Comment by wardbell** [comment]
Please highlight inconsistencies and call out any trick in TS that you don't know how to perform with reasonable grace in JS.

**Comment by khuongduybui** [comment]
For example, in the *Exporting Application Code* examples, only the JS version has annotations. When I first glanced over it I couldn't help asking myself "how the hell do I know what annotations to put in that array?" I figured out a few minutes later, but still...

I will have more useful feedbacks after I try to actually use the instructions in the cookbook this weekend.
One more time, thank you very much for pointing it out.

**Comment by bannazz** [comment]
Okay, the cookbook link is no longer working. please refer to any other resource that elaborate on how to do anything useful in angular 2 using javascript. you can't expect the whole javascript community to favor a new language and stop javascripting!

**Comment by bannazz** [comment]
you are losing a LOT of supporters in the community thanks to that lack of documentation. I can't imagine how its taking you YEARS to add the documentation of the key language here.

And frankly your _slow it down so they learn typescript forceably_ strategy can't work anyway because typescript is awful to some of us (me) just for what it is, a language made by microsoft that is not even stable yet and being forceably taught through taking away a major web framework from existence and change its core programming language to "super set of bla bla"  then later on....much later on announce, hey we don't support js anymore take your pick js or us.

I don't know why the heck did I trust google with a framework anyway...it was a mistake and thanks to you I will never make it again without those docs. thanks for setting me right

But just open the damned issue and declare a time where this is gonna be ready because your "please bear with us" from v2 docs didn't say for years, and it definitely didn't exist at all in the angular 4 docs. its like saying....that's the norm now....deal with the normal totally not cross platform and totally not reusable thing.

**Comment by bannazz** [comment]
Did it not occur to you to add the docs of version 2 for javascript through the whole development time and the whole time it took to make it to v 4.x? its not taking long, its being removed slowly and very VERY noticeably!!

**Comment by bannazz** [comment]
Did it not occur to you to add the docs of version 2 for javascript through the whole development time and the whole time it took to make it to v 4.x? its not taking long, its being removed slowly and very VERY noticeably!!

**Comment by bannazz** [comment]
for example I do not (and can not) compile a single bit of my code using a microsoft product, for security reasons

will I be able to use this thing ever?

**Comment by khuongduybui** [comment]
To be honest I moved on after Dec 2016 and never looked back.

On a side note I almost moved on past NativeScript as well, but they added a pure Javascript (non Ts, non Angular) version with *thoughtful* docs and *working* examples.

**Comment by bannazz** [comment]
Wish some people from angular 2+ could do the same really, but this looks big, like a political or financial major agenda role here. js is huge, they knew for a fact that this will be very annoying ahead of publishing version 2.0. but they still did it and are doing it still.

**Comment by bannazz** [comment]
Why didn't anyone reply so far!
Should I protest for it?

ADD THE DOCS!
MAKE ANGULAR GREAT AGAIN! XD

**Comment by Foxandxss** [comment]
You need to realize that this repo is dead and no one is looking at it. Just me, I still receive the emails because I posted here.

**Comment by bannazz** [comment]
Okay, any proper way to have an answer to my(and everyone else's) question?

How to use this in js?
Where can I find the knowledge to do that?
When are the docs going to be published? (because they are surely complete long ago; they write it before they write the code, its google)

**Comment by khuongduybui** [comment]
1. Looks like the code for documentation are moved to the main repo: https://github.com/angular/angular/tree/master/aio/content

2. I quickly glanced at the open issues in that repo and saw nothing about Javascript. I guessed people who want to use Javascript have abandoned angular.

**Comment by khuongduybui** [comment]
But just in case you want to vent your frustration and file an issue on that main repo, feel free to mention me 👍

**Comment by Foxandxss** [comment]
Typescript is javascript. Just have extra optional features.

**Comment by khuongduybui** [comment]
Thanks for your very useful observation @Foxandxss.
We all know for sure we CAN use Angular with Javascript only.
We just don't know HOW.

**Comment by tilwinjoy** [comment]
@bannazz  pssst, you easily [annoy these people](https://github.com/angular/angular.io/issues/919#issuecomment-268562851) if you ask for JS documentation.

@khuongduybui  yes I was an angular 1.x user and I chased this issue in between their changing repos, eventually abandoned Angular.

**Comment by Foxandxss** [comment]
Open an issue if you wish in the angular repo, this is deprecated and goes nowhere.
