### ISSUE TITLE
Link Brocken - 404 Not Found in Angular Quick-Start

### ISSUE THREAD

**Issue by frostyandy2k** [angular/angular.io#2999]
At URL:
https://angular.io/docs/js/latest/quickstart.html

Following link is broken in the styles.css file pointing to the full set of master styles:
https://github.com/angular/angular.io/blob/master/public/docs/_examples/styles.css

In chapter "Add some style"

Thank you for the nice tutorial!

**Comment by wardbell** [comment]
Thanks ... but we are about to replace all of the JS docs and this error will be rendered moot.

**Comment by JChrist** [comment]
I'm not sure whether this replacement you mentioned is related to the ts docs as well, but the broken link appears on https://angular.io/docs/ts/latest/tutorial/toh-pt5.html as well.
The current link is: https://raw.githubusercontent.com/angular/angular.io/master/public/docs/_examples/_boilerplate/styles.css

while (I believe) it should be:
https://raw.githubusercontent.com/angular/angular.io/master/public/docs/_examples/_boilerplate/src/styles.css
