### ISSUE TITLE
Change link on the homepage to point to the ng-conf playlist

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular.io#3]
keynote1 + playlist: https://www.youtube.com/watch?v=QHulaj5ZxbI&index=1&list=PLOETEcp3DkCoNnlhE-7fovYvqwVPrRiY7

or playlist alone: https://www.youtube.com/playlist?list=PLOETEcp3DkCoNnlhE-7fovYvqwVPrRiY7

**Comment by IgorMinar** [comment]
Can you please also update the link at https://angular.io/docs/js/latest/resources.html and move it before the ng-europe link?

**Comment by alexwolfe** [comment]
Sure, David updated this earlier but I rolled back because it blew away some previous changes. Can fix tonight

**Comment by alexwolfe** [comment]
fixed
