### ISSUE TITLE
I can add a reference to a component without closing the tag - causes it to load twice.

### ISSUE THREAD

**Issue by iainplimmer** [angular/angular.io#3009]
I can make a reference to a component that I create in another component as follows:

    `<app-tasklist></app-tasklist>`

However, if i do not close the tag......

    `<app-tasklist><app-tasklist>`

The component is actually loaded twice if the component tag is not closed. The compiler should realise that this is a typo and give a warning. At the moment (for someone who has tried to get started with NG2 a couple of times in BETA to have a feel around), it just feels like the issue is with import statements, or a bug in the compiler and is frustrating.

**Comment by Foxandxss** [comment]
If you feel it is a bug, create a plunker reproduction and post it at angular/angular. This repo is only for documentation issues.

Thanks.

**Comment by iainplimmer** [comment]
My mistake @Foxandxss, sorry about that ;)
