### ISSUE TITLE
Adding http://courses.wishtack.com/angular-2 free online training to resources

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular.io#3023]
Hi,

Is there a way to add my free online training http://courses.wishtack.com/angular-2 to angular.io/resources ?

For the moment, it's in french but will soon be translated to english :)

Thank you in advance.

Younes

**Comment by juleskremer** [comment]
@StephenFluin

**Comment by yjaaidi** [comment]
Thx Jules

**Comment by StephenFluin** [comment]
This is now live and I believe it can be closed.

**Comment by yjaaidi** [comment]
@juleskremer @StephenFluin Thank you very much!!!
