### ISSUE TITLE
Angular2 UrlResolver - class AppComponent_Host - inline template:0:0 caused by: No provider for Token Application Packages Root URL

### ISSUE THREAD

**Issue by vijender1256** [angular/angular.io#3028]
I am trying to resolve the image URL's:

**app.module.ts code**
```
import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { AppComponent } from "./app.component";
import { routing, appRoutingProviders } from "./app.routing";
import { Routes, RouterModule } from "@angular/router";
import { UrlResolver } from '@angular/compiler';

const routes: Routes = [
];

@NgModule({
    imports: [
        BrowserModule,
        routing,
        RouterModule.forRoot(routes, { useHash: true })
    ],
    declarations: [
        AppComponent
    ],
    providers: [
        appRoutingProviders, UrlResolver
    ],
    bootstrap: [AppComponent]
})
export class AppModule {
}
```

**app.component.ts code:**

```
import { Component } from "@angular/core";
import { Router } from "@angular/router";
import { UrlResolver } from '@angular/compiler';

@Component({
    moduleId: module.id,
    selector: "my-app",
    templateUrl: "app.component.html"
})
export class AppComponent {
    constructor(private urlResolver: UrlResolver) { }

    public resolvePath(path) {
        return this.urlResolver.resolve(module.id, path);
    }
}
```

I am providing UrlResolver, but the constructor injection of UrlResolver is causing error:

![image](https://cloud.githubusercontent.com/assets/12258728/21437850/2fcd3834-c854-11e6-9dd3-d54ed14dab2f.png)

**app.component.html code**
```
 <img [src]="resolvePath('Logo.jpg')" alt="Logo" width="50" height="50">
```
why error on constructor injection, should I add anything in providers ?

**Comment by mlc-mlapis** [comment]
Because "UrlResolver" depends on '@angular/compiler' this is not an usable way at all. It is not possible to in AOT mode but only in JIT mode.

**Comment by vijender1256** [comment]
@mlc-mlapis what is the alternative way to fix the issue ? Thanks

**Comment by mlc-mlapis** [comment]
As I know just your own function with the same functionality. You can take some information from "__moduleName" (if SystemJS is used or a suitable alternative for other loaders):
```
private componentBaseUrl: string = __moduleName.substring(0, __moduleName.lastIndexOf('/')) + '/';
```

**Comment by vijender1256** [comment]
This is my tsconfig.json, in future someone from A2 team answering question might point out what needs to be changed in this file as well:

```
{
  "compilerOptions": {
    "outDir": "build/dist/app",
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules",
    "build"
  ]
}
```

**Comment by mlc-mlapis** [comment]
Probably nothing directly in this file but the solution has to be something what works crossover JIT, AOT, loaders, ...

**Comment by vijender1256** [comment]
@mlc-mlapis thank you for the help :)

**Comment by vijender1256** [comment]
For people who had same issue I had this work around to get the relative URL's. I have my application deployed on to my server and after that it had issues finding the html files as all my folders are under Virtual directory in IIS:

http://dabsaa01/Ebr/build/dist/app/app.component.html -->404 not found

however it has no problem while testing in local pc as the URL is

http://localhost:20313/build/dist/app/app.component.html --> able to find it since it in the proper location in the project directory. 

This issue is due to the Ebr virtual directory on IIS , its unable to find the path since Ebr in the path, even after me using module.Id concept and html resides in the same folder as js.

Here is the possible workaround for local vs application on server:

**customUrlResolver.ts code:**

```
import { UrlResolver } from '@angular/compiler';

export class CustomUrlResolver extends UrlResolver {
    resolve(baseUrl: string, url: string): string {
        let nUrl = super.resolve(baseUrl, url);
        let appUrl = nUrl;
        if (!(nUrl.indexOf("localhost") >= 0)) {
            appUrl = "." + appUrl;
        }
        return appUrl;
    }
}
```
**main.ts code**

```
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";
import { UrlResolver } from '@angular/compiler';

import { AppModule } from "./app.module";
import { CustomUrlResolver } from './customUrlResolver';

platformBrowserDynamic().bootstrapModule(AppModule, {
    providers:
    [
        { provide: UrlResolver, useClass: CustomUrlResolver }
    ]
});
```

**app.module.ts code**

```
import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { AppComponent } from "./app.component";
import { routing, appRoutingProviders } from "./app.routing";
import { Routes, RouterModule } from "@angular/router";
import { UrlResolver } from '@angular/compiler';

const routes: Routes = [
];

@NgModule({
    imports: [
        BrowserModule,
        routing,
        RouterModule.forRoot(routes, { useHash: true })
    ],
    declarations: [
        AppComponent
    ],
    providers: [
        appRoutingProviders, UrlResolver
    ],
    bootstrap: [AppComponent]
})
export class AppModule {
}
```
With above code it is fixing issue with relative urls even with virtual directory on IIS.

How ever i had issues finding images url, since its in different folder structure:

here is the workaround:
```
import { Component } from "@angular/core";
import { Router } from "@angular/router";
import { UrlResolver } from '@angular/compiler';

@Component({
    moduleId: module.id,
    selector: "my-app",
    templateUrl: "app.component.html"
})
export class AppComponent {
    constructor(private router: Router) { }
    private logo: string = "";
    public resolvePath(path) {
        if (!(this.logo.length > 0)) {
            this.logo = module.id.substring(0, module.id.lastIndexOf('build')) + 'src/Content/images/logo.jpg';
            }
        return this.logo;
    }
}
```

Anyone from Angular team, please explain how to fix this issue without all these workaround code, for now I am living with this workaround thanks :)

**Comment by wardbell** [comment]
This is not an angular.io issue. You might try your luck with an [angular issue](https://github.com/angular/angular/issues)
