### ISSUE TITLE
Angular2 Docs

### ISSUE THREAD

**Issue by tbragaf** [angular/angular.io#303]
Hi all!

I already posted this on angular/angular, and I was forwarded here. Please follow this path.
1. https://angular.io/cheatsheet
2. Title "Directive and component change detection and lifecycle hooks (implemented as class methods)" (use find)
3. afterViewInit() Description.

It says "Called after onContentInit when the component's view has been initialized. Applies to components only.".

Called after afterContentInit() right?

Stay awesome,
Tiago Braga

**Comment by wardbell** [comment]
Fixed
