### ISSUE TITLE
Consuming an Angular2 component hosted on a remote endpoint 

### ISSUE THREAD

**Issue by smangalath** [angular/angular.io#3033]
This is not an issue with any angular modules directly , however , i am interested to know if any patterns already available to solve this problem.

Context
I have an angular2 component that is hosted on a remote endpoint. It is bundled using webpack2.
Now one of our sister groups wants to consume this component in their angular2 based application which will be using  webpack2 for app bundling

Problem
How would the application download the component bundle and integrate with the app in the runtime.

**Comment by Foxandxss** [comment]
This kind of questions belongs to stackoverflow. Sorry

**Comment by smangalath** [comment]
thanks, just curious   if angular cli team has encountered or visualized such a use case ?
