### ISSUE TITLE
SearchBox on the sidebar doesn't work due to CORS

### ISSUE THREAD

**Issue by e-cloud** [angular/angular.io#3044]
See 
![image](https://cloud.githubusercontent.com/assets/5255354/21542432/9d51ef9a-cdf8-11e6-8e57-cb622c6f4b4a.png)

**Comment by Foxandxss** [comment]
Is that the chinese page? I never saw that with our normal page.

If it is, open an issue in their repo and if not, I am closing this because we are migrating.
