### ISSUE TITLE
Outdated Routing documentation

### ISSUE THREAD

**Issue by vadim-shb** [angular/angular.io#3055]
Outdated Routing documentation. In official documentation here:
https://angular.io/docs/ts/latest/guide/router.html
Paragraph "Milestone #3: The Heroes Feature" is outdated. Can not strictly follow the instructions, because file names and some parts of code not based on current version of "Tour of Heroes" (which is here: https://angular.io/resources/live-examples/toh-5/ts/eplnkr.html)

For example there is no hero-list.component.ts and HeroListComponent class in current version of "Tour of Heroes"

**Comment by wardbell** [comment]
Pretty messed up, mainly because it refers to the wrong episode of the tutorial: should have been based on the "Services": https://angular.io/resources/live-examples/toh-4/ts/eplnkr.html

While this isn't supposed to be a word-for-word tutorial, we agree that we should be much more on target.

Will correct in forthcoming PR.

**Comment by vadim-shb** [comment]
1) There is no RouterModule in "Services" (https://angular.io/resources/live-examples/toh-4/ts/eplnkr.html) part. Do you really think, that advanced "Routing & Navigation" documentation can be based on this episode of tutorial? RouterModule appears in "Routing" episode, so my link was correct.

2) Now I realise, that this issue not only about "The Heroes Feature" milestone. But also about whole "Routing & Navigation" chapter, which is based on outdated tutorial (possibly RC5 or something). I agree that this is minor issue. But still an issue. So why do you close it before actualization of documentation?

**Comment by wardbell** [comment]
Yes, I know there is no routing in "Services".  I wanted to grab code for the routing guide _before_ the Tour of Heroes tackles routing. This is, after all, a separate guide to routing. That is why I believe the source should be copied from "Services", not "Routing".

Moreover, the code for the heroes feature is much simpler in "Services" than in "Routing". For example, there are no separate HTML and CSS files to worry about.

I don't see what you mean about "outdated". We're just trying to grab some code for the heroes here ... enough to keep the routing discussion moving forward and without rewriting a bunch of code that doesn't illuminate routing. I fail to grasp your objection.

Closed this issue so I wouldn't forget to get it later. Sorry, that is premature of me. I'm working on it today. All will become clear soon I hope.

**Comment by vadim-shb** [comment]
Oh, I see... This misunderstanding because I started advanced "Routing & Navigation" guide from Milestone 3 chapter (I was interested only in RouterModule.forChild() understanding). This chapter links to "Tour of hero" tutorial so I thought I can start from it. I miss first couple milestones, which could get start point in "Services".

**Comment by wardbell** [comment]
Not _your_ problem. In fact, you lead me to some things that needed improvement. Thanks.
