### ISSUE TITLE
The code in the appendix section of the services section of Angular tutorial is wrong

### ISSUE THREAD

**Issue by velkur** [angular/angular.io#3057]
Link: https://angular.io/docs/ts/latest/tutorial/toh-pt4.html#!#slow

It is currently:
'''
getHeroesSlowly(): Promise<Hero[]> {
  return new Promise(resolve => {
    // Simulate server latency with 2 second delay
    setTimeout(() => resolve(this.getHeroes()), 2000);
  });
}'''

It should be:
'''
getHeroesSlowly(): Promise<Hero[]> {
  return new Promise(resolve => {
    // Simulate server latency with 2 second delay
    setTimeout(() => resolve(HEROS, 2000);
  });
}
'''

**Comment by wardbell** [comment]
Nope. Both work.  The `resolve` method accepts either a value or a promise of a value such as that returned by `getHeroes()`.
