### ISSUE TITLE
Adding http://www.learn-angular.fr to resources

### ISSUE THREAD

**Issue by wKoza** [angular/angular.io#3069]
Hi,

Can i propose a PR to add les link http://www.learn-angular.fr to angular resources ?  This blog is a set a courses about Angular. 

It's in french. 

Thank you in advance.

William

**Comment by wKoza** [comment]
Hi,

@StephenFluin, are you ok to add this link to Angular ressources ? 

ty
William

**Comment by StephenFluin** [comment]
@wKoza I've added you to the index temporarily, but please be aware that list list is undergoing changes, and will soon be reduced in number of posts and refocused on more traditional courses rather than self-driven blog style content.

**Comment by wKoza** [comment]
thanks @StephenFluin !
