### ISSUE TITLE
bad `ngStyle` example

### ISSUE THREAD

**Issue by zoechi** [angular/angular.io#3072]
https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ngStyle

```ts
setStyles() {
  let styles = {
    // CSS property names
    'font-style':  this.canSave      ? 'italic' : 'normal',  // italic
    'font-weight': !this.isUnchanged ? 'bold'   : 'normal',  // normal
    'font-size':   this.isSpecial    ? '24px'   : '8px',     // 24px
  };
  return styles;
}
```
should IMHO be considered as **DON'T** example

- It binds a method in the view `[ngClass]="setClasses()"` which is discouraged and should be avoided except one knows what she's doing

- It returns a new instance for every call. If it would at least cache the result in an instance field and return that as long as not dependencies are changed, it would be ok.

**Comment by zoechi** [comment]
> except one knows what she's doing

I mean that demonstrating binding to methods in docs without special mention of the pitfalls is a bit dangerous because people might not know about the pitfalls.
If you know that the method must not return a new instance every time it's called, and that the method shouldn't do expensive work, then binding to a method is just fine.
Binding to a getter is basically the same but I think it's known more widely that getters shouldn't do expensive work.

**Comment by wardbell** [comment]
Do you really think someone is going to treat this as a recommended practice. The point is to show how the `NgClass` works _syntactically_.

I'd happily look at a PR. I'm worried that, in making it "correct", we'll lose sight of the point.  If you can keep it simple, I'm interested.

**Comment by zoechi** [comment]
> Do you really think someone is going to treat this as a recommended practice. 

That's why I created this issue, because someone was arguing on SO that this should work because it is even explained this way at (with the link in my original issue comment).

Changing it to 
```ts
styles = {
    // CSS property names
    'font-style':  this.canSave      ? 'italic' : 'normal',  // italic
    'font-weight': !this.isUnchanged ? 'bold'   : 'normal',  // normal
    'font-size':   this.isSpecial    ? '24px'   : '8px',     // 24px
};
setStyles() {
  return styles;
}
```
would already fix the main issue but then 
```ts
styles = {
    // CSS property names
    'font-style':  this.canSave      ? 'italic' : 'normal',  // italic
    'font-weight': !this.isUnchanged ? 'bold'   : 'normal',  // normal
    'font-size':   this.isSpecial    ? '24px'   : '8px',     // 24px
};
``` 
with
```html
<div [ngStyle]="styles">
```
would also do.

I'm not sure what of this is part of the point that is supposed to be made by this example.

**Comment by ph55** [comment]
> Do you really think someone is going to treat this as a recommended practice.

Well, here I am.

Whole discussion started from [stackoverflow question](http://stackoverflow.com/questions/41471232/angular2-template-expression-called-twice-for-each-component-on-change-detection)
In case of rendering multiple components of the same type, `setStyles()` would be called on each of them when change detection runs.

From docs:
> The NgStyle directive may be the **BETTER CHOICE** when we want to set many inline styles at the same time.

As you see, its not just 

> show how the NgClass works syntactically

Its actually proposed as preferred option without explaining pitfalls.

**Comment by wKoza** [comment]
Ok well, I prefer the second option 

`
styles = {
    // CSS property names
    'font-style':  this.canSave      ? 'italic' : 'normal',  // italic
    'font-weight': !this.isUnchanged ? 'bold'   : 'normal',  // normal
    'font-size':   this.isSpecial    ? '24px'   : '8px',     // 24px
};
`
with
`
<div [ngStyle]="styles">
`

We can understand how NgStyle directive works syntactically.

**Comment by wardbell** [comment]
Ya all **nailed** me for being a grumpy old man. I'll get out a PR.  Thanks for making the case.

**Comment by zoechi** [comment]
No worries :smile:,  :heart: your work!

**Comment by wardbell** [comment]
Fixing in PR #3076
