### ISSUE TITLE
Can't see previous versions of Documentation

### ISSUE THREAD

**Issue by jtillman** [angular/angular.io#3084]
On the documentation site "angular.io", you only are given the latest version of documentation and no way to select which version of the documentations you are attempting to develop on. 

I'm in a scenario where I can't upgrade to the latest version because another framework doesn't yet support it, but I am unable to correctly setup a working build because dependencies have change drastically between builds.

**Comment by wardbell** [comment]
>have changed drastically between builds

Really? There have been no breaking changes since the release of 2.0.  What build are you talking about.

In any event, we have no intention of providing documentation for any pre-release build. Sorry. Must close.

**Comment by jtillman** [comment]
Interesting response. As far as I can tell, angular's library dependencies have change in version increments especially with the different polyfill requirments from version to version as you all try to make things more self contained. I know from a webpack configuration standpoint, things have change. Anywho, your call.
