### ISSUE TITLE
Redirect after async call does not display the page

### ISSUE THREAD

**Issue by sergiulucutar** [angular/angular.io#3089]
I have a problem with the redirecting of a certain page in case of a 500 response. So I have the following code:

```  
    notifyError(err){
        this.router.navigateByUrl('/error');
    }

    myGet(url) {
        let response = super
          .get(url)
          .timeout(3)
          .share();

        response.subscribe(
          this.success.bind(this),
          this.handleError.bind(this)
        );
        return response;
      }
```

I call the get method and  subscribe to the returned result like this:

```  
    response = this.myCustomhttp.myGet(userUrl);

    response .subscribe(
      this.handleUserData.bind(this),
      this.handleUserError.bind(this)
    );
```

For both subscribers, the error callback gets called, so both the redirect and the handleUserError gets executed. The problem is the page gets stuck until the timeout is reached and then the error page is displayed. I've seen that if I click on the page while it is stuck, it resumes the normal flow. Can anyone help me with this ?

**Comment by mattdistefano** [comment]
You probably want to post this on StackOverflow or https://github.com/angular/angular/issues - this repo is just for issues with the angular.io website, so unless you're requesting documentation changes, you won't get much help here.

**Comment by wardbell** [comment]
@mattdistefano is correct. I'd have answered anyway if the answer was immediately obvious but there isn't enough context for that. So, with sadness, I'm closing and urging you to take your case to S.O.
