### ISSUE TITLE
README using wrong nvm link

### ISSUE THREAD

**Issue by fvanwijk** [angular/angular.io#309]
Are you sure that nvm from npmjs.org is the correct one?
When installing it give a deprecated warning. It think you should install from `nvm.sh`.
See creationix/nvm#304

**Comment by filipesilva** [comment]
It seems to be the wrong one, since two lines below you're asked to run `nvm use 4`, which isn't part of the commands provided by the `npm` found in `npmjs.org`. I'll put up a PR.

**Comment by fvanwijk** [comment]
Note the difference between `npm` and `nvm`.
I had to run `npm install 4` before I could run Node 4.

**Comment by filipesilva** [comment]
Sorry, my bad. I meant 'provided by the `nvm`' instead.
