### ISSUE TITLE
"Test a component with an external template" is not necessary

### ISSUE THREAD

**Issue by Iar0** [angular/angular.io#3098]
Following the testing docs, I found that the [Test a component with an external template](https://angular.io/docs/ts/latest/guide/testing.html#!#component-with-external-template) section is not necessary. 

Omitting that using "moduleId: module.id" is not necessary anymore, I run and tested a basic component with external template and stylesheet as described in the [Test a component](https://angular.io/docs/ts/latest/guide/testing.html#!#simple-component-test) section. Using the same approach, the tests were successfully accomplished.

Am I wrong or it can be removed from the docs? 

ps: I use angular 2.2.3

**Comment by Foxandxss** [comment]
what were you using? Webpack?

**Comment by Iar0** [comment]
My bad, I created a new project with the CLI that switched to Webpack as told [here](https://github.com/angular/angular-cli#webpack-update). As is clearly explained in the testing's docs, "WebPack developers need not call compileComponents because it inlines templates and css as part of the automated build process that precedes running the test.". I think that the same logic apply to the use of the moduleId property.

Thank you for the quick hint!
