### ISSUE TITLE
Document what is <ng-content> tag and how content projection works

### ISSUE THREAD

**Issue by devoto13** [angular/angular.io#3099]
Searching for `ng-content` on https://angular.io/docs/ts/latest/ doesn't produce any useful results and if I'm not mistaken there is no any detailed description about what it is and how it works. There are quite some blog posts showing examples of using it. It creates a lot of confusion for users, see:

- angular/angular#13760
- angular/angular#13894
- angular/angular#13921
- angular/angular#12639
- angular/angular#13059

Points, which should probably be documented:

- projection just moves nodes from one place to another, which leads to following conclusions:
    - not possible to use projected content multiple times ([link](https://github.com/angular/angular/issues/13894#issuecomment-272557621))
    - projected nodes/components, will be always created, even if you wrap them into `*ngIf`, e.g. `<div *ngIf="false"><ng-content></ng-content></div>`. It is reason for problems in angular/angular#13760 and angular/angular#13921 ([link](https://github.com/angular/angular/issues/13921#issuecomment-272557367))
    - when using `ViewEncapsulation.Emulated` (and probably `Native` as well?) projected nodes will have encapsulation of the place, where they were created and not where, they are projected 
- how to query only subset of nodes using `<ng-content select="<selector>">`
    - document, that only top-level nodes can be selected by this approach
- document a recipe with template, Tobias referring [here](https://github.com/angular/angular/issues/13059#issuecomment-264598276) to created projected nodes only when they are needed

PS During work on this issue, it may be good idea to also improve documentation of [projectableNodes](https://github.com/angular/angular/issues/13453) as they are tied to functionality discussed here.

**Comment by artaommahe** [comment]
@devoto13 i think that `<template>`/`TemplateRef`/`ngTemplateOutlet` should be added to this section too. Their usage solved my issue with components instantiating with `ng-content` regardless real DOM state (https://github.com/angular/angular/issues/13921)

**Comment by devoto13** [comment]
@artaommahe thanks for you addition. Things you mention are actually in the last item of the list. Probably should have wrote it more clear.

**Comment by ShadowManu** [comment]
bump?

**Comment by karptonite** [comment]
I agree that documentation on this would be useful, not just to make it easier to use, but to allow us to be confident that we aren't using an "undocumented feature" that could go away unexpectedly.

**Comment by Foxandxss** [comment]
it is coming it is coming. Sorry, we are preparing cool stuff for the ng-conf and that consumes our time. We will address this shortly

**Comment by MarcelCorleone** [comment]
Has this been forgotten? "We will address this shortly." Though I'm not sure what's your definition of "shortly" but it seems to be at least 50 days.

**Comment by klinki** [comment]
I'm not sure about shortly, but eventually is more than 190 days (and I'm little bit suspicious if it doesn't mean never :( )

**Comment by Foxandxss** [comment]
In fact, we have. The problem is that we are migrating to a new site and all the changes are being made in there. We haven't update our live site in a while, that is true, because we are concentrating to this new site.

Sorry for the inconvenience.

**Comment by martinmcwhorter** [comment]
It looks like the new web site is up and running. Still cannot find any documentation on ngContent.

**Comment by Foxandxss** [comment]
What kind of documentation are you expecting?

**Comment by PadishahTJK** [comment]
just usual  documentation with  explanation  end simple  how  to use <ngcontent> and  rest

**Comment by martinmcwhorter** [comment]
Content Projection could probably use its own section in the documentation.
Anyone knew to angular may not even know this feature exists. If they do
happen to find out about it, they will have to find documentation
elsewhere.

**Comment by Foxandxss** [comment]
There are 3 guides talk mentions content projection as today.

DI in action, lifecycle hooks and ts to js.

We will see if we can put a better place for it.

**Comment by artaommahe** [comment]
@Foxandxss 
![selection_666](https://user-images.githubusercontent.com/1944061/27790012-5a54e580-5ff7-11e7-8f0e-9ed9c6d0c670.png)
![image](https://user-images.githubusercontent.com/1944061/27790036-72ff3b58-5ff7-11e7-9a23-324fbe6f2858.png)
In provided pages there is nothing about `select` and projected content lifecycle (ngIf on `ng-content` does not affect projected content initialization)

**Comment by Foxandxss** [comment]
The search is having a few problems lately, we are fixing it right now. About the API, I will double check with the team.

About the docs themselves, open an issue in the angular repo, this repo is deprecated and no one (but me) is paying attention.

Open an issue asking for docs and list what you would like to see on it.

**Comment by tomchinery** [comment]
@Foxandxss New issue created, referencing this one. https://github.com/angular/angular/issues/17983

**Comment by devoto13** [comment]
Closing in favor of https://github.com/angular/angular/issues/17983. Please subscribe to that issue for further updates.
