### ISSUE TITLE
Docs: WEBPACK: AN INTRODUCTION missing angular.png

### ISSUE THREAD

**Issue by kbdguy** [angular/angular.io#3114]
I went through the exercise step-by-step to build the project and was foiled at first attempt to npm start.  Webpack error displayed: couldn't find angular.png.  I found it and put it in folder public/images, which is where app.component.html says it should be.  Then all worked fine.

So, there needs to be instruction on installing angular.png in the instructions, or other work-around.

**Comment by Foxandxss** [comment]
There are instructions, read carefully.

**Comment by kbdguy** [comment]
perhaps somewhere, or at some time, but not now, where it counts, at url https://angular.io/docs/ts/latest/guide/webpack.html

**Comment by Foxandxss** [comment]
![](https://puu.sh/tqTNA/a26671ede5.png)

Click on the logo there.

**Comment by kbdguy** [comment]
That is terrible.  You have to hover to see the "click" instruction.  The instruction should be in the plainly readable text.

**Comment by kbdguy** [comment]
and it should instruct where to copy the file.

**Comment by Foxandxss** [comment]
Create a pull request, we are always open to improve the docs.

**Comment by kbdguy** [comment]
ok, thanks.
