### ISSUE TITLE
Angular2 testing setup not working.

### ISSUE THREAD

**Issue by aravindfz** [angular/angular.io#3124]
**I'm submitting a bug report...**  

I navigated to the [Testing Guide](https://angular.io/docs/ts/latest/testing/#!#setup) of angular. When I clicked on the [Setup Instructions](https://angular.io/docs/ts/latest/testing/setup.html) with a motive to create my first testing application I find 404 error which seems to be strange. 
**Current behavior**
**Getting 404 not found**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by Foxandxss** [comment]
We need more information. A reproduction or something.
