### ISSUE TITLE
Add sample repos or plunkers to docs

### ISSUE THREAD

**Issue by robianmcd** [angular/angular.io#3126]
**I'm submitting a ...**
```
[X] feature request
```

**Current behavior**
Many of the documentation articles in the advanced and cookbook section of angular.io/docs describe how to build a particular angular app but do not give a sample repository or plunker that demonstrates that app

**Desired behavior**
Documentation articles would link to a repo or plunker similar to the ones linked to in the quick start documentation. e.g.
https://github.com/angular/quickstart
 https://angular.io/resources/live-examples/quickstart/ts/eplnkr.html

**What is the motivation / use case for changing the behavior?**
This would make it much easier to try out the concepts being described in the documentation

Migrated from https://github.com/angular/angular/issues/14042

**Comment by wardbell** [comment]
Can you identify a guide or cookbook that _lacks_ a plunker? I think almost all of them do.

**Comment by robianmcd** [comment]
As far as I can tell the webpack guide doesn't have one 

https://angular.io/docs/ts/latest/guide/webpack.html

**Comment by Foxandxss** [comment]
Perhaps that is the only one (and style guide). You can't plunk a webpack application.

**Comment by robianmcd** [comment]
same goes for https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

you could have a sample repo that demonstrates them

**Comment by robianmcd** [comment]
I never noticed the "See the live example" links before but I see now that most articles do have examples. Here's another one that doesn't though

https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html
