### ISSUE TITLE
Angular 2 Version "~2.0.1" Internet Explorer "SystemJS Syntax Error"

### ISSUE THREAD

**Issue by blubberbo** [angular/angular.io#3128]
This is in addition to [#14066](https://github.com/angular/angular/issues/14066)

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When opening my Angular 2 application in Internet Explorer (10 or 11), I get the error `(SystemJS) Syntax Error"`

**Expected behavior**
The application works in Chrome and Firefox, so I would expect it to work in IE as well. 

**Minimal reproduction of the problem with instructions**
I went to recreate a bare-bones application to see if it works and it didn't, so then I went even more basic and just went to look at the Angular 2 Quickstart example here: [https://angular.io/docs/ts/latest/quickstart.html](https://angular.io/docs/ts/latest/quickstart.html) and noticed the link "QuickStart example on Plunker" does not render as a in Internet Explorer (it is a custom html tag for an angular 2 application). I tried copy and pasting the link to IE and it does not work either. I cannot find any Angular 2 Applications that work in IE.

For instance, when I load the website `https://angular.io/docs/ts/latest/quickstart.html`, this is what I get:
![image](https://cloud.githubusercontent.com/assets/17286750/22214637/334cc184-e14d-11e6-986f-551c29cf127a.png)

**What is the motivation / use case for changing the behavior?**
I would like my application to work in IE as well

**Please tell us about your environment:**
Windows, .NET, Visual Studio, NPM

* **Angular version:** 2.0.X
2.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
IE 10, 11 (earlier versions as well I would guess)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

thank you

**Comment by Foxandxss** [comment]
I believe this issue was due to the plunker live examples and that got fixed already. Please open a new issue if that is not the case.
