### ISSUE TITLE
cheatsheet

### ISSUE THREAD

**Issue by Hotell** [angular/angular.io#314]
in `@Component configuration` there is a wrong signature of `styles` definition

instead 
```
styles: '.primary {color: red}'
styleUrls: ['my-component.css']
```
correct:
```
styles: ['.primary {color: red}']
styleUrls: ['my-component.css']
```

both `styles` and `styleUrls` are: 
```typescript 
string[]
```

**Comment by naomiblack** [comment]
Thanks! committed a fix to the online guide. (the print versions will be updated with -45)
