### ISSUE TITLE
Expired certificate for angular.io

### ISSUE THREAD

**Issue by jloosli** [angular/angular.io#3154]
When trying to connect to angular.io, I get the attached warning (NET::ERR_CERT_DATE_INVALID in chrome), (SEC_ERROR_EXPIRED_CERTIFICATE).

![angular-io-error-firefox](https://cloud.githubusercontent.com/assets/617816/22354906/bbe34042-e3e4-11e6-844e-68759f8df337.png)
![angular-io-error](https://cloud.githubusercontent.com/assets/617816/22354905/bbe11272-e3e4-11e6-9280-0641b938b07a.png)

**Comment by Foxandxss** [comment]
We are on it ;)

**Comment by naomiblack** [comment]
this is resolved
