### ISSUE TITLE
angular.io API reference pages show v4 API docs but the latest release is officially documented as v2

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#3186]
This is a follow-up to a question on the docs-authoring Slack channel (issue opened on @naomiblack's request).

The ng.io API Reference page shows API docs for V4.0.0-BETA.2 (https://angular.io/docs/ts/latest/api/), but the `travis.yml` has  `LATEST_RELEASE=2.4.0`. Might V4 have been used by mistake as a base to generate the docs or has ng.io already switched to v4?

cc @naomiblack @juleskremer @IgorMinar

**Comment by juleskremer** [comment]
Fixed; tl;dr, I mistakenly put my local copy to 4 before deploying.
