### ISSUE TITLE
Suggested Edits for the Pipes Guide Page

### ISSUE THREAD

**Issue by joeeames** [angular/angular.io#319]
1. The 3rd sentence: "Once data arrive, we could plaster them directly to screen." although possibly technically correct, doesn't read right. Suggest a rephrase.

2. The code snippet is wrong  directly underneath the heading "The stateful AsyncPipe".  The template needs double quotes around it.

3. The section could use information on how setting pure: false also allows the pipe to be re-evaluated when the data source changes (such as adding an item to a list) which is useful even if the pipe itself is still stateless.

**Comment by wardbell** [comment]
Hi Joe
1. Not sure what to do with "doesn't sound right". It is colloquial but maybe too colloquial, especially for international readers. I'll come up with something.

2. That was one of many small technical errors. New version generates doc from a code sample that corrects these errors. PR awaiting acceptance.

3. Would you elaborate with a use case? A code snippet would help greatly.

**Comment by wardbell** [comment]
@joeeames Awaiting your reply to (3).  Do you have something for me?

**Comment by wardbell** [comment]
I assume these thoughts have been incorporated in your #697

**Comment by joeeames** [comment]
Yeah, or completely obviated.
