### ISSUE TITLE
Document what is "destructured imported symbols"?

### ISSUE THREAD

**Issue by tiratano** [angular/angular.io#3191]
I have found an unfamiliar word - "destructured imported symbols" from style guide (https://angular.io/docs/ts/latest/guide/style-guide.html#!#03-06).
What is the exact meaning of "destructured imported symbols"?
Please, anyone who knows the meaning help me!

**Comment by Foxandxss** [comment]
That is a ES6 and Typescript feature. Sorry on the phone right now, but Google that and I'm sure you will find an explanation. 

If not, I'll give you a better answer at home.

**Comment by tiratano** [comment]
@Foxandxss Thanks. My understanding is below.
1. We can import some module with import style which started supports from ES6. (e.g: import { Elephant, Horse } from "animals";)
2. Elephant and Horse are the imported symbols.
3. Elephant and Horse are the destructured symbols.
4. Finally, Elephant and Horse are the destructured imported symbols.
Please let me know if something goes wrong.

**Comment by SebastienPaquet** [comment]
test

**Comment by SebastienPaquet** [comment]
I had the same question. At this point in the docs, the new term coming up is **destructured**.

`import { Elephant, Horse } from "animals";`
does import **Named exports** using the "**destructuring assignment syntax**"
> **The destructuring assignment syntax** is a JavaScript expression that makes it possible **to extract data from arrays or objects into distinct variables**. 
[https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment](url)

> There are two different types of export: Named exports and Default exports.
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export#Using_named_exports](url)





@tiratano
