### ISSUE TITLE
Incorrect terminology in TypeScript to JavaScript

### ISSUE THREAD

**Issue by trotyl** [angular/angular.io#3195]
In the [TYPESCRIPT TO JAVASCRIPT](https://angular.io/docs/ts/latest/cookbook/ts-to-js.html) documentation, it's using code like:

```javascript
export class HeroComponent {
  title = 'Hero Detail';
  getName() {return 'Windstorm'; }
}
```

While calling that **ES6 JavaScript with decorators**.

But the fact is `title = 'Hero Detail';` is neither ES6 nor Decorators, but another separate proposal at stage 2 (https://github.com/tc39/proposals => Public Class Fields), it's not correct at any sense.

Besides, Decorator proposal (http://tc39.github.io/proposal-decorators/#sec-syntax) does not dependent on nor cover the class property proposal. (Actually the so-called "property decorator" can only apply to methods)

How to rectify it?

1. Changing the wording `ES6 JavaScript with decorators` to `ES6 JavaScript with decorators and class properties`, but it seems to long;
2. Just calling that `ES next`, since both Class & Property Decorator are stage 2 proposals;
3. Do not use class property syntax in code of `ES6 JavaScript with decorators` version.

**Comment by Foxandxss** [comment]
What you say is correct out of context, but if we unify all the different context, it makes sense.

We show 1 example, step by step in 4 different "languages". The ES6 + decorators will eventually show an example of ES6 + decorators. That doesn't mean that the example you are giving in here contains decorators. It will eventually contain decorators but not yet in that step.

We can't change the headers to specify "what you see in the example" because that will confuse the users that are going step by step.

About the properties, not much idea there. WDYT @filipesilva ?

**Comment by filipesilva** [comment]
It's completely true that the public class fields are a different proposal. But as far as decorators are concerned, *class property decorators* still need class fields (via the [angular2 babel preset](https://github.com/shuhei/babel-plugin-angular2-annotations#even-without-this-plugin-thanks-to-babel-plugin-transform-decorators-legacy)).

So while not completely descriptive, I still thinking that just saying that we're trying to have as much decorator support as possible (and using whatever presets get us there) is better than being overly specific about everything that goes into that.

There's also a simplistic progression described that highlights when the class fields go away:

> When translating from TypeScript to ES6-with-decorators, remove class property access modifiers such as public and private. Remove most of the type declarations, such as :string and :boolean but keep the constructor parameter types which are used for dependency injection.
>
> From ES6-with-decorators to plain ES6, remove all decorators and the remaining types. You must declare properties in the class constructor (this.title = '...') rather than in the body of the class.
