### ISSUE TITLE
Angular test project has 7 failing tests and 4 pending tests

### ISSUE THREAD

**Issue by AmyBlankenship** [angular/angular.io#3204]
For some reason, the issue template didn't prepopulate, so I'm just going to say it.

The test project used in the official Angular testing docs has failing and pending tests https://angular.io/resources/live-examples/testing/ts/app-specs.eplnkr.html. That's probably not intentional.

**Comment by Foxandxss** [comment]
Definitely not. We were talking about that today. I am going to fix it soon.

**Comment by AmyBlankenship** [comment]
Thanks for the quick response!

**Comment by AmyBlankenship** [comment]
BTW, I was getting this error on my own services and I found this https://blog.thoughtram.io/angular/2015/09/17/resolve-service-dependencies-in-angular-2.html. Haven't had a chance to test this in my own code and was actually going to the test project to see if it was working there :). You probably already knew the fix, but if not maybe this helps.

**Comment by AmyBlankenship** [comment]
Just looking at it, it looks like for the HttpHeroService at least the issue may be that the constructor wants Http, but the provider is providing XHRBackend.

**Comment by Foxandxss** [comment]
That is normal, it is just missing a piece. I am finishing something first and then I will fix that one.

**Comment by AmyBlankenship** [comment]
I just wanted to share my observations in case it saved you some time. Not trying to pressure you :)

**Comment by Foxandxss** [comment]
No worries at all. It is good to explore this issues to learn how it supposes to work.

**Comment by AmyBlankenship** [comment]
There's still one failing test

**Comment by AmyBlankenship** [comment]
Four failures now
