### ISSUE TITLE
dgeni publishes docs for @internal class members

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular.io#321]
example: https://angular.io/docs/ts/latest/api/core/ElementRef-class.html contains `parentView` and `boundElementIndex`, which are `@internal`

**Comment by IgorMinar** [comment]
@naomiblack I wanted to fix this, but it looks like when we switched to generating api docs from the angular.io repo we didn't update all of the custom dgeni packages. in angular/angular there were several fixes I don't see in angular/angular.io repo.

do you know what happened there?

**Comment by petebacondarwin** [comment]
This was fixed by https://github.com/angular/angular.io/commit/97ae3d0ca962b72e529c118523371f2635a39716
