### ISSUE TITLE
Add omnibox search support

### ISSUE THREAD

**Issue by NoNameProvided** [angular/angular.io#3213]
Now to search for something in the docs, the user has to wait until the page is loaded and then start typing in the search field. Adding omnibox search support to speed this up would make sense.

The implementation is fairly easy as you only have to add an `opensearch.xml` file in the root of the page. A minimal implementation would be:

```xml
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">
<ShortName>angular.io</ShortName>
<LongName>Search angular.io</LongName>
<Description>Search angular.io</Description>
<Developer>Google</Developer>
<Attribution>Copyright Google</Attribution>
<AdultContent>false</AdultContent>
<Language>en-us</Language>
<InputEncoding>UTF-8</InputEncoding>
<OutputEncoding>UTF-8</OutputEncoding>
<Image width="16" height="16" type="image/x-icon">https://angular.io/favicon.ico</Image>
<Url type="text/html" method="GET" template="https://angular.io/search?q={searchTerms}"/>
<moz:SearchForm>https://angular.io</moz:SearchForm>
</OpenSearchDescription>
```

**Comment by juleskremer** [comment]
Hello there, we are rebuilding our docs site and will have a new search implementation with the new site.  I am going to close this issue as it will be addressed when we roll out the new site.
