### ISSUE TITLE
Main.ts is missing from quickstart plunker

### ISSUE THREAD

**Issue by SanderElias** [angular/angular.io#3215]
If you open the dev console in the [quickstart plunk](https://angular.io/resources/live-examples/quickstart/ts/eplnkr.html), you will see that the file main.js is missing from the plunk. It works correctly, anyway.
The source, main.ts is also missing. 
This should be fixed because a lot of people look at those sample for guidance on how to get started.

**Comment by Foxandxss** [comment]
I will check. We did some drastic changes, then we removed them. I will check what is the status now.
