### ISSUE TITLE
Missing Step in Tour of Heroes Tutorial - "npm init -y" after cloning angular2-quickstart

### ISSUE THREAD

**Issue by sambuchl** [angular/angular.io#322]
I may be wrong, but I believe there's a missing step at the beginning of the Tour of Heroes tutorial.

After you've cloned the Quickstart directory, you also need to run the "npm init -y" again in the new new Tour-of-Heroes directory to create the new package.json file.

**Comment by wardbell** [comment]
The instructions don't say "clone the Quickstart directory". They say

>Copy the "QuickStart" code to a new folder and rename the folder `angular2-tour-of-heroes`

The copy would result in a fully formed package.json, don't you think?

Please let us know whether to pursue this further or close.

Thanks.

**Comment by sambuchl** [comment]
Hi Ward,

I believe you're correct - I've run the tour-of-heroes code twice now by
copying the Quickstart code and haven't seen any errors. You can close!

Thanks for your direction!
- Sam
