### ISSUE TITLE
Explore Angular Resources - "Platforms" for IDEs is a bit missleading for new developers

### ISSUE THREAD

**Issue by thomasclaudiushuber** [angular/angular.io#3220]
On https://angular.io/resources/ Visual Studio Code has the "Platforms: Windows, Linux". You should add MacOS here. And to be consistent, these platforms should be added to WebStorm and IntelliJ as well. Makes it simpler for new developers browsing that site.

I was not able to send a PR, as these informations are stored in a Firebase db. :)

**Comment by StephenFluin** [comment]
Fixed!

**Comment by thomasclaudiushuber** [comment]
Yep, looks good now. Thanks.
