### ISSUE TITLE
Route path missing in the tutorial

### ISSUE THREAD

**Issue by bhroberts52** [angular/angular.io#3222]
The router link to the hero-detail component from dashboard.component.html produces a path that is missing from the route definitions in the tutorial.  
`[routerLink]="['detail', hero.id]"`
is looking for:
`{ path: 'dashboard/detail/:id', component: HeroDetailComponent }`
not
`{ path: 'detail/:id', component: HeroDetailComponent },`

**Comment by brandonroberts** [comment]
Are you referring to the link in the routing tutorial? It has a slash in front of `detail`

```html
<a *ngFor="let hero of heroes"  [routerLink]="['/detail', hero.id]"  class="col-1-4">
```

**Comment by bhroberts52** [comment]
Thank you for clearing that up for me
