### ISSUE TITLE
Team comments showing up in docs

### ISSUE THREAD

**Issue by Josh68** [angular/angular.io#3225]
For example: https://angular.io/docs/ts/latest/guide/template-syntax.html

`<div class="alert is-critical"><p>Ward: <code>firstName</code> appears here (below) for the first time without any mention it was coming and isn't in the 
code sample. Do we mean <code>name</code> instead?</p>
</div>`

I assume it's not intended for these to be incorporated in the docs, and figure pull requests to remove them aren't the correct solution.

Thanks

**Comment by Foxandxss** [comment]
That was fixed.
