### ISSUE TITLE
TrackBy Demo plunker 

### ISSUE THREAD

**Issue by aravindfz** [angular/angular.io#3229]
**I'm submitting a bug report...**  

I was going through the ngFor directive **[documentation](https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html#!#ngForTrackBy-anchor)** The Live Demo shown over this **[link](http://plnkr.co/edit/KVuXxDp0qinGDyo307QW?p=preview)** does not provide enough illustration.

**Expected behavior** : Demo is expected to have all examples for the directive

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by Foxandxss** [comment]
The live demos of the API are going to be revamped soon. On the other hand, API issues goes to angular/angular so please, open an issue there so they know about this :)
