### ISSUE TITLE
Contradicting phrase

### ISSUE THREAD

**Issue by nikosgpet** [angular/angular.io#3230]
**Current behavior**

In the angular documenation 
https://angular.io/styleguide#!#04-10

It's writtent : 
**Do** _not_ provide services in shared modules. Services are usually singletons that are provided once for the entire application or in a particular feature module.

**Expected behavior**

**Do** should be used for positive phrases, **Avoid** for negative phrases. 

The advice is really contradicting, especially given that services **_are_** used in the shared module given as example below this advice.

Depending on what you actually meant the phrase should either be changed to : 

**Avoid** providing services in shared modules. Services are ...
or 
**Do** provide services in shared modules. Services are ...

**Comment by johnpapa** [comment]
I agree that `Avoid providing ...` would be clearer.

**Comment by thanhnguyen92** [comment]
@nikosgpet Did you think two sentences are the same?

> Avoid providing services in shared modules. Services are ...
> or
> Do provide services in shared modules. Services are ...

Because **Avoid** stands for negative and **Do** stands for positive meaning.
I think the true sentence just "**Do provide** services in shared modules. Services are ..."

**Comment by AnthonyCC** [comment]
I found the documentation is still very confusing even after renaming **Do not** to **avoid** because the `FilterTextService` is in fact provided in the `shared.module.ts` in the example. If we shouldn't provide services in the shared module, may I ask why it is provided in the shared module in the example?

**Comment by nikosgpet** [comment]
Yeah, @AnthonyCC I agree with you. Even if we solve the **Do not** problem and just put **Avoid** I still find it a confusing piece of advice.

I understand that we have to be very careful when providing services in shared modules. I don't understand though why we should altogether avoid providing services in shared modules, nor what we are supposed to do instead. It is especially confusing the fact that the example given is actually not following this advice (?!). 

I understand that there is some logic behind this advice, but: 
1. It should be explained better, perhaps in more length and more clearly.
2. The example should either follow the advice or it should be better explained why the example doesn't follow it.

**Comment by Foxandxss** [comment]
It is fixed on the new site. We just need to go live.

**Comment by nikosgpet** [comment]
@Foxandxss I can see you have updated the phrase to use **Avoid**, it's just that I still find it a very confusing piece of advice. This time I am talking about the actual content of the advice.

Although we are discouraged from providing services in shared modules, the example given below the advice does exactly the opposite: It provides a service inside a shared module! The example makes sense, but the fact that it's not following its own advice is very confusing.

At the same time, the advice leaves me without knowing what to do instead: What if I have a service that is common for many modules? Is there a way I can add a service in a shared module but make sure it won't be initialized many times?
