### ISSUE TITLE
Probably slip up content in template guide

### ISSUE THREAD

**Issue by SanderElias** [angular/angular.io#3234]
There is this:
![image](https://cloud.githubusercontent.com/assets/1249083/22837196/ceadd43a-efbf-11e6-822a-5774a98b7259.png)

In the [template guide page](https://angular.io/docs/ts/latest/guide/template-syntax.html)

I don't think that means anything to users of the page.

**Comment by Foxandxss** [comment]
Yeah, not sure what happened there. Closing as already reported and PR standing.
