### ISSUE TITLE
Angular.io is not Coded Using Angular 2x

### ISSUE THREAD

**Issue by justinwilaby** [angular/angular.io#3241]
##[Angular.io](http://angular.io/) is written in AngularJS v1.6.0.

With no dogfooding at Angular.io, the argument *for* the use of Angular 2+ makes for a more difficult sell to product owners.  In a planning meeting for a greenfield project, please explain how I should answer the question: "If Angular 2x is so great and greatly improves developer productivity over AngularJS, then why isn't the documentation using it?"

![screen shot 2017-02-12 at 8 38 46 am](https://cloud.githubusercontent.com/assets/2652885/22864097/c49954f6-f0ff-11e6-8766-be77f1b7a72c.png)

**Comment by Foxandxss** [comment]
We will have a new site soon in Angular v2-4. This project was created looong ago, way before Angular 2.x was stable. We will present something in the near future.

Closing this because there are others issues about the same topic.

Cheers.
