### ISSUE TITLE
Inconsistencies In Reactive Forms Section

### ISSUE THREAD

**Issue by justinwilaby** [angular/angular.io#3244]
in the [Create a reactive forms component](https://angular.io/docs/ts/latest/guide/reactive-forms.html#!#create-component) section the `hero-detail.component.html` example starts out like this:
```js
<h2>Hero Detail</h2>
<h3><i>Just a FormControl</i></h3>
<label class="center-block">Name:
  <input class="form-control" [formControl]="name">
</label>
```
Note the use of `[formControl]="name"`
Then it is changed later on to:
```js
<h2>Hero Detail</h2>
<h3><i>FormControl in a FormGroup</i></h3>
<form [formGroup]="heroForm" novalidate>
  <div class="form-group">
    <label class="center-block">Name:
      <input class="form-control" formControlName="name">
    </label>
  </div>
</form>
```
Note the use of `formControlName="name"` without mention of why this has changed, what the differences are and when to use one over the other except for one cryptic sentence:

> The HeroDetailComponent template uses formControlName directive from the ReactiveFormsModule.

It seems this would be easy to clarify to the reader and prevent possible confusion.

**Comment by Foxandxss** [comment]
@kapunahelewong can you take a look please?

**Comment by kapunahelewong** [comment]
In there now investigating.

**Comment by shairez** [comment]
Just bumped into the same thing and saw you already opened up and issue about it. 

@justinwilaby I think we should leave this one open until there is a PR
(or maybe there is one already that I'm unaware of)

Thanks!

**Comment by kapunahelewong** [comment]
Hi @shairez I'm working on a few things for this page and including this in the PR for it. Thank you! :)

**Comment by shairez** [comment]
Awesome! thanks @kapunahelewong
