### ISSUE TITLE
Documentation correction - guide/forms.html uses template variable before it's defined

### ISSUE THREAD

**Issue by robstarbuck** [angular/angular.io#3251]
Following the guide on angular forms:

https://angular.io/docs/ts/latest/guide/forms.html

A reference to the template variable "heroForm" is made before it's inclusion.

    <button type="button" class="btn btn-default" (click)="newHero(); heroForm.reset()">New Hero</button>

Above this, in the section headed "Create an initial HTML form template" only.

    <form>

is shown

**Expected behavior**

At this point I would expect to see the template variable.

    <form #heroForm="ngForm">

**Comment by Foxandxss** [comment]
Can you take a look @kapunahelewong ?

**Comment by kapunahelewong** [comment]
Thank you @robstarbuck and @Foxandxss.

I've submitted a PR addressing this concern:
https://github.com/angular/angular.io/pull/3521
