### ISSUE TITLE
Broken links on reactive forms

### ISSUE THREAD

**Issue by shairez** [angular/angular.io#3255]
Search for the sentence 

> See the API reference for more information about *radio buttons*, *selects*, and *checkboxes*.

The three links - 

https://angular.io/docs/ts/latest/guide/api/forms/index/RadioControlValueAccessor-directive.html
https://angular.io/docs/ts/latest/guide/api/forms/index/SelectControlValueAccessor-directive.html
https://angular.io/docs/ts/latest/guide/api/forms/index/CheckboxControlValueAccessor-directive.html

lead to a 404 page

**Comment by Foxandxss** [comment]
Thank you. Guide was moved from one place to another and those links needed a change :)

**Comment by shairez** [comment]
👍
