### ISSUE TITLE
Update i18n documentation (2.4.x): System is not defined

### ISSUE THREAD

**Issue by MickL** [angular/angular.io#3279]
Following the [i18n cookbook](https://angular.io/docs/ts/latest/cookbook/i18n.html) i get `System is not defined`.

Im using latest Angular CLI. My index.html looks like this:

```
<body>
  <app-root>Loading...</app-root>

  <script>
    // Get the locale id somehow
    document.locale = 'de';

    // Map to the text plugin
    System.config({
      map: {
        text: 'systemjs-text-plugin.js'
      }
    });

    // Launch the app
    System.import('app').catch(function(err){ console.error(err); });
  </script>
</body>
```

**Comment by MickL** [comment]
Took me ages to figure this out. **Documentation should be updated**. Probably the problem is that the documentation suggests Angular CLI which is not using system.js. Also System.js has the global namespace "SystemJS" instead of "System".

1. Download [system.js](https://github.com/systemjs/systemjs), but it in root (/app) and import it before the script tag.
2. In index.html remove the System.import('app')
3. Rename everything from System to SystemJS (index.html, i18n-provides.ts)

Finally it looks like this:

_index.html_

```
<body>
  <app-root>Loading...</app-root>

  <script src="system.js"></script>
  <script>
    // Get the locale id somehow
    document.locale = 'es';

    // Map to the text plugin
    SystemJS.config({
      map: {
        text: 'systemjs-text-plugin.js'
      }
    });
  </script>
</body>
```

_i18n-providers.ts_
```
export function getTranslationProviders(): Promise<Object[]> {
   [...]
}

declare let SystemJS: any;

function getTranslationsWithSystemJs(file: string) {
  return SystemJS.import(file + '!text'); // relies on text plugin
}
```

**Comment by Foxandxss** [comment]
That is not the proper solution for the CLI either.

We are cooking a solution for certain guides to provide alternative solutions for the CLI and webpack.

Closing as duplicated (#3238)

**Comment by MickL** [comment]
At least it is a solution. Someone who reads the cookbook is probably unexperienced like me and ends frustrated there.

**Comment by Foxandxss** [comment]
Believe me, it is not. That will only lead to more grief and pain.

**Comment by MickL** [comment]
Could you please explain why its pain because my project is nearly in production with this.

**Comment by Foxandxss** [comment]
Because you are mixing different loaders. CLI uses webpack so you need to use a webpack solution. System.JS is another option.

It is like riding a motorbike inside a car because one tire was flat.

@filipesilva do you have any idea in how to do it with the CLI?

**Comment by MickL** [comment]
Ah okay see i didn't know that! Funny to clear that light in the dark. 

I wouldn't compare it like this. Lets say i drive with a car around the world but to get food i use a motorcycle?

So the only need of system.js in my project is to load the translation files. There are probably lighter solutions than 18kb JavaScript + text-plugin.

**Comment by Foxandxss** [comment]
> I wouldn't compare it like this. Lets say i drive with a car around the world but to get food i use a motorcycle?

No, you are mixing both together, at the same time.

I bet the CLI can load your translations files without anything extra nor system.js.

Let's see if Filipe has something to say or I will try later myself.

**Comment by MickL** [comment]
I guess its good like this because i use AOT-compilation while he grabs translations with system.js JIT. (AOT translation-documentation is missing some extra work which is not covered on official documentation nor anywhere i found)

**Comment by filipesilva** [comment]
Heya @MickL, I have good news and bad news.

Good news is that i18n use/extract functionality is present in the CLI. Bad news is that it's fairly new it's not well documented.

We have an issue to track documentation for this, but it hasn't been documented yet: https://github.com/angular/angular-cli/issues/2711

The best I can do right now is to point you to the tests to see how we test it's working. The gist of it is that you can extract the messages using `ng xi18n` and use files with `ng build --aot --i18n-file`.

Translation usage test: https://github.com/angular/angular-cli/blob/master/tests/e2e/tests/build/aot/aot-i18n.ts
Extraction tests: https://github.com/angular/angular-cli/tree/master/tests/e2e/tests/i18n

**Comment by MichaelBitard** [comment]
Correct me if I'm wrong, from what I see in the tests, it seems the i18n is static? You cant have a multi-lang application? You have to build one application for each language?

**Comment by MickL** [comment]
The documentation shows the JIT method where you have only one build. Actually i use AOT prebuild app with JIT translations. You could improve performance by prebuild every language separate.

**Comment by MichaelBitard** [comment]
Yes but as @Foxandxss said the JIT method use SystemJS, it's not a viable option.

**Comment by MickL** [comment]
@filipesilva Does it create a single index.html and a separate build for every language? Would be awesome!

**Comment by MeMeMax** [comment]
So is a JIT version for i18n translations in CLI coming or will there only be AOT support?
