### ISSUE TITLE
Quickstart Seed Project from Angular.io Error on npm start

### ISSUE THREAD

**Issue by lee-alderdice** [angular/angular.io#3281]
Hi,

I am just beginning to learn Angular.  Having followed the instructions in the tutorials and setup node.js on running the application with npm start there is an error.

The log file is attached ... is this an issue on my system that I need to resolve?

Many thanks for any help.
[npm-debug.txt](https://github.com/angular/angular.io/files/788064/npm-debug.txt)

**Comment by chazeah** [comment]
Was having this error and did two things:
1. Pinned jasmine types to lower version: `"@types/jasmine": "2.5.41",`
2. Used a simpler `loaders`: https://github.com/angular/angular.io/issues/3227#issuecomment-278992005

Hopefully that helps!

**Comment by lee-alderdice** [comment]
Hi,
Thanks so much for the reply.  I found the jasmine types and I was at version 2.5.36 ... I have updated mine to match yours.  Please excuse the noob question, what are and where are loaders?
Thanks.

**Comment by chazeah** [comment]
If you're following the tutorial, the `loaders` line is in `webpack.common.js`.

**Comment by Foxandxss** [comment]
He is not using Webpack, just the quickstart.

Problem with your error is that it doesn't show much.

**Comment by lee-alderdice** [comment]
That is exactly what I was thinking ... I am still trying to get it all working, if intermittently as it is on the job learning that I am doing.  I have been adjusting Environment Variables, Directories, reinstalling stuff ... still no joy.

**Comment by lazaridis-com** [comment]
@lee-alderdice , did you finally fix this?

You can try out the cli-quickstart (it is more beginner friendly) :

https://angular.io/docs/ts/latest/cli-quickstart.html

And you can install latest versions fo node/npm/angular, and try the tutorial again.

**Comment by Foxandxss** [comment]
Reopen if this is still an issue.

**Comment by lee-alderdice** [comment]
Hi.

This worked a treat.  Thank you so much.

**Comment by lee-alderdice** [comment]
By using the CLI QuickStart as advised by @lazaridis-com and then building out from there I have got much further.   Installing the Heroes tutorial and running `npm start` still fails but starting from the CLI quick set up, building the files one by one and using `ng serve -o` works.  

However I have hit an issue with a missing `.then()` property on the type Hero[], in the revised getHeores() method that has me stumped.  Shall I raise an issue here or SO?

**Comment by lazaridis-com** [comment]
[when answering via email to github issues, please delete the quoted text before sending the reply ]

@lee-alderdice, glad it got better. As for your new problem: yes, please prefer to ask a question on SO.
