### ISSUE TITLE
Broken links for ViewMetadata

### ISSUE THREAD

**Issue by hajderr** [angular/angular.io#3287]
Hello

Please check the documentation for ViewEncapsulation
https://angular.io/docs/ts/latest/api/core/index/ViewEncapsulation-enum.html

The links to ViewMetaData are broken and result in a 404.

The referenced link: https://angular.io/docs/ts/latest/api/core/index/ViewMetadata#encapsulation

**Comment by Foxandxss** [comment]
API issues to the angular repo.
