### ISSUE TITLE
Quickstart: little hint not to register providers twice

### ISSUE THREAD

**Issue by sannies** [angular/angular.io#3307]
I ran into https://github.com/angular/angular/issues/11618 

The quickstart example registers the HeroService at the HeroComponent. That put me on the wrong track. I changed the app and added the HeroService in the root module while experimenting as well have it accessible in other components. Seems like a natural thing to do but that's where the mess started.
A sentence like "Do not register providers twice as this will create two independent instances." might have helped me in the quickstart chapter "When to use the NgModule and when an application component?"
I'd propose to add something like this.

**Comment by Foxandxss** [comment]
We changed our quickstart long ago but this issue is recent.

Where are we doing that exactly? And I am not saying that is wrong, I am just curious to see the context.

**Comment by Foxandxss** [comment]
Closing as not getting more information

**Comment by chan71** [comment]
@Foxandxss It is still referring to component level providers in the quick start guide. Better to add a note as @sannies suggested. 
See 'Parent and children communicate via a service' section of https://angular.io/guide/component-interaction.

Source code of component-interaction/src/app/missioncontrol.component.ts has the MissionService 
 as providers.

**Comment by Foxandxss** [comment]
Sorry, I am a bit lost.
