### ISSUE TITLE
Document what is "blocking and tackling"?

### ISSUE THREAD

**Issue by tiratano** [angular/angular.io#3308]
I have found an unfamiliar word - "blocking and tackling" from ADVANCED - Angular Module chapter 
(https://angular.io/docs/ts/latest/guide/ngmodule.html).
...
"Most of this is familiar blocking and tackling."
...

What is the exact meaning of "blocking and tackling"?
Is that some kind of sports idioms? Then what's that mean for this context??
Please, anyone who knows the meaning help me!

**Comment by juleskremer** [comment]
We recently made an update to the ngmodule page and this verbage no longer exists; yes, it was a sports analogy; please see the new version which should clarify for you the original intention.
