### ISSUE TITLE
Add ngStyle to Cheat Sheet

### ISSUE THREAD

**Issue by siva636** [angular/angular.io#3331]
The 'Built-in Directives' section of the Cheat Sheet has `ngClass`, but `ngStyle` is missing and needs to be added.

**Comment by Foxandxss** [comment]
CheatSheet issues goes to the angular/angular repo because the cheatseet is in there.

**Comment by DzmitryShylovich** [comment]
@Foxandxss 
> the cheatseet is in there

https://github.com/angular/angular/blob/1f3198cb505a6bb74aadf022c7142f3f4d8cbe28/aio/content/guide/cheatsheet.md this one? :)

**Comment by Foxandxss** [comment]
No, that is clearly empty. I believe that they are [here](https://github.com/angular/angular/tree/2.4.x/modules/%40angular/docs/cheatsheet). Master changed for v4 so I guess we pull them from the 2.4.x branch.
