### ISSUE TITLE
Arguments types do not match parameter warning in tutorial code. 

### ISSUE THREAD

**Issue by gonaumov** [angular/angular.io#3364]
There is the following warning into AngularJS tutorial code which is located on this url: 
https://angular.io/docs/ts/latest/tutorial/toh-pt5.html 
I mean this code snippet: 
```
ngOnInit(): void {
  this.route.params
    .switchMap((params: Params) => this.heroService.getHero(+params['id']))
    .subscribe(hero => this.hero = hero);
}
```
```
Arguments types do not match parameter
```
![thewarning](https://cloud.githubusercontent.com/assets/4079371/23745597/6da754ce-04c1-11e7-9fa6-9eb218bc20ae.png)

**Comment by vinay30** [comment]
I don't think this is a problem with the tutorial. It seems to be an issue with the Typescript compiler in Webstorm/PHPstorm. Try updating your IDE version to resolve the issue.

Despite the errors shown, you should still be able to run the app and it should work fine if that's the only error.
