### ISSUE TITLE
`UrlMatcher` link returns 404

### ISSUE THREAD

**Issue by SamVerschueren** [angular/angular.io#3374]
While I was exploring custom url matchers, I noticed that this feature is undocumented. I had to look into the source code to find an example. The [Routes class](https://angular.io/docs/ts/latest/api/router/index/Routes-type-alias.html) on the angular.io website states

> `matcher` defines a custom strategy for path matching and supersedes `path` and `pathMatch`. See [UrlMatcher](https://angular.io/docs/ts/latest/api/router/index/UrlMatcher) for more info.

But when you navigate to the `UrlMatcher` link it will return a 404. The documentation of that feature is put inline into the source code right [here](https://github.com/angular/angular/blob/2.4.8/modules/%40angular/router/src/config.ts#L267-L288). Can I do anything to help fix this problem?

**Comment by Foxandxss** [comment]
>Please file Developer Guide, Cookbook, and code sample issues only in this Angular.io github repo.

>Angular API issues, cheatsheet corrections, feature requests, defect reports, and technical questions concerning Angular itself belong in the angular source code github repo. We can't handle those topics here and will ask you to re-post them on the angular repo.

**Comment by Equinox** [comment]
@Foxandxss Where do you suppose people should report links that are 404ing on the angular.io website to?

Because that's exactly what this PR is, as evident by [this](https://github.com/angular/angular/issues/14833#issuecomment-285870595).

**Comment by SamVerschueren** [comment]
@MarkPieszak Aslef asked me to report it right here. So not sure :).

**Comment by Foxandxss** [comment]
@Equinox in the angular/angular site.

The API documentation is extracted here from the angular/angular repo and all the links, say the urlmatcher broken link comes from the angular/angular repo as well. So they need to be fixed from there and not from here.

That being said, if the problem is API related but is the parser who is making the errors, yes, they need to be reported in here.

**Comment by Foxandxss** [comment]
I am going to investigate because that url should be parsed, so perhaps I am wrong and the problem lies here in the parser.

**Comment by MarkPieszak** [comment]
Apologies if I steered them to the wrong repo but figured it made sense here 😞 @foxandxss

**Comment by Foxandxss** [comment]
No problem Mark. Some stuff is hard to pinpoint.

The fact is, the documentation is _not_ being generated for UrlMatcher for not being public. I will personally report that.

**Comment by Stexxen** [comment]
So is this an issue for this repo or the main angular one, as it appears both sides say it should be raised in the other, see https://github.com/angular/angular/issues/14791.
