### ISSUE TITLE
Fix capitalization of `router` in toh-pt5

### ISSUE THREAD

**Issue by lverns** [angular/angular.io#3385]
See the numbered list starting [here](https://github.com/angular/angular.io/blob/c2bb6ad9350e2245196713635e6c250b610d3ace/public/docs/ts/latest/tutorial/toh-pt5.jade#L779).
```
  1. Import the `router` from the Angular router library
  1. Inject the `router` in the constructor (along with the `HeroService`)
  1. Implement `gotoDetail` by calling the `router.navigate` method
```
On the first line, it should certainly be 
```
  1. Import the `Router` from the Angular router library
```
since the line the user needs to write is 
```typescript
import { Router } from '@angular/router';
```
The capitalization of the second entry should probably also be uppercase since we are injecting the `Router` component and naming our variable `router`.

**Comment by Foxandxss** [comment]
Can you take a peek @kapunahelewong

**Comment by kapunahelewong** [comment]
Thank you @lverns! Great catch. I've submitted a PR for this:

https://github.com/angular/angular.io/pull/3526
