### ISSUE TITLE
Plunkr examples are not working

### ISSUE THREAD

**Issue by mohessaid** [angular/angular.io#3395]
### Expected Behavior
When I run a live example from the docs I should be able to see the example running in plunkr without any intervention.
### Actual Behavior
All the examples using external template and style files like in the routing or http tutorials are not working in plunkr due to an error in the construction of these files's urls.
### Suggestions:
To make these examples work in plunkr I updated the systemjs loader by correcting the substring replacing line  to keep the letter 'a' in 'app' like this:
```javascript
urls.push(`'${basePath.substr(1)}${match[2].substr(1)}'`);`
```
becomes : 
```javascript
urls.push(`'${basePath}${match[2].substr(1)}'`);`
```
or 
```javascript
urls.push(`'${basePath.substr(0)}${match[2].substr(1)}'`);
```

This will work only on the preview link not in the embedded one.
To fix the embedded link problem we just need to add this if statement : 
```javascript
if (url.href.indexOf('preview') != -1){
    basePathParts.shift();
 }
```
after this one : 
```javascript
if (url.href.indexOf('plnkr') != -1) {
    basePathParts.shift();
    basePathParts.shift();
 }
```

**Comment by Foxandxss** [comment]
I have a PR to fix it. Thanks for investigating it tho.

The problem is that plunker needs a way, embedded as you mention needs another way, testing another way, local running another and the upgrade guide, another one. I addressed them all in one PR.

**Comment by mohessaid** [comment]
Ah ok, good to hear, you can only add an if statement to check for the 'preview' part in the url and you will fix the plunkr problem.

**Comment by Foxandxss** [comment]
Yes, pretty much that, I just realized a different error as well, so the PR does a bit more.
