### ISSUE TITLE
Cannot read property 'config' of null from http://localhost:3000/resources/zips/toh-6/toh-6.zip

### ISSUE THREAD

**Issue by javaspeak** [angular/angular.io#3402]
This issue is about one of your examples you have on the "Tutorial: Tour of Heroes" downloadable example.  When running "ng serve" on the example one gets:
     
      Cannot read property 'config' of null
    
I am using a Mac with Yosemite and I did the following:

     git clone https://github.com/angular/angular.io.git
     git clone https://github.com/angular/angular
     sudo ./scripts/before-install.sh
     sudo ./scripts/install.sh  
     gulp serve-and-sync
     In a browser I went to:   http://localhost:3000/docs/ts/latest/tutorial/
     I downloaded http://localhost:3000/resources/zips/toh-6/toh-6.zip
     I unzipped toh-6.zip
     I changed directory into toh-6
     npm install
     ng serve

On typing "ng serve" I got:

     $ ng serve
     Cannot read property 'config' of null
     TypeError: Cannot read property 'config' of null
      at Class.run (/Users/johndickerson/workspaces/prospect/toh-6/node_modules/@angular/cli/tasks/serve.js:22:63)
      at check_port_1.checkPort.then.port (/Users/johndickerson/workspaces/prospect/toh-6/node_modules/@angular/cli/commands/serve.js:103:26)
      at process._tickCallback (internal/process/next_tick.js:103:7)

I have the following npm global installs:
    $pwd
     /usr/local/lib/node_modules/@angular/cli
    $ npm version
    { '@angular/cli': '1.0.0-rc.4',
    npm: '4.1.2',
    ares: '1.10.1-DEV',
    cldr: '30.0.3',
    http_parser: '2.7.0',
    icu: '58.2',
    modules: '51',
    node: '7.6.0',
    openssl: '1.0.2k',
    tz: '2016j',
    unicode: '9.0',
    uv: '1.11.0',
    v8: '5.5.372.40',
    zlib: '1.2.11' }

I am not sure if this is a Mac thing.  The funny thing is that in:

    toh-6/node_modules/@angular/cli/tasks/serve.js:22:63

it shows:

    const projectConfig = config_1.CliConfig.fromProject().config;

if I go to "fromProject" I see the file:

    toh-6/node_modules/@angular/cli/models/config.d.ts

At the top of the config.d.ts file it has:
    
     export declare const CLI_CONFIG_FILE_NAME = ".angular-cli.json"; 

Notice there is a dot at the beginning of the name:   ".angular-cli.json"

This file does not exist anywhere.

There is a file without a dot in:

     toh-6/node_modules/@angular/cli/blueprints/ng/files/angular-cli.json

I realize that this could be an  "@angular/cli" problem rather than an "angular.io" problem. 

If instead of using "ng serve", I use "npm start" it does not get past loading on in the browser and in the server the only problem I can see:

    17.03.21 17:10:24 404 GET /systemjs-angular-loader.js

Forgive my lack of knowledge at the moment but maybe I have somehow highlighted a problem with the example or the lack of instructions in the example or am stupid and am wasting everyone's time.

Thank you for your time.

**Comment by Foxandxss** [comment]
The example is NOT a `angular-cli` example so that won't work. You need to `npm start` it.

**Comment by javaspeak** [comment]
Thanks Foxandxss,

Once I added the missing /systemjs-angular-loader.js "npm start" worked. 

It is missing from here:

    e.g.  http://localhost:3000/resources/zips/toh-6/toh-6.zip

It is also missing in some of the other examples.

Cheers

John

**Comment by Foxandxss** [comment]
I need to check that. I fixed that yesterday but I am not sure if we went live after that.

**Comment by javaspeak** [comment]
You are right, I cloned the rep before yesterday before your fix.  Sorry for not checking again before raising the ticket.

https://angular.io/resources/zips/toh-6/toh-6.zip is fine.

You can close the ticket.

Cheers
