### ISSUE TITLE
Failed at the angular.io@0.0.0 harp script 'harp "server"

### ISSUE THREAD

**Issue by javaspeak** [angular/angular.io#3407]
On running the following command for angular.io:

     gulp serve-and-sync

I get:

    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! angular.io@0.0.0 harp: `harp "server" "."`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the angular.io@0.0.0 harp script 'harp "server" "."'.

I have the latest clone of angular.io

I have the latest stable versions.  See log trace below for versions:

My log file:

      ~/.npm/_logs/2017-03-22T07_49_20_963Z-debug.log

is attached.

[2017-03-22T07_49_20_963Z-debug.log.txt](https://github.com/angular/angular.io/files/860705/2017-03-22T07_49_20_963Z-debug.log.txt)

**Comment by Foxandxss** [comment]
That doesn't give too much information.

Although, `serve-and-sync` needs the `angular/angular` project to be downloaded as well as a sibling folder.

Try `server-and-sync-devguide`.

**Comment by javaspeak** [comment]
Thank you and sorry for wasting time.  I will think twice before raising a ticket until am more expert with angular.io

In fact for some reason harp was running and hogging the port.  Maybe it did not stop last time for some reason.

Thank you for the server-and-sync-devguide tip.

You can close the ticket.

**Comment by Foxandxss** [comment]
Nothing to be sorry about.
