### ISSUE TITLE
Angular 2 Tutorial-Http section-hero-search-component

### ISSUE THREAD

**Issue by ArezooK** [angular/angular.io#3409]
Hi,
I'm very new to angular so please forgive me if this issue is useless. In doing the tutorial I found that after adding the hero-search.component.ts file as is written in the tutorial would cause a 404 not found code. I eventually fixed this by adding a "moduleId: module.id," to the hero-search component. I couldn't get it to work without adding this line and I think this line should be added in the tutorial version of the code for the future. Let me know if there was another way I could have fixed it.

**Comment by Foxandxss** [comment]
No, that is completely my fault. In fact I am going to fix it right now. The quickstart is missing a piece. You don't need the moduleId.

**Comment by ArezooK** [comment]
what is it missing?

**Comment by Foxandxss** [comment]
I will give you the changes as soon as I put them.

**Comment by Foxandxss** [comment]
https://github.com/angular/quickstart/commit/eaf53869d0c2f4011138fc4f311abe913006a99f

There are the changes. Take a peek.
