### ISSUE TITLE
Invalid GitHub path of "Defined in" link at API pages

### ISSUE THREAD

**Issue by Quramy** [angular/angular.io#3424]
The "Defined in" links at API pages have prefix `https://github.com/angular/angular/tree/4.0.0/modules/`, such as `https://github.com/angular/angular/tree/4.0.0/modules/core/src/metadata/directives.ts#L827-L828` at the bottom of [Input API page](https://angular.io/docs/ts/latest/api/core/index/Input-interface.html).
I think that the prefix should be `https://github.com/angular/angular/tree/4.0.0/packages` .

**Comment by Foxandxss** [comment]
I think we fixed all of that. We just need to go live again.
