### ISSUE TITLE
Browser is not reloaded on all local file changes

### ISSUE THREAD

**Issue by filipesilva** [angular/angular.io#344]
While running `serve-and-sync`, changing `public\docs\ts\latest\tutorial\toh-pt1.jade` will trigger a `browserSync` to reload the page, accompanied by a `[BS] File changed: public\docs\ts\latest\tutorial\toh-pt1.jade` message on the console.

However, changing `public\docs\ts\latest\quickstart.jade` doesn't either reload nor present a console message.

The culprit seems to be this glob in the browserSync tasks: `files: ["public/docs/**/*/**/*" ]`.

**Comment by petebacondarwin** [comment]
We need to be a bit more explicit because we don't want to trigger a reload on the changes to the API docs or examples, since that is already covered by the other watchers.

**Comment by petebacondarwin** [comment]
Fixed via #369
