### ISSUE TITLE
incorrect dashboard header in toh documentation

### ISSUE THREAD

**Issue by swseverance** [angular/angular.io#3444]
toh-pt5.jade displays an image (/resources/images/devguide/toh/dashboard-top-heroes.png) that contains an incorrect header. The header reads 'My Dashboard', when it should read 'Top Heroes'

**Comment by Foxandxss** [comment]
Can you take a peek @kapunahelewong ?

**Comment by kapunahelewong** [comment]
I've included this update with a PR fixing another issue in the same doc. Thank you very much @swseverance!!
