### ISSUE TITLE
Documentation truncated if return type is a type union

### ISSUE THREAD

**Issue by PerfectPixel** [angular/angular.io#3449]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Documentation of the API seems to be truncated if the return type of a function or property is a type union. E.g. `errors : ValidationErrors|null` becomes `errors : ValidationErrors|` and the documentation ends after this property. See below for example links.

**Expected behavior**
Documentation should show the correct return type and be complete.

**Minimal reproduction of the problem with instructions**
Take a look:
https://angular.io/docs/ts/latest/api/forms/index/AbstractControl-class.html
https://angular.io/docs/ts/latest/api/forms/index/Validators-class.html

* **Angular version:** 4.0.0

**Comment by Foxandxss** [comment]
This belongs to angular/angular since it is an API issue.
