### ISSUE TITLE
AbstractControl documentation is not complete

### ISSUE THREAD

**Issue by affinehat** [angular/angular.io#3454]
In the transition to Angular 4, AbstractControl documentation seems to be missing some functions. Compare the class overview of https://angular.io/docs/ts/latest/api/forms/index/AbstractControl-class.html with https://v2.angular.io/docs/ts/latest/api/forms/index/AbstractControl-class.html.

Also, https://github.com/angular/angular/blob/4.0.0/packages/forms/src/model.ts shows that the class still has these functions.

**Comment by Foxandxss** [comment]
that belongs to angular/angular
