### ISSUE TITLE
Why add 'typeRoots' prop in tsconfig-aot.json

### ISSUE THREAD

**Issue by eminoda** [angular/angular.io#3456]
what's the typeRoots means?
i cancel this typeRoots,the demo is running just ok
````
"typeRoots": [
      "node_modules/@types/"
    ]
````

**Comment by Foxandxss** [comment]
It is a fix for our project. Since we have like 20-30 demo projects inside our own project, we need that to make the demo work.

**Comment by Foxandxss** [comment]
Can we make it easier for the end user @filipesilva ?
