### ISSUE TITLE
QuickStart not working in Safari on OSX

### ISSUE THREAD

**Issue by pavelku** [angular/angular.io#3485]
I am new to angular so I just downloaded a fresh copy of everything including QuickStart onto my macbook pro and the QuickStart does not work in Safari 9.1.2 (Chrome and Firefox work fine). I get the following message:

Error: (SystemJS) Unexpected identifier 'resolvedUrl'
	eval@[native code]
	invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:365:31
	run@http://localhost:3000/node_modules/zone.js/dist/zone.js:125:49
	http://localhost:3000/node_modules/zone.js/dist/zone.js:760:60
	invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:398:36
	runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:165:57
	drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:593:42
	g@http://localhost:3000/node_modules/core-js/client/shim.min.js:8:10017
	http://localhost:3000/node_modules/core-js/client/shim.min.js:8:10139
	k@http://localhost:3000/node_modules/core-js/client/shim.min.js:8:14294
	Evaluating http://localhost:3000/systemjs-angular-loader.js
	Error loading http://localhost:3000/systemjs-angular-loader.js
	Error loading http://localhost:3000/app/app.module.js as "./app/app.module" from http://localhost:3000/main.js — 

I searched the web but haven't found anything like this. My OSX is 10.11.6.

Node --version = v6.10.1

**Comment by zhaoyucn** [comment]
I ran into the same error.

**Comment by delphist2008** [comment]
You can try to open "systemjs-angular-loader.js" and replace  "let" in "let resolvedUrl = url;" with "var".

**Comment by Foxandxss** [comment]
Please confirm if this is a problem so I can change it.

Grrr safari.

**Comment by pavelku** [comment]
Yes, it was a problem but deplhist2008's suggestion fixed it.

**Comment by Foxandxss** [comment]
I am going to leave it open because I need to change that anyway.

**Comment by pavelku** [comment]
Ok. Thanks.
