### ISSUE TITLE
[PROJECT] Provide an Issue Template

### ISSUE THREAD

**Issue by lazaridis-com** [angular/angular.io#3493]
When creating new issues in this repo, a text should be shown, like this (partially taken from the README) :

"
Use this Issue Tracker only for Angular Documentation Issues (Developer Guide, Cookbook, and code samples)

DO NOT use this 

> Angular API issues, cheatsheet corrections, feature requests [and] defect reports [...] [for] Angular itself belong in the angular source code github repo. We can't handle those topics here and will ask you to re-post them on the angular repo: https://github.com/angular/angular

If you have Questions, please consider using SO or Gitter.
"

**Comment by Foxandxss** [comment]
Yes, but we are migrating really **soon** to the angular/angular repo so no there is no value now.

**Comment by lazaridis-com** [comment]
@Foxandxss , it surely has it benefits to have code&docu in one repo... but has the angular core-project not already too much traffic on it? I mean, an angular-docs subproject/repo/tracker enables to keep the noise  away from the core-developers.

**Comment by Foxandxss** [comment]
That is not up to me
