### ISSUE TITLE
[RFC] Rework the SideNav (Design, Structure and Naming)

### ISSUE THREAD

**Issue by lazaridis-com** [angular/angular.io#3500]
The current docs side-navigation

https://angular.io/docs/ts/latest/

 is a little bit misleading/confusing. Personally, when I first saw it, I just thought this 3 letter thing, ending with "f", starting with "w". Will not explain more, I want to behave on this project.

Now, the defects:

* The 2 "white-on-gray" caption entries like "CORE DOCUMENTATION" and "ADDITIONAL DOCUMENTATION" look like they are selected/highlighted
* The menu-entries have far too much height (in comparison to the captions), they should have the height of the captions.

Suggested menu-structure:

* Search Box
* OVerview
* BEGINNER (currently CORE DOCUMENTATION)
  * Intro (the current "quickstart")
  * Quick Start (the current Cli Quickstart)
  * Entry Tutorial (the current Tutorial, needs to be drastically simplified)
* INTERMEDIATE (currently ADDITIONAL INFORMATION)
  * Developer Guide (the current Guide)
  * API Reference
* (ADVANCED)
  * Advanced Concepts
* (EXPERT)
  * Expert Talk  (the main developers write their souls out, going brutally into details)

When looking at this, it becomes clear that the sections (captions) are not necessary, they make things more confusing. So without captions/sections:

* Search Box
* Overview
* Intro
* Quick Start 
* Entry Tutorial
* Developer Guide
* API Reference
* Advanced Concepts
* Expert Talk

Nice, compact and self-explaining, with the level of expertise increasing top-to-bottom.

**Comment by Foxandxss** [comment]
We have a brand new side nav in the new site. Different design and different structure. I would suggest you to check it, but I better suggest you to wait a bit. We still need to make some changes to that new structure.

**Comment by lazaridis-com** [comment]
[please avoid closing issues that fast]

I noticed that there is some ongoing work:

=> Where can I find the new site? ( see additionally angular/angular#15738, affects missing project-status doc )

When do you expect to launch the new site?

Couldn't you at least remove the "CORE DOCUMENTATION" and "ADDITIONAL INFORMATION" labels for now? This would make things a little bit better, until the new site goes live.

**Comment by Foxandxss** [comment]
Site will go live soon. I don't have a more concrete answer than that.

I closed the issue because there is nothing useful we can do right now. The new site will arrive very very shortly and the whole side nav is completely different. The current site is actually frozen.

**Comment by Foxandxss** [comment]
I'd suggest you on the other hand to look into the new site navbar (https://aio-staging.firebaseapp.com) and if you have an opinion for it, create an issue at angular/angular like this one.

I don't expect that side navbar to change that much, so it could be a good idea.
