### ISSUE TITLE
blog entry contains a code example that is not working

### ISSUE THREAD

**Issue by zoechi** [angular/angular.io#3502]
http://angularjs.blogspot.co.at/2017/03/angular-400-now-available.html

```html
<div *ngIf="userList | async as users; else loading">
  <user-profile *ngFor="let user of users; count as count" [user]="user">
  </user-profile>
  <div>{{count}} total users</div> <!-- outside the scope of *ngFor -->
</div>
<ng-template #loading>Loading...</ng-template>
```
`count` can only be used inside `<user-profile>`

See also http://stackoverflow.com/questions/43212647/angular-official-docs-ngfor-count-demo-not-working/43213156?noredirect=1#comment73498450_43213156

**Comment by michaeI** [comment]
It seems like the **_count_** property was removed from NgFor directive - it is not working in angular 4.3 and it is not in the docs:
https://angular.io/api/common/NgForOf#local-variables

They seem to fix the issues by removing the features ...
