### ISSUE TITLE
Tutorial HTTP Section wrong Text

### ISSUE THREAD

**Issue by crtl** [angular/angular.io#3503]
Hi,
in the  [HTTP seciton of the tutorial](https://angular.io/docs/ts/latest/tutorial/toh-pt6.html) I found the following typo:

> Observables
> [...]
> Background
> [...]
>A request-cancel-new-request sequence is difficult to implement with **function Promise() { [native code] }s, but easy with s**.

**Comment by Foxandxss** [comment]
Uhh, ah, super weird.

Thanks.

**Comment by Foxandxss** [comment]
This is fixed on master. We will go live today.
