### ISSUE TITLE
Internationalization, select in title attribute

### ISSUE THREAD

**Issue by aviadisr** [angular/angular.io#3506]
HI, 

I am trying to use the select operator in title attribute and it is not working. 
Should it be working? is it the right syntax?

**Not working**:
`<div  i18n-title title="Visits ({timeView, select, pastHour {Last Hour} pastDay {Last 24 Hours} other {Daily visits})"></div>`

The same is working fine if I put it as the div content.
**working:**
`<div i18n>Visits ({timeView, select, pastHour {Last Hour} pastDay {Last 24 Hours} other {Daily visits})/div>`

The versions I am using are:
"@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",

Appreciate any help on that,

Thanks, 
Aviad

**Comment by ocombe** [comment]
Hello, sorry ICU expressions don't work in attributes yet, it's on our list of things to do (see: https://github.com/angular/angular/issues/9104)

**Comment by aviadisr** [comment]
Thanks for the answer.
For my  project this one and "use translation strings outside of a template" are both show stoppers. 
Hope you'll finish it soon.
