### ISSUE TITLE
"Latest" documentation will break bookmarks.

### ISSUE THREAD

**Issue by gravidThoughts** [angular/angular.io#3536]
I imagine that some developers build a knowledge base about the technologies they are working with and rely on bookmarks to access web resources within that system.

For example i have a `4.x` tag and a link to the changelog. I access that at the end of this year and I am looking at 5.x changelog.

Is there an architectural reason why `latest` is used in the url?

**Comment by Foxandxss** [comment]
A `4.x` tag where? The changelog part confused me. Can you explain with more detail?

**Comment by gravidThoughts** [comment]
Sorry. I meant in my knowledge base system, i have tagged that link with `4.x`.
When I query against `4.x` and `changelog` tags in my system, it will bring up a link that now really is for `5.x`

The point being, over time `latest` in the URL will mean something different. Why not just use an explicit version?

**Comment by Foxandxss** [comment]
`Latest` was an idea that began with the project but never took place. So latest is just another piece of the url that conveys no meaning. Our doc will be always the latest docs, except the one we have in v2.angular.io which is the v2 edition.

We are migrating to a new site and we are getting rid of it.

**Comment by gravidThoughts** [comment]
What will happen when 5 comes out?

**Comment by Foxandxss** [comment]
we will archive the current site probably like we did with v2

**Comment by gravidThoughts** [comment]
And new versions of the documentation will have URLs that will never change?

**Comment by Foxandxss** [comment]
yes sir

**Comment by gravidThoughts** [comment]
Ty sir!
