### ISSUE TITLE
Changes not being detected inside Reactive Form

### ISSUE THREAD

**Issue by IVIyg0t** [angular/angular.io#3546]
Unfortunately... I do not know how to replicate this issue... Otherwise I would provide you guys with a plunker. 

The Issue:
For some reason, the dropdown of a `md-select` does not want to display.  At the time I was thinking it was an issue with the Material 2 stuff.... But since then I've boiled it down to possibly being a change detection issue...  When thinking it was Material 2 problem I decided to roll my own Material-esque dropdown component.  This also did not work.  With a few log statements I was able to tell that the bits are being flipped accordingly, but the div that should shown/hid with ngIf does not show/hide.  It will only show/hide depending on the default value for the toggler.  I.e: when i set the default toggle to false the dropdown does not show... When I set the default to true the dropdown shows... But I cannot get the DOM to update the hide/show on click inside of this Reactive Form. 

Has anyone else experienced this?  What's the best way to go about fixing this?  Is there a way to force Angular to compile and redraw the form element?

Thanks guys... Sorry I'm not able to provide more concrete data :(

**Comment by Foxandxss** [comment]
That sounds like a question for stafckoverflow my friend.

Also, this repo is closed.

**Comment by IVIyg0t** [comment]
Oh, haha.  Thanks!
