### ISSUE TITLE
docs(aio): template reference variables cannot actually be referenced "anywhere" in the template

### ISSUE THREAD

**Issue by adamdport** [angular/angular.io#3555]
https://angular.io/guide/template-syntax#ref-vars: 

> You can refer to a template reference variable _anywhere_ in the template.

According to [this thread](https://github.com/angular/angular/issues/13516#issuecomment-267555104), this is incorrect, and should be fixed in the documentation. 

In addition, [it gets a bit complicated when combining template variables inside an `*ngIf`](https://github.com/angular/angular/issues/6179#issuecomment-237216645), and I think this deserves at least a mention in the "Template reference variable warning notes" section.

**Comment by hristokostov** [comment]
@Foxandxss what is the reason for closing this issue?

**Comment by Foxandxss** [comment]
This repo is "closed", deprecated. There is a giant warning when you create an issue, something like "Please don't open an issue here, do it on the angular repo. We will close all isues here"

**Comment by hristokostov** [comment]
Thanks for the quick reply, @Foxandxss . Does it mean all issues here are lost/ignored and have to be opened again in the angular repo?

**Comment by Foxandxss** [comment]
No, all the issues that were created before we made the switch are properly documented internally  in a document.

**Comment by hristokostov** [comment]
OK, thanks.
