### ISSUE TITLE
Webpack quickstart doesn't work as explained in the document. Can anyone help me in getting the correct setup ?

### ISSUE THREAD

**Issue by Maseeharazzack** [angular/angular.io#3568]
https://angular.io/guide/webpack

Dowloaded the quickstart it doesn't work properly. Is there any other alternative or any fix possible?
![image](https://user-images.githubusercontent.com/25129101/33318394-834980c6-d460-11e7-956d-0d15163e4aac.png)

**Comment by ericmartinezr** [comment]
Try to read the issue template next time. You can also read the message in the README.md :D

**Comment by Maseeharazzack** [comment]
Thanks ericmartinezr I will try to check that !

**Comment by Maseeharazzack** [comment]
Any other solution? I am unable to find any solution for this issue?

**Comment by Foxandxss** [comment]
The webpack guide is deprecated and will be removed.
