### ISSUE TITLE
https://angular.io/ down again

### ISSUE THREAD

**Issue by wlaidler** [angular/angular.io#3570]
![image](https://user-images.githubusercontent.com/1678737/33494379-135c9a9a-d691-11e7-981b-e0ab6d153246.png)

**Comment by salilchhetri** [comment]
I'm facing the same issue since today morning. Here's what I see in the console. 
![snip20171202_1](https://user-images.githubusercontent.com/11385867/33512275-dcf8c5a6-d752-11e7-87a6-961b4bca07f2.png)

**Comment by maxblax** [comment]
Same error for me. Still down...

**Comment by awanishraj** [comment]
+1

**Comment by maxblax** [comment]
http://devdocs.io/angular/

**Comment by gkalpak** [comment]
Can you please open issues about angular.io on https://github.com/angular/angular?

**Comment by ocombe** [comment]
You can use https://next.angular.io/ until we fix the main site

**Comment by ocombe** [comment]
It should be fixed now

**Comment by IgorMinar** [comment]
resolved: https://github.com/angular/angular/issues/20758#issuecomment-348789315
