### ISSUE TITLE
**docs(aio):** angular.io is not opening

### ISSUE THREAD

**Issue by pratik916** [angular/angular.io#3571]
https://angular.io/ has stopped working because of below error.

Code https://angular.io/polyfills.0dfca732c5a075c110d0.bundle.js

![aio1](https://user-images.githubusercontent.com/12393740/33514471-763061f8-d77a-11e7-9a8e-761c6ca2068b.PNG)

![aio2](https://user-images.githubusercontent.com/12393740/33514478-a16f1be8-d77a-11e7-88b6-beef871b122b.PNG)

**Comment by elmarti** [comment]
+1

**Comment by awanishraj** [comment]
+1

**Comment by sriganeshharitz** [comment]
+1

**Comment by gkalpak** [comment]
Duplicate of #3570.

**Comment by ocombe** [comment]
You can use https://next.angular.io/ until we fix the main site

**Comment by ocombe** [comment]
It should be fixed now

**Comment by IgorMinar** [comment]
resolved: https://github.com/angular/angular/issues/20758#issuecomment-348789315
