### ISSUE TITLE
marked filter incompletely applied?

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#364]
@petebacondarwin I checked out the latest from master, ran npm install, and I keep getting jade errors. Were you able to run `gulp check-deploy`? I have jstransformer-marked@1.0.1

I had to revert before e86fde8dc9375d01332db5ccd63170b46313b86a in order to build the site.

Help?

**Comment by petebacondarwin** [comment]
I believe that this is fixed by the following commit: https://github.com/angular/angular.io/commit/1372a78fed3090bd5c31abf2cd5f49b512163cdb
and also by ensuring that you run the commands using node 4.1.x
