### ISSUE TITLE
Docs: "the the"

### ISSUE THREAD

**Issue by aquinum6** [angular/angular.io#366]
Link: https://angular.io/docs/ts/latest/guide/forms.html
I think it should be only one "the" and there is used twice.

![untitled-1](https://cloud.githubusercontent.com/assets/1774702/11121759/e483ef1c-8957-11e5-9ceb-73202f6479d5.jpg)

**Comment by manekinekko** [comment]
I sent a PR.

**Comment by PascalPrecht** [comment]
Thanks @aquinum6 for opening this detailed issue. 

This is fixed in https://github.com/angular/angular.io/pull/367 we can close this one.
