### ISSUE TITLE
Enable case-sensitive filenames in tabs

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#37]
Tabs in code-box sections currently have UPPER CASE letters and seem geared toward displaying alternate files in different languages (e.g. ES5 & TypeScript versions of the same code). That isn't great if you're displaying multiple files in the same language, or files with different purposes (that happen to be in different languages).

For example, Dart examples typically have 1 or more Dart files, 1 or more HTML files, and 1 pubspec.yaml file. An example is at the top and bottom of my latest copy of [displaying-data.jade](https://github.com/angular/angular.io/blob/api-branch-dart-2/public/docs/dart/latest/guide/displaying-data.jade).

**Comment by alexwolfe** [comment]
fix in branch
