### ISSUE TITLE
RouteRegistry should uppercase "user"

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular.io#379]
In [`RouteRegistry#generate`](https://angular.io/docs/ts/latest/api/router/RouteRegistry-class.html) you can read 

>Given a normalized list with component names and params like: ['**user**', {id: 3 }] generates a url with a leading slash relative to the provided parentComponent.

When the first letter should be uppercased

>Given a normalized list with component names and params like: ['**User**', {id: 3 }] generates a url with a leading slash relative to the provided parentComponent.

**PS**
Shouldn't say also ?
>Given a normalized list with ***routes*** names

Not sure about the last one.

**Comment by wardbell** [comment]
Yup.  Should be **route** names, not **component** names.

**Comment by wardbell** [comment]
API doc corrections belong in [**angular source code**](https://github.com/angular/angular/issues).  
Please copy there. Closing here.
