### ISSUE TITLE
Optionally show filename in code sections

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#38]
This would let us avoid having to put a comment on the first line with the filename. Adding that comment made me hesitate to use line numbers in files, since we don't have those comments in the actual files.

For an example, see code in https://angular.io/docs/dart/latest/guide/displaying-data.html. 

Here's an example of code that has a filename (from https://www.dartlang.org/codelabs/darrrt/):
![filename-in-code-section](https://cloud.githubusercontent.com/assets/2164483/7287783/b013d4da-e90d-11e4-97a0-da82b4cbd60d.png)

The name could be at the upper or lower right, or maybe you have a better idea. Of course, we'd need to be careful not to cover up actual code.

**Comment by gorork** [comment]
@kwalrath @alexwolfe Just in case you haven't seen the changes from my pull request, the idea is to display names in header. 

File names have blue text color to correspond to the active button, and they appear with the same 'fadein' effect as code, which visually unite them. Additionally they have a nice "file-ish" icon. 

All of this lets user notice this information, which is pretty important for tutorials.

![screen shot 2015-05-17 at 09 01 20](https://cloud.githubusercontent.com/assets/6679057/7671160/11e510e0-fc76-11e4-8325-63c4dd709822.png)

For a single code snippet, they might still be showcased in header like this:
![screen shot 2015-05-17 at 09 01 47](https://cloud.githubusercontent.com/assets/6679057/7671163/348138fe-fc76-11e4-91c2-48ca8bf13bbb.png)

Hope this helps!

**Comment by alexwolfe** [comment]
@gorork this is very nice, thank you for the help. I'll tag you when my branch is in and we push the directives out, I'll likely incorporate your handy work. Great stuff, thank you! :+1:

**Comment by gorork** [comment]
@alexwolfe Sounds good! 
In a meantime, do you have something visual I could help with (e.g. #20 or #41)? However, if somebody is already working on these two, then maybe something else?

**Comment by alexwolfe** [comment]
@gorork Thanks I actually have two: 
1. https://github.com/angular/angular.io/issues/119
2. https://github.com/angular/angular.io/issues/19

Thanks so much for the help, I'll throw some more interesting design one's you're way when they pop up. Feel free to reassign those two to me if you're not comfortable with them or they don't look like fun :)

**Comment by kwalrath** [comment]
@gorork I love your solution.

**Comment by gorork** [comment]
@kwalrath @alexwolfe Hey guys, it's been a while! Any update on this issue?

**Comment by kwalrath** [comment]
@naomiblack does the latest site design handle the issue of providing a title for single files?

**Comment by kwalrath** [comment]
To answer my own question: Yes it does. See https://angular.io/docs/styleguide.html for details of using +makeExample.
