### ISSUE TITLE
Devguide-router: suggested edit

### ISSUE THREAD

**Issue by jvandemo** [angular/angular.io#389]
First of all, the guide is awesome! Great work @wardbell!

A small suggestion: currently [line 67](https://github.com/IdeaBlade/angular.io/blob/devguide-router/public/docs/ts/latest/guide/router.jade#L67) of the guide says:

> "Display it where? It will display in a **`RouterOutlet`** that we've placed in the host view's HTML."

I think this is technically not entirely correct as the content is actually inserted **after** the `router-outlet` and not inside of it.

So maybe something like

> "Display it where? It will display just behind **`RouterOutlet`** that we've placed in the host view's HTML."

would be more accurate?

**Comment by wardbell** [comment]
Thanks. I meant to confirm whether it appears inside, after, or replaces. Then forgot to look. I'm keeping this issue open until I figure out exactly what I want to say. Good catch.

**Comment by wardbell** [comment]
Closing for now. Please inspect again when it is released! Thanks.

**Comment by jvandemo** [comment]
@wardbell: ok, will do. Feel free to ping me if you want me to review the entire document before publishing. Keep up the good work!
