### ISSUE TITLE
Devguide-router: suggested edit

### ISSUE THREAD

**Issue by jvandemo** [angular/angular.io#390]
I think the route name 'Crisis Center' on [line 87](https://github.com/IdeaBlade/angular.io/blob/devguide-router/public/docs/ts/latest/guide/router.jade#L87) should be 'CrisisCenter'.

Not sure if creating an issue for this is the recommended way to report this. I would happily create a PR if possible. Feel free to let me know if there is more efficient way.

Thank you!

**Comment by wardbell** [comment]
Thanks for that, Fixed. This is an early early draft. It could be wildly different at any time. Not ready for PRs until we publish it. But do appreciate feedback.

**Comment by jvandemo** [comment]
@wardbell: thank you! I have read the entire document today and it is awesome. Great work so far!

What would you suggest? Shall I create issues for typos etc at this moment already? 

Or do you want me to wait until the document has matured and has been merged in the original repository?

I just want to make sure I don't chase you with issues before you feel the document is ready for review.

Thanks in advance and huge thumbs up!

**Comment by wardbell** [comment]
Please wait until the doc is released. Then ... bring it on!

I'm closing for now. I'll see more from you later.

**Comment by jvandemo** [comment]
:+1:
