### ISSUE TITLE
where is the source code for the angular2 app in testing tutorial?

### ISSUE THREAD

**Issue by mlennie** [angular/angular.io#401]
I'm in the "first app tests" page here: https://angular.io/docs/ts/latest/testing/first-app-tests.html 
I just read the line: "Step away from the Jasmine 101 folder and turn to the root folder of the application that we downloaded in the previous chapter."

I can't find the app to download. What chapter? What application?
Thanks

**Comment by mithun-daa** [comment]
In every likelihood it meant something to the effect of "Follow the ['QuickStart'](https://angular.io/docs/ts/latest/quickstart.html) steps and might just be a type. The [QuickStart](https://angular.io/docs/ts/latest/quickstart.html) does set up a folder structure. I am guessing that it was assumed that you had already gotten through the [QuickStart](https://angular.io/docs/ts/latest/quickstart.html) (which would not be a wrong assumption).

**Comment by mithun-daa** [comment]
This issue is a duplicate of #334

**Comment by mlennie** [comment]
Ah ok thanks @mithun-daa

**Comment by wardbell** [comment]
closed because duplicates #334
