### ISSUE TITLE
Angular 2 tutorial dead link in docs

### ISSUE THREAD

**Issue by jsec516** [angular/angular.io#402]
Link for form chapter is dead
https://angular.io/docs/ts/latest/guide/forms
which is found in the following url:
https://angular.io/docs/ts/latest/tutorial/toh-pt1.html

**Comment by mithun-daa** [comment]
You are missing the `.html` extension. Also, the forms chapter is not the same as what you mentioned. It is actually under *Developer Guides -> Forms*
Here is the complete link just in case.
https://angular.io/docs/ts/latest/guide/forms.html

**Comment by jsec516** [comment]
@mithun-daa thanks for the reply. I was just mentioning that there is a typo in the docs.

If you go to https://angular.io/docs/ts/latest/tutorial/toh-pt1.html 
There is a section named "Declare Multiple Form Directives" which contain following line
> Learn more about Angular Forms in the [Forms chapter](https://angular.io/docs/ts/latest/guide/forms)

I think 'Forms chapter' link is broken, because it redirects me to the 404 page. Let me know if I miss anything.

**Comment by mithun-daa** [comment]
You are right - the link is missing the `.html` extension. I have sent in a PR with that fix.

**Comment by wardbell** [comment]
Fixed thanks to PR #393
