### ISSUE TITLE
docs/ts/latest/guide/displaying-data 404 error

### ISSUE THREAD

**Issue by CreepyGnome** [angular/angular.io#411]
When going through the [tutorial part 1](https://angular.io/docs/ts/latest/tutorial/toh-pt1.html) it has a note in the Show our Hero section that states "Learn more about interpolation in the Displaying Data chapter." with a link to https://angular.io/docs/ts/latest/guide/displaying-data that then gives a 404 error.

**Comment by PascalPrecht** [comment]
This should already be fixed in master here ~ https://github.com/angular/angular.io/pull/375

@wardbell has this commit been deployed already?

**Comment by wardbell** [comment]
Yes
