### ISSUE TITLE
/docs/ts/latest/tutorial/toh-pt1.html Hero object placement instructions

### ISSUE THREAD

**Issue by CreepyGnome** [angular/angular.io#412]
The instructions on where to place the Hero object in the app.ts file in the /docs/ts/latest/tutorial/toh-pt1 document is not clear enough. It states "Create a Hero class with id and name properties. Keep this near the top of the app.ts file for now." The issue is with "near the top" that is to vague, as it can mean below the component declaration or above it. If you place the class below the component declaration and above the AppComponent class it will not work, it has to go above the component declaration and below the import declaration.  This tutorial should be more clear on things like this as the only thing you  can expect people to have a little knowledge of is JavaScript. Do not assume they have even a strong knowledge of that. 

So since it has to be right after the first line this is more than "near the top" and I recommend just being more specific on this, and possible future steps.

**Comment by wardbell** [comment]
Done. Closed by #941
