### ISSUE TITLE
https://angular.io/docs/ts/latest/tutorial/toh-pt1.html first mention of error 

### ISSUE THREAD

**Issue by CreepyGnome** [angular/angular.io#413]
On part 1 of the tutorial https://angular.io/docs/ts/latest/tutorial/toh-pt1.html you have the statement "Unfortunately, that change broke our application and we're no longer displaying the hero in the browser. Let’s fix that next." which is great and exactly what the follower of the tutorial will see visually.  

Then shortly after this in the next section you state "Unfortunately when we view the app in the browser we still have an error:" which has a few problems with it. First you say "still have an error" however this is the first mention of an error so you cannot "still have" one so you should say something like "we now have an error". The other issue is you do not state how the follower of the tutorial can find the error as it does not show up on the page when rendered. You seem to be assuming that they know to go look in the dev tools of their browser which up until this point you have not discussed at all. 

You may want to use this error message as an opportunity to make sure the follower of the tutorial knows how to get to the dev tools in the browsers you want to support in the tutorial. Plus for each browser you wish to support explain how to get to the location that will show the error. For example, in Chrome they would need to hit F12 and then get to the Console and it should be the first exception in the list, which at this point in the tutorial I actually have 6 errors showing in Chrome 46.

**Comment by wardbell** [comment]
I can't find this phrasing anymore. Maybe it was cured in an update? If you find it again, please open an issue.
