### ISSUE TITLE
Conflicting styles in nav bar

### ISSUE THREAD

**Issue by gamebox** [angular/angular.io#423]
Looks like the nav bar have both `background-regal` and `md-default-theme` set on it.  The background colors on each are very close, `#0273D4` vs `#1976D2` and both apply `color: #FFF` or an alternative thereof.  `.md-default-theme` seems to cascade to other selectors though.

Is the intention to have `background-regal`?  Might need to up the specificity( :cry: ) of that selector, or lower the specificity of the `.md-default-theme` selector, though unfortunately it is in an inline style block so would still win.  Can we just remove those properties from that ruleset?

Let me know the intention and I'll submit a PR

**Comment by wardbell** [comment]
Need a PR before we can entertain your suggestion. Closing until then. Thanks for the thoughts though.
