### ISSUE TITLE
API listing remaining issues since the restructure in alpha-47

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#433]
Look at what's up now on https://angular.io/docs/ts/latest/api/
- [x] missing angular2/compiler
- [x] missing angular2/platform/browser
- [ ] autocomplete doesn't let you filter by lib (e.g. you should be able to type "common" as a filter and see everything under *angular2/common*)

**Comment by naomiblack** [comment]
See https://github.com/petebacondarwin/angular.io/commit/cd9bf0cea54de6d6f6e22562fe3a5360dff28c11 for initial work that added the other missing libs

**Comment by petebacondarwin** [comment]
Actually that commit tries to fix the fact that the jade templates were hard-coded to have only one level of folders below the angular2 folder; but now we have `angular2/platform/browser` so we need to fix that

**Comment by petebacondarwin** [comment]
The missing libs commit is https://github.com/angular/angular.io/commit/eb37614d68ec9b81b79ef0c0abf8cc13cfe6a7c8

**Comment by petebacondarwin** [comment]
I can fix up the autocomplete for lib...
