### ISSUE TITLE
template/ng-content adding extra spacing in alpha47

### ISSUE THREAD

**Issue by filipesilva** [angular/angular.io#440]
After upgrading from alpha46 to alpha47, there seems to be some extra spacing added when projecting elements via `ng-content` or using anything `<template>` related (`ng-if`, `ng-switch`, `ng-for`).

plunker alpha46: http://plnkr.co/edit/698ShxZ0FhziYHxCu3t3?p=preview
![image](https://cloud.githubusercontent.com/assets/4172079/11558932/4e129a04-99ad-11e5-9e88-a2544edbb60c.png)

plunker alpha47: http://plnkr.co/edit/R8biozWaYxy1VcKJLqiQ?p=preview
![image](https://cloud.githubusercontent.com/assets/4172079/11558939/5ceec480-99ad-11e5-9ee0-2687ffd1aec7.png)

**Comment by IgorMinar** [comment]
@vicb please take a look

**Comment by wardbell** [comment]
Copied issue to [angular/angular, #5618](https://github.com/angular/angular/issues/5618)

**Comment by filipesilva** [comment]
Jeez, I thought I had reported this on https://github.com/angular/angular. Good catch Ward.

**Comment by vicb** [comment]
@filipesilva there is a PR pending on the angular repo. It would help if you could make sure it fixes your issue.
