### ISSUE TITLE
Site menu is broken om toch devices

### ISSUE THREAD

**Issue by hkgrani** [angular/angular.io#46]
I have this problem both om iPhone 6 and on HTC nexus tablet (only in portraitmode)

When the top toolbar is in narrow mode the toolbar turns into a dropdown button. Clicking this drop down  you are not able to select from the menu on these touch devices. Using a mouse on a desktop computer works

**Comment by naomiblack** [comment]
I have this same issue on my moto x -- I can workaround by turning the screen to landscape. Looks like a layout issue?

**Comment by alexwolfe** [comment]
Fixed :+1:
