### ISSUE TITLE
Recommend directory/library structure for Dart

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#461]
Parts or no parts? Relative or package: includes? What should the directory structure look like under web/ and lib/? How do non-Dart files (e.g. HTML) figure in?

@yjbanov and I should talk about this. See https://github.com/angular/angular/pull/5620 for more info about parts.

**Comment by kwalrath** [comment]
Our samples are consistently structured: no `library` directive, everything but main files go under lib, relative includes whenever possible. However, we keep most files directly under lib/ and don't (yet) use the Resource API. And we don't discuss the conventions that we use.

So I'm going to keep this bug open, as a reminder to consider doing more.

In related news, the directory structure and import conventions for library packages are now covered by https://www.dartlang.org/tools/pub/create-library-packages.html. The language tour will no longer cover `part` and `part of`, once @sfshaza commits https://chromiumcodereview.appspot.com/1679013002/.

**Comment by yjbanov** [comment]
I thought Resource API was dead @sethladd ?

Here would be my recommendations specifically for Angular apps:

- put as much code under `lib/` as possible so it can be imported and, more importantly, _tested_. It is tempting to put stuff in `web/` but code there is hard to unit-test.
- put component code and corresponding `html` and `css` files in the same directory; name related files the same (e.g. `button.dart`, `button.html`, `button.css`); use relative `templateUrl` and `cssUrl`. This way most file viewers will group related files together in long file lists and relative URLs will allow moving files around without having to update URLs.

**Comment by kwalrath** [comment]
Thanks for the details, @yjbanov. The Resource API I'm referring to is [package:resource](https://pub.dartlang.org/packages/resource), not the deprecated dart:core class.

**Comment by chalin** [comment]
This issue was moved to dart-lang/site-webdev#259
