### ISSUE TITLE
Abstract classes are not being processed by dgeni

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular.io#462]
For example `Compiler`, `AbstractControl`, `ViewContainerRef` are all missing from https://angular.io/docs/ts/latest/api/

This issue also causes many internal `@link`s to be broken.

// @naomiblack

**Comment by petebacondarwin** [comment]
One problem is that we are still using TypeScript 1.5.x in angular.io.
Updating to 1.6 (or maybe 1.7) improves things...

**Comment by petebacondarwin** [comment]
Upgrading TypeScript to 1.7.3 (se https://github.com/angular/angular.io/commit/326e1f73951e685ae0422749b3d2149afa88d64a) appears to have fixed this problem.

**Comment by IgorMinar** [comment]
Yay

**Comment by IgorMinar** [comment]
verified
