### ISSUE TITLE
running build-dart-cheatsheet after build-api-docs clobbers the api docs

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#463]
I'm not sure why this is the case, but if you run build-dart-cheatsheet, the API docs seem to get clobbered?

This is an issue when running `gulp check-deploy` because it doesn't itself run `build-api-docs`.

Why not build the cheatsheet along with the rest of the API docs...?
<img width="1312" alt="screen shot 2015-12-09 at 8 21 32 am" src="https://cloud.githubusercontent.com/assets/2286589/11691173/b201e2d6-9e4e-11e5-850b-5d74e68c65d0.png">

**Comment by petebacondarwin** [comment]
I wonder if you merged an outdated version of my PR...

**Comment by petebacondarwin** [comment]
This is fixed by 05a272a116e6aa3645ff0653d37d2594ae25e6cb
