### ISSUE TITLE
Internal links hide header

### ISSUE THREAD

**Issue by filipesilva** [angular/angular.io#477]
Clicking internal links will hide the linked section header. This is a problem present throughout `angular.io` though, because there is no padding/margin to offset the navbar at the top of the main section.

So we get this:
![image](https://cloud.githubusercontent.com/assets/4172079/11746679/0e9d2220-a017-11e5-8e1b-d0f635a120b7.png)

While we should get this:
![image](https://cloud.githubusercontent.com/assets/4172079/11746779/75b1eed2-a017-11e5-852f-8915f1e37969.png)

**Comment by petebacondarwin** [comment]
We had this problem with angular.js docs.  We fixed it by adding a directive:

```js
.directive('scrollYOffsetElement', ['$anchorScroll', function($anchorScroll) {
  return function(scope, element) {
    $anchorScroll.yOffset = element;
  };
}]);
```

and then using it on the header that was hiding the content:

```html
  <div id="wrapper">
    <header scroll-y-offset-element class="header header-fixed">
      <section class="navbar navbar-inverse docs-navbar-primary" ng-controller="DocsSearchCtrl">
    ...
```

We can do this in angular.io easily too.
