### ISSUE TITLE
Code styling in docs blends in with background

### ISSUE THREAD

**Issue by johnpapa** [angular/angular.io#505]
The color  `color: #9E9D24;` is being used for strings. This is too subtle on the light grey background for me to clearly see it. I recommend a darker color here. I show it below with darkslategrey ... but admittedly its not great either and and someone with a better eye should choose a nice dark color that contrasts with the light background.

Also, the header for the code blocks is gray just like the code block. I suggest the same blue that the angular docs uses #0273D4.

Here is what we have now:

![image](https://cloud.githubusercontent.com/assets/1202528/11800791/addeea38-a2ad-11e5-9c96-4cc867ad6a24.png)

and this

![image](https://cloud.githubusercontent.com/assets/1202528/11800802/d25774ac-a2ad-11e5-9941-b1203de01afa.png)

and I propose these

![image](https://cloud.githubusercontent.com/assets/1202528/11800808/df7963c0-a2ad-11e5-8bf8-6c04ffd22f1e.png)

and

![image](https://cloud.githubusercontent.com/assets/1202528/11800850/5bc76b2a-a2ae-11e5-8c42-968368c925a1.png)

cc / @naomiblack @wardbell

**Comment by robertmesserle** [comment]
@johnpapa What about the tabbed headers?

![image](https://cloud.githubusercontent.com/assets/571363/11802185/ad21e7a4-a2a2-11e5-9ad4-18612931118d.png)

**Comment by johnpapa** [comment]
for tabs, thats doable.

but the gray on gray is very subtle. i'd opt for something that has more contrast there.

**Comment by robertmesserle** [comment]
![image](https://cloud.githubusercontent.com/assets/571363/11802285/dfefd898-a2a3-11e5-8c51-6149f6d29bbc.png)

thoughts?

**Comment by johnpapa** [comment]
tab colors are better.

**Comment by wardbell** [comment]
Closing because either it's fixed or it won't be.
