### ISSUE TITLE
link to lifecycle hooks is broken

### ISSUE THREAD

**Issue by david-gang** [angular/angular.io#519]
At 
https://angular.io/docs/ts/latest/api/core/Component-var.html

the link of  [lifecycle hooks](https://angular.io/docs/ts/latest/api/core/angular2/lifecycle_hooks)  brings to a 404 page

**Comment by naomiblack** [comment]
@IgorMinar this is an API docs issue... we should do a pass through for broken links

**Comment by wardbell** [comment]
Not an angular.io issue
