### ISSUE TITLE
Best Practices Document blocked by Google Drive

### ISSUE THREAD

**Issue by comfroels** [angular/angular.io#536]
I was unable to view the best practices document listed at the bottom of the resources section of the site. It was blocked with permissions from google drive

**Comment by filipesilva** [comment]
Hi! Does this still happen to you? I tried right now on an incognito tab and I could access all the documents in that section. 

Can you try again and post a screenshot here please?

**Comment by comfroels** [comment]
I apologize, I must have had something strange going on with my Google session. Loads up now for me, thanks for the reply, though!

**Comment by filipesilva** [comment]
Glad to be of help!
