### ISSUE TITLE
In plunkr examples, anchor tags with href=javascript:false does not work as expected in Firefox

### ISSUE THREAD

**Issue by princemaple** [angular/angular.io#550]
They were meant to stop the clicking from doing anything, but leads to a page with "false" as the only content on it in Firefox.

Before clicking the link:
![screenshot_121615_125902_pm](https://cloud.githubusercontent.com/assets/1329716/11829951/c8cd1ffc-a3f4-11e5-9a3f-92e3c43397ac.jpg)

After clicking the link:
![screenshot_121615_125920_pm](https://cloud.githubusercontent.com/assets/1329716/11829957/d39a632c-a3f4-11e5-8b16-ec30e83337ee.jpg)

**Comment by wardbell** [comment]
Fixed a different way a while back.
