### ISSUE TITLE
docs need a note explaining that live examples only work in chrome 46+

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#564]
From a user-submitted issue...

It might be worth mentioning more prominently that the examples only work in Chrome 46+ and users on earlier versions need to include a link to the es6-shim cdn. Perhaps in a note box or callout. It does mention es6-shim later in the appendix but it took me a while to find it.

**Comment by wardbell** [comment]
Covered in #566

**Comment by wardbell** [comment]
Closed by 82383bc673723757e4a666dfeec018d245de9dc4
