### ISSUE TITLE
Wrong anchor 'Lifecycle Hooks' in the Architecture Overview page (Developer Guides)

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular.io#565]
Moved over from https://github.com/angular/angular/issues/5961

> The Lifecycle Hooks link point to # instead of the description of what it is.
Seem not be defined or wrong to me.
https://angular.io/docs/ts/latest/guide/architecture.html

**Comment by wardbell** [comment]
Fixed in PR #582
