### ISSUE TITLE
es6-shim is included in package.json but not in index.html.

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#566]
This makes chrome unable to run the quickstart app as-is.

**Comment by wardbell** [comment]
We discuss it in the text as an option to add if you need it. Most browsers don't. Not sure if we should just throw it on to index.html "in case". Will ask around.

**Comment by filipesilva** [comment]
I think shim related issues will remain despite callouts to this effect. Additionally, these are problems that a user might not have during the quickstart, but rather later on when he is doing a chapter (or his own experiments) on a different browser. 

In fact, if I were to use A2 now, or in the future, in a production system, as a seasoned developer I would see myself forced to add the shim. If I do not, it is merely a question of time until a user has problems.

This makes me think that having the shim should be the default, and removing it should be optional.

**Comment by filipesilva** [comment]
Also #564 seems to be the same as this.

**Comment by wardbell** [comment]
Ok. I will update all TS samples, plunkers, and the TS quickstart to load the shim by default. Would you look at the JS side of this please?

**Comment by wardbell** [comment]
All samples ship with a complete set of shims in packages and in index.html. Don't think this is a problem anymore.
