### ISSUE TITLE
"npm run go" is consistently referred to as "These two commands"

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#567]
URL: https://angular.io/docs/ts/latest/tutorial/toh-pt1.html

"npm run go" is consistently referred to as "These two commands" for example see the second page of "The Hero Editor" tutorial.

![image](https://cloud.githubusercontent.com/assets/2286589/11855185/8ebd8578-a3fd-11e5-851f-984db14bff5d.png)

**Comment by johnpapa** [comment]
yep ... i'll hit these in my changes tonight.

**Comment by johnpapa** [comment]
this is now fixed in parts 1, 2, and 3. please close after verifying @naomiblack
