### ISSUE TITLE
extra firstline indent in lang-bash code style should be removed

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#57]
For example, step 3 in https://angular.io/docs/js/latest/quickstart.html

![screen shot 2015-04-28 at 11 22 14 am](https://cloud.githubusercontent.com/assets/2286589/7377074/031dc016-ed99-11e4-8aca-9ee001c8a1c7.png)

**Comment by alexwolfe** [comment]
fixed in my branch, coming soon
