### ISSUE TITLE
explain why angular 2 doesn't have filter or orderby pipes

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#570]
This comes up in feedback often as a request. Would be good to explain it.

**Comment by DeborahK** [comment]
@wardbell I can take this on if no one else is working on it. I assume this should be written into the pipes chapter under built-in pipes ...

**Comment by rvanmarkus** [comment]
:+1:

**Comment by doczoidberg** [comment]
yes, I came here from a google searching for angular 2 and order by

**Comment by silentdth** [comment]
+1

I guess we could add them in as a pull request?

**Comment by wardbell** [comment]
It's on the way

**Comment by silentdth** [comment]
Great!
