### ISSUE TITLE
quickstart should require zone.js@0.5.8

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#571]
Seen in https://angular.io/docs/js/latest/quickstart.html

Hi, in package.json, there should be also zone.js@0.5.8

{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "npm run lite",
    "lite": "lite-server"
  },
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-beta.0",
    "systemjs": "0.19.6",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "zone.js": "0.5.8"
  },
  "devDependencies": {
    "lite-server": "^1.3.1"
  }
}

Otherwise it could cause:
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package zone.js@0.5.8 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.0 wants zone.js@0.5.10

**Comment by filipesilva** [comment]
Hi Naomi! You mentioned `0.5.8` but the npm error seems to indicate `0.5.10`, so that is the version I put in the PR above.
