### ISSUE TITLE
No padding around chapter sub titles in docs

### ISSUE THREAD

**Issue by johnpapa** [angular/angular.io#578]
There is not padding around the subtitle of a chapter when the browser width is shrunk to about < 800px.

<img width="795" alt="screen shot 2015-12-17 at 1 30 32 pm" src="https://cloud.githubusercontent.com/assets/1202528/11878229/6d8a3f48-a4c2-11e5-97a5-cfae0623bf90.png">

cc @naomiblack @wardbell

**Comment by wardbell** [comment]
Closed by #687
