### ISSUE TITLE
Dropdown for quickstart lists JS but shows TS

### ISSUE THREAD

**Issue by jonathandturner** [angular/angular.io#58]
The quick start https://angular.io/docs/js/latest/quickstart.html seems to list JS and Dart, but if you select JS it shows TS.

Would be cool if you could select TS, JS (for vanilla ES5/ES6), or Dart.

**Comment by naomiblack** [comment]
I think we're going to leave this as-is for now, because we really want JS developers to see the TS example side-by-side so they can compare with ES5.
