### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by milesholt** [angular/angular.io#581]
I'm getting the following error while trying to use the HTTP service example (https://angular.io/docs/ts/latest/api/http/Http-class.html):

Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:3000/angular2/http
	Error loading http://localhost:3000/app/boot.js
angular2-polyfills.js:138

Tried it on Chrome and Firefox. 

Code:

import {Component} from 'angular2/core';
import {Http, HTTP_PROVIDERS} from 'angular2/http';

@Component({
  selector: 'my-app',
  viewProviders: [HTTP_PROVIDERS],
  template: '<p>Test Http page</p>'
})

export class HttpComponent {
 
}

It works if I remove the line -
'viewProviders: [HTTP_PROVIDERS]'

**Comment by ericmartinezr** [comment]
@milesholt you have to add the http bundle

For example
```
<script src=".../http.dev.js"></script>
```

**Comment by milesholt** [comment]
That worked, thanks
