### ISSUE TITLE
Possible typo Developer guides 9.

### ISSUE THREAD

**Issue by amritk** [angular/angular.io#587]
In routing and navigation from the Developer guide, under Router Lifecycle Hooks:

>There is a important difference between the router lifecycle hooks and the component hooks. The component hooks are synchronous. The component hooks are synchronous and they can't stop creation or stop destruction!

Are one of them supposed to be router lifecycle hooks?

**Comment by filipesilva** [comment]
I believe this section has been reworded since. Can you double check if it is still confusing?

**Comment by wardbell** [comment]
Yes. I took care of it. Thanks for drawing attention to that mistake.
