### ISSUE TITLE
Docs spelling mistake

### ISSUE THREAD

**Issue by danielgolub** [angular/angular.io#590]
https://angular.io/docs/ts/latest/guide/architecture.html

Here's a **HeroServce** that fetches heroes and returns them in a resolved promise. The HeroService depends on the LoggerService and another BackendService that handles the server communication grunt work.

It should be HeroService, not HeroServce.

**Comment by wardbell** [comment]
Closed by e14f950a7cffc8a7086cf7f7159ecec4f87ab0f4
