### ISSUE TITLE
require system.js as dependency?

### ISSUE THREAD

**Issue by ArgTang** [angular/angular.io#597]
I just got the 5 min quickstart to run but i had to add systemjs as a dependency. 
Chrome did not want to run the example without:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
Rx.js:2 Uncaught ReferenceError: System is not defined
angular2.dev.js:2 Uncaught ReferenceError: System is not defined
localhost/:16 Uncaught ReferenceError: System is not defined
```

i see that rxjs has system.js as a devdependency, is that a reason it does not install? do we need to add it?

**Comment by wardbell** [comment]
SystemJS is a listed dependency. Why do you think it is not?

**Comment by ArgTang** [comment]
yes you are right. dont know how i missed that. wood for trees or something
