### ISSUE TITLE
Unit Testing (Routing)

### ISSUE THREAD

**Issue by jimulle** [angular/angular.io#599]
Is there a plan to add a section of the "Testing Guides" chapter focusing on testing routing? I cant seem to find much documentation online for testing routing in Angular2.

**Comment by wardbell** [comment]
A "plan" to do so exists in the sense that it is on our list. I don't think it is possible at the moment - at least it isn't practical. You're stuck with end-to-end testing for the nonce.

**Comment by wardbell** [comment]
Closing because this is old. There is material on testing components that use the router in the current chapter with a future update on the `RouterTestingModule` coming.
