### ISSUE TITLE
emphasize that dart_to_js_script_rewriter transformer must be after angular2 transformer

### ISSUE THREAD

**Issue by kasperpeulen** [angular/angular.io#600]
@kwalrath 
In https://angular.io/docs/dart/latest/quickstart.html it could be empasized that dart_to_js_script_rewriter transformer must be after angular2 transformer. If this is not done, templates break:

![image](https://cloud.githubusercontent.com/assets/1035299/11957157/32d5b506-a8c0-11e5-8f27-251de39c083b.png)

**Comment by kwalrath** [comment]
Thanks, Kasper!

**Comment by chalin** [comment]
This issue was moved to dart-lang/site-webdev#254
