### ISSUE TITLE
Typescript dev environment in JS quickstart

### ISSUE THREAD

**Issue by s9tpepper** [angular/angular.io#607]
The quickstart page for JS mentions needing a Typescript configuration and TypeScript aware editor, I think this part is not relevant for JS but I'm just starting to get acclimated to Angular 2.

**Comment by s9tpepper** [comment]
The relevant text: 

Development Environment

We'll need a place to stand (the application project folder), some libraries, some TypeScript configuration and the TypeScript-aware editor of your choice.

**Comment by filipesilva** [comment]
That's a mistake alright! I'll fix it.
