### ISSUE TITLE
(Angular 2.0.0 beta.0 + Polymer 1.0) paper-input data binding not working on IE11

### ISSUE THREAD

**Issue by ldtung** [angular/angular.io#612]
I have a paper-input component declared as below, where myField is a field initialized with value="TestValue"

paper-input ngDefaultControl [(ngModel)]="myField" label="my label"

On chrome, it's working fine, "TestValue" is displayed when loading screen.
The two way data binding working fine.
but on IE11, "TestValue" is not displayed. Even if i changed value in paper-input to something else,
the data model is not updated.
I noticed that on IE, the ShadowDOM is not supported natively. Is that a problem?

Any idea? Thank in advance

**Comment by naomiblack** [comment]
Please file issues with angular 2 under https://github.com/angular/angular/issues, along with a plunker if possible? This repository is just the site content. 

Your issue seems related to https://github.com/angular/angular/issues/5531 possibly comment on that one, or open a new issue?

**Comment by ldtung** [comment]
I knew the reason why, on IE, the Angular application which using Polymer elements must wait until all htmls loaded before booting up.
This solution works for me:
// Remember that we must wait until all HTML links loaded before booting the Angular 2 application.
// on IE, it's not working without this.
HTMLImports.whenReady(function () {
System.import('dist/boot').catch(
console.log.bind(console)
);
});
