### ISSUE TITLE
Router doc typos

### ISSUE THREAD

**Issue by johnpapa** [angular/angular.io#619]
1. **Maye** should be **Maybe** https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/guide/router.jade#L205

2. Live example is not working. When clicked it leads to a problem https://angular.io/resources/live-examples/router/ts/plnkr.html
![image](https://cloud.githubusercontent.com/assets/1202528/12034799/e1914342-ae03-11e5-8a86-eb22cbee0b3a.png)

3. Images may need to be updated for new CSS to match ToH

4. Is the intent of `~/app` well known? Should you consider `/app` ? 
https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/guide/router.jade#L288

5. We (ward and I) discussed moving the routing setup of `ROUTING_PROVIDERS` to the `AppComponent`. You may want to revise this accordingly.
https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/guide/router.jade#L287-L300 and https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/guide/router.jade#L470

6. This has been adjusted in ToH to have `<nav> ... </nav>` around the links. Consider matching.
https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/guide/router.jade#L314

7. There is an extra period after the word **folder** that needs to be removed
https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/guide/router.jade#L441-L442

8. **significantly** is spelled wrong
https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/guide/router.jade#L771

9. Sentence should end with the word **right**
https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/guide/router.jade#L797

10. You mention the `routerCanDeactivate` method but it is not implemented yet in the code example you just showed. This is important!
https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/guide/router.jade#L892

cc @wardbell

**Comment by wardbell** [comment]
Thanks, John 

I took almost all of your suggestions.

I decided against (5) *for the moment*. I'm inclined to keep `ROUTER_PROVIDERS` at the boot level for the moment, particularly in view of my uncertainty about when and how to switch to the `HashLocationStrategy`.
