### ISSUE TITLE
Generate a Dart API doc version

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#62]
Needs infrastructure for conditional code examples, and Dart examples in the API

**Comment by alexwolfe** [comment]
@naomiblack can you assign this to someone, not sure who should take this. Thanks.

**Comment by naomiblack** [comment]
I'm still working on it, slowly.

**Comment by kwalrath** [comment]
@chalin is working on this.

**Comment by chalin** [comment]
See #1593 for comments on progress made to date.

**Comment by chalin** [comment]
Closed #1593 "quick fix". The new task tracker & status issue is #1880.
