### ISSUE TITLE
ContentChild query does not work with string queries

### ISSUE THREAD

**Issue by bennylut** [angular/angular.io#625]
When using the ContentChild annotation with a type query it works very well but when I try to use string query - for some reason the annotated field is always null. 

the following is a SSCCE that reproduce the problem:

```
import {Component, ContentChild} from 'angular2/core';
import {bootstrap} from 'angular2/platform/browser';

@Component({
  template: `
    <ng-content select="inner"></ng-content>
  `,
  selector: 'ctr'
})
class TestContainerComponent {
  @ContentChild('inner') inner;

  ngAfterContentInit() {
    console.log('inner: ', this.inner);
  }
}


@Component({
  template: `
    <ctr> <inner> SOME TEXT </inner> </ctr>
  `,
  selector: 'app',
  directives: [TestContainerComponent]
})
class TestAppComponent { }

function main() {
    return bootstrap(TestAppComponent).catch(err => console.error(err));
}

document.addEventListener('DOMContentLoaded', main);
```

When running the above code the result is: 
console: inner: null
view: SOME TEXT

although the API docs show a usage example with a type query, the type definition indicates that the query can be either a Type or a string (Type | string) 

EDIT
I am sorry, I posted the issue here instead of in the angular/angular site - it was re-posted there, please close this issue here..

**Comment by wardbell** [comment]
Closed at your request
