### ISSUE TITLE
Conditionals within prose

### ISSUE THREAD

**Issue by btford** [angular/angular.io#63]
I'd like to know how to add conditional text in our Jade templates.

I have three cases:

1. Conditionally changing a phrase or word
2. Conditionally using different paragraphs:
3. I'd like to break up some of the content into separate files and conditionally inlining the contents of them: `if (dart) { include('router/example1/dart.jade' } else { include('router/example1/es5.jade' } ` etc.

For all of these, I need to support four cases: ES5+Angular 1, ES5+Angular 2, TypeScript+Angular 2, Dart+Angular 2.

Jade probably supports this, but I do not have cycles to investigate. A short example would suffice. Thanks!

**Comment by alexwolfe** [comment]
@btford good point, I'll put some documentation in the style guide then close this when it's ready.

**Comment by wardbell** [comment]
Obsolete issue. See jade-sharing.
