### ISSUE TITLE
Specify that Router and Http bundles must be added when using SystemJS

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular.io#632]
So far the docs use SystemJS to set up the apps. The problem is that when the user reaches the routing or the http module they hit against this wall

```
Uncaught SyntaxError: Unexpected token < 
```

It's hard to debug, since basically says nothing. This is solved by adding the necessary bundle which the docs don't mention. They're in the plnkr examples, but it's not obvious.

A few examples of users suffering of this

https://github.com/angular/angular.io/issues/581
https://github.com/angular/angular/issues/6003

Not to mention [StackOverflow](http://stackoverflow.com/search?q=%5Bangular2%5D+%22Unexpected+token+%3C%22) and others.

**Comment by wardbell** [comment]
Actually the need to load the router is and always was [in the router documentation](http://localhost:3000/docs/ts/latest/guide/router.html#!#getting-started).

Unfortunately, this instruction appears well down the page.  I'll add it also to the "Basics" section near the top so folks encounter it earlier.

**Comment by wardbell** [comment]
Closed by PR #637
