### ISSUE TITLE
Use a filter for escaping HTML

### ISSUE THREAD

**Issue by btford** [angular/angular.io#64]
It's cumbersome to do this manually: https://github.com/angular/angular.io/blob/master/public/docs/js/latest/guide/displaying-data.jade#L149-L155

Jade docs: http://jade-lang.com/reference/filters/

**Comment by kwalrath** [comment]
Yes, please.

**Comment by alexwolfe** [comment]
+1 we'll have to create our own custom filter. Haven't found a good one for this yet.

**Comment by alexwolfe** [comment]
https://angular.io/docs/styleguide.html

Added to code examples now in styleguide :)
