### ISSUE TITLE
IE11 issues - requires zone for getHeroesSlowly, Router refresh issue

### ISSUE THREAD

**Issue by MichaelChambers** [angular/angular.io#645]
I ran the Tour of Heroes tutorial, but had issues with the getHeroesSlowly command in IE11. It works fine in Chrome and Firefox.

Using this plunk: http://plnkr.co/edit/7zs004cRaz4ebfDZz5nN?p=preview
I cannot get the heroes list to show up in IE11 without uncommenting the app/app.component.ts line 54: `this._ngZone.run(...`
Note that the promise works and the data is retrieved 2 seconds later, but Angular doesn't update with the new data.

I also had an IE11 issue with the Routing example. I updated the plunk with the es6 shim - http://plnkr.co/edit/IedH4JQg45z6pP92VvY1?p=preview
 Just like the issue above, it works fine in Chrome. But in IE11, I have to click 3 times to switch and show the other top level route:
 (It loads with neither Crises Center nor Heroes selected)
 First Click on Dashboard Heroes - I get the HEROES title below but no list
 Second Click on Dashboard Heroes - the Heroes dashboard button blue background/white text styling shows up
 Third Click on Dashboard Heroes - the Heroes list shows up.
 Same 3 clicks to get the Crises Center list.
 And I can't get to either detail page, because the list goes away on the first click, and I guess it needs more.

(I first reported these in the wrong spot - https://github.com/johnpapa/angular2-tour-of-heroes/issues/41 )

**Comment by claurin** [comment]
Setting a stop in IE11 devtools on: 

setTimeout(()=>resolve( HEROES ), 2000) 

and then hitting continue allows time for HEROES to be defined and render in the component.

**Comment by claurin** [comment]
This IE11 issue reported at es6-promise seems relevant:

https://github.com/jakearchibald/es6-promise/issues/109

**Comment by wardbell** [comment]
Fixed as of beta.7
