### ISSUE TITLE
useAsDefault in parent route doesn't redirect to default child

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular.io#646]
From this [question](http://stackoverflow.com/q/34601822/4933038)

In this [plnkr](https://angular.io/resources/live-examples/router/ts/plnkr.html) from the docs the current `useAsDefault` doesn't work as expected.

```
  // AppComponent.ts
  { // Crisis Center child route
    path: '/crisis-center/...',
    name: 'CrisisCenter',
    component: CrisisCenterComponent,
    useAsDefault: true // <<--
  },

  // CrisisCenterComponent
  @RouteConfig([
  {path:'/',         name: 'CrisisCenter', component: CrisisListComponent, useAsDefault: true},
  {path:'/:id',      name: 'CrisisDetail', component: CrisisDetailComponent},
  {path:'/list/:id', name: 'CrisisList',   component: CrisisListComponent}
])
```

Note the extra `useAsDefault` in the AppComponent's RouteConfig. This doesn't work as noted in the question. By removing it and adding a redirectTo it works as expected.

```
  // AppComponent.ts
  { path : '/', redirectTo : ['CrisisCenter'] },
  { // Crisis Center child route
    path: '/crisis-center/...',
    name: 'CrisisCenter',
    component: CrisisCenterComponent
  },
```

I'm not aware to be honest of that behavior in Router (although it makes perfect sense, asking it as a feature would be nice), but I think it's a mistake.

**Comment by wardbell** [comment]
You are correct.  It doesn't work when the target component is a child routing component. It is supposed to work. Redirect serves a different purpose.

I have reported this issue and left the doc as is, hoping that it will become correct soon.  I may have to reevaluate my notion of "soon".

**Comment by ericmartinezr** [comment]
@wardbell thanks for answering. I thought it was a mistake in the docs, thanks for confirming.
