### ISSUE TITLE
We should not recommend installing with sudo

### ISSUE THREAD

**Issue by btford** [angular/angular.io#65]
From the readme:

> sudo npm install -g harp@v0.15.2

This is poor practice.

See: 
* http://www.johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/
* https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

**Comment by btford** [comment]
Also: is there a reason we recommend installing a specific version of harp?

If so, we should recommend running with `npm run`, and add harp to our `package.json`: https://docs.npmjs.com/cli/run-script

**Comment by alexwolfe** [comment]
@btford I would say we should lead with the recommended but provide both. It's ultimately a developers choice how they want to roll. Our job is not to enforce but to guide. I've user tested this type of thing extensively (sudo vs non sudo) and it causes some serious issues if you don't have both (people simply fail). We cannot assume a developers level of experience with best practices etc. many are beginners. 

On a personal note, yes non sudo is a much better way to roll. However, UX wise I've seen this fail too many times.

**Comment by alexwolfe** [comment]
Updated readme to lead with non sudo install and added or sudo... depending on your permissions.

**Comment by btford** [comment]
@alexwolfe – I can appreciate the UX benefits, but I must insist that we avoid `sudo`. `npm install` makes no guarantees about sandboxing install scripts. Any script could easily call out to shell as super user. If any package in the transitive list of dependencies for harp is compromised, it means we'd potentially help a malicious package author own someone's computer.

IMO because the security risks are so great, they should trump UX.

I'm happy to take personal responsibility for replying to issues on this repo about installing harp, should they arise.

**Comment by btford** [comment]
How about this:

1. add a `package.json` to this repo.
2. `npm install --save harp`

In the readme:

> Run `harp` with `npm run harp`

This avoids making the user update their shell's PATH, and avoids any possible warnings about permissions, since harp is installed only locally.

**Comment by alexwolfe** [comment]
@btford I think the best thing is for us to just link to the harp js site. Will take all of the responsibility off of us, I can update the readme to just point there, ie install harp.js etc. 

There was a breaking change in harp's latest version so we hard versioned on harp@v0.15.2
I plan on fixing the bug this weekend and will this should go away and we can use the latest.

**Comment by petebacondarwin** [comment]
I agree with @btford - users don't want to have to click a link when a simple two line command snippet is ample.
