### ISSUE TITLE
Public build of master HEAD

### ISSUE THREAD

**Issue by abierbaum** [angular/angular.io#652]
Is there an autogenerated site that always has the latest and greatest build of the ng2 docs straight from master?  

If not, I think this would be very useful as the documentation continues to evolve and expand.  I have found a number of questions and confusing topics that have already been fixed in the docs.  It would have saved me a great deal of time and frustration if I could just browse the in development documentation.

**Comment by wardbell** [comment]
Sorry no. When you wrote we were behind on publishing. Now we publish pretty quickly, often several times a day.

If you need fresher than that, you'll have to clone and generate yourself per the instructions in the README.md.  That's the best we've got.
