### ISSUE TITLE
First line of <code> block has different indentation

### ISSUE THREAD

**Issue by btford** [angular/angular.io#66]
![screen shot 2015-04-28 at 5 00 43 pm](https://cloud.githubusercontent.com/assets/474988/7382731/30b7b700-edc8-11e4-9e71-1747476e6f3b.png)

Occurs in modern chrome on all `<code>` blocks.

**Comment by alexwolfe** [comment]
nice catch :eyes:

**Comment by alexwolfe** [comment]
should be fixed now
