### ISSUE TITLE
Getting 404 error while refreshing browser.

### ISSUE THREAD

**Issue by sagar-k** [angular/angular.io#663]
Hi, 

I have created a sample app using @RouteConfig and it working fine, See the url changes and view added according to configuration. but when I am refreshing page its shown 404 error :( .

I am using webStrom IDE to build and run the angularJS2 APP.

The same problem happen with given live example on angular.io

I have download the sample code example for routing and navigation in AngularJS2 on https://angular.io/resources/live-examples/router/ts/plnkr.html which given on angular.io and open the project into webStrom and run on it.

It working fine but after do some routing  and then refresh the page it shown 404 Error. 

And Please correct me if I do an wrong way :)

**Comment by wardbell** [comment]
I'm sorry but this repository is not the proper place to ask for help. It IS a place to describe specific/actionable issues with the documentation.  I suggest you ask your question again on StackOverflow.

Accordingly, I'm closing this issue.
