### ISSUE TITLE
image not refreshed after taking a photo from a camera

### ISSUE THREAD

**Issue by zamrokk** [angular/angular.io#664]
i am using this simple code with ionic 2 : 

     <button (click)="takePicture()" >Take a pic!</button>
    <img [src]="url || '//:0'">

then this is my Typescript page : 

      public takePicture() {
        console.log("Going to take a pic ...");
        navigator.camera.getPicture(function (imageURI) {
            this.url = imageURI;

            console.log("URI of the picture taken is : "+this.url);

            //var image = document.getElementById('myImage');
            //image.src = imageURI;

        }, function (err) {
            console.log(JSON.stringify(err));
        }, {});
    }

after taking the picture, nothing is displayed. I noticed that the "src" is not updated by Angular. I tested a part of the code in comments thats works using "var image= ... image.src=..."  but is directly manipulating the DOM and i don't want this.

Please do you see where is coming the problem ?

**Comment by zamrokk** [comment]
i also post the same issue on stackoverflow

http://stackoverflow.com/questions/34660141/image-not-refreshed-after-taking-a-photo-from-a-camera

**Comment by positron** [comment]
This repository is for the angular2 documentation, https://angular.io/, not the angular code itself.
