### ISSUE TITLE
Plunker example for ngModel not updated

### ISSUE THREAD

**Issue by juristr** [angular/angular.io#673]
Hi,

the [Plunker example](http://plnkr.co/edit/R3UX5qDaUqFO2VYR0UzH?p=preview) for the [ngModel](https://angular.io/docs/ts/latest/api/common/NgModel-directive.html) docs page isn't up-to-date as it still uses the `[(ng-model)]` version from the alpha version. The src code on the docs page itself is fine.

Wanted to submit a PR as it is really easy to fix, but I'm not sure whether I can just fork the plunker and link the fixed one to the docs or whether you have a dedicated user/procedure for updating plunks. In case, let me know and I submit a PR. 

Here's the fixed Plunkr in case: http://plnkr.co/edit/l5ARZfIzgkShOgJUHRPp?p=preview

_(btw. is this the place to submit issues with the docs or the angular repo??_

**Comment by wardbell** [comment]
Not the place.  Issues with API docs go in the [**angular source code**](https://github.com/angular/angular/issues).

This is one of a great many out-of-date API samples. A sweep of API docs is coming. So I'm closing this, not because you're wrong, but because it should be handled there.

Thanks.
