### ISSUE TITLE
link to the dartlang.slack.com angular2 channel in Help & Support for Dart

### ISSUE THREAD

**Issue by kasperpeulen** [angular/angular.io#675]
I think this channel is much more helpful for Dart developers:
https://dartlang.slack.com/messages/angular2/details/

Then the irc (where it currently links to), see (https://angular.io/docs/dart/latest/help.html)

**Comment by kwalrath** [comment]
I agree.

**Comment by kwalrath** [comment]
Just to be clear, is it https://angular.io/docs/dart/latest/help.html that you're talking about?

**Comment by wardbell** [comment]
Closing because @naomiblack removed "help and support" from the docs navigation. Not sure what will take its place.
