### ISSUE TITLE
Suggestion for content navigation structure

### ISSUE THREAD

**Issue by gnomeontherun** [angular/angular.io#678]
I'd like to suggest some restructuring to the navigation to better guide the reader through a learning path. Right now the navigation is somewhat choppy. Even the learning path outlined in the architecture guide has you jump around several places.

I have it in two segments, reference and learning. I think there will be a lot of people who come back for the API docs, and having that near the top will be helpful, along with other reference materials. 

The bottom would have the content in an order that would be conceptually possible to read directly through as the learning path. I also suggest there should be a dev guide on Components, since they are so fundamental. I also didn't think it was necessary to separate 'developer' and 'testing' guide content.

* Home
* Architecture
* API
* Cheatsheet

-----

* Quickstart
* Tutorial
  * Tour of Heros chapters
* Guides
  * Components (Not currently there)
  * Templates & Displaying Data
  * Pipes
  * Events (currently called User Input)
  * Forms
  * Attribute Directives
  * Structural Directives
  * Routing & Navigation
  * Dependency Injection
  * Hierarchical Injectors
  * Lifecycle Hooks
  * Upgrading from Angular 1
  * Testing with Jasmine
  * Unit tests
* Glossary

**Comment by wardbell** [comment]
Naomi already has a re-org that addresses most of your concerns. It’s on the backlog

 

A chapter on components and directives is on the backlog.
