### ISSUE TITLE
A slight hiccup

### ISSUE THREAD

**Issue by longhaohe** [angular/angular.io#679]
![image](https://cloud.githubusercontent.com/assets/13602053/12261319/3f706c7e-b95b-11e5-9cf2-e5d12793abcc.png)

[Angular Cheat Sheet](https://angular.io/docs/ts/latest/guide/cheatsheet.html)

**Comment by wardbell** [comment]
The cheat sheet is actually defined in the Angular repo. Raising the [issue #7504](https://github.com/angular/angular/issues/7504) there.

**Comment by petebacondarwin** [comment]
This is already fixed at https://github.com/angular/angular/commit/c8e909f8c9f0b18a6728b0088851099f54ca7826
