### ISSUE TITLE
Within the guide, changing languages always puts you at the index

### ISSUE THREAD

**Issue by btford** [angular/angular.io#68]
If I'm in "Angular 2 JS" docs for the router, and I click the "Angular 2 Dart" select box at the top of the page, I am taken to the index page for the "Angular 2 Dart docs" rather than to the page on the router in "Angular 2 Dart."

![screen shot 2015-04-28 at 5 43 40 pm](https://cloud.githubusercontent.com/assets/474988/7383116/4c030658-edce-11e4-85d4-d43b1da1db63.png)

This makes it difficult for me to compare the JS and Dart versions of the Router while I'm maintaining two separate copies.

**Comment by alexwolfe** [comment]
@btford this will change in the future, temporary hold over since the pages are not mirroring right now.

**Comment by kwalrath** [comment]
Ward was fixing this. Looking at the website, the behavior seems correct now.
