### ISSUE TITLE
Quickstart Not working

### ISSUE THREAD

**Issue by aomahony** [angular/angular.io#69]
I cloned the repo and followed the steps, and it's resulting in:

 Uncaught SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
es6-module-loader@0.16.5.src.js:2605 GET https://registry.jspm.io/app.js 404 (Not Found)
es6-module-loader@0.16.5.src.js:140 Potentially unhandled rejection [3] Error loading "app" at https://registry.jspm.io/app.js
Not Found: https://registry.jspm.io/app.js (WARNING: non-Error used)

**Comment by naomiblack** [comment]
@rkirov is this closed now?

**Comment by rkirov** [comment]
This issue with zone.js that occurs only in firefox (@aomahony pls include the browser you are using). Brian fixed it in https://github.com/angular/zone.js/commit/16855e59a6f11d8d4b927c9f7ea64c03696549ac, but we have to wait for zone.js release before it makes it into the official bundle release.

Because the quickstart uses a fixed bundle from https://github.com/angular/ts-quickstart I just patched the changes into that bundle (https://github.com/angular/ts-quickstart/commit/302f64685fa45b8d17385a0193383d4da2d98e41). The quickstart should work in Firefox now.

**Comment by aomahony** [comment]
It wasn't working in Chrome (apologies for not including that, I shall next time!), but now it's working in Chrome and Firefox, but not Safari.  Here's the error:

[Error] Potentially unhandled rejection [2] Map@[native code]
clone@http://localhost:8081/bundle/angular2.dev.js:10206:46
AppView@http://localhost:8081/bundle/angular2.dev.js:29677:58
createView@http://localhost:8081/bundle/angular2.dev.js:16933:46
_createViewRecurse@http://localhost:8081/bundle/angular2.dev.js:28186:44
createInPlaceHostView@http://localhost:8081/bundle/angular2.dev.js:28112:51
http://localhost:8081/bundle/angular2.dev.js:18817:72
run@http://localhost:8081/bundle/angular2.dev.js:87:24
zoneBoundFn@http://localhost:8081/bundle/angular2.dev.js:64:22
D@https://jspm.io/es6-module-loader@0.16.5.js:1:12117
I@https://jspm.io/es6-module-loader@0.16.5.js:1:11746
when@https://jspm.io/es6-module-loader@0.16.5.js:1:15420
run@https://jspm.io/es6-module-loader@0.16.5.js:1:14459
_drain@https://jspm.io/es6-module-loader@0.16.5.js:1:3232
drain@https://jspm.io/es6-module-loader@0.16.5.js:1:1653
	(anonymous function) (es6-module-loader@0.16.5.js, line 1)
	i (es6-module-loader@0.16.5.js, line 1)
	u (es6-module-loader@0.16.5.js, line 1)
	(anonymous function) (angular2.dev.js, line 127)
	(anonymous function) (angular2.dev.js, line 71)
	run (angular2.dev.js, line 87)
	zoneBoundFn (angular2.dev.js, line 64)

**Comment by rkirov** [comment]
Thanks @aomahony! https://github.com/angular/angular/issues/1640 tracks the Safari issue, but it might take a day or so to fix properly.

**Comment by aomahony** [comment]
No problem!  Safari to me is the new IE of "those types of problems" ;)

**Comment by rkirov** [comment]
https://github.com/angular/angular/pull/1644 tracks the fix for safari. It didn't make it to alpha.22, but most likely it will be in alpha.23.

Closing this issue as angular/angular will track the progress.
