### ISSUE TITLE
Css added with "styleUrls " does not get apply.

### ISSUE THREAD

**Issue by pankajbadukale** [angular/angular.io#695]
When using "styleUrls" it create <style> element in header and add CSS RULES there. But in this way css does not get apply on document(page).

Can't we do such way like=> Rather than creating style element and appending css rules there. Create "link" tag and append it to web document with 'src' as defined in "StyleUrls".

**Comment by wardbell** [comment]
This suggestion is more appropriate on the `angular/angular` repo. THIS repo is for documentation issues.
