### ISSUE TITLE
Ability for users to find Angular Google Drive Folder

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular.io#7]
I constantly hear from people that they can't find our google drive folder with all the design docs, notes and presentations.

This is why we recently added the eye-stabbing yellow button to https://angularjs.org.

Can a link to the same folder be added to some highly visible place?

The url is: http://goo.gl/sj0Nk1

**Comment by alexwolfe** [comment]
Can you provide some context and background on who usually asks, how often, and the purpose of these docs. Will make it easier to design a solution for this. Thanks!

**Comment by alexwolfe** [comment]
Updated the title to simply describe the issue.

**Comment by alexwolfe** [comment]
You can now find a link to the Design Docs & Notes in the footer of every page and the Resources section in the Docs. 

- https://angular.io/
- https://angular.io/docs/js/latest/resources.html
- https://angular.io/docs/dart/latest/resources.html

Closing for now, we can reopen later if we hear issues with users finding it on the .io site.
