### ISSUE TITLE
ElementRef in Angular@2.0.0-beta.0 and Angular@ElementRef 2.0.0-beta.1

### ISSUE THREAD

**Issue by khoanguyenlio** [angular/angular.io#718]
I tried to update angular2.0.0-beta0 to angular 2.0.0-beta 1 and I got a problem when use elementRef. In Beta0, everything perfect!

`constructor(dcl: DynamicComponentLoader, private elementRef: ElementRef, private renderer: Renderer, ds: SaleDataService, private ticketDataSelection: TicketDataSelection, private z: NgZone) {}`

`load() {
      if (this.selectedTicketTab == 0) {
        this.dynamicComponentLoader.loadIntoLocation(childComponet,
                  this.elementRef, "childComponents")
          .then((r) => {
            this.instances.push(r);
            this.isPayment = r.instance.payment;
          });`

but when update beta1. I debug inside, too many thing changed :(. And i got this error: 
`ORIGINAL EXCEPTION: There is no component directive at element [object Object]`

**Comment by zoechi** [comment]
See also angular/angular#6543
