### ISSUE TITLE
Add "Code Copy" button in 5mins quick-start tutorial.

### ISSUE THREAD

**Issue by afirdousi** [angular/angular.io#720]
It will be great if we can add "copy" button on top of all code samples like package.json, tsconfig.json and other .ts code snippets. This will be very handy and will help the "5 mins quick-start" be a "5 min" quick start tutorial. 

The most naive of implementations could be :

 var holdtext = $("#id-of-the-code-area-comes-here").innerText;
  Copied = holdtext.createTextRange();
  Copied.execCommand("Copy");

May be wrap this in an Angular utility.

**Comment by wardbell** [comment]
I like it.

**Comment by petebacondarwin** [comment]
Me too. I think github has a good solution for this

**Comment by petebacondarwin** [comment]
This is what Github uses: https://github.com/zeroclipboard/zeroclipboard

**Comment by petebacondarwin** [comment]
But that requires a hidden flash element. Not sure why the would use this over @afirdousi's suggestion... Perhaps browser compatibility? But we have significantly lower requirements in that regard

**Comment by wardbell** [comment]
The flash approach is overwrought IMO but, as you say, maybe we're missing something. Either way, it seems best to throw into an A1 directive for angular.io site-wide use and plug it into our code panel generation. Does that make it _your_ department?

**Comment by petebacondarwin** [comment]
Oh alright then!

**Comment by filipesilva** [comment]
The flash thing was for legacy reasons. Nowadays most browsers have `execCommand('Copy')` - except safari it seems. 

[Stackoverflow link](http://stackoverflow.com/questions/22581345/click-button-copy-to-clipboard-using-jquery)

**Comment by wardbell** [comment]
@filipesilva  That's a very thorough explanation and I like the solution. c/@petebacondarwin

**Comment by petebacondarwin** [comment]
From the SO answer there is https://zenorocha.github.io/clipboard.js/

**Comment by filipesilva** [comment]
It seems like a good choice, yes. It also offers a [fallback recommendation](http://zenorocha.github.io/clipboard.js/#browser-support) for safari so it seems like every angle is covered.

**Comment by afirdousi** [comment]
Yes @filipesilva  is right. The solution i recommended

var holdtext = $("#id-of-the-code-area-comes-here").innerText;
Copied = holdtext.createTextRange();
Copied.execCommand("Copy");

may have issues in Safari. So clipboard.js is a good solution :+1:

**Comment by petebacondarwin** [comment]
OK. I will knock up a directive using this tool. It is even under MIT license woohoo!

**Comment by wardbell** [comment]
Closed by merge of Pete's excellent solution #728

**Comment by afirdousi** [comment]
Works like a charm @petebacondarwin  ! :+1:
