### ISSUE TITLE
API docs: code truncated on the right

### ISSUE THREAD

**Issue by wardbell** [angular/angular.io#726]
Here's an example in chrome browser from the [Component Instruction](https://angular.io/docs/ts/latest/api/router/ComponentInstruction-class.html) API page.

![image](https://cloud.githubusercontent.com/assets/129061/12434669/13e5a8dc-bebd-11e5-8b1e-42e4f3d360af.png)

Resizing the browser window or font size does not help.

**Comment by afirdousi** [comment]
Seems like a problem in all browsers.

.prettyprint {
white-space: normal;
}

should fix it. Will work on resize too.

**Comment by afirdousi** [comment]
@wardbell do you know which gulp task generates css out of the scss? i tried gulp build-and-serve but that didn't seem to work.

**Comment by wardbell** [comment]
I do not know. Maybe @petebacondarwin does

**Comment by petebacondarwin** [comment]
The harp server generates the css on the fly.
You can get the output if you run `harp compile`

**Comment by petebacondarwin** [comment]
@afirdousi actually what we need is `white-space: pre-wrap`. This ensures that the whitespace is not collapsed, which would be disastrous for the code formatting. See the summary table in https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by afirdousi** [comment]
Makes sense in our scenario @petebacondarwin .

Thanks a bunch for guiding me to harp compile
