### ISSUE TITLE
Tutorial documentation: CSP and different app location

### ISSUE THREAD

**Issue by BernhardPosselt** [angular/angular.io#732]
Hi,

I've tried to work through the tutorial today and ran into two difficult issues that took me a long time to figure out. I've got a bit of a special setup:

* I've got a strict CSP policy so SystemJS did not work in the beginning, also script tags can not contain any JavaScript
* My JavaScript folder is in a different place than usual (relative path: '../../../apps/components/js')

I've read through the SystemJS docs (I'm unfamiliar with that tool) and did not really figure out how to solve it. The Gitter chat finally gave me some hints and I managed to get it running.

The CSP issue was solved by using **system-csp-production.js** instead of **system.src.js**. Any reason that this is not the default configuration? Could this be added as a hint if the default system.src.js should remain?

I've managed to solve the second issue by using the following config.js:
```js
System.config({
    packages: {
        app: {
            format: 'register',
            defaultExtension: 'js'
        }
    },
    map: {
        app: '../../../apps/components/js/app'
    }
});

System.import('app/boot')
    .then(null, console.error.bind(console));
```

This was also tricky since setting **baseURL** seemed to overwrite the AngularJS configs.

I've already given up once in the earlier alpha because of these issues, so I think it should be added to the tutorial. What do you think? I could also prepare a PR if needed, however I need some opinions first :)

**Comment by wardbell** [comment]
The SystemJS site describes the **system-csp-production.js** as ".. a separate build for production only."

The doc samples and tutorial are most definitely *not guidance for production builds*. They are intended for learning Angular 2 features and techniques.

It would be inappropriate for us to even hint that these **demos** are suitable for a secure, production environment. 

We'd love to have guidance for production builds. I don't know where to find reliable sources for such guidance at this time. So much about the environment (I'm not talking about Angular) is in flux.

Maybe you can contribute a blog post or comparable advice on StackOverflow?

While I appreciate this suggestion and the need, I'm confident that we won't be putting this kind of advice in the tutorials.

All the best.

**Comment by BernhardPosselt** [comment]
Probably also a good idea to improve the SystemJS documentation, I will ask around in their repository :)
