### ISSUE TITLE
Tutorial Routing & Navigation link to "live example" is broken

### ISSUE THREAD

**Issue by bjorneven** [angular/angular.io#742]
The Live Example-link in the section [Wrap up](https://angular.io/docs/ts/latest/guide/router.html#!#final-app) is broken. 

It directs the browser to https://angular.io/docs/ts/latest/resources/live-examples/router/ts/plnkr.html 
I suppose the correct URL should be https://angular.io/resources/live-examples/router/ts/plnkr.html

**Comment by filipesilva** [comment]
Right you are! I'll open PR with a fix.
