### ISSUE TITLE
Copy paste button appears on aside blocks

### ISSUE THREAD

**Issue by filipesilva** [angular/angular.io#744]
I believe this is unintended, as aside blocks aren't for code.

Example: https://angular.io/docs/ts/latest/api/router/CanActivate-decorator.html

![image](https://cloud.githubusercontent.com/assets/4172079/12531761/e280dfc8-c1fa-11e5-832e-bc94313cc42d.png)

/cc @petebacondarwin

**Comment by petebacondarwin** [comment]
Oh no!

**Comment by petebacondarwin** [comment]
Actually the problem is that the copy button is for the code to the left of the aside block but the aside block is floating over the code block and covering up its right hand side. We need a bit of CSS magic here to get the code block to take the correct length.

**Comment by filipesilva** [comment]
Ah you're right!

**Comment by petebacondarwin** [comment]
We need someone with sersious CSS-foo to battle with this - my initial hacking led to naught.

**Comment by filipesilva** [comment]
Got it! Seems like the copy button is overflowing. Added `overflow:auto` to the containing element and it seems to fix it. I am unsure if this affect anything else though.

![image](https://cloud.githubusercontent.com/assets/4172079/12533735/05a6925e-c232-11e5-8e48-e1369f02ca4a.png)

**Comment by petebacondarwin** [comment]
That works for me! Although, it does mean that the icon looks slightly too high in that specific case. But that is much better than it was. Let's land that change.

**Comment by wardbell** [comment]
Also dealt with the change in positioning.
