### ISSUE TITLE
getHeroesSlowly() example requires new Import line

### ISSUE THREAD

**Issue by ederkley** [angular/angular.io#764]
If implementing the *getHeroesSlowly()* function on the following page: 
[https://angular.io/docs/ts/latest/tutorial/toh-pt4.html]
Note that the **hero.service.ts** file needs the following line added to the Imports:
`import {Hero} from './hero';`
Otherwise, the  `return new Promise<Hero[]>...` code doesn't recognise *Hero* as a valid type.
This is fairly obvious and seems to be assumed during the tutorial as it appears in the final code example at the bottom of the page but is not explicitly mentioned.

**Comment by wardbell** [comment]
It is semi-obvious and this is an optional appendix. Added a phrase to the appendix reminding about the import. See PR #792
