### ISSUE TITLE
copy-button directive overlaps nav

### ISSUE THREAD

**Issue by Kevin-K** [angular/angular.io#768]
![image](https://cloud.githubusercontent.com/assets/7290455/12645782/3ec25396-c59a-11e5-8e13-af100ca06e15.png)

![image](https://cloud.githubusercontent.com/assets/7290455/12645892/001f582c-c59b-11e5-8149-ece4c4437273.png)

The z-index on the copy-button directive (`z-index: 1000`) causes overlap onto the nav bar when scrolling (`z-index: 5`).

**Comment by wardbell** [comment]
closed by #769
