### ISSUE TITLE
quickstart repo does not have app.ts at root

### ISSUE THREAD

**Issue by jcoyne** [angular/angular.io#78]
Despite the fact it's defined in tsconfig.json:
https://github.com/angular/ts-quickstart/blob/master/tsconfig.json#L17

Thus when you start the compiler you get:
```
$ tsc -w
error TS6053: File 'app.ts' not found.
message TS6042: Compilation complete. Watching for file changes.
```

Should app.ts be moved out of `complete/` and down to the root?

I would have reported this on the ts-quickstart repo, but issues are not enabled there.

**Comment by rkirov** [comment]
https://github.com/angular/angular.io/commit/1f3940977cf58eb9374a0043f2e34f56ee234740 reworded the quickstart to tell the user to generate `app.ts` before starting `tsc`.
