### ISSUE TITLE
Typescript Jasmine Testing main.js reference incorrect

### ISSUE THREAD

**Issue by NicholasMurray** [angular/angular.io#793]
The references to

<script src="../node_modules/jasmine-core/lib/jasmine-core/main.js"></script>

are incorrect and should instead be

<script src="../node_modules/jasmine-core/lib/jasmine-core/boot.js"></script>

**Comment by NicholasMurray** [comment]
Added pull request #794 to fix issue

**Comment by wardbell** [comment]
Sorry  but this is wrong. We changed our recommendation for this filename from 'boot' to 'main'.
Your change would reverse that.
