### ISSUE TITLE
Weird page width constraint on mobile

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular.io#801]
The mobile style constraints the width in a weird way on iPhone 6S.

![image](https://cloud.githubusercontent.com/assets/216296/12773741/6db27070-c9f3-11e5-9a7b-2f97a2b9562a.png)

**Comment by IgorMinar** [comment]
It should have used the full width of the screen.

**Comment by wardbell** [comment]
Not a problem on a Windows Phone. ;-)

**Comment by wardbell** [comment]
Closed by #985
