### ISSUE TITLE
misleading link in quickstart (javascript version)

### ISSUE THREAD

**Issue by paolochiodi** [angular/angular.io#803]
At the end of the quickstart guide there's a link to the tutorial named "Join us on the Tour of Heroes Tutorial!" that links to the tutorial url but shows the docs home.
Overall, the tutorial is not available in the javascript versions.

I think this is misleading, especially for newcomers: would be helpful to have a message explaining that the tutorial is only available in the typescript or, at least, remove the link from the quickstart.

(cross posted from https://github.com/angular/angular/issues/6862#issuecomment-179209338)

**Comment by wardbell** [comment]
Fair point. The JS language track is woeful at the moment. We have it high on our backlog. Leaving open until we get there.

**Comment by wardbell** [comment]
We now have that cross linking.
