### ISSUE TITLE
the dart DEVELOPERS GUIDE need update

### ISSUE THREAD

**Issue by Matrix-Zhang** [angular/angular.io#814]
I'm a fresh man with both dart and angularjs, 

i just follow the develop guide to learn...

but when i do the exercise with displaying data (https://angular.io/docs/dart/latest/guide/displaying-data.html)

the same code doesn't work, i google the solution for a lot of time...

finaly, i find the answer at https://github.com/angular/angular/blob/master/modules/angular2/docs/migration/kebab-case.md

**Comment by kwalrath** [comment]
The fix for this is in PR #666, which has been languishing, waiting for review. I'll try harder to get a reviewer.

**Comment by kwalrath** [comment]
The changes are in and will be released the next time the site is published (within a few days). Thanks very much for your bug report, and please continue to file more bugs when you encounter doc problems!
