### ISSUE TITLE
A new generation of debugger tool for SPA frameworks

### ISSUE THREAD

**Issue by systemaker** [angular/angular.io#815]
Hello,
For me the poor level of javascript debuggers today is Really a BIG Issue :D  for frontend apps
so i think that it's time for SPA frameworks to develop some better debuggers and it would be great if this new angular version come also with a JavaScript debugger addon or toolset as visualy easy as theseus for brackets.

Please don't give me shitty pro arguments about Google developer tools or batarang or nginspect , etc .. thanks :D

**Comment by wardbell** [comment]
Closing this as issues here should be confined to documentation issues.
