### ISSUE TITLE
Add info about the transformer

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#825]
Once https://github.com/angular/angular/issues/6956 is fixed, we should link to https://github.com/angular/angular/wiki/Angular-2-Dart-Transformer from any Dart docs on angular.io that discuss transformer arguments in pubspec.yaml. We might even want to create a page on angular.io about just the transformer.

**Comment by kwalrath** [comment]
Also... be sure to explain COMMON_DIRECTIVES, CORE_DIRECTIVES, FORM_DIRECTIVES, etc.

**Comment by chalin** [comment]
Wiki page has a new home: https://github.com/dart-lang/angular2/wiki/Transformer

**Comment by chalin** [comment]
This issue was moved to dart-lang/site-webdev#258
