### ISSUE TITLE
Docs sidebar doesn't show submenus in mobile devices

### ISSUE THREAD

**Issue by luisvt** [angular/angular.io#828]
When you open sidebar on https://angular.io/docs in a mobile device submenus are not showed making impossible to navigate to sub topics

![screen shot 2016-02-10 at 1 04 58 pm](https://cloud.githubusercontent.com/assets/1688987/12956760/8d7291a6-cff7-11e5-9cb6-96ebbef65595.png)

**Comment by wardbell** [comment]
Fixed it. Please try again.
