### ISSUE TITLE
Bio modal only works for the first row of images

### ISSUE THREAD

**Issue by un33k** [angular/angular.io#83]
When you look at the bios, the first row works well if you click on any images.
Then if you scroll down to the second row, you only see half of the modal. 
On the third row, you only see the very bottom of the modal.
On the forth row, the modal is totally gone.

I think you may need to line the modal to the top of the page and not the top of the sliding page.
The position of the modal is 'relative' I think.

https://angular.io/about/

**Comment by un33k** [comment]
Works in latest Chrome, but not in IE / Firefox.

**Comment by un33k** [comment]
![modal-not-working](https://cloud.githubusercontent.com/assets/407537/7503516/83ed0a0c-f411-11e4-9155-b51229050eb5.png)

**Comment by alexwolfe** [comment]
I think this might be a problem with the dialog directive in Angular Material https://material.angularjs.org/#/demo/material.components.dialog

Can you confirm and open the ticket there if that's the case? Thanks!

**Comment by naomiblack** [comment]
fixed a long while ago...
