### ISSUE TITLE
Hero example & plunker incorrectly suggest that a http json response is retrieved by res.json().data 

### ISSUE THREAD

**Issue by elinberg** [angular/angular.io#830]
**When retrieving an HTTP Response to return json data. The documentation suggests that the data is retirieved via res.json().data.**
 The correct, or working syntax is just **res.json()** . The .data property does not exist. This is very disconcerting because there is really not an easy way to troubleshoot this. In short it really ate my lunch and I'd like to save others the time and the anguish. The discrepancy can be view on the following documentation page: 

[HTTP Client fetch-data example](https://angular.io/docs/ts/latest/guide/server-communication.html#!#fetch-data)

**Comment by keke8273** [comment]
scratched my head for two hours for the exactly same problem. Figured it out eventually, then I saw this post.

**Comment by wardbell** [comment]
I'm replying as an individual, not as a representative of Google (which I am not). What I am about to say is not pleasant. It is merely true.

Your hours of head scratching may have lead you to three important life lessons:

1. Read the documentation
1. Make no assumptions
1. Learn the target web api

We did our part. We warned you about the shape of the returned web api result on at least two occasions. For example:

>We must also know the shape of the data returned by the server API. We shouldn't expect json() to return the heroes array directly. ***The server we're calling always wraps JSON results in an object with a data property*** [emphasis mine]. We have to unwrap it to get the heroes. This is conventional web api behavior, driven by security concerns.

We never said that every http json response is retrieved by `res.json().data`.   That would be foolish. ***No one*** can tell you how to interpret *every* http response.

We said that `res.json().data` is the way to extract the data from *this particular server response*.

You are free to complain that *your* api doesn't do this and that *you* think this is a bad design. To which I reply without hesitation "get over it."  We are rarely lucky enough to face the web api we prefer. It is usually someone else's design, someone with a different notion of what is "right".  The wise developer adapts.

There was no error in this example.  The `data` property does exist ... for this sample's web api. It exists for reasons clearly stated in the documentation and, in fact, matches the behavior of many existing web apis.

In the real world there is, in fact, an *easy way to troubleshoot this* (aside from reading the documentation):   send a request to the server and look at what it returns on the network tab of the developer tools. 

In this sample, which intercepts HTTP requests with an in-memory server, the shape of the result is clearly [stated in the documentation](https://angular.io/docs/ts/latest/guide/server-communication.html#!#appendix-tour-of-heroes-in-memory-server). You could breakpoint that service if you liked.

At one level I am sorry for your pains. But at another level ... not so much.

**Comment by elinberg** [comment]
Is this your life's work. Bitching about people's experience? There are others that had the same problem I did. I thought I might save another developer the anguish by posting an issue and it is an issue. Can't you just be helpful without being an asshole or is that just your nature. Get over it!

Sent from Outlook Mobile




On Sun, Feb 14, 2016 at 4:14 PM -0800, "Ward Bell" <notifications@github.com> wrote:












I'm replying as an individual, not as a representative of Google (which I am not). What I am about to say is not pleasant. It is merely true.



Your hours of head scratching may have lead you to three important life lessons:


Read the documentation
Make no assumptions
Learn the target web api




We did our part. We warned you about the shape of the returned web api result on at least two occasions. For example:




We must also know the shape of the data returned by the server API. We shouldn't expect json() to return the heroes array directly. The server we're calling always wraps JSON results in an object with a data property [emphasis mine]. We have to unwrap it to get the heroes. This is conventional web api behavior, driven by security concerns.




We never said that every http json response is retrieved by res.json().data.   That would be foolish. No one can tell you how to interpret every http response.



We said that res.json().data is the way to extract the data from this particular server response.



You are free to complain that your api doesn't do this and that you think this is a bad design. To which I reply without hesitation "get over it."  We are rarely lucky enough to face the web api we prefer. It is usually someone else's design, someone with a different notion of what is "right".  The wise developer adapts.



There was no error in this example.  The data property does exist ... for this sample's web api. It exists for reasons clearly stated in the documentation and, in fact, matches the behavior of many existing web apis.



In the real world there is, in fact, an easy way to troubleshoot this (aside from reading the documentation):   send a request to the server and look at what it returns on the network tab of the developer tools. 



In this sample, which intercepts HTTP requests with an in-memory server, the shape of the result is clearly stated in the documentation. You could breakpoint that service if you liked.



At one level I am sorry for your pains. But at another level ... not so much.

**Comment by wardbell** [comment]
Language please. Not nice!  

I tried to give a substantive response.  I do regret the brief moment when my reply said "Get over it"; I changed it to "You missed the point" but obviously not before you caught me with my guard down.

FWIW, I drew sharper attention to the importance of knowing the API and the possibility that your web API might not send back an object with a `data` property.

Closed by 99caf75
