### ISSUE TITLE
package.json Typescript quickstart

### ISSUE THREAD

**Issue by mptrs** [angular/angular.io#835]
The package.json has a dependency on angular2": "2.0.0-beta.3. But beta.3 does not have the browser.d.ts that is needed in the main.ts for reference.

When using beta6 it does work.

`///<reference path="..\node_modules\angular2\typings\browser.d.ts"/>`

**Comment by wardbell** [comment]
This version of the QS is about to be entirely replaced ... and the problem you've identified will be swept away. Talking a day or two. Closing.
