### ISSUE TITLE
 ionic.bundle.js:1 Uncaught SyntaxError: Unexpected token < app.js:4 Uncaught ReferenceError: angular is not defined(anonymous function) @ app.js:4 controllers.js:4 Uncaught ReferenceError: angular is not defined

### ISSUE THREAD

**Issue by Hulk-Tron** [angular/angular.io#840]
I am keep getting this error on chrome and firefox when i start the node.js server but when i close that server firefox display views right but chrome still giving the same error kindly help me 
my app.js file is 
var UserModel_1 = require("./DBRepo/UserModel");
var GeneralRoutes = require("./routes/general");
var express = require("express");
var path = require("path");

var bodyParser = require("body-parser");
var mongoose = require("mongoose");
var app = express();

app.set("port", 8080);
app.use(express.static(path.join(__dirname, './public')));
var staticDIR = path.resolve(__dirname, "./public");
app.use(express.static(staticDIR));
app.use(bodyParser.json());
app.use(function (req, res, next) {
  //next();
  if (req.query.token) {
    UserModel_1.findUser({ FirebaseToken: req.query.token })
        .then(function (dbUser) {
          if (dbUser) {
            req.user = dbUser;
            next();
          }
        }, function (err) {
          next(err);
        });
  }
  else {
    next();
  }
});
app.use("/api", GeneralRoutes);
app.get("*", function (req, res) {
  var indexViewPath = path.resolve(__dirname, "./public/index.html");
  res.sendFile(indexViewPath);
});
app.listen(app.get("port"), function () {
  console.log("Server in listening state on " + app.get("port"));
});
mongoose.connect("mongodb://localhost/data");
module.exports = app;

**Comment by Hulk-Tron** [comment]
kindly help me

**Comment by filipesilva** [comment]
Hi @Hulk-Tron! 

This question might be better suited for the [ionic repo](https://github.com/driftyco/ionic/issues/), since it it's very configuration dependent. Have you tried asking there?

**Comment by Hulk-Tron** [comment]
No brother ! i havent ask there i think this is node server issue but i cant figure it out

**Comment by filipesilva** [comment]
I'd say it is not a node server issue but rather a dependency issue in `index.html`. Likely a missing script tag for angular.

But were it to be a node issue, dependency issue, angular issue or ionic issue, this repo is dedicated only to the documentations present in www.angular.io. That is why my recommendation is that you try one of the other repos - this one will not do.

**Comment by wardbell** [comment]
Closing because not relevant to angular docs
