### ISSUE TITLE
ngModel not support in radio button yet?

### ISSUE THREAD

**Issue by Matrix-Zhang** [angular/angular.io#854]
`<tr>
   <th>Valve Control:</th>
   <td>
     <input ngControl='valve' [(ngModel)]='device.newValveStatus' type='radio' name='new_valve_status' value='on'/>On<br/>
    <input ngControl='valve' [(ngModel)]='device.newValveStatus' type='radio' name='new_valve_status' value='off'/>Off
  </td>
</tr>`

the device.newValveStatus is 'on', but the radio buttons no one checked....

by the way, i' m use dart

**Comment by zoechi** [comment]
This repository is for documentation.
Have you checked https://github.com/angular/angular/search?q=radio&state=open&type=Issues&utf8=%E2%9C%93

GitHub issues are for bug reports and feature requests. 
      For support questions please use other channels like [StackOverflow](http://stackoverflow.com/questions/tagged/angular2), [Gitter](https://gitter.im/angular/angular), [Google groups](https://groups.google.com/forum/#!forum/angular), ...
