### ISSUE TITLE
Main navbar overflows when width is reduced

### ISSUE THREAD

**Issue by bowdenk7** [angular/angular.io#855]
If I reduce the browser width to half of my 1920x1080 monitor, the main navbar overflows to the next line. This causes the "Events" button to block the docs search on some pages. See below:

![image](https://cloud.githubusercontent.com/assets/820883/13155878/bd20b1ec-d634-11e5-81a0-e280142d973c.png)

**Comment by WonSong** [comment]
The feedback icon starts wrapping at 1014px

![1014px](https://cloud.githubusercontent.com/assets/5981331/13386311/c10414a6-de5f-11e5-975f-b049dc3268f4.png)

The event menu starts wrapping at 962px

![962px](https://cloud.githubusercontent.com/assets/5981331/13386317/cb313936-de5f-11e5-9c17-63268504cbd8.png)

``` sass

/*
* Metrics
*
* Metrics based on material design 8pt unit
*/

$unit: 8px;
$phone-breakpoint: 480px;
$tablet-breakpoint: 800px;
```

There are only 3 break points defined.

``` sass

// main-nav
@media handheld and (max-width: $phone-breakpoint),
screen and (max-device-width: $phone-breakpoint),
screen and (max-width: $tablet-breakpoint) {
  padding: 0px 0px 0px ($unit * 2);
}

```

What's the desired fix?

**Comment by wardbell** [comment]
Would love to see a PR that you recommend to fix the problem

**Comment by ericjim** [comment]
The nav has been changed since, the breakpoint has also been increased in size to prevent this from happening. Will close the issue.
