### ISSUE TITLE
Why are we manually manipulating the DOM instead of using bindings?

### ISSUE THREAD

**Issue by btford** [angular/angular.io#87]
Here, for instance: https://github.com/angular/angular.io/blob/master/public/resources/js/site.js#L75-L117

This code is really hard to understand. Taking better advantage of Angular's data binding would help a lot, and would let us easily drop the jQuery dependency.

**Comment by alexwolfe** [comment]
My new branch gets rid of all of this.

**Comment by alexwolfe** [comment]
I'm closing this for now, the branch I shared should get rid of everything and remove all jquery dependancies. I'll tag you on the review for that branch.
