### ISSUE TITLE
Angular 2 routing doesn't work in firefox in case of special character %2F

### ISSUE THREAD

**Issue by Somiks** [angular/angular.io#870]
My link https://domain1.lv/static/loan/#/credit-details/HEAD-RLC-161%2F2013 doesn't work in firefox (after refreshing component isn't running). In chrome it works fine. Without %2F refreshing works properly.

**Comment by zoechi** [comment]
Angular.io is actually about Angular2 documentation issues. Please report Angular2 issues in https://github.com/angular/angular/issues (without `.io`)
