### ISSUE TITLE
Tutorial docs need a typings reference for es6 Promises

### ISSUE THREAD

**Issue by aciccarello** [angular/angular.io#876]
Migrated from @brazenest's issue angular/angular#7231

The "Tour of Heroes" tutorial code uses the `tsconfig.json` from Quickstart, which targets ES5, but beginning at Part 4 it makes use of the Promises feature which was introduced in ES6 (aka ES2015). TypeScript compilers fail at this stage because the tutorial's code currently does not reference a typings file for the Promises feature.

As specified in the "Breaking Changes" section of the beta6 changelog, the top section of the `main.ts` file in Part 4 of the tutorial should begin with:

```JavaScript
import {bootstrap}    from 'angular2/platform/browser';
///<reference path="node_modules/angular2/typings/browser.d.ts"/>
import {AppComponent} from './app.component';
```

**Comment by alexeagle** [comment]
@wardbell changed the quickstart section to include the `es6-shim` typing in the original app, so using Promise later would type-check. I'll let Ward confirm if that's the solution here.

**Comment by wardbell** [comment]
@aciccarello - Thanks but we do NOT recommend adding that `///<reference` line. We have expanded the QuickStart instructions to include typings.  The matching Tour of Heroes reflects this (see the plunkers).

@alexeagle Have already updated QuickStart for this stuff and published.  

I'm assuming we should close this issue as it has been addressed.
