### ISSUE TITLE
Help point people to file docs issues in angular.io repo

### ISSUE THREAD

**Issue by aciccarello** [angular/angular.io#877]
I've noticed several questions in the angular/angular repo about docs issues that should be filed here. What ways could the docs help point people to this repo when they have a docs related question? Maybe the docs repo should be mentioned on the [contributing](https://angular.io/contribute.html) and [support](https://angular.io/support.html) pages?

I think the difficulty is helping people know what docs issues need to be filed here. Issues like angular/angular/issues/7206 belong here because it is about a tutorial. But if there is a problem with documentation in the source code I assume that should be filed in the main repo.

**Comment by wardbell** [comment]
Excellent idea. I filed as [issue #7502](https://github.com/angular/angular/issues/7502) over there.

I also updated the README.md in this repo to clarify these points.
