### ISSUE TITLE
router guide: add missing ES5 code

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#88]
Search for the following string, and replace it with code.

```
//TODO Need Angular2 Example here for ES5
```

I count at least 7 occurrences where there really is no ES5 code:

* "Then you can add the router into your app by importing the Router module in your app.js file:"
* "So how do we configure the app? Let's open app.js and find out. Add this to the file:"
* "Let's make a controller:"
* "And add the controller's module as a dependency to our main module in app.js:"
* "In app.js:"
* "In detail.js, we implement a controller that uses the id route parameter:"
* "For example, as specified below, when a user navigates to `/`, the URL changes to `/user` and the outlet at that level loads the `user` component."

Some additional occurrences appear to be cases where there is an ES5 example above, so the code exists but needs to be presented correctly.

**Comment by rkirov** [comment]
https://github.com/angular/angular.io/commit/5333d2d87c0233708f9aabcc4aa34137c9fd4313 handles the first part of the missing examples.

**Comment by kwalrath** [comment]
I still see one missing ES5 example, just after "Or, we can define an alias myUser like this:".

**Comment by wardbell** [comment]
Obsolete issue.
