### ISSUE TITLE
router guide: add missing TS code

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#89]
Look for the following and replace it with TypeScript code:

```
//TODO Need Angular2 Example here for TypeScript
```

I think there's just 1 occurrence, and it should be deleted.

**Comment by kwalrath** [comment]
Updated the initial comment to reflect the current state of the page.

**Comment by alexwolfe** [comment]
@kwalrath can you assign this task to whoever you think should fix it. Thanks!

**Comment by kwalrath** [comment]
I don't see any missing TS code any more.
