### ISSUE TITLE
router guide: fix formatting

### ISSUE THREAD

**Issue by kwalrath** [angular/angular.io#90]
Sometimes \` characters are visible in the output (they should be `<code>...</code>`). An example: "You can use \`redirectTo\` ..."

Under "Sibling Outlets", the HTML code is visible (on a white background) at the bottom of the code box, whether the ES or HTML tab is selected.

Also, there are places where adjacent code snippets should be combined into a single tabbed view.

Under Sibling Outlets, there's an ES5/HTML example followed immediately (no text) by a ES5/TS example. Besides that problem, the template part of the TS example is blank (unescaped HTML?).

**Comment by kwalrath** [comment]
I've updated the initial comment to reflect the current state of the page.

**Comment by wardbell** [comment]
Obsolete issue.
