### ISSUE TITLE
Document when `()` and `[]` are necessary in hostbindings

### ISSUE THREAD

**Issue by zoechi** [angular/angular.io#904]
There seem to be different requirements when `()` is required for events and `[]` for attributes, styles, and class bindings in  `host: { '...': '...'}` or `@HostBinding('...')`.   
Sometimes `()`/`[]` seem necessary,  sometimes they don't work when they are added.  
Not sure if there are also differences between Dart and TS.

**Comment by wardbell** [comment]
Hmm.  The API docs are conflicting on this.

Here is an example in [metadata.ts](https://github.com/angular/angular/blob/4bfe49cd422ac3bc72f73a5e8f89bcc474472dfe/modules/angular2/src/core/metadata.ts#L1305)
```
class NgModelStatus {
   constructor(public control:NgModel) {}
   @HostBinding('[class.valid]') get valid { return this.control.valid; }
   @HostBinding('[class.invalid]') get invalid { return this.control.invalid; }
}
```

Here is a conflicting one in [directives.ts](https://github.com/angular/angular/blob/4bfe49cd422ac3bc72f73a5e8f89bcc474472dfe/modules/angular2/src/core/metadata.ts#L1305)

```
class NgModelStatus {
    constructor(public control:NgModel) {}
    @HostBinding('class.valid') get valid { return this.control.valid; }
    @HostBinding('class.invalid') get invalid { return this.control.invalid; }
}
```

Which is it?  Asking @vicb and @tbosch

**Comment by tbosch** [comment]
The version without `[` is the right one.
I.e. in `host: ...` we require `(` and `[` to differentiate between fixed attributes, property bindings and event bindings. But in `@HostBinding` / `@HostListener` we already know that it is a property bindings / event binding so we don't need `[` / `(`

**Comment by wardbell** [comment]
Moved (and referenced) to [angular/angular issue #7500](https://github.com/angular/angular/issues/7500)
