### ISSUE TITLE
The EventEmitter docs should mention how to pass arguments

### ISSUE THREAD

**Issue by kaeku** [angular/angular.io#907]
First of all, I'm not sure if there's any possibility of creating a pull request on the API part of the docs. If there's any possibility to do so, I'd be more than happy to place a pull request on the EventEmitter docs. However, I couldn't find any files in the repo.

The EventEmitter docs (https://angular.io/docs/ts/latest/api/core/EventEmitter-class.html) tell the user about the basic concepts of using EventEmitter's, but fail to mention that you have to put `$event` as the function call's argument. After all that's the logical solution. I feel like users don't like to think while -reading docs, though. :)

### Picking up on the example from the official docs:

-  `this.open.emit(null);` should probably be `this.open.emit('some argument');`

- Also, I feel like there should be some mention of how the `@Output` is 'picked up'. 
 - For example, a parent component containing `(open)="openZippy($event)"` or any mention close to this would greatly improve the clarity of this doc.

**Comment by wardbell** [comment]
Some guidance on `EventEmitter` is on the documentation backlog. Hang in there.

**Comment by jeffbcross** [comment]
@kaeku the API reference is all contained in source code on github.com/angular/angular. Your particular suggestion would be added to [this file](https://github.com/angular/angular/blob/master/modules/angular2/src/facade/async.ts).

**Comment by kaeku** [comment]
Meanwhile found that as well and should probably have linked my new pull request here. My bad 🤓

Pull request can be found here: https://github.com/angular/angular/pull/7382

Thanks tho @jeffbcross :)

**Comment by wardbell** [comment]
Closing this issue based on the above.
