### ISSUE TITLE
Minor formatting issue on mobile devices in "Step By Step Guide"

### ISSUE THREAD

**Issue by PzYon** [angular/angular.io#92]
When browsing to /docs/js/latest/guide/ on a mobile device, there is too much padding/margin on the left hand side on the ul/li.

**Comment by PzYon** [comment]
It's nothing big, but I wanted to try to fix it myself. However I had problems when following the installation guide for developers. Everything is up and running, not all jade-files seem to "compile" correctly. E.g. I can see "= current.path[1]" below the header bar (coming from public\_includes\_head-include.jade).

**Comment by sgimeno** [comment]
I'm having the same issue,  `current.path` is not being resolved. It could be an issue with Harp v0.17.0? I'm using  v0.16.0 and the page renders fine.

**Comment by kwalrath** [comment]
If it's a Harp issue, it should be solved soon by #96.

**Comment by PzYon** [comment]
Great. I can confirm that it works with version 0.16.0. Thanks for your tip.

**Comment by alexwolfe** [comment]
Fixed
