### ISSUE TITLE
Angular2 site/ API Preview link  is not working

### ISSUE THREAD

**Issue by micronyks** [angular/angular.io#927]
right now, 

I have been trying to access different APIs through API Preview link.When I try to click the link `API Preview` https://angular.io/docs/ts/latest/api.html, it says,

```
404

Whoops. Looks like what you're looking for can't be found.
```

There was/is no prior intimation on site.

I don't know where to submit or intimate about this issue. If its not suitable place let me know. I'll delete it from here.

**Comment by wardbell** [comment]
closed by #932
