### ISSUE TITLE
Menu Navigation 404 not found error

### ISSUE THREAD

**Issue by kuntal-b** [angular/angular.io#928]
Issue described bellow link

https://github.com/angular/angular/issues/7486

**Comment by zoechi** [comment]
dup of #927

**Comment by skeep** [comment]
problem is the link to going to `https://angular.io/docs/ts/latest/api.html` where as it's expected to go to `https://angular.io/docs/ts/latest/api/` or `https://angular.io/docs/ts/latest/api/index.html`

**Comment by bjwyse** [comment]
Duplicate of https://github.com/angular/angular.io/issues/927. Please close.

**Comment by wardbell** [comment]
closed as dup
