### ISSUE TITLE
Provide a way for users to pick a single language pref for code-box styles

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#93]
For the Angular 2 for JS docs, we offer code samples in both TS and ES5. Can we make the toggle sticky and persistent across the site so that a developer can select ES5 and then see all their code samples in their preferred language?

Related bonus points: should we similarly have conditional body text vars so that we can, for example, refer to the name of the file that the codebox displays (main.ts or main.js) appropriately for the language choice on the page?

**Comment by kevmoo** [comment]
Ideally, hitting the `DOCS` tab the first time, it should just go to https://angular.io/docs/ (at it exists as of this writing, we a link to TS docs, of course).

Then once a "section" is picked it should stay sticky with future clicks on `DOCS`.

Maybe?

**Comment by wardbell** [comment]
Obsolete issue.
