### ISSUE TITLE
Not clear how to use async validators

### ISSUE THREAD

**Issue by dchacke** [angular/angular.io#934]
cc @robwormald 

It seems that asynchronous validators need to be the third parameter passed to the `Control` constructor, but I didn't see this in the documentation. Perhaps this could be made more obvious?

Example:

```typescript
this.formField = new Control('', Validators.required, SomeAsynchronousValidator.method);
```

**Comment by wardbell** [comment]
Where do you recommend making this observation? Pull requests are most welcome!

**Comment by dchacke** [comment]
I don't know where it would make most sense, I think you would know that better. I reported this in the Gitter chatroom and @robwormald asked me to file an issue here.

As far as pull requests go, I have been much more occupied lately making sense of the docs as they are, so perhaps you could implement that ;-)

**Comment by sturdynut** [comment]
@dchacke - Are you struggling with using async validators or are you suggesting the docs for the `Control` class needs additional details on how to create/use async validators?

If it helps, here is a plunker demonstrating using an asynchronous validator.
http://plnkr.co/edit/npJCFKzl3Z2yt4i8VKYk

Cheers.

**Comment by dchacke** [comment]
All I'm saying is that somewhere in the docs it should say something like this:

```javascript
new Control('', SomeSynchronousValidator.method, SomeAsynchronousValidator.method);
```

And if I have multiple synchronous validators and/or multiple asynchronous validators, they need to be joined together:

```javascript
new Control('', Validators.compose([
  FirstSynchronousValidator.method,
  SecondSynchronousValidator.method
]), Validators.composeAsync([
  FirstAsynchronousValidator.method,
  SecondAsynchronousValidator.method
]));
```

I didn't see this in the docs anywhere and had to figure this out by trial and error. Therefore, it may be helpful to add this to the docs.

**Comment by sturdynut** [comment]
I see what you are saying, looking at the docs for `Control` (https://angular.io/docs/js/latest/api/common/index/Control-class.html) it is not clear about how to pass a collection of sync/async validators, which to me is a more realistic use case.

I did dive into the api docs section of the project hoping to make some updates, but I'm not quite sure where I need to update it.  I'm hoping to get a better understanding soon.

**Comment by Foxandxss** [comment]
Control is gone, if you think this issue still exist, please create a new issue 👍
