### ISSUE TITLE
Query:QueryFactory - first given link of plunker shows ngZone demo , not Query Api's demo

### ISSUE THREAD

**Issue by micronyks** [angular/angular.io#957]
check this below link and then first given plunker link ,
https://angular.io/docs/ts/latest/api/core/Query-var.html.

first given plunker link shows `ngZone` demo and not `query api`'s demo. I was trying to learn about `query api` but didn't get help from the first link as it shows `ngZone` demo.

<hr>

Example (live demo)

Assume that <tabs> component would like to get a list its children <pane> components as shown in this example:

```
 <tabs>
      <pane title="Overview">...</pane>
      <pane *ngFor="#o of objects" [title]="o.title">{{o.text}}</pane>
    </tabs>

```

please fix it.

**Comment by wardbell** [comment]
Old. Doesn't show that example anymore
