### ISSUE TITLE
logo on the homepage is squashed in width

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#962]
The main logo image was widened to add the "now in 2.0!" tagline, but the site CSS expects it to be a perfect square (which it was before). We need to fix the CSS so that the logo isn't squashed any more.

Logo is here: https://angular.io/resources/images/logos/angular2/shield-with-beta.png (download and open the file to see the white text for the tagline. In the browser preview it's white-on-white and invisible)
As seen on the homepage of http://angular.io

**Comment by ericjim** [comment]
Perhaps my eye for design isn't as keen as yours @naomiblack , but I am not sure I notice the "squashed width" in the logo. Do you have an screenshot of how it used to look before? Or how you want it to look?

This is currently how it looks live in production. I've included the computed properties from Chrome DevTools, the image asset is already at 100% width within its own container (I've added the width css property to be explicit in the pic, but it's not needed), it seems to me that the asset is already at full width, regardless of the height.
<img width="1440" alt="screen shot 2016-03-29 at 11 58 31 am" src="https://cloud.githubusercontent.com/assets/1329167/14114646/b01c425a-f5a5-11e5-88bf-d56c9714ddae.png">

**Comment by ericjim** [comment]
I believe it is also this https://github.com/angular/angular.io/issues/1177
