### ISSUE TITLE
flicker in drop-down menu for version

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#963]
If you switch between dev guide chapters at https://angular.io/docs/ts/latest/, the language picker flickers as the font size changes from what it was on initial load to the final style used in the page.

![image](https://cloud.githubusercontent.com/assets/2286589/13764973/5b478f08-ea12-11e5-82ca-46008d595bbf.png)

Should hunt this down and fix it.

**Comment by ericjim** [comment]
We are awaiting a merge for https://github.com/angular/angular.io/pull/999 to fix the issue

**Comment by naomiblack** [comment]
@ericjim I merged in a1678e5 but still see the flicker.

**Comment by ericjim** [comment]
@naomiblack with @alexwolfe changes, should we close this issue?

**Comment by naomiblack** [comment]
fixed!
