### ISSUE TITLE
update dgeni templates and site CSS for new API design

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#964]
We worked with a designer to come up with improved styling for the API doc pages. Implementing this has two parts:
- new CSS styles that dgeni can use to apply the new "denser, more structured" look
- work on dgeni templates to output the content as dictated by the new design, using the new CSS styles

The designer we worked with didn't have Angular expertise, so came up with a WIP PR (https://github.com/angular/angular.io/pull/585) where she applied the style changes to the output final pages to show what it should look like. The WIP is just for illustration; the work was done on the generated output files, not the source that is used to create them.

See attached PDF for the full design:

[APIDoc_design-proposal.pdf](https://github.com/angular/angular.io/files/173138/APIDoc_design-proposal.pdf)

**Comment by pcharlebois** [comment]
List of tasks & priorities for API Doc:

Banner
- [ ] Social media buttons
- [ ] Material badges
- [ ] Top menu bar with install button

Main content
- [ ] Layout changes - 2 column grids
- [ ] Tooltip hover
- [ ] Live demo header for code examples (markdown)
- [ ] Styles for class details
* Class details descriptions?

Floating menu

Side-bar
- [ ] Menu link with icon
* Where does the current menu fit into the new design?

**Comment by naomiblack** [comment]
Please note that we do not yet have hooks for the Stable / Draft / Deprecated indicator output by dgeni, and I think we still need to figure out how to make "Improve This Doc" work. @IgorMinar @petebacondarwin.

**Comment by ericjim** [comment]
To accomplish this work the template file located in `tools/api-builder/templates/class.template.html` @amitafr I'll walk you through it.

**Comment by ericjim** [comment]
Additional fields in the documentation are needed to achieve the proposal @naomiblack. Consider the following [Angular 2 directive](https://github.com/angular/angular/blob/master/modules/angular2/src/common/directives/ng_switch.ts). There currently doesn't exist a predictable way of delimiting sections in the doc string. @petebacondarwin has discussed with me the possible intent of adding `@howtouse`, `@whatitdoes`, etc. However, a decision must be made on this @IgorMinar.

**Comment by naomiblack** [comment]
Updating with status for others. I ran this past @mhevery -- `@howtouse` etc sounds fine. We'll start by updating ng-Switch and trying it out.

One concern is that we'll need to update the Dart transformers to correctly output this for the Dart version of the API docs. Could you keep a list of the new annotations that you add so it's easy for me to get them all in one update later?

**Comment by ericjim** [comment]
@naomiblack I've made a list here https://github.com/angular/angular.io/issues/1028, I will be submitting a separate PR which adds support for these tags.

**Comment by ericjim** [comment]
Still a work in progress, but I've managed to get the dgeni+jade templates to work in our favour.
![screenshot 2016-04-07 17 23 50](https://cloud.githubusercontent.com/assets/1329167/14367357/9b2dc854-fce5-11e5-8101-4e77de80c350.png)

**Comment by ericjim** [comment]
Many of the things in the proposal have been implemented. I would say that we are missing the following:

#### Bar for code examples and live demo
<img width="1078" alt="screen shot 2016-04-22 at 2 33 10 pm" src="https://cloud.githubusercontent.com/assets/1329167/14751292/299cee6e-0897-11e6-81ef-28a820d2bd72.png">

#### Tooltips
<img width="112" alt="screen shot 2016-04-22 at 2 33 46 pm" src="https://cloud.githubusercontent.com/assets/1329167/14751309/3ee1c6a0-0897-11e6-8065-3a0c9394cc71.png">

#### Floating Footer in API Doc
<img width="954" alt="screen shot 2016-04-22 at 2 34 11 pm" src="https://cloud.githubusercontent.com/assets/1329167/14751334/564f9f60-0897-11e6-80e8-ddcbb352b52c.png">

**Comment by lazaridis-com** [comment]
@wardbell , you closed #585 due to the pending redesign of angular.io. Maybe this issue here should be closed, too?

**Comment by Foxandxss** [comment]
Indeed
