### ISSUE TITLE
broken links in drop-down language selector for some API docs

### ISSUE THREAD

**Issue by naomiblack** [angular/angular.io#970]
*Problem*
- Look at https://angular.io/docs/ts/latest/api/platform/browser/bootstrap-function.html
- In the language-dropdown, pick "typescript"
- The link that this opens is https://angular.io/docs/ts/latest/api/platform/ which 404s

Why is the drop-down for this function missing the rest of the URL?

**Comment by naomiblack** [comment]
@petebacondarwin @wardbell I'm not sure if this is dgeni or a drop-down issue... could you have a look?

**Comment by petebacondarwin** [comment]
This is a Jade issue, but I will take a look

**Comment by petebacondarwin** [comment]
I fixed it with a kludge that is no better than what is there already :-(
