### ISSUE TITLE
Getting started guide: Angular path returns 404.

### ISSUE THREAD

**Issue by armno** [angular/angular.io#98]
From this guide https://angular.io/docs/js/latest/guide/setup.html, it uses `2.0.0-alpha.21` which is currently missing from https://code.angularjs.org/.
so both https://code.angularjs.org/2.0.0-alpha.21/angular2.dev.js (TypeScript) and https://code.angularjs.org/2.0.0-alpha.21/angular2.sfx.dev.js (ES5) returns 404.

(I'm not sure how code.angularjs.org is populated but at the time of writing this, there are alpha 19, 20, and 22 for Angular 2.)

**Comment by rkirov** [comment]
It has to be updated to 'alpha.22'
