### ISSUE TITLE
Warning regarding beta11 on component interaction

### ISSUE THREAD

**Issue by filipesilva** [angular/angular.io#988]
The [component interaction live example](https://angular.io/resources/live-examples/cb-component-communication/ts/plnkr.html) has a very specific warning relative to beta.11.

This warning should be removed when updating to a version where the issue is fixed.

**Comment by wardbell** [comment]
Must also remove the beta.11 warning added to `public/docs/ts/index.html` in commit ac7097300ad96c23cfb0db682c308300494325f0

**Comment by wardbell** [comment]
Took care of this when we updated to beta.12
